### PR TITLE
fix(builder): layouts condition

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Minor bug if layout already exists in listing

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by galvez — APPROVED** [review]

**Comment by manniL** [comment]
Makes sense to me. The layout shouldn't have been loaded once *and* should be a `.vue` file.

**Review by TheAlexLichter — APPROVED** [review]

**Review by pi0 — APPROVED** [review]

**Comment by clarkdo** [comment]
@ricardogobbosouza @manniL @pi0 
What if layout is `.js` or `.ts` ?

I suppose the original condition is for make `.vue` have higher priority than other extensions.

**Comment by Atinux** [comment]
I agree, I think this could lead to a breaking change if people were using `.js` or `.ts` extension for layouts.

**Comment by manniL** [comment]
Agree. We *should* add a test case for that and revert if it's broken.

**Comment by clarkdo** [comment]
@manniL Let me try to add a test

**Comment by manniL** [comment]
@clarkdo whoops. saw it too late, sorry! 🙈

**Comment by clarkdo** [comment]
@manniL Sorry, I didn't notice your pr since I was changing and pushing code.

**Comment by manniL** [comment]
@clarkdo No worries :D

**Pull request merged**
