### PR TITLE
fix(babel-preset-app): add explicit dep on used babel plugin

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

https://github.com/babel/babel-plugin-proposal-private-property-in-object/issues/1#issuecomment-1584287021
resolves nuxt/nuxt#21489
resolves https://github.com/nuxt/create-nuxt-app/issues/1030

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds an explicit dependency on the version of `@babel/plugin-proposal-private-property-in-object` we need in the project.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Eugene313 — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
@danielroe If it takes too long to release this, I can temporarily add a workaround in Babel. Out of curiosity, did you get similar bug reports ~1 week ago?

In Babel 7.22.0 we removed the `@babel/plugin-proposal-private-property-in-object` because we didn't need anymore. That broke all create-react-app installs because it has a bug identical to the one fixed in this PR, and since create-react-app is not maintained we temporarily added the dependency back to Babel.

To avoid having the unnecessary dependency, we now replaced it with a placeholder whose unique goal is to fix CRA compatibility, and that otherwise behaves as a missing dependency when required.

I'm surprised that we didn't discover this problem in Nuxt when we released 7.22.0 🤔

**Comment by nicolo-ribaudo** [comment]
Oh well :)

**Comment by danielroe** [comment]
Sorry for the pain @nicolo-ribaudo!

For everyone else, until this is released in 2.17, you can opt in to use `nuxt-edge` in your projects, or add this plugin explicitly as a dev dependency. (I'll be triggering an edge release shortly.)

We expect to release 2.17 this weekend.

**Comment by Eugene313** [comment]
Yes I had same problem 1 week ago

**Pull request merged**
