### PR TITLE
feat: add meta `headAttrs`

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Add meta `headAttrs`

## Checklist:

- [ ] All new and existing tests are passing.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by manniL** [comment]
Hey @ricardogobbosouza 👋 

As that options isn't documented in [vue-meta](https://github.com/declandewet/vue-meta) we should documented it there first before providing an interface for it in Nuxt IMO.

**Comment by ricardogobbosouza** [comment]
Hi @manniL, i agree
There is this option but it is not documented

**Comment by ricardogobbosouza** [comment]
I created a PR https://github.com/declandewet/vue-meta/pull/294

**Comment by manniL** [comment]
vue-meta PR merged.

**Comment by manniL** [comment]
@pi0 There is no vue-meta release necessary I think as just the docs were missing ☺️

**Comment by manniL** [comment]
@ricardogobbosouza Can you add a simple test (just modify one of the fixtures ;) to cover the change)

**Review by pi0 — DISMISSED** [review]

**Comment by pi0** [comment]
@manniL @ricardogobbosouza Shall we delegate example and tests to another PR or are you working on it? I don't want to make this enhancenemnt stalled.

**Review by galvez — DISMISSED** [review]
This has gotten me before @ricardogobbosouza -- thanks!

**Comment by ricardogobbosouza** [comment]
Hi @pi0
I'm taking tests today.

**Review by TheAlexLichter — APPROVED** [review]

**Review by pi0 — APPROVED** [review]

**Pull request merged**
