### PR TITLE
feat: allow `pick` in fetch API to be string

### LINKED ISSUE #15603: Pick as root `data` when using fetch API
### Describe the feature

Currently, the `useFetch` and `useAsyncData` options we have are:

```ts
type UseFetchOptions = {
  // other keys...
  pick?: string[]
```

It would be nice to have the option to pick a single key (so `pick?: string | string[]`), where the only key is automatically unwrapped as the data key of the fetch return object. Example:

```ts
const { data } = await useFetch('https://reqres.in/api/users/2', {
  pick: 'data'
}

// Then I can access directly data.value.id instead of data.value.data.id
```
The response sample can be accessed here: [https://reqres.in/api/users/2](https://reqres.in/api/users/2).

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

### PR DESCRIPTION
**Pull request by smilosevic**
### 🔗 Linked issue

[#15603](https://github.com/nuxt/nuxt/issues/15603)

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

If `pick` is used as a string, the value of that key in the data structure will be returned. Resolves [#15603](https://github.com/nuxt/nuxt/issues/15603)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — CHANGES_REQUESTED** [review]
This is a nice idea and solution for the linked issue.

However, we need to update the types for asyncData so that the return type is correct when using this. Would you be able to do that?

**Comment by Atinux** [comment]
Actually, why not using `transform` for this instead?

**Comment by pi0** [comment]
I also fully agree that this is a nice feature but also transform seems safer. Keeping type complexity low and easily possible / readable to do. We might document this solution.

**Comment by smilosevic** [comment]
Hi everyone. This is my first pull request, and I'm not sure what to do next. Should I close it if we are not going with this?

**Comment by danielroe** [comment]
I think let's close it for now. We're thinking it would be simpler to advise users to use the `transform` option instead rather than increase type complexity, e.g.

```ts
useFetch('/api/test', {
  transform: data => data.thing,
  // rather than pick: 'thing'
})
```

The PR was otherwise good - thank you ❤️ I'll look forward to seeing your next one!

**Pull request closed without merging**
