### PR TITLE
fix(vue-app): check whether route exists within Nuxt app before replacing

### PR DESCRIPTION
**Pull request by danielroe**
## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)

## Description
Fixes redirection issue introduced in https://github.com/nuxt/nuxt.js/pull/9050

## Checklist:
- [x] All new and existing tests are passing.

### CODE REVIEW

**Comment by pabloalvzal** [comment]
Hello @danielroe @pi0 

I am migrating our company's web client to Nuxt and I may have found a bug on the latest version (bug fix). I was working on Nuxt 2.15.6 and just did the upgrade to 2.15.7. 

It seems that on normal route navigation, all things work well! But on page reload the forward slash `/` gets replaced in the route by `%2F`. In our case, this leads to 404's because we use the URL to build the API call. 

I can probably work around it by validating the API call everytime, but I thought I should let you know.

**Comment by danielroe** [comment]
@pabloalvzal Could you provide a bit more info on the situation in a new issue?

**Comment by Sendoo** [comment]
Hello @danielroe @pi0
I have a similar problem, only the trailing slash is simply removed from the url on the first load.
With further routing, the trailing slash is not removed.
It started after updating to version 2.15.17.
Version 2.15.16 does not have this problem.

**Comment by joaquinvexels** [comment]
> Hello @danielroe @pi0
> 
> I am migrating our company's web client to Nuxt and I may have found a bug on the latest version (bug fix). I was working on Nuxt 2.15.6 and just did the upgrade to 2.15.7.
> 
> It seems that on normal route navigation, all things work well! But on page reload the forward slash `/` gets replaced in the route by `%2F`. In our case, this leads to 404's because we use the URL to build the API call.
> 
> I can probably work around it by validating the API call everytime, but I thought I should let you know.

same

**Comment by curtgrimes** [comment]
I'm experiencing a redirect loop on this update compared to the last patch release (redirecting from no slash to slash to no slash etc. until browser stops the redirect loop) but I do not have time at the moment to create a minimal reproduction.

**Comment by mvandiest** [comment]
```
Hello @danielroe @pi0

I am migrating our company's web client to Nuxt and I may have found a bug on the latest version (bug fix). I was working on Nuxt 2.15.6 and just did the upgrade to 2.15.7.

It seems that on normal route navigation, all things work well! But on page reload the forward slash / gets replaced in the route by %2F. In our case, this leads to 404's because we use the URL to build the API call.

I can probably work around it by validating the API call everytime, but I thought I should let you know.
```

Also seeing the `%2f` issue on page reload.

**Comment by darioferderber** [comment]
Hi @pi0, @danielroe,

I'm having trouble with routes that have defined aliases after upgrading to 2.15.7 from 2.15.6.

Route example:
```
{
  name: 'Homepage',
  path: '/hr/',
  component: 'pages/Homepage.vue',
  chunkName: 'pages/Homepage',
  pathToRegexpOptions: {
    strict: true
  },
  alias: ['/en/']
},
```

If I navigate to '/en/' (with anchor tag) location gets replaced to '/hr/' (only on client side).

**Comment by ChristianAlbrecht** [comment]
> Hello @danielroe @pi0
> 
> I am migrating our company's web client to Nuxt and I may have found a bug on the latest version (bug fix). I was working on Nuxt 2.15.6 and just did the upgrade to 2.15.7.
> 
> It seems that on normal route navigation, all things work well! But on page reload the forward slash `/` gets replaced in the route by `%2F`. In our case, this leads to 404's because we use the URL to build the API call.
> 
> I can probably work around it by validating the API call everytime, but I thought I should let you know.

We are also seeing this issue with slashes being replaced on page reload or direct navigation.

A few more details.
This only seems to happen for a specific route, which has a named parameter, that can contain multiple levels of path segments. The corresponding path expression:

`path: '/space/:repository([^]*)?/'`

with 2.15.6 we get for `repository` something like `folder/subfolder` but after the update to 2.15.7 it is `folder%2Fsubfolder`. This also replaces our URL at that point, which leads to subsequent errors in our web application so that for now we reverted back to 2.15.6

**Pull request merged**
