### PR TITLE
feat: jest-puppeteer example

### PR DESCRIPTION
**Pull request by awronski**
## Types of changes
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Example how to test Nuxt.js app with Jest and Puppeteer.
It helps to test live SPA application and simulate user input with headless Chromium browser.

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Review by TheAlexLichter — APPROVED** [review]

**Review by TheAlexLichter — DISMISSED** [review]
Please fix the lint issue :relaxed:

**Comment by awronski** [comment]
Everything should be fixed.

The only warning is about the browser variable. But it is injected by the jest. It is correct.

**Comment by manniL** [comment]
@awronski CI is still failing. Please disable the eslint rule that line then.

**Review by pi0 — APPROVED** [review]

**Comment by awronski** [comment]
@pi0 Should I fetch/merge with upstream or leave it as it is?

**Pull request merged**
