### PR TITLE
feat(kit): support passing getter to `addVitePlugin` and `addWebpackPlugin`

### PR DESCRIPTION
**Pull request by antfu**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This should save a bit by avoiding creating plugins that didn't end up using, like webpack plugins when running Vite and vice versa. 

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
I love it in general. Only a question: Can't unplugin be lazy by default?

**Comment by antfu** [comment]
When we pass the option, it returns a plugin object - even if the hooks are not in use, it still creates an extra object and the compatible layer. What else can be lazy? (`unplugin.webpack` is lazy, `unplugin.webpack({})` is not)

**Comment by pi0** [comment]
> When we pass the option, it returns a plugin object - even if the hooks are not in use, it still creates an extra object and the compatible layer. What else can be lazy?

I think we can make hooks themselves lazy initialized (on first rollup call via a proxy or wrapper). This way it is automagically lazy initialized.

**Comment by antfu** [comment]
I don't honestly think it needs to be more lazy, proxy on hooks that are called a lot of times might introduce extra overhead. And this feature is not only for unplugins but also for other modules to install different plugins.

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
I think this PR will pair well with https://github.com/nuxt/nuxt/pull/20587 - we can remove some of the extra steps it takes to lazily initialise the plugin, and use the getter that this PR provides.

**Pull request merged**
