### PR TITLE
feat(webpack): support passing function as `postcssOptions`

### LINKED ISSUE #7015: using function for build.postcss config option
### What problem does this feature solve?

I am using a function inside of a .postcssrc.js config file, to react to the current processed file. Doing this, I am able to use purgeCss only on one specific file. 
So basically I am doing this:

	module.exports = ({ file }) => {
		const doPurgeCSS = file.basename === 'example.scss';
	
		if (doPurgeCSS) {
			plugins['@fullhuman/postcss-purgecss'] = {
				someOtherOptions
			};
		}
	
		return {
			plugins
		};
	};

I know that I would lose the default nuxt config using this code, but for the reproduction I ommited this part due to simplicity.

The docs (https://nuxtjs.org/faq/postcss-plugins/) say using a config file is already deprecated and won't work in nuxt 3. But as far as I understand, you can not pass a function to the build.postcss option right now and therefore there is no other way to do this at the moment. 

### What does the proposed changes look like?

Allow build.postcss to use a function, and expose CTX to it, just like postcss-loader does (https://github.com/postcss/postcss-loader#context-ctx) to make the config file dynamic.

### PR DESCRIPTION
**Pull request by obulat**
### 🔗 Linked issue

resolves #7015 
#19482
closes #8899

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This is an updated version of #8899 that applies the changes to the now-default PostCSS 8 config.

If postcss config is a function, we execute the custom function, but we also apply the default config of Nuxt. Therefore we can ensure that the config has a minimum default.

Postcssconfig can either be an object (already supported) or a function which gets passed in the loadercontext. But nuxt does not support passing in a function currently.

#### Why

Passing in a function allows more complex uses cases, e.g. by applying different postcss steps for different ressources. (see also https://github.com/webpack-contrib/postcss-loader#function)

#### Solution

This approach adds a new "postcssConfig" option to the "postcss" Nuxt config. Either this is the regular postcssConfig, or it is a function. see https://webpack.js.org/loaders/postcss-loader/#postcssoptions
(only works with postcss@8, because postcss-loader >= 4.0 is required, and postcss7 nuxt setup conflicts with this version of postcss-loader)

e.g.
nuxt.config.js.
```
module.exports = {
  build: {
    postcss: {
      postcssOptions: loaderContext => {
        // e.g. do something else with ".sss" files
        if (/\.sss$/.test(loaderContext.resourcePath)) {
          return {
            parser: 'sugarss',
            plugins: [['postcss-short', { prefix: 'x' }], 'postcss-preset-env']
          };
        }

        return {
          plugins: [['postcss-short', { prefix: 'x' }], 'postcss-preset-env']
        };
      }
    }
  }
};
```
### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by obulat** [comment]
I am not sure that this change correctly applies the `preset` properties to the `postcss-preset-env` configuration.
I also don't know how to add tests. Is there an existing test that I could adjust for this change, @danielroe?

I would also need to open a separate PR for updating the documentation. The current section on PostCSS config sessions has not yet been updated to Nuxt 2.16 changes (https://nuxtjs.org/docs/configuration-glossary/configuration-build#postcss)

**Comment by obulat** [comment]
> I am not sure that this change correctly applies the preset properties to the postcss-preset-env configuration.

I have extracted the changes to `preset` to a separate PR (#19518) because it makes the review faster, and I could test that it works.

I'm not sure how to test this PR, though.

**Comment by danielroe** [comment]
@obulat would you be happy to resolve conflicts in this PR? I can help with adding a test fixture.

**Review by danielroe — DISMISSED** [review]

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
Merging to include in 2.17. Feel free to come back to me if you think there's anything missing here.

**Comment by obulat** [comment]
> Merging to include in 2.17. Feel free to come back to me if you think there's anything missing here.

Thank you for getting this PR finished, @danielroe!

**Pull request merged**
