### PR TITLE
fix(webpack): extract css breaks hmr and source-maps

### LINKED ISSUE #5386: Setting 'extractCSS' to 'true' invalidates HMR
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[CodeSandbox](https://codesandbox.io/s/v0j50l7rv7)

### Steps to reproduce

- Create new nuxt@^2.5.0
- Set extractCSS to true in the build property of nuxt.config.js

### What is expected ?

To work and reload style as expected

### What is actually happening?

The style does not change until the page is refreshed manually

### Additional comments?

- I have used 2.4.3 previously and everything worked like a charm
- When 'extractCSS' is not set, there is no problem

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8933">#c8933</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by TheAlexLichter**
Resolves #5386 #5390 

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)

## Description

Related: https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/161

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Comment by galvez** [comment]
@manniL thanks for handling this, I think it explains some oddity I've seen.

**Comment by manniL** [comment]
Works fine :relaxed: 	

@galvez Np at all! :+1:

**Comment by manniL** [comment]
Works fine :relaxed: 	

@galvez Np at all! :+1:

**Review by atinux — APPROVED** [review]
Nice one @manniL

**Review by pi0 — APPROVED** [review]

**Pull request merged**
