### PR TITLE
Feature Request: Store directory structure changes

### PR DESCRIPTION
**Pull request by airjp73**
This is similar to issue #1576.

I thought it would be really useful to allow an alternative directory structure for the Vuex store. I've changed it so that you can break up a module into state/getters/actions/mutations files like this. Also allows using `module/index.js`.

```
store
  state.js
  actions.js
  mutations.js
  getters.js
  module1/
    state.js
    actions.js
    nested-module/
      state.js
  module2/
    index.js
    getters.js
```

But it's still compatible with the existing directory structure (unless you have files named state.js, actions.js, etc). And you can mix and match.

```
store
  index.js
  module1.js
  module1/
    nested-module.js
  module2/
    state.js
    actions.js
```

Also, this is my first PR ever, so I apologize if I did this all wrong.

### CODE REVIEW

**Comment by husayt** [comment]
This looks cool. I hope also fixes issue with vuex modules in current implementation.

**Comment by Atinux** [comment]
Hi @airjp73 

Thank you for this PR, I like this idea also. I want to make sure there is no side-effect with this.

If I have something like this:

```
store/
  foo.js <- export state, mutations and actions
  foo/
    index.js <- export state
    state.js <- export default state 
    mutations.js
    actions.js 
```

What would it do with your changes?

**Comment by airjp73** [comment]
Thank you guys for the comments.

@Atinux, the current behavior would be that your foo module would end up with the state described in `foo/state.js`. I like this kind of specific > general behavior. `foo/state.js > foo/index.js > foo.js`

However, I did a little more rigorous testing and it looks like that doesn't always hold true. For example:

```
foo/
    actions.js
    index.js
```

Will end up with the actions in index.js instead of actions. I think the current implementation might rely a little on the order in which the files are processed. I can put in a fix for this today.

**Comment by airjp73** [comment]
I made the fixes. Now it should always work the way I said in my last comment. The specific `foo/actions.js` type files will override `foo/index.js`, which will override `foo.js`.

But you can also mix and match if you want. If you have:

```
foo.js <- export state
foo/
    index.js <- export actions
    mutations.js <- export default mutations
```

Then you will end up with a foo module that has state, actions, and mutations. And then, if you were to try to add mutations to `foo.js` or `foo/index.js` it wouldn't do anything--you would just have the mutations in `foo/mutations.js`.

**Comment by simllll** [comment]
Nice feature,looking forward to it

**Comment by galvez** [comment]
@airjp73 I've fixed conflicts on your PR and resubmitted. Ping us if you still want to update this PR.

**Pull request merged**
