### PR TITLE
from_transitions should exist

### PR DESCRIPTION
**Pull request by killix**
I experimented a weird issue with the transition.
This fix should make the transition key in components optional.

### CODE REVIEW

**Comment by Atinux** [comment]
@pi0 can you take a look at it please?

**Comment by pi0** [comment]
@killix Would you please check against `tapable` branch? https://github.com/nuxt/nuxt.js/blob/tapable/lib/app/client.js#L19 It should fix this problem after merge :)

**Comment by killix** [comment]
the link point to 404.

**Comment by pi0** [comment]
@killix because now it is inside `dev` :)

**Pull request closed without merging**
