### PR TITLE
exit code 1 in case of failed builds

### LINKED ISSUE #3534: [edge ] Failed build script should not return exit code 0
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js](https://github.com/nuxt/nuxt.js)

### Steps to reproduce

Try to build project with for example invalid import. During build a error will print out, but the exit code will be 0. This make build marked as valid in CI

### What is expected ?

```
>echo %ERRORLEVEL%
1
```

### What is actually happening?

```
ERROR in ./src/pages/dashboard/welcome/setup.vue?vue&type=script&lang=js (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/dashboard/welcome/setup.vue?vue&type=script&lang=js)
Module not found: Error: Can't resolve '~/components/dashboard/LandlordEdit' in 'C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\src\pages\dashboard\welcome'
 @ ./src/pages/dashboard/welcome/setup.vue?vue&type=script&lang=js (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/dashboard/welcome/setup.vue?vue&type=script&lang=js) 14:0-63 20:30-42
 @ ./src/pages/dashboard/welcome/setup.vue?vue&type=script&lang=js
 @ ./src/pages/dashboard/welcome/setup.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
Done in 38.18s.

>echo %ERRORLEVEL%
0
```

### Additional comments?

Is there a workaround?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7384">#c7384</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by aldarund**
Fixes https://github.com/nuxt/nuxt.js/issues/3534

### CODE REVIEW

**Comment by aleshaanddustin18** [comment]
Failed build

**Review by clarkdo — COMMENTED** [review]
Have you tried `nuxt-edge` ?

In https://github.com/nuxt/nuxt.js/blob/dev/bin/nuxt#L12-L19, we already added a hook for exiting process on fatal errors.

**Comment by aldarund** [comment]
@clarkdo hm. Yes, i was using edge.

**Comment by aldarund** [comment]
@clarkdo ok, i have checked again. The problem is that error is null here
https://github.com/nuxt/nuxt.js/blob/dev/bin/nuxt-build#L72
so the hook is not triggered because value is null ( a bit of strange behavior as for me..)

**Comment by aldarund** [comment]
@clarkdo catch triggered. But 'error' variable is null. And when u pass null variable to consolation as arg it doesn't trigger hook.
There no special case, just build for example app with invalid import

**Comment by clarkdo** [comment]
So it would be better to investigate the root cause of why the error message is missing, how do you think ?

**Comment by aldarund** [comment]
@clarkdo ye sure, when i was creating this pr i wasnt aware of the hook. Although imo hook should be triggered by consola even if null is passed as arg

**Comment by aldarund** [comment]
ok, i have found what cause null error. Will update PR soon

**Review by clarkdo — APPROVED** [review]
LGTM

**Pull request merged**
