### PR TITLE
v2.12.0

### PR DESCRIPTION
**Pull request by pi0**
### 🚀 Features

- `general`
  - #6950 Support `crossorigin` attribute in SSR script and `preload` tags
  - #6868 Improve programmatic usage
  - #7029 Expose webpack config
  - #6272 Allow disabling loading-screen
- `wepack`
  - #6987 Support `@import` using `~assets` in css files
  - #6272 Allow disabling loading-screen
- `vue-app`
  - #6880 New fetch syntax
  - #6939 Pass error as param to `nuxt-loading` fail method
  - #6244 Trigger` watchParam` when param is changed in same route
- `cli`
  - #6855 Pass context when `nuxt.config` exports a function

### 👌 DX

- `builder`
  - #6924 Analyze mode warning rewording 
- `general`
  - #6881, #6896 HMR support for server middleware
- `generator`
  - #6882 Log message or full error for unhandled error without stack trace
- `cli`
  - #6904 Display listening URLs after build
- `vue-app`
  - #7032 Improve missing inject value error message
  - #6775 Middleware not executing on double browser back navigation
- `core`
  - #7079 Better module not found handling

### 🔥 Performance

- `vue-renderer`
  - #6973 Early return `render` when redirect happens
  - #6846 Don't serialize session when `injectScripts` is false

### 🐛 Bug Fixes

- `core`
  - #7002 Deprecated `render:context` and `render:routeContext` hooks was not being called
- `babel-preset-app`
  - #7070 TypeError when import cjs in webpack building
- `vue-app`
  - #6946 Use child transition name when navigating to parent
  - #6854 Add fallback context for errors
  - #6803 Resolve leave transition on child routes
  - #6807 Move head to the index to avoid global state
- `webpack`
  - #6864 Provide global `URL` and `URLSearchParams`

### 💅 Refactors

- `general`
  - #6954 Use scope variable memo for modern utils
- `utils`
  - #6953 Eliminate side effect from modern utils

### 📝 Examples

- `cached-components`
  - #6997 Remove non-existing link

### 🏡 Chore

- `general`
  - #6816 Simplifies Code Contributions & Reviews
- `ci`
  - #6857 Support Github actions

### 👓 Tests

- `general`
  - Fix socket-hang-up test
  - Separate dev and unit test
  - Avoid unexpected outside stderr assertion count
  - Fix uncompressed resource size
  - Wrap error test with consola to make output clear

### 💖 Thanks to

- 404-NOTFOUND (@404-NF)
- HG (@husayt) 
- James George (@jamesgeorge007)
- Jason Poindexter (@jsonpoindexter)
- Mark Honeychurch (@markhoney)
- Matteo Rigon (@matteo-rigon)
- Sand Of Vega (@sandofvega)
- Sean Hellum (@JesterOrNot)
- Vladlen (@negezor)
- @wppd

### CODE REVIEW

**Comment by Timkor** [comment]
Shouldn't it be v2.12.0?

**Comment by pi0** [comment]
@Timkor typo 🙈 Thanks 😊

**Comment by husayt** [comment]
@pi0 After upgrading `/api`  route configured via @nuxt/proxy and @nuxt/axios stops working in 'SPA' dev mode. With 2.11 it all works fine. This could affect many others. If it is a known issue, it's definitely worth to mention this as a breaking change.

**Comment by pi0** [comment]
@husayt I'll check thanks for heads-up. Do you have a reproduction link?

**Comment by husayt** [comment]
> @husayt I'll check thanks for heads-up. Do you have a reproduction link?

I am  still investigating. As my setup is a bit complicated I am trying to get a simpler reproduction example. 

If anyone else stumbles upon this please let know, as with more information it will be easier to get to bottom of this.

**Comment by husayt** [comment]
@pi0 I found the issue, but not sure what exactly is causing this. It affects proxy behavior when  `router.base` is defined.

The behavior changed somewhere between 2.11.0-26277131.7af9ec8c and
2.11.1-26376495.084a1ca

Before for the following configuration 

```js
 proxy: {
    "/api": {
      target: "http://myserver.com",
      pathRewrite: {
        "^/api": "/alpha"
      },
      changeOrigin: false,
      prependPath: false
    }
},
router: {
    base: "/alpha/"
}
```

I would `/api` have pointing to `http://myserver.com/alpha` e.g. `/api/user` would  call `http://myserver.com/alpha/user`. But after the change  I can't access `/api`

**Comment by pi0** [comment]
@husayt It may be related to HMR improvements. I'll check thanks for repro. Meanwhile would you please create an Issue for this?

**Review by atinux — APPROVED** [review]

**Review by galvez — APPROVED** [review]

**Pull request merged**
