### PR TITLE
WIP: feat: new routing system to allow multiple route params

### PR DESCRIPTION
**Pull request by atinux**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

The breaking change only affects users that have a `$` in the files inside `pages/` (should not exists but we never know).

## Description

The idea is to replace the `pages/_dynamic.vue` to `pages/$dynamic.vue`.

Main advantage, usage of params:
- In the middleware of the route (`pages/author-$username.vue`)
- Multiple route params (`pages/product-$sku-$variant.vue`)

I also added a warning for easier migration.

This change is planned for **Nuxt 3**.

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Comment by Atinux** [comment]
We may need to clean the `next` branch so we can start working on it again :)

**Comment by ricardogobbosouza** [comment]
@Atinux 
I think the `$` key could be configurable, what do you think?

**Comment by begueradj** [comment]
But this is a breaking change. I mean application done with previous Nuxt.js versions will need to be re-written.

**Comment by ricardogobbosouza** [comment]
Being configurable and defined the default with `_` can be released as an improvement and in nuxt 3 it would change to `$`

**Comment by Atinux** [comment]
@begueradj actually it will still work with `_dynamic.vue` with Nuxt 3 but will be deprecated and removed with Nuxt 4.

I don't think it's a good idea to make it configurable since it starts becoming a standard.

The *only breaking change* is that if someone has a `$` in the pages files 😄

**Comment by evillt** [comment]
Awesome!

Did you guys ever considered support [Passing Props to Route Components](https://router.vuejs.org/guide/essentials/passing-props.html#passing-props-to-route-components)?

I don't know how many guys using this feature, but support this feature not a bad idea to nuxt, huh?🤔

**Comment by Atinux** [comment]
You can add this feature by using `extendRoutes` @evillt :)

We are going to move to `[variable]` instead since `$` is used by the shell, see https://github.com/zeit/next.js/issues/7607#issuecomment-503767041

**Comment by evillt** [comment]
@Atinux 

Yes!

But I want to mean is:

Create a file `{id}.vue` under the `pages` folder, will auto transform to

```js
{
  path: '/:id',
  props: true,
  ...
}
```

by nuxt routing system.

Of course advanced route config will still using `extendRoutes`.

**Comment by Atinux** [comment]
@evillt for this I recommend to use the [router-extras-module](https://github.com/nuxt-community/router-extras-module) to active such options :)

**Comment by evillt** [comment]
@Atinux Sure!

**Comment by Atinux** [comment]
Finally, since `[]` will also break in next OS X terminal, the `_` is the better alternative from my POV so we will stick to it :)

**Pull request closed without merging**
