### PR TITLE
feat: custom pushAssets function to control http2 push headers

### LINKED ISSUE #4011: http2 push headers - should be a function
### What problem does this feature solve?

Now there is no configuration to decide what resources we want to push to the client.
So if it is returning client we are pushing all the resources even if he has it.

If the ```http2: push``` will be a function we could decide if we want to push and what.
It will be huge client optimalization.

Now we have something similar in ```shouldPrefetch``` and ```shouldPreload```

### What does the proposed changes look like?

Besides ```file``` and ```type``` we need ```request``` to check for cookies or some other headers and ```response``` to set some output.

This is just example how we could use new implementation.
(isReturningVisitor is some custom logic that check for client cookies)

```js
render: {
    http2: (req, res, file, type) => {
       return isReturningVisitor(req) === false && type === 'script'
    }
  },
```

Than for example [nginx](https://www.nginx.com/blog/nginx-1-13-9-http2-server-push/) can read the push headers and push the resources.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7870">#c7870</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by awronski**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Resolves: #4011 

Adds `pushAssets(req, res, publicPath, preloadFiles)` option to `http2`.
Function returns array of links. Now we can conditionally decide which assets we want to push.

Undocumented filter function `shouldPush` was marked as `deprecated`

## Checklist:
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]
LGTM. As this is almost a refactor i think we can add tests later.

**Comment by awronski** [comment]
@pi0 I am thinking about removing `publicPath` from arguments of `pushAssets(..)`. Because user has it in `nuxt.config.js`. What do you think?

**Comment by pi0** [comment]
@awronski This value _may_ be different. It should be read from client manifest to follow the value passed at compile time.

**Comment by clarkdo** [comment]
Doc and release note need to be updated

**Comment by awronski** [comment]
@clarkdo I will update docs

**Pull request merged**
