### PR TITLE
chore(github): add Chinese translation for issue template

### PR DESCRIPTION
**Pull request by clarkdo**
Add Chinese translation for issue template

### CODE REVIEW

**Review by pimlie — COMMENTED** [review]
Why is Chinese so special that it needs to be added here? Should we also add Spanish, Russian, French or other languages with large Nuxt communities?

**Comment by manniL** [comment]
@pimlie 

AFAIK: Vue & Nuxt are quite popular in Asian countries. Learning English isn't as "established" there as it is in e.g. European Countries.

**Comment by pimlie** [comment]
True, but:
- Asia is bigger then just China
- We shouldn't favor a single language like this. Imo we cant reasonably defend adding Chinese but not eg French (3 core-team members), Russian (@aldarund) or Portuguese (@galvez) which are all in the top 10 of most spoken languages according to [wikipedia](https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers)
- Except for @clarkdo nobody can support issues written in Chinese anyway (same would apply ofc to adding Russian or Portugese)

**Review by pi0 — APPROVED** [review]
I think there are valid reasons for add Chinese:

- Nuxt.js is based on Vue.js which has the biggest market in china
- In the past, there were no issues other than English but some Chinese ones. So that makes sense to guide Chinese developers in the right direction

Suggestion for later improvements: Maybe we can also request them to please write in English in CMTY

**Pull request merged**
