### PR TITLE
v2.5.0

### LINKED ISSUE #4849: Specify custom webpack entry points for the client and server
### What problem does this feature solve?

Currently specifying `config.entry` in `build.extend(config)` is ignored.

The **client** entry is assigned without merging the value of `config.entry` that might have been set in `build.extend`:

https://github.com/nuxt/nuxt.js/blob/dcdbaba710c88c2f2b4c848aaa5f881074764556/packages/webpack/src/config/client.js#L178

The **server** `config.entry` is the result of merging a default config—overriding any `config.entry` value passed in `build.extend`:

https://github.com/nuxt/nuxt.js/blob/89f88669c10ce9100b109749aeab445638b851a8/packages/webpack/src/config/server.js#L71

It would be great if custom entry points could be specified in `build.extend` so that custom chunks could be generated independently of the Nuxt app.

Specify a custom entry name of `app` could throw an error notifying the user that this is reserved by Nuxt.

### What does the proposed changes look like?

```js
// nuxt.config.js
import { resolve } from "path"

export default {
  build: {
    extend(config, { isClient }) {
      if (isClient) {
        console.log(config.entry) // { app: [ "path/to/client.js", "eventsource-polyfill", "etc..." ] } (currently undefined)
      } else {
        console.log(config.entry) // { app: [ "path/to/server.js" ] } (currently undefined)
      }
      
       // This is ok
      config.entry.custom = resolve("custom-entry.js")
      
      // Throws error "entry.app is reserved by Nuxt"
      // Could use Object.defineProperty for the
      // config object passed to build.extend to
      // throw an error when attempting to set entry.app
      config.entry.app = resolve("app.js") 
    }
  }
}
```

Running `dev|build|generate` would create another chunk called `custom`.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8543">#c8543</a>)</em></sub></div>

### LINKED ISSUE #4991: `nuxt generate` should exit with non-zero code on errors
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://github.com/njam/nuxt-generate-error](https://github.com/njam/nuxt-generate-error)

### Steps to reproduce

If an exception is thrown during rendering of a page in `nuxt generate`, this error is printed, but still the script exits with status 0. For both handled and unhandled errors. This is especially problematic in CI, as unhandled errors go unnoticed.

The repo to reproduce the error just throws an error in `created()`:
```js
  created() {
    throw new Error("My error");
  }
```

Clone repo to reproduce:
```console
git clone git@github.com:njam/nuxt-generate-error.git
cd nuxt-generate-error
yarn install
yarn run generate
echo $?
```

### What is expected ?

Should exit with a code higher than 0.

### What is actually happening?

Exits with code 0.

### Additional comments?

As a workaround I'm currently registering a modules like this:
```js
export default function() {
  this.nuxt.hook('generate:routeFailed', ({ route, errors }) => {
    let error = errors[0].error
    throw new Error(`Error generating ${route}:\n${error}`)
  })
}
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8629">#c8629</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by pi0**
## What's new?

15,000 line changes with 230 squashed commits by more than 30 contributors made this version possible! :heart:  

### Typescript DX

No longer needed to install `nuxt-ts` for typescript support. Nuxt.js officially supports TS by installing `@nuxt/typescript`. Please see #5079 for reasons behind such migration.

### Babel

Babel 7.4, Core-js v3, and `Object.assign` polyfill for better browser support.

### Stability

More than 30 fixes, refactors and performance improvements.

### Open in Browser

Use `nuxt dev -o` to instantly open project in the browser and enjoy a cool loading screen:

nuxt-loading-screen

### Programmatic API / Middleware

If not already done, please explicitly call `nuxt.ready()` after `new Nuxt()`. `nuxt.ready()` was always `async`, but not awaiting the function call has now a severe impact.

```diff
   const nuxt = new Nuxt(config)
++ await nuxt.ready()
```

### TypeScript

1. Please replace `nuxt-ts` dependency and use `nuxt` + `@nuxt/typescript`. (Also `nuxt-ts-edge` to `nuxt-edge` + `@nuxt/typescript-edge` for edge users)

```diff
{
--  "nuxt-ts": "^2.4.2"
++  "@nuxt/typescript": "^2.5.0"
++  "nuxt": "^2.5.0"
}
```

2. Configuration API to customize/disable type checking has been moved from `build.useForkTsChecker` to `build.typescript.typeCheck`. Please see #5079 for more details.

```diff
build: {
-- useForkTsChecker: false // or ForkTsChecker options
++ typescript : {
++   typeCheck: false // or ForkTsChecker options
++ }
}
```

## Features

- feat(babel): include `es6.object.assign` by default (Clark Du) (52fe145a)
- feat(cli): lock project during build or generate  (#4985) (Pim) (4e51723e)
- feat(cli): option to open the project in the browser  (#4930) (Ricardo Gobbo de Souza) (4c7bd9c5)
- feat(generate): return non-zero code or page error (fixes #4991) (#5195) (Jarek Lipski) (c6565c97)
- feat(module): support src as a function in addModule (#4956) (Ricardo Gobbo de Souza) (1e9eb4b7)
- feat: support `.nuxtignore` (#4647) (Xin Du (Clark)) (59be77a2)
- feat: support `devModules` option (#5102) (Jonas Galvez) (e87711c5)
- feat(ts): nuxt configuration typedefs (#4854) (Kevin Marrec) (92f81e01)
- feat(vue-app): universal fetch (#5028) (Pooya Parsa) (2015140d)
- feat(vue-renderer): improvements (#4722) (Pooya Parsa) (29297160)
- feat(vue-renderer): use async fs (#5186) (Pooya Parsa) (d07aefa5)
- feat(ts): better DX for typescript support (#5079) (Kevin Marrec) (920f444b)
- feat: loading screen (#5251) (Sébastien Chopin, Pooya Parsa) (ef41e205)
- feat: support core-js 3 (#5291) (Xin Du (Clark)) (d094c4a9)

## Fixes

- fix(builder, vue-app): order of plugin execution based on order in array (#5163) (Dmitry Molotkov) (a867dbd3)
- fix: correct public path in generation and start (#5202) (Xin Du (Clark)) (648062c3)
- fix: default for-exit to false to prevent dev exit (pooya parsa) (a347ef9b)
- fix: disable "analyze" for nuxt generate (#4975) (Alexander Lichter) (574a2eb2)
- fix: disable parallel build when extractCSS is enabled (Clark Du) (aad46ed6)
- fix: extra properties in templateFiles (#4925) (Xin Du (Clark)) (ca191240)
- fix: fix non standard esm modifications (pooya parsa) (fb87a559)
- fix: generate failure (#5007) (Andrey Shertsinger) (bcd672f9)
- fix: keep-alive component data should not be updated (#5188) (Xin Du (Clark)) (1ea86617)
- fix: not send Server-Timing header if no timing info (Clark Du) (d9a0b5f6)
- fix(postcss): default to preset-env and cssnano last (#5215) (Alexander Lichter) (adf423a5)
- fix: publicPath is not reactive in dev restarting (#5227) (Xin Du (Clark)) (1fb7538d)
- fix: refactor file watchers (chokidar/linux workaround) (#4950) (Pim) (5ec5932b)
- fix: remove cache-loader for external resources (#4915) (Xin Du (Clark)) (0223e56d)
- fix: respect namespaced in store module (#5189) (Xin Du (Clark)) (9e1ef888)
- fix: revert templatFiles name (#4924) (Xin Du (Clark)) (f70645e5)
- fix: trailing comma in tsconfig (#5061) (Sergey Vikulov) (1fb44d94)
- fix(ts): deprecate `isClient`, `isServer`, `isStatic` (#5211) (Daniel Hritzkiv) (29c3c425)
- fix(types): reflect chainlable NuxtLoading methods (#5104) (Matjaž Lipuš) (66273f4b)
- fix: Unexpected token .... Expected a property name in Safari (Clark Du) (eef7f695)
- fix(vua-app): clone mount error to prevent mutating read-only error object (#5214) (Alexander Lichter) (37006f62)
- fix(vue-app): avoid css chunk error (#5173) (Yutaka Sasaki) (41028a40)
- fix(webpack): clone `config.entry` (fixes #4849) (#5236) (Julien Dargelos) (82167651)
- fix: disable extract-css-chunks-webpack-plugin in dev mode (#4888) (Xin Du (Clark)) (928a230f)
- fix(server): handle decodeURI error (#5243) (phof) (5b7f6d78)
- fix: correct socket address in use error message (Clark Du) (2eb19653)
- fix(utils): relax lock settings (#5280) (Pim) (65a431d6)
- fix(vue-app): multiple named views cause invalid syntax (#5262) (Michael Leaney) (d03a61b0)
- fix(webpack): loaders in extend config is broken (#5292) (Xin Du (Clark)) (0eb5ed97)
- fix(vue-app): duplicated router.base when using context.redirect(object) (#5290) (Nianyong) (cf02e822)
- fix(vue-app): decode router base to support unicode characters (#5297) (Alexander Lichter) (3ac01df4)

## Performance Improvements

- perf: await routeData promises in parallel (#5027) (Alexander Lichter) (0826d7e5)
- perf(core): skip esm for node_modules and non .js files (#5220) (Pooya Parsa) (aabb1f69)
- perf(webpack): use `futureEmitAssets` (#5003) (Alexander Lichter) (3997d504)
- perf(ts): transpileOnly when using `nuxt-ts start` (#4906) (Kevin Marrec) (17cc12f0)

## Examples

- examples(jest-puppeteer): fix package .json (#4997) (Andrew Cravenho) (dfc8dd57)
- examples: improve vuex store example (#5017) (Alexander Lichter) (a9511e58)
- examples(pug): fix example by adding plain-pug-loader (#5223) (Paul Geisler) (320a46fe)
- examples(vuex-store): change to module store (#4923) (Alexander Lichter) (be41ae1c)
- examples: add pug-stylus-coffee (#4927) (chiboreache) (6d059698)
- examples: add tsx example (#4855) (andoshin11) (5101dc6a)
- examples: fix jest test dependencies (#5155) (Dmitry Molotkov) (1c3761a6)
- examples: fix links to vue-meta repo (#5018) (Pim) (06f4762e)
- examples: rebase on latest stable nuxt version (#4874) (Alexander Lichter) (47898fbd)
- examples: zero-downtime pm2 typescript example (#4907) (Dmytro) (1fb9af33)
- examples: fix dynamic components example (#5294) (Dmitry Molotkov) (d9db45c2)

## Refactors

- refactor: generate routes and template files in builder (#4883) (Xin Du (Clark)) (4c5a59e1)
- refactor: improve modern middleware and spa modern rendering (#5037) (Xin Du (Clark)) (05299d67)
- refactor: isModernBrowser return boolean for avoiding duplicate call (Clark Du) (c6d8e8ff)
- refactor: not detect modern browser if modern mode is disabled (Clark Du) (2b4d79c1)
- refactor: remove builder coupling from server (#5157) (Pooya Parsa) (13cb0f73)
- refactor: remove unnecessary onEmit in old webpack (Clark Du) (eac6d022)
- refactor: some small stuff (#4979) (Alexander Lichter) (69dfd848)
- refactor: fix typos (#4922) (Alexander Lichter) (569b6aab)
- refactor: unify context in webpack module (#5054) (Xin Du (Clark)) (9860eb6a)
- refactor: use spread syntax for plugin push (#4976) (Alexander Lichter) (31cb1873)
- refactor: fallback to babel-preset-env defualt targets when buildTarget is not specified (Clark Du) (176641f6)
- refactor(ts): add warning for nuxt-ts deprecation (#5301) (Kevin Marrec) (a11afd45)

## Chore

- chore(babel-preset): create readme with basic docs  (#5127) (HG) (04cdd602)
- chore: don`t ignore .nuxtignore (#5169) (Dmitry Molotkov) (39c9ab59)
- chore: enable yarn.lock maintenance (#5063) (Xin Du (Clark)) (17b53ebf)
- chore(vue-app): suppress deprecated warning for classic vuex in prod (#5137) (Shingo Sato) (f39205a7)

## Tests

- test: add await for promisable expect (Clark Du) (fabf1c07)
- test: add chrome detector (#4984) (Xin Du (Clark)) (855705bd)
- test: add describe.posix and win (Clark Du) (e9ba2f97)
- test: fix macos e2e tests (Pooya Parsa) (2c763df1)
- test: improve nuxt-loading component tests (#5005) (Pim) (75a74543)
- test: mock enquirer in typescript tests (#5025) (Pim) (ad6a8cda)
- test: skip reqest in dev test for now (Clark Du) (3e678793)
- test: try to fix unhandled request (Clark Du) (2f2baacb)
- test: turn off cli dev test (Clark Du) (5c053f5c)
- test: unit tests for generator (#4857) (Xin Du (Clark)) (e22a282e)
- test: unit tests for @nuxt/util (#4880) (Xin Du (Clark)) (96bab9f0)
- test: unit tests for server module (#5154) (Xin Du (Clark)) (cc573a49)
- test: update cli snapshot (Clark Du) (3dd1a285)
- test: unhandled open handles (Clark Du) (858c9eeb)
- test: change cli.test to be more accurate (#4957) (Xin Du (Clark)) (68f6880f)
- test: use puppeteer-core (#4929) (Pooya Parsa) (940a36fd)
- test: fix e2e test by downloading chromium (#5254) (Pooya Parsa) (2561b68a)
- test: fail tests in case of unhandled errors (#5255) (Pooya Parsa) (d6b505aa)

### CODE REVIEW

**Comment by chrysanthos** [comment]
This is a huge list! Awesome job guys! 🚀

**Review by atinux — APPROVED** [review]

**Review by clarkdo — APPROVED** [review]

**Review by kevinmarrec — APPROVED** [review]

**Comment by manniL** [comment]
@pi0 Weren't some of the fixes covered in previous patch releases? :thinking: :relaxed:

**Comment by clarkdo** [comment]
@pi0 @manniL 
I think it's due to cherry-pick in previous patch release which dev branch will include the fix as a different commit.

If we don't use cherry-pick, the changelog will be correct.

**Review by aldarund — APPROVED** [review]

**Comment by pi0** [comment]
Removed cherry-pick entries from v2.4.5, v2.4.3, v2.4.2. Thanks @manniL for checking that.

**Review by galvez — APPROVED** [review]

**Comment by kevinmarrec** [comment]
Updated PR description with warning regarding Configuration API change regarding TypeScript.

**Review by kevinmarrec — APPROVED** [review]

**Comment by pi0** [comment]
Changelog updated

**Comment by Atinux** [comment]
Good for me!

**Comment by Atinux** [comment]
I just published `@nuxt/loading-screen` `v0.0.4`

**Comment by manniL** [comment]
Let's ship #5291, #5290 and #5292. Then we are good to go from my POV

**Comment by pi0** [comment]
- Changelogs updated. 
- `[release]` triggered to test final changes on `nuxt-edge`

The dev branch should be better to be frozen now for release

**Comment by manniL** [comment]
Updated the migration guide wording for awaiting `nuxt.ready`. Feel free to correct me if I wrote sth. wrong :relaxed:

**Comment by chanlito** [comment]
Yes yes yes! 👏👏👏 Thanks all.

**Pull request merged**
