### PR TITLE
fix(nuxt): prefetch object-syntax routes with `<NuxtLink>`

### PR DESCRIPTION
**Pull request by Mini-ghost**
### 🔗 Linked issue

- #19136

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Based on PR #19120, the `preloadRouteComponents` function now accepts a `RouteLocationRaw` type as a value. This update has also been made to `<NuxtLink>` to allow `RouteLocationRaw` as a valid value type.

This PR does not modify the type of hook `link:prefetch`, but obtains `router.resolve(to.value).fullPath` before calling the hook, because others still need string path, rash modification may cause Breaking change.

https://github.com/nuxt/nuxt/blob/7f67fcec73016dcc31b232c92d4a50db4aaef9fc/packages/nuxt/src/pages/runtime/plugins/prefetch.client.ts#L23-L40

https://github.com/nuxt/nuxt/blob/7f67fcec73016dcc31b232c92d4a50db4aaef9fc/packages/nuxt/src/app/plugins/cross-origin-prefetch.client.ts#L26-L34

https://github.com/nuxt/nuxt/blob/7f67fcec73016dcc31b232c92d4a50db4aaef9fc/packages/nuxt/src/app/plugins/payload.client.ts#L14-L18

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — COMMENTED** [review]
1. we currently support prefetching _external_ links if `experimental.crossOriginPrefetch` is enabled, which the router won't be able to resolve. Maybe worth adding a check for whether a link is external?
2. if we resolve in the `link:prefetch` hook we'll end up double-resolving
3. possible solution to 1 and reduction in resolutions - we can skip if `to.value` is already a string?

**Comment by Mini-ghost** [comment]
If it is an external link, `to.value` is a string, so I only judge whether `to.value` is a string, if yes, skip it, if not, execute `router.resolve(to.value)` .

**Review by atinux — APPROVED** [review]

**Review by danielroe — APPROVED** [review]

**Comment by nathanchase** [comment]
FYI: Something in this PR broke NuxtLink, and am getting flooded with
`[Vue warn]: Extraneous non-props attributes (rel) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.` anywher that uses a custom NuxtLink template.

Example:
```
<NuxtLink
   v-slot="{ href }"
  :custom="true"
  :to="`/user/${id}`"
>
    <a :href="href">
      <img src="avatar.png">
    </a>
</NuxtLink>
```

This didn't occur in 3.2.2, but does in 3.2.3. - I will try to create a repro of the error in a nuxt.new StackBlitz.

**Comment by nathanchase** [comment]
StackBlitz with the error:
https://stackblitz.com/edit/github-hmvahh?file=app.vue

**Comment by danielroe** [comment]
That should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release with https://github.com/nuxt/nuxt/pull/19379

**Pull request merged**
