### PR TITLE
feat: respect beforeEnter for route if set

### LINKED ISSUE #3722: Router hooks not working
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://codesandbox.io/s/0oy5pxrwww](https://codesandbox.io/s/0oy5pxrwww)

### Steps to reproduce

```javascript
module.exports = {
  router: {
    extendRoutes (routes, resolve) {
      routes.push({
        name: 'logout',
        path: '/logout',
        beforeEnter: (to, from, next) => {
          next({ name: 'something' });
        },
      })
    }
  }
}
```

### What is expected ?

Nothing happens. Event does not work

### What is actually happening?

expect the event to work

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7564">#c7564</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by TheAlexLichter**
The `vue-router` enables the possibility to set a per-route guard called [`beforeEnter`](https://router.vuejs.org/guide/advanced/navigation-guards.html#per-route-guard).

With this PR, the guard will be respected and added to the router.

Resolves #3722

### CODE REVIEW

**Review by clarkdo — COMMENTED** [review]
Better to have some tests.

**Comment by manniL** [comment]
@clarkdo Don't worry, will add some! Just want to see if CI passes with the current changes and some feedback :relaxed:

**Review by clarkdo — APPROVED** [review]
LGTM

**Review by galvez — APPROVED** [review]

**Comment by Atinux** [comment]
SQUASHED AND MERGED YEAH! 🤟

**Pull request merged**
