### PR TITLE
extendedRoutes now works with the generate command. closes #275

### LINKED ISSUE #275: extendedRoutes not working with nuxt generate
[https://nuxtjs.org/api/configuration-router/#extendroutes](extendedRoutes) not working with `nuxt generate`.  I'm working on a fix, will attach the pull request here once done.

### PR DESCRIPTION
**Pull request by cj**

### CODE REVIEW

**Comment by Atinux** [comment]
Hi @cj 

The `extendRoutes` can be used also to `unshift()` or updated the actual routes, so I don't think this is the right fix.

Can you show me an example of the actual bug you're having?

**Comment by cj** [comment]
@Atinux add this to your nuxt.config.js and then run `nuxt generate`, you'll see the error you get.

```
  router: {
    extendRoutes (routes) {
      routes.push({
        path: '/index.html',
        component: resolve(__dirname, 'src/pages/index.vue')
      })
    }
  }
```

**Comment by cj** [comment]
@Atinux Once you are at that part of the code `this.routes` is a flat array `['/', '/about', '/contact']`, but the current code just pushes your `extendedRoutes` object to that array, which then results it in throwing an error.

**Comment by Atinux** [comment]
@cj, @alexchopin is going to work on it, he is the master of the routes generation in nuxt.js :)

**Pull request closed without merging**
