### PR TITLE
proposal for validation pages

### PR DESCRIPTION
**Pull request by agoalofalife**
Hello guys!
I had the problem, I wanted to perform validation on the basis of data vuex
but in the context of the method  **validate**  it's impossible

So why not transfer data from vuex?
It would be great!

### CODE REVIEW

**Comment by Atinux** [comment]
HI @agoalofalife 

Do you mind creating a PR also on the docs repo to update the doc?

**Comment by agoalofalife** [comment]
HI @Atinux 
I don't understand about the documentation
Could you write more detail..

**Comment by Atinux** [comment]
Nevermind I will take care of it :)

**Comment by agoalofalife** [comment]
I just didnt understand exactly what were you talking about, if you need me to add the changes to documentation then it's not a problem

**Comment by Atinux** [comment]
Could you make the changes to reflect the same behavior on server-side too @agoalofalife ?

Here the line: https://github.com/nuxt/nuxt.js/blob/master/lib/app/server.js#L154

**Comment by Atinux** [comment]
For the documentation, I was talking about making a pull request on this file: https://github.com/nuxt/docs/blob/master/en/api/pages-validate.md

**Comment by agoalofalife** [comment]
@Atinux I sent the changes to the server
 changes in documentation will be sent later

**Comment by Atinux** [comment]
I updated your code to add the `store` option only when the store is activated (store folder).

**Comment by agoalofalife** [comment]
@Atinux what these symbols mean? )
`<% something %>`

**Comment by Atinux** [comment]
@agoalofalife actually, every file inside `lib/app/` are lodash templates, a bit hard to explain :)

**Comment by agoalofalife** [comment]
cool
well I'll send later PR in the documentation :)

**Pull request merged**
