### PR TITLE
An unrecognized pr

### PR DESCRIPTION
**Pull request by yuchonghua**
An unrecognized pr

### CODE REVIEW

**Comment by yuchonghua** [comment]
@Atinux  hi, the recent very busy bar, pay attention to rest, sorry, I have been bothering you, if I need to amend the pr or the need for improvement, a lot of guidance, if I can not let you adopt amendments, I look forward to receiving your comments and suggestions so that I can do better

**Comment by Atinux** [comment]
Hi @yuchonghua 

I cannot add ddv to nuxt because nuxt.js has to be simple, but you can create `nuxt-ddv` to use nuxt.js + ddv.

Take a look at [nuxt-cluster](https://github.com/eggplanetio/nuxt-cluster) to see how they do to integreate nuxt.js with cluster.

**Comment by yuchonghua** [comment]
It can only open a server interface Let me achieve through the expansion of the database, is only open a revised lib/server.js https://github.com/nuxt/nuxt.js/pull/160/files#diff-c945a46d13b34fcaff544d966cffcaba

**Comment by yuchonghua** [comment]
@Atinux

**Pull request closed without merging**
