### PR TITLE
chore(examples): fix jest test dependencies

### PR DESCRIPTION
**Pull request by aldarund**

### CODE REVIEW

**Comment by clarkdo** [comment]
Is babel-core for babel-jest? babel-jest 24 has already upgraded to @babel/core

**Comment by aldarund** [comment]
@clarkdo its for vue-jest as i see
https://codesandbox.io/s/github/nuxt/nuxt.js/tree/dev/examples/jest-vtu-example broken without babel-core.

> AIL  components/Btn/Btn.spec.js
>   ● Test suite failed to run
> 
>     Cannot find module 'babel-core'
> 
>     However, Jest was able to find:
>         './Btn.spec.js'
>         './Btn.vue'
> 
>     You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'vue'].
> 
>     See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string
> 
>       at Object.<anonymous> (node_modules/vue-jest/lib/compilers/babel-compiler.js:1:15)

**Comment by clarkdo** [comment]
How about using vue-jest 4.0-beta?

**Comment by aldarund** [comment]
if its stable enough it would be good idea :)

**Comment by aldarund** [comment]
@clarkdo tested, work fine. updated to 4-beta2

**Review by clarkdo — APPROVED** [review]
LGTM

**Pull request merged**
