### PR TITLE
feat: use ~ with postcss-import

### PR DESCRIPTION
**Pull request by clarkdo**
When use `postcss-import`(by default now), `@import ~/assets` cannot resolve path with webpack alias and will throw a error as https://github.com/nuxt/nuxt.js/issues/1453 described.

This pr will make `postcss-import` can resolve alias: `~` and `~~`.

### CODE REVIEW

**Comment by Atinux** [comment]
Should we handle `@` and `@@` as well too? CC @pi0

**Comment by clarkdo** [comment]
Actually I want to pass the `base.config.resolve` to here, but it may be a little wired, so I just used the most commonly `~` and `~~`

**Comment by pi0** [comment]
If `post-css-loader` is going to be problematic, maybe it would be better to entirely remove it. `css-loader` should handle imports. Also with custom postcss configurations things will go unexpected more. And if is needed to keep it my suggestion is to add `@` and `@@` aliases too.  @clarkdo @Atinux

**Comment by Atinux** [comment]
Let's keep it for version 1. Actually I use TailwindCSS with Nuxt.js and it's great that it's handled directly, but postcss performances are terrible :/

**Pull request merged**
