### PR TITLE
chore(test): fix external redirect link

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Fix current failing test by correcting the doc link.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by pi0** [comment]
We are adding back `/2.x` (or probaby `/v2`) it was a quick fix for docus issue. I guess we can find a more permanent redirect not breaking e2e test in the future...

**Comment by clarkdo** [comment]
@pi0 Should we merge this or wait fix from doc side ?

**Comment by pi0** [comment]
Let's use example.com? :D They seem to preserve both trailing slash cases

**Comment by clarkdo** [comment]
Looks good

**Pull request merged**
