### PR TITLE
feat: Fix env variables not accessible.

### PR DESCRIPTION
**Pull request by mathieutu**
Salut les gars !

As discussed with @Atinux in https://github.com/nuxt/nuxt.js/pull/2171, this PR fixes this issue:

```js
env: {
  FOO: 'bar'
}

console.log(process.env['FOO']); //bar
const key = 'FOO'; console.log(process.env[key]); // undefined
```

Also, we don't need the @0pt1m1z3r PR anymore. (His/her issue is fixed automatically by this one (side effect).

The principle is to replace directly the whole `process.env`, so we can access it like a normal object without any trick.

It's (obviously) **fully tested** (I've added some tests to check the complete env feature (context and process)

We also need to update the documentation, as this warning is not required anymore:
https://nuxtjs.org/api/configuration-env#process-env-

Thanks for the amazing job and see you!

### CODE REVIEW

**Comment by mathieutu** [comment]
An other thing: for now, we don't transfer automatically the server environment variables to the application, and we need a module to handle `.env`files. Is it by choice, or just because it's not implemented yet in the core? 

(for example create-react-app handle both: .env file, and all env variable which start with REACT_APP)

Would you like a pull request with this/theses feature(s)?

**Review by clarkdo — COMMENTED** [review]
Thank you for the contribution, pr looks good.

The only thing I want to ask is that can useless dead codes be removed by `UglifyJS` as before ?

For example, below codes will be removed in production building:
```js
if (process.env.NODE_ENV === 'development') {
  //...
}
```

**Comment by 0pt1m1z3r** [comment]
@mathieutu @Atinux @clarkdo 
This decision does not solve the problem, which solves my PR #2171 .
You just replace only `process.env`. 
So, `process.env.object.obj.again` will be replace to `{ // full env object }.object.obj.again`. And that's exactly what I decided.

But I also think that for large objects need to use other way (store) instead of process.env.

**Comment by mathieutu** [comment]
@clarkdo: Hem.. actually I have no idea of that. I'm looking for that.
@0pt1m1z3r: ok, my bad, I didn't understand that it was your problem. So our PRs are completely opposed 😅! What's your problem with the `{ // full env object }.object.obj.again`? It work's perfectly at the end.

I don't know if we can do a mix of both, I will investigate.

**Comment by clarkdo** [comment]
@qm3ster 
Your comment makes sense, webpack will replace all `process.env` to an env object `{...}`.
Although `UglifyJSPlugin` may remove some dead and useless codes, but the others may contain the duplicate codes of the env object, if the object is big, if will affect the bundle size and performance indeed.

**Comment by 0pt1m1z3r** [comment]
@mathieutu don't worry about mix. I can fix my PR after merge your PR.

full env object can be very big, and `process.env` can be use very often. So one code will be repeated many times and take up a lot of space.

**Comment by mathieutu** [comment]
Yeah it's relevant and I totally can understand that, but if we cannot handle a mix, ie replace directly `process.env.foo` to `bar` and replace `process.env` to `{foo: "bar"}`, I don't see any way to fix the issue `key = 'FOO'; process.env[key]`;

If we can do that, it will be perfect both for the bundle size and Uglify!

I'll try to test that today.

**Comment by mathieutu** [comment]
Hey!
I've tested a `yarn build` on my branch, and actually I can't reproduce what you said @0pt1m1z3r!

I've tried a 
```js
mounted() {
        //env: {FOO: 'baz}
        const key = 'FOO';
        console.log(process.env[key], process.env.FOO, process.env['FOO']);

        if (process.env.FOO === 'baz') {
            console.log('it should appear');
        }

        if (process.env.FOO === 'bar') {
            console.log('it should not appear');
        }
    },
```

and when I check in the webpacked file it appears as: 
```js
mounted:function(){console.log(Object({NODE_ENV:"production",VUE_ENV:"client",FOO:"baz"}).FOO,"baz","baz"),console.log("it should appear")}
```
which seams to be totally perfect!!

If your read at the [webpack documentation](https://webpack.js.org/plugins/define-plugin/): 

>Usage
>Each key passed into DefinePlugin is an identifier or multiple identifiers joined with ..
>
>    If the value is a string it will be used as a code fragment.
>    If the value isn't a string, it will be stringified (including functions).
>    **If the value is an object all keys are defined the same way.**
>    If you prefix typeof to the key, it's only defined for typeof calls.
>
>The values will be inlined into the code allowing a minification pass to remove the redundant conditional.

So for me it works perfectly out of the box! 🎉 

Do you agree?

**Comment by mathieutu** [comment]
I precise that in the light of the last finds, this PR should not be a breaking change, and could be merged in the next 1.* release! 😇

**Comment by 0pt1m1z3r** [comment]
@mathieutu I do not understand what you are trying to explain now.
Our PRs are different and they make different changes.
It will not be difficult for me to adapt my PR to your changes.

**Comment by 0pt1m1z3r** [comment]
@mathieutu Pay attention to this:
`process.env[key]`
replaced to
`Object({NODE_ENV:"production",VUE_ENV:"client",FOO:"baz"}).FOO`

**Comment by mathieutu** [comment]
@0pt1m1z3r I was answering to your comment https://github.com/nuxt/nuxt.js/pull/2974#issuecomment-371764782, where you told that by setting the whole env instead of each key, webpack replace the entire env at each time. I've tested and it's not the case, the default behavior of webpack handle that.

In my piece of code, you can see that when using the standard `process.env.FOO` and `process.env['FOO']` it works exactly the same. It is replaced by a whole object just when you want to take a env variable dynamically (it doesn't know what will be the key), like in the `const key = 'FOO'; console.log(process.env[key]);` example.

So it **doesn't alter the current usage and performances: the actual behavior is unchanged**. 

The question of nested env (which is in fact a webpack issue, and not nuxt's) is still here, but as you said, it comes easy to handle it.

**Comment by Atinux** [comment]
Could you try with key being imported from another file of more complex than being a string (could be done cacatenation with others variables), Webpack has a feature where it already knows what `key` value is when it’s simple operations.

**Comment by mathieutu** [comment]
In this example, it will be the same as in the dynamic `process.env[key]` so it will replaces `process.env` by all the env object. It will do that all the time in that case.

`console.log(Object({NODE_ENV:"production",VUE_ENV:"client",FOO:'bar'}})[a.a]` 
where a.a is a minified variable calculated by webpack.  

To summarize again:

- for  `process.env.FOO` and `process.env['FOO']` it works **exactly the same than before**.
- for `process.env[dynamicallyGeneratedKey]` it will replace by the all object. 

So, the performances are untouched for the static/standard/old way, and it just allows you to use the dynamic way, even if in this case the all object is used.

I've checked in other projects (React ones), and they have done it this way.

**Comment by mathieutu** [comment]
Here we go!
Last commit handle nested object performance, no need to change anything anymore @0pt1m1z3r! 😉

And for information, the replacement feature works with `foo.bar.baz`, `foo['bar'].baz`, `foo.bar.1.baz`, `foo.bar[1]['baz']`, etc... 

I've tested it manually, watching in the compiled files, and added some tests with the values you provided to be sure to handle all your cases: 
```js
env: {items: [{id: 1, name: 'Kobe'}, {id: 2, name: 'Michael'}], foo: {bar: {baz: 'hello', 'wi-fi': true}, 'a"-"b': {'b\'c': {}}}}
```
However, I do not know how to unit test the definePlugin feature and check what was replaced after webpack compilation..

Let me know if I can do something else guys!

**Comment by yoyo837** [comment]
waiting for this... :）

**Comment by mathieutu** [comment]
@Atinux @pi0 Hi guys, do you need something more to merge it, or is it just a matter of time ?

**Comment by pi0** [comment]
Hey @mathieutu. Sorry for late answering. Actually, this would be a really good enhancement for Webpack/Nuxt.js. But I have strong reasons to not directly including this for all users (and probably is not recommended)

First, nor webpack or web browsers had never any support for *Environment Variables* thing. This is just a magical hack of webpack's `DefinePlugin` to statically replace `process.env.*` during compile time. Such variables are not actually **variable** but just a **constant** value copied everywhere being used. An example that many users may wrongly use when using `process.env.object`:

```js
  data() {
    const a = process.env.object.obj.x
    const b = process.env.object.obj.y

    return { processEnv: process.env.object }
  }
```

This will actually compile into this:

```js
/* harmony default export */ __webpack_exports__["default"] = ({
  layout: 'custom-env',
  data: function data() {
    var a = {"bool":false,"string":"ok","num2":8.23,"obj":{"again":true}}.obj.x;
    var b = {"bool":false,"string":"ok","num2":8.23,"obj":{"again":true}}.obj.y;

    return { processEnv: {"bool":false,"string":"ok","num2":8.23,"obj":{"again":true}} };
  },
```

What if `env` object was bigger and used in many more places? 

Besides of that, this is probably not what you want: "runtime environment variables." We internally talked with the nuxt team and we may instead make a Nuxt module that supports real dynamic env variables using SSR hydration and also supporting `.env` files. Also if above behavior if what you **clearly want**, we can have a module for it :)

**Comment by mathieutu** [comment]
Hey @pi0 !

Sorry by I don't totally understand your point! 😅 

Firstly your example is wrong. If you're trying to compiled it you will have:
```js
data: function data() {
    var a = {"again":true}.x;
    var b = {"again":true}.y;

    return { processEnv: {"bool":false,"string":"ok","num2":8.23,"obj":{"again":true}} };
  },
```
and it's only because `x` and `y` don't exist in `obj`, It's *exactly* the same behavior without the PR.
If they do, you will directly have their value: `process.env.object.obj.again` will be directly compiled as `true`.

The only two things this PR change are:
- Dynamically call an env variable. (`process.env[dynamicallyGeneratedKey]`)
- Increase performance of nested object (see https://github.com/nuxt/nuxt.js/pull/2171 for explanation, it includes it)

If you want to transfer the whole env feature to a module, why not, but does it really worth it? Imo this is a pretty current need.

For .env file, a friend of mine have already done a module which is available in nuxt-comunity repo (but it can be perfected). 

I know I'm not a good English speaker, so maybe I don't succeed to make me understood,. If one a of the french brothers want to translate, we eventually could exchange in French... 😞

**Comment by renoirb** [comment]
Bonjour!

Hi all. This is a comment and my thoughts related to env vars and not an invalidation of the work done here. I'm sure we all want consistent behavior and I see this ticket looks like the one holding such a conversation.

I'm also, Trying to figure out how to properly handle SSR, Nuxt custom serverMiddleware and client side XHR using Axios that's used all over the place (serverMiddleware, SSR, client-side).

I agree that env variables aren't supported client side. 

 The intent, for many cases here, I assume, is to make nuxt service know at startup time what settings to use while using exactly the same code and build output.

Because maybe the same build artifact would run from staging.foo.example.org, as much as foo.example.org, than other domain names such as example2.org.

Domain names, TLS or not, API keys, and so on shouldn't be visible in build output.

Instead of  using a module that risk of getting mingled and become part of a build output, maybe by programmer mistake, why not having a server-side endpoint that exposes a selected list of key-values.

GET /env  and ONLY nuxt from server render knows this route and answers with the runtime values set.

Has there been attempts around this idea?

On my side, I'm making a PR to @clarkdo hare that might do just that.

(TODO; place links)

**Comment by galvez** [comment]
Following up on @pi0's comments, I believe this falls way off the Unix philosophy / standards. Environment variables aren't supposed to be nested objects, or objects at all. Unix environment variables cannot hold complex datatypes across platforms. Use `process.env.VAR` directly (in a server context) to access the fresh value of an environment variable. Nuxt's `env` is perhaps misnamed, but intended to provide environment-provided constants in server and client contexts, seamlessly.

Closing this for the time being. @Atinux @pi0 @clarkdo @manniL if you have further comments, please reopen.

**Pull request closed without merging**
