### PR TITLE
feat(webpack,cli): standalone build mode

### PR DESCRIPTION
**Pull request by pi0**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This PR implements @clarkdo idea (https://github.com/nuxt/nuxt.js/pull/4645#issuecomment-450365285) for standalone build mode and resolves #4645.

The `build.standalone` option is turned off by default to prevent any behaviour/breaking changes.

## Benchmarks

- Tested on bare-bone hello-world
- Cold start time is measured using the production build of nuxt. From reading config until `nuxt.ready()`
- Built on windows (Yeah I'm using windows again :P)

Normal build: 
- Size of `server.js`: `22 Kib`
- Cost of dependencies (`vue`, `vue-router`,  `lodash` (/omit), `vue-no-ssr`, `debug`): `7.4M`
- Cold start: `306.385ms`
- Memory usage: `29.9` MB (RSS: `106 MB`) 

Standalone build:
- Size of `server.js`:  `145 Kib`
- cold start: `306.550ms`
- Memory usage: `28.6 MB` (RSS: `106 MB`)

Results prove that there should be no big runtime diffs with the standalone mode. Still, we need to benchmark nuxt against real-world projects to decide on the default value.

## Remarks

- This is strange what dependency adds `lodash/omit` to the server bundle. Standalone build tree shakes only needed parts but should be still addressed
- We need to announce users to use `nuxt build --standalone` when they need to use it with `nuxt-start`. 
  - Alternative: For now we can add dependencies again to the `nuxt-start` distribution but it makes package bigger again

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by clarkdo** [comment]
In standalone mode, webpack will bundle all deps, but if 3rd party lib is using dynamic require, it may throw module not found error.

For example: [`consola` requires `winston`](https://github.com/nuxt/consola/blob/master/src/reporters/winston.js#L9), but `winston` is `devDependency`, so webpack will throw error when bundle `winston` into server bundle

**Comment by pi0** [comment]
@clarkdo Yes. That's a known problem of webpack with Node.js libraries like consola. We can whitelist some in standalone mode. But i don't recommend because it is dangerous in terms of a standalone build.

**Comment by aldarund** [comment]
What about when someone dont want ( or just updated nuxt from 2.3 to 2.4 and it will break) to use standalone mode, but rather just use nuxt start as solo production dependency. Then there still will be problem from #4645.

**Comment by pi0** [comment]
@aldarund I just mentioned this in PR body as an alternative option:

> Alternative: For now we can add dependencies again to the nuxt-start distribution but it makes package bigger again

But I assume it is a soft breaking change. We can make `nuxt-start` smarter to detect non-standalone builds and warn users.

**Review by aldarund — DISMISSED** [review]

**Review by galvez — DISMISSED** [review]
This is absolutely great.

**Review by atinux — DISMISSED** [review]

**Comment by pi0** [comment]
Updates:

- Dependencies for alternative approach added right into `nuxt-start` package (c664e3df7b2175d23e88e8c2df95c85ce005fcb1, https://github.com/nuxt/nuxt.js/commit/b5a0f788dc01ce60403835ffb59fa73978c21179)

- The mentioned extra import for lodash removed from server.js. (https://github.com/nuxt/nuxt.js/commit/6178c470ba81367e0c9f856b38781d270d65edfe). Reducing hello world's server size to `124 KiB` (Saving 21Kib)

**Comment by manniL** [comment]
We need docs for that, right? 🤔

**Comment by pi0** [comment]
@manniL please add todo but it is experimental for now :)

**Comment by Norserium** [comment]
@pi0, could you describe the current status of this future? It looks undocumented now.

**Comment by pi0** [comment]
Hi @Norserium it is indeed stable and being used for vercel serverless builder for a long time. I think there should be an open issue for documenting /cc @debs-obrien

**Comment by Norserium** [comment]
@pi0, yes i[t's](https://github.com/nuxt/nuxtjs.org/issues/499). But it's defined as an experimental mode.

**Comment by pi0** [comment]
That's why issue reopened ;)

**Comment by mercs600** [comment]
@pi0 how should I work with standalone option when modules defined in nuxt.config.js are required on demand ? Do we have some "whitelist" do tell the builder we want to use these specific module in standalone mode ?

**Comment by pi0** [comment]
@mercs600 You can instead move build-only modules to `buildModules` and list runtime modules in `modules` :)

**Comment by mercs600** [comment]
right! I forgot about buildModules, thanks ✋

**Pull request merged**
