### PR TITLE
v2.10.1

### PR DESCRIPTION
**Pull request by pi0**
### 🐞 Fixes

- `vue-app, webpack`
  - #6504 Remove consola from client
- `utils`
  - #6515 Fix error when `router.trailingSlash` is `false`
- `generator`
  - #6362 Remove trailing slash when no subFolders are used
- `webpack`
  - #6520 `chunkhash` and `contenthash` not work with `extractCSS`
- `cli`
  - #6525 Enable server for `nuxt build` when pages should be generated

### 🏡 Chore

- `readme`
  - #6511 Remove deprecated starter template

### ⚓ Dependency Upgrades

- `vue-meta`: Upgraded to [`v2.3`](https://github.com/nuxt/vue-meta/releases) which fixes duplicated tags in SPA mode

### 💖 Thanks to

- Dennis Herzberg (@dennis47528)
- Yuki Terashima (@y-temp4)

### CODE REVIEW

**Review by pimlie — COMMENTED** [review]
#6525 showed we have a serious gap in our tests. The danger of merging the fix without any tests to fill that gap is that adding those tests will be postponed indefinitely

Can we somehow add those tests (somewhat quickly) so we are releasing a fix which we can guarantee shouldnt happen again?

**Review by aldarund — APPROVED** [review]

**Review by galvez — APPROVED** [review]

**Review by TheAlexLichter — APPROVED** [review]

**Comment by vinayakkulkarni** [comment]
Lowkey hoping this gets released sooner than later.

Got few of my projects hanging on v2.9.x

**Review by pimlie — APPROVED** [review]
#6537 adds new tests which should mostly close the gap mentioned above

**Comment by clarkdo** [comment]
@pi0 The error comes from `memory-fs@0.5.0`. We're using `^0.4.2` now, so it should be safe to release.

**Pull request merged**
