### PR TITLE
feat: update outdated examples

### PR DESCRIPTION
**Pull request by clarkdo**

### CODE REVIEW

**Comment by clarkdo** [comment]
@Atinux @pi0 @alexchopin 
Could you please review the codes when you are available, many thanks!

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Thanks, @clarkdo for your time on contributing :) Meanwhile we add CircleCI integration as it is much faster and stable, the Travis improvements seems so good +1

**Comment by clarkdo** [comment]
Thank @pi0  for the patient review. BTW, I also submitted several pr about examples, can you pls help to take a look?

**Comment by pi0** [comment]
Sure. Done :)

**Comment by clarkdo** [comment]
Thank you very much!

**Comment by Atinux** [comment]
Thank you @clarkdo for your help :)

**Pull request merged**
