### PR TITLE
hotfix(vue-app): ReferenceError error passed with routeChanged

### PR DESCRIPTION
**Pull request by aldarund**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Fixes https://github.com/nuxt/nuxt.js/pull/4321/files/22b430cd61a9763cfcccaa42074707303b69dba7#r237040105

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Comment by clarkdo** [comment]
Should this pr be a hotfix ?

**Review by clarkdo — APPROVED** [review]

**Comment by aldarund** [comment]
It could be

**Comment by clarkdo** [comment]
> It could be

@aldarund Could you please make `fix-undef-err` based on `2.x` ?

**Comment by aldarund** [comment]
@clarkdo https://github.com/nuxt/nuxt.js/pull/4444

**Comment by clarkdo** [comment]
Close since #4444

**Comment by Atinux** [comment]
This one should be closed I guess, there is 200+ file changed

**Pull request closed without merging**
