### PR TITLE
feat: allow scrollToTop to be explicitly disabled

### PR DESCRIPTION
**Pull request by homerjam**
This enables us to manually override scroll position. For instance to offset scroll position before a transition.

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by manniL** [comment]
Hey @homerjam 

This would be a breaking change, so it won't be merged until Nuxt 3.0

However, you can adapt the `scrollBehavior` in your `nuxt.config.js` through the `router.scrollBehavior` key on your own :relaxed:

**Comment by homerjam** [comment]
Hi @manniL 

Thanks, I'm using that for now.

My mistake I thought that this wouldn't be a breaking change as I thought scrollToTop was undefined by default. Perhaps there's a better way in that case, something more explicit. To clarify my use case is for regular (or parent) page components as opposed to child components.

Feel free to close if you feel this could be improved. Though I'd be interested to know if anyone else has come across a need for this.

**Review by clarkdo — COMMENTED** [review]
@homerjam Could you add a unit test for it ? 😸

**Comment by manniL** [comment]
@homerjam It actually isn't a breaking change. Seems like I mixed something up there 🙈 Sorry! Kudos to @clarkdo for the follow up ;)

**Comment by homerjam** [comment]
I will when I can! Something along the lines of scrolling the page then checking the scroll position hasn't changed after a page navigation right?

**Comment by homerjam** [comment]
PR in the works

**Comment by galvez** [comment]
This is continuing in #4564 -- thanks @homerjam!

**Pull request closed without merging**
