### PR TITLE
inject ssrContext into createRouter and createStore

### PR DESCRIPTION
**Pull request by jasonc08**
I want to read the user agent before i select the component in the router, so I inject the ssrContext into the createRouter(). I think it may be useful if ssrContext is injected into createStore, therefore i also inject it into createStore().

in my router.js
```
export function createRouter (ssrContext) { 
 
  let userAgent = ''
  if(ssrContext)
    userAgent = ssrContext.req.headers['user-agent']
    else
    userAgent = navigator.userAgent 
```
If there is a better solution, please let me know, thanks.

### CODE REVIEW

**Comment by pi0** [comment]
req is available in nuxt global context too. I love the idea but i think would be better to pass the same context everywhere instead of a low level one which is only SSR only.

**Comment by jasonc08** [comment]
but how can i get the user agent in the createRouter(), since global.req returns null.

**Comment by Atinux** [comment]
Hi @jasonc08 

What do you need to use the `ssrContext` inside `createRouter`?

**Comment by jasonc08** [comment]
I need to get the user agent in order to determine it is a mobile device or a desktop. Some of the pages will share the same components, however, some of them will have mobile and desktop version of components. In the router.js, i want to set  { path: '/DetailPage',
component: ismobile? mobilecomponent : desktopcomponent}.

**Comment by qm3ster** [comment]
@Atinux should we nuke [`nuxt-community/router-module`](https://github.com/nuxt-community/router-module) since such feats are now possible with one's [bare goddamn hands](https://github.com/nuxt/nuxt.js/blob/20d16e8425d03f22dba30c05d377402be483b777/test/fixtures/module/router.js)?

**Comment by Atinux** [comment]
@qm3ster actually no it has to disable nuxt routing system, so it’s not that easy for new users (https://github.com/nuxt-community/router-module/blob/master/src/index.js)

**Pull request merged**
