### PR TITLE
Store generation

### PR DESCRIPTION
**Pull request by Granipouss**
https://github.com/nuxt/nuxt.js/issues/80

### CODE REVIEW

**Comment by Atinux** [comment]
Is it good to merge now @Granipouss ?

**Comment by Granipouss** [comment]
Well if it's good for you, it's good for me

**Comment by Atinux** [comment]
Great job @Granipouss 👏 

It will be in the next release, I will work on the doc to make it as clear as possible how to use it.

**Comment by Granipouss** [comment]
You're very welcome !
I'll continue to work on it, to add the possibiliy of nesting modules

**Comment by Atinux** [comment]
I don't think that nested module is required since it will let the possibility to create files inside a folder that won't be imported as modules.

**Comment by Granipouss** [comment]
Don't you think that it would be useful/cool to be able to have nest directories leading to nested modules ?

**Comment by Atinux** [comment]
Does Vuex allows more than 1 depth sub module? If yes, it might be a solution to work on it yeah :)

**Comment by Granipouss** [comment]
Yeah it's a brand new feature:
https://vuex.vuejs.org/en/modules.html
I think it goes with the namespacing

**Comment by Atinux** [comment]
Ok I didn't know it could go with more than 1 level, so you can work on the feature :)

**Pull request merged**
