### PR TITLE
feat(vue-app): trigger watchParam when param is changed in same route

### LINKED ISSUE #6235: Strange behaviour of nested pages
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/example-hello-world-kw5w9](https://codesandbox.io/s/example-hello-world-kw5w9)

### Steps to reproduce

1. Go to page `test`
2. Open Console. You will see console.log message each time when parent page was triggered
3. Press button 1-1-q. -> No messages. Works correct
4. Press button 1-2 -> Parent page was triggered. Incorrect
5. Press button 2-2 -> No messages. Works correct
6. Press button 2-2-q -> No messages. Works correct
7. Press button 2-2 ->  Parent page was triggered. Incorrect
 

### What is expected ?

Parent page should be triggered only on server side

### What is actually happening?

If you change only `params` or only `query` part of route everything works correct.
If you change `params` and `query` part  of routing simultaneously then parent page component will be triggered

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9645">#c9645</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Try to resolve #6235 , need more discussion.

Currently when dynamic path is changed (it means same route: like /test1 -> /test2 under /:test), we will always call asyncData instead of reusing, I'm not sure it this is in purpose @Atinux @pi0 .

~~After the pr, asyncData will be called in client side when:~~

- ~~route is changed (checking by from.name !=== to.name)~~
- ~~route is not change, but param is changed and watchQuery is true~~
- ~~route is not change, but query is changed and watchQuery is true~~

~~If current behaviour is correct and by design, how do you think adding a `watchParam` and make default value as `true` which means by default always calling asyncData when changing slug path.~~

I've changed this pr for adding `watchParam`

Behaviour after this pr:

- param is changed with same component, call asyncData
  - if only child param changed, call asyncData of child
  - if `watchParam` is false, `not` call asyncData of child 
- query is changed with same component, `not` call asyncData
- both param and query are changed with same component, call asyncData

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by Atinux** [comment]
It was on purpose to call `asyncData` when the param changes but the same Component is used (actually it's a feature I missed in vue-router and did not want to people to use `watch: $route`).

I like the idea of introducing `watchParam: false` to disable it (even if I don't see a real use case)

**Comment by clarkdo** [comment]
@Atinux Shared parent compoent may be a use case ? https://github.com/nuxt/nuxt.js/issues/6235

**Comment by clarkdo** [comment]
@Atinux According to `children.patch.browser.test`, it seemed that `asyncData` is not called when param is changed.

Current behaviour is:

- param is changed with same component, not call asyncData
- query is changed with same component, not call asyncData
- both param and query are changed with same component, call asyncData

I don't think it's a correct behaviour, with the current pr, behaviour is:

- param is changed with same component, call asyncData
- query is changed with same component, not call asyncData
- both param and query are changed with same component, call asyncData

What do you think ?

**Comment by Atinux** [comment]
I agree with the behaviour you describe, but we have to keep in mind about the Parent -> Child calls too,

- param is changed with same component, call asyncData
 - if only child param changed, call asyncData of child
- query is changed with same component, not call asyncData (expect if use `watchQuery`)
- both param and query are changed with same component, call asyncData

**Comment by galvez** [comment]
@Atinux @clarkdo is there anything left to do here other than update tests?

**Review by galvez — DISMISSED** [review]

**Comment by clarkdo** [comment]
@Atinux @pi0 Can you review this again ?

**Comment by msonowal** [comment]
@Atinux 
Why this is not merged till now as its a must have like watchQuery

**Review by pi0 — DISMISSED** [review]

**Review by atinux — DISMISSED** [review]
Approve but missing the docs PR :)

**Review by pi0 — APPROVED** [review]

**Pull request merged**
