### PR TITLE
feat(webpack): support `build.hotMiddleware.client`

### PR DESCRIPTION
**Pull request by wangxingkai**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
The `build.hotMiddleware` in the `nuxt.config.js` is not working.
According to the config section in the document of [webpack-hot-middleware](https://github.com/webpack-contrib/webpack-hot-middleware#client), the config for client should be set to the path in the webpack config. Currnently we don't have them in the path.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by pi0 — CHANGES_REQUESTED** [review]
HotMiddlware options are already set here:

https://github.com/nuxt/nuxt.js/blob/40fbe5ba47573341d17823219033fb05b567bab3/packages/webpack/src/builder.js#L212

**Comment by pi0** [comment]
@wangxingkai I still understand the use case for setting client options. But we can't stringify entire `hotMiddleware` option into client query string. Maybe using `build.hotMiddleware.client` ?

**Comment by wangxingkai** [comment]
> @wangxingkai I still understand the use case for setting client options. But we can't stringify entire `hotMiddleware` option into client query string. Maybe using `build.hotMiddleware.client` ?

Yep, sure. We still keep { log, path, heartbeat } in the `build.hotMiddleware`, and put all the client config inside `build.hotMiddleware.client`.

**Comment by pi0** [comment]
@wangxingkai Now what do you think of something like this:

```js
const clientOptions = {
  reload: true,
  timeout: 30000,
  name: this.name,
  path: `${this.options.router.base}/__webpack_hmr/${this.name}`,
  ...this.options.build.hotMiddleware.client
}

const clientOptionsStr = querystring.stringify(clientOptions).replace(/\/\//g, '/')

`webpack-hot-middleware/client?${clientOptionsStr}`
```

**Comment by wangxingkai** [comment]
@pi0 Looks simpler. but two things:
1. `path` and `name` may not want to be overridden.
2. `this.options.build.hotMiddleware` may be undefined.

I have updated this PR.

**Review by pi0 — DISMISSED** [review]
Seems great!

**Comment by pi0** [comment]
@wangxingkai would you please take a look at unit-tests?

**Review by pi0 — APPROVED** [review]

**Pull request merged**
