### PR TITLE
feat: move build to packages

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by pi0 — COMMENTED** [review]
Nice changes @clarkdo. But I wonder what if in the future we want to use `nuxt-build` like `nuxt-start` (An specific version for builder only). What's your idea to rename it with something like `nuxt-package` or `nuxt-packaging`?

**Comment by clarkdo** [comment]
package is good， will change it

**Comment by clarkdo** [comment]
@pi0 Changed to nuxt-pack, is that ok ?

**Review by pi0 — APPROVED** [review]
LGTM

**Review by TheAlexLichter — APPROVED** [review]

**Pull request merged**
