### PR TITLE
feat(cli): improve banner lines dx

### PR DESCRIPTION
**Pull request by pi0**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

- Alignments for OCD people like me
- Use cyan to keep consistent with all **informative** messages and avoid drawing attention
- The environment is `development` or `production` with notice of custom `NODE_ENV` if provided.

Before:

image

After (prod with custom `NODE_ENV`):

image

windows: (outdated)

image

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by clarkdo — COMMENTED** [review]
What will the banner look like if version is a long git string?

**Comment by pi0** [comment]
@clarkdo It is however only for our internal development not end-users :)

image

**Review by clarkdo — DISMISSED** [review]

**Comment by pimlie** [comment]
What is `mode: server-side`? I understand the first `Rendering: server-side` but `mode: server-side` doesnt seem to make much sense to me.

**Comment by manniL** [comment]
Maybe `ssr: enabled` / `ssr: disabled` instead? 🤔

**Comment by Atinux** [comment]
I am not found of using acronyms here since it targets also beginners, Rendering: server-side looks good :)

**Comment by manniL** [comment]
> I am not found of using acronyms here since it targets also beginners

..which should learn what SSR means anyway when they are using it through dynamic SSR or static site generation, right? 😋

**Review by atinux — APPROVED** [review]

**Pull request merged**
