### PR TITLE
fix(vue-app): decode router base to support unicode characters

### LINKED ISSUE #4948: router.base value with Extended unicode (åäö) fails
### Version

[v2.4.1](https://github.com/nuxt.js/releases/tag/v2.4.1)

### Steps to reproduce

`yarn create nuxt-app test_nuxt && cd test_nuxt` (I selected express and not much else)

Drop ```router: {
    base: "/%C3%B6l/",
  }``` 
intro you nuxt config. start a dev server. go to http://localhost:3000/öl. 

### What is expected ?

I expect the site to load properly from the /öl url. 

### What is actually happening?

you may see the page blink and disappear with a DOM tree mismatch hydration error in the console. mode: 'spa' doesn't work at all (it can't find the page). base addresses without weird characters work fine. 

my live nuxt site running at https://litteraturbanken.se/översättarlexikon/ exhibits another symptom: using the back button at any time throws up the 404 page. cannot reproduce this with a minimal example, however. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8606">#c8606</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by TheAlexLichter**
## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Resolves #4948

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by aldarund** [comment]
How about test ? :)

**Comment by manniL** [comment]
@aldarund 	WIP ;)

**Comment by aldarund** [comment]
What if they specify base: '/öl' - will it work? 
Also what if they specify non decodable uri base? How graceful error will be?

**Comment by manniL** [comment]
> What if they specify base: '/öl' - will it work?

It will. I can change the test to it if you want :relaxed:

> Also what if they specify non decodable uri base? How graceful error will be?

If you specify an URL base that's non-decodable, you should receive errors way earlier, as it has to go through the server first.

**Review by atinux — APPROVED** [review]

**Review by aldarund — APPROVED** [review]

**Review by pi0 — APPROVED** [review]

**Pull request merged**
