### PR TITLE
fix(vue-app): null check for `$root` access

### LINKED ISSUE #9149: Fallback to $root instance is not available - could be handled with null check
### Versions

- nuxt: 2.14.7 - 2.15.4
- node: 12.18.1

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>
Dependencies in nuxt.config - 
<details>
buildModules: [
        '@nuxtjs/vuetify',
    ],

    modules: [
        'nuxt-i18n',]

</details>

I recently tried upgrading to 2.15.4, but I am facing $root not available issue. 
While loading the application packages/vue-app/template/index.js file is being visited 4 times, but in the last instance $root is becoming undefined. I am not sure why.
The control is not going beyond - `const globalNuxt = this.$root.$options.<%= globals.nuxt %>` , as this.$root is not available. 

To resolve this, we can add a null check against this.$root.
What would rather work is -
```
const globalNuxt = this.$root ? this.$root.$options.<%= globals.nuxt %> : null // null check added
if (process.client && !globalNuxt && typeof window !== 'undefined') {
return window.$nuxt
}
```

### What is Expected?
$root & $nuxt to be available, in case if not - replacement should be provided

### What is actually happening?
In some instances $root is not being available - hence throwing error while loading the application

### PR DESCRIPTION
**Pull request by PayelKarmakar06**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Resolves:  #9149 

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Review by clarkdo — COMMENTED** [review]
Can you please provide more info about your issue and how can $root be undefined  ?

**Comment by SKhler** [comment]
I was lucky that i made Millions from Stocks today. That‘s enough for me! I don‘t wan’t Billions... i wan’t him!!! I‘m a bad Girl 💰💰💰


Gesendet von Yahoo Mail für iPhone


Am Mittwoch, April 14, 2021, 7:29 PM schrieb Xin Du (Clark) ***@***.***>:




@clarkdo commented on this pull request.

Can you please provide more info about your issue and how can $root be undefined ?

**Comment by PayelKarmakar06** [comment]
While loading the application packages/vue-app/template/index.js file is being visited 4 times, but in the last instance $root is becoming undefined. I am not sure why.
The control is not going beyond - const globalNuxt = this.$root.$options.<%= globals.nuxt %> , as this.$root is not available.

[(https://github.com/nuxt/nuxt.js/issues/9149)]
@clarkdo

**Comment by clarkdo** [comment]
The change itself looks fine, but I think it might hide the root cause which we'd better investigate.

/cc @pi0 @danielroe

**Comment by PayelKarmakar06** [comment]
It's a little urgent, we have to upgrade from nuxt@2.14.6 very soon to handle some of the vulnerabilities. Would it be possible for you to approve this PR and keep the issue ticket open to keep the root cause analysis under radar? @clarkdo

**Comment by clarkdo** [comment]
@pi0 @danielroe Any idea about this ?

**Comment by danielroe** [comment]
I agree with @clarkdo.

The issue (see also https://github.com/nuxt/nuxt.js/issues/8359) is likely a consequence of https://github.com/nuxt/nuxt.js/pull/8170.

@PayelKarmakar06 Could you provide a reproduction of your issue using https://template.nuxtjs.org?

**Comment by PayelKarmakar06** [comment]
@danielroe as I mentioned earlier, I am not sure why this is happening. I tried to provide a repro already, but was not able to.

**Comment by PayelKarmakar06** [comment]
Hi @danielroe / @clarkdo / @pi0,
Is there any possible way to proceed within providing the repro? It's a minimal change, and should not cause any side effect. I really need this change to be able to upgrade to the latest version of Nuxt.

**Comment by PayelKarmakar06** [comment]
@danielroe , is there any way to fix it without providing the repro?

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Having a reprodution would be much better but since it is an effect of recent refactor (#8170) let's have it. And sorry for delay @PayelKarmakar06. You can try it by using `nuxt-edge` package.

**Comment by PayelKarmakar06** [comment]
@pi0 thanks a lot!

**Pull request merged**
