### PR TITLE
fix: bundle resources other than js(x)/json in node_modules

### LINKED ISSUE #4060: SASS: tilde package reference is broken on SSR
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://github.com/ChristianKlee/nuxt-fonts-test](https://github.com/ChristianKlee/nuxt-fonts-test)

### Steps to reproduce

Install nuxt-fonts-test and switch between my master (Nuxt 2.1) and nuxt-142 (Nuxt 1.4.2) branch to see the error.

### What is expected ?

The font of a NPM Module (in this example node_modules/test/Charmonman.ttf) are included and after a nuxt generate in the dist folder

### What is actually happening?

Error Message "SyntaxError: Invalid or unexpected token" on nuxt and nuxt generate.

### Additional comments?

Since Nuxt 2.0 it isn't possible to use an NPM package as a style library with fonts. 
The reproduction link based on create-nuxt-app with the only addition to include a global sass file and a custom NPM module "test" with a font.
If I comment line 3 of screen.scss everything runs fine, without the included font-family.
On all version before Nuxt 2.0 it was possible to include such a NPM module. 
Based on the release notes, I can't identify this as a feature/different implementation but maybe I overlook something.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7917">#c7917</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Fix #4060

Disable webpack-node-externals for resources which are not js/jsx/json, like: images, fonts or videos

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by manniL** [comment]
Do we need to include `ts`/`tsx` as well?

**Comment by clarkdo** [comment]
ts needs to be transpiled by ts-loader, maybe should exclude when use ts-node

**Comment by Atinux** [comment]
I may have some doubts about this, since Vue is actually having this rule as well, may be worth asking Vue team too

**Comment by clarkdo** [comment]
It's for server side bundle, does vue have same case ?

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
I agree about this change since:
1. Server bundle should only contains js/json
2. Other resources should be whitelisted to their reference be correctly resolved

**Review by galvez — APPROVED** [review]

**Review by atinux — APPROVED** [review]

**Review by TheAlexLichter — APPROVED** [review]

**Pull request merged**
