### PR TITLE
fix(webpack): allow files with `.cjs` extension to be transpiled

### LINKED ISSUE #10339: Javascript files with .cjs extension can not be transpiled
The pattern used for babel-loader doesn't include the `.cjs` extension thus trying to transpile a module that has *.cjs export doesn't have an effect.

See also https://github.com/unjs/ufo/issues/50

### Versions

- nuxt: 2.15.8
- node: 14

### Reproduction

Try to use anything from `ufo` on the client-side. The resulting bundle will include a spread operator but should be transpiled because Nuxt transpiles `ufo` by default (https://github.com/nuxt/nuxt.js/blob/777a4b7f5033c86c37cbd93008f3ca792e4af8bc/packages/webpack/src/config/base.js#L78-L78).

### What is actually happening?

https://github.com/nuxt/nuxt.js/blob/777a4b7f5033c86c37cbd93008f3ca792e4af8bc/packages/webpack/src/config/base.js#L332-L332

### PR DESCRIPTION
**Pull request by rchl**
Fixes #10339

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Not sure if you consider it a bug fix or a feature but it seems like a bug to me.

Resolves #10339

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Comment by rchl** [comment]
There is also this line that maybe should be updated also:

https://github.com/nuxt/nuxt.js/blob/4f87ed0ca1d57edd9b6882ce824f799f31128255/packages/webpack/src/config/base.js#L242-L242

@clarkdo

**Comment by danielroe** [comment]
@rchl Agreed. Would you update that one as well?

**Review by danielroe — APPROVED** [review]

**Review by DraftProducts — APPROVED** [review]

**Comment by rchl** [comment]
Any plans to merge and release a new Nuxt 2 version?

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Thanks for working on this pull request @rchl and sorry it took long to merge. CI was failing because of dependencies. And indeed we plan to make at least two minor versions for Nuxt 2 and including this fix as well.

**Pull request merged**
