### PR TITLE
fix(nuxi): allow nuxt.config and module setup to use `process.dev`

### PR DESCRIPTION
**Pull request by harlan-zw**
### 🔗 Linked issue

-

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

To check whether Nuxt is running in development, you can use the `process.dev` flag. 

This works as expected at runtime. However, when using the same flag at build time, the result will be undefined (see https://stackblitz.com/edit/nuxt-starter-jev4hu?file=nuxt.config.ts).

The recommendation is to use `nuxt.options.dev`, but for consistency, we should override this environment variable when we set the `NODE_ENV` as well.

This isn't exactly a bug, just something that has just caught me out.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
I would suggest using`isDevelopment` from `std-env` for a standard way to check this. `process.dev` shim was only introduced in runtime to allow tree-shaking.

**Comment by harlan-zw** [comment]
I don't think this is a great recommendation for modules, modules would need to explicitly include std-env as a dependency just for this check which could result in version conflicts (unless marked as external).

We have nuxt.options.dev which is fine, but IMO a consistent API is favorable.

**Comment by danielroe** [comment]
My worry would be that we don't want to obscure the differences between build-time and runtime code, which otherwise we're at great pains to establish (e.g. not importing `@nuxt/kit` in runtime code, etc.).

> A valid use case for a consistent API is when build-time and runtime code is shared. For example when emitting assets after prerendering is finished. (i.e nuxt-simple-sitemap, nuxt-og-image)

I think this is something we should think about - what about a utility that can run + require code 'within' a nuxt context? Or code registered in a nitro (runtime) plugin that runs after a build is complete. I think storage/bundled storage solves some of this but maybe worth brainstorming some ideas....

**Comment by harlan-zw** [comment]
> My worry would be that we don't want to obscure the differences between build-time and runtime code, which otherwise we're at great pains to establish (e.g. not importing `@nuxt/kit` in runtime code, etc.).
> 
> > A valid use case for a consistent API is when build-time and runtime code is shared. For example when emitting assets after prerendering is finished. (i.e nuxt-simple-sitemap, nuxt-og-image)
> 
> I think this is something we should think about - what about a utility that can run + require code 'within' a nuxt context? Or code registered in a nitro (runtime) plugin that runs after a build is complete. I think storage/bundled storage solves some of this but maybe worth brainstorming some ideas....

This is better for targeting the root issue.

Have moved to a discussion here: https://github.com/nuxt/nuxt/issues/22255

**Pull request closed without merging**
