### PR TITLE
feat: allow disabling loading-screen

### PR DESCRIPTION
**Pull request by pi0**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Following up #6026. Adding the ability to disable loading-screen.

- Loading-screen (and indicator as depends on it) will be disabled by default for production and non-cli usages
- Retry strategy will be applied as a fallback if disabled. It also handles development mode errors.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by clarkdo** [comment]
To whom needs a hacky way to disable the module before this pr is released:

```js
  // nuxt.config.js
  export default {
    hooks: {
      config(options) {
        options.buildModules = options.buildModules.filter(
          module => module[0] !== '@nuxt/loading-screen'
        );
      },
    },
  };
```

**Comment by rinu** [comment]
Please remove my name from this. I haven't written any of this and it's not even close to what I wanted.

**Comment by clarkdo** [comment]
@rinu 
image

**Comment by clarkdo** [comment]
@nuxt/core-team From what I can see, `stale bot` bring more unexpected works than convenience, what do you think remove it ?

**Comment by galvez** [comment]
@pi0 mind if I pick this up?

**Comment by pi0** [comment]
@galvez sure. feel free adding more commits to my branch :) (just please assign yourself before)

**Review by clarkdo — APPROVED** [review]

**Comment by calebjclark** [comment]
@pi0 thanks for working on this loadingScreen feature. I just used it in my project, and it works great.

Should this be added to the website documentation? I had to read through your code to figure out how to use it.

Also, it should probably be added to @nuxt/types. I'm using typescript, which required me to add the hacky @ts-ignore:

```js
import { Configuration } from '@nuxt/types';

const config: Configuration = {
  build: {
    // @ts-ignore
    loadingScreen: false,
  }
};

export default config;
```

**Comment by manniL** [comment]
@calebjclark PRs are welcome ;)

**Pull request merged**
