### PR TITLE
feat: server.timing for Server-Timing

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Review by pi0 — DISMISSED** [review]
Cool! @clarkdo :+1:

**Comment by pi0** [comment]
Mini docs:

Enabled `server.timing` option (disabled by default) adds a middleware to measure SSR generate time and add it to headers ('Server-Timing')

**Review by pi0 — APPROVED** [review]

**Comment by fatlinesofcode** [comment]
@clarkdo this works great for when i used nuxt dev but i cant see the timing when i used production e.g. nuxt build && nuxt start

If there something else we have to do get the timings in production mode?

**Comment by clarkdo** [comment]
@fatlinesofcode Hi, can you provide a reproducible repo?

**Comment by fatlinesofcode** [comment]
hi @clarkdo  thanks for the reply.

I forked the hello world repo and im able to replicate the issue
https://codesandbox.io/s/example-hello-world-3q0d6

When running a lighthouse audit i can see the timing measure in the report using dev but not in production.

Screen Shot 2019-09-04 at 5 16 09 pm

**Comment by fatlinesofcode** [comment]
example in dev mode 
https://codesandbox.io/s/example-hello-world-7z1fk

Screen Shot 2019-09-04 at 5 21 02 pm

**Comment by clarkdo** [comment]
Thanks, I’ll look into it within this week🙏

**Pull request merged**
