### PR TITLE
fix(nuxt): expose internal nitro type alias

### PR DESCRIPTION
**Pull request by danielroe**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

`useStorage` is currently not typed in a Nuxt project as internally the `#internal/nitro` type is used in the Nitro auto-imported `useStorage`. This PR provides a missing alias that allows that to be typed properly.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
I'm worried by this, we also expose internal types from subpaths that can be changes in non semver-major. Is there anything better we can do to expose utils like `useStorage` from a subpath like `nitro/runtime` maybe.

**Comment by danielroe** [comment]
The issue is the Nitro type for `useStorage` references the internal alias. Maybe it can use a relative path instead?

**Comment by danielroe** [comment]
@pi0 Any further thoughts on this? I would like to merge this or resolve the bug upstream.

**Comment by pi0** [comment]
We shouldn’t expose internal types of nitro. We should probably fix in upstream exporting public import types :)

**Comment by danielroe** [comment]
The upstream problem to be solved is that the upstream [generated `.d.ts`](https://unpkg.com/browse/nitropack@2.2.3/dist/runtime/index.d.ts) relies on the internal alias:

```ts
export { useStorage } from "#internal/nitro/virtual/storage";
```

**Comment by pi0** [comment]
Indeed. And it shouldn't (not are virtuals are to be exposed but some like `useStorage` are and should have been outside).

**Comment by danielroe** [comment]
~> https://github.com/unjs/nitro/pull/1026 🙌

**Pull request closed without merging**
