### PR TITLE
fix: infinite loop if error page contains error

### LINKED ISSUE #4140: error.vue infinite loop
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://codesandbox.io/s/vvz3072j15](https://codesandbox.io/s/vvz3072j15)

### Steps to reproduce

1. Create custom error.vue that contains an error
2. trigger error.vue
3. notice the infinte error loop

### What is expected ?

something catches the error

### What is actually happening?

catches and attempts to load the error.vue infinitely

### Additional comments?

The main issue is that the API for the `error` prop being passed to the error.vue page has changed. Before 2.x, it was expected that `error.response` was available. Anybody that was using this, ie: `error.response.data` now have this error. There should be a notice to nuxt users so they are aware of this API change.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7995">#c7995</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by TheAlexLichter**
Resolves #4140 (maybe.. soon 🙈)

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by nobuyuki1965** [comment]
Help

**Comment by husayt** [comment]
Have stumbled on this the other day. Now I see what it causing this. Thanks @manniL

**Comment by pimlie** [comment]
Maybe it feels a bit hacky, but you could wrap the render function of the NuxtError component with a try/catch:
```js
    import NuxtError from '../../layouts/error.vue'

    const render = NuxtError.render
    NuxtError.render = (...args) => {
      try {
        return render.call(NuxtError, ...args)
      } catch(e) {
        console.warn(e)
      }
    }
```

This catches the error. Then you could probably also add a nuxt error wrapper component that either loads the custom error page if that works, or the default nuxt error page when that component is broken.

**Comment by galvez** [comment]
@manniL is there still work to be done here?

**Comment by manniL** [comment]
@galvez There is, yes :see_no_evil: I wasn't able to find a nice solution for the problem posed in the actual issue :frowning_face:

**Comment by mtltechtemp** [comment]
@manniL Any news?

**Comment by manniL** [comment]
Tried changes from @pimlie but still am kinda stuck on that. Feedback, contributions and ideas welcome!

**Comment by manniL** [comment]
Closing here for now. If anybody has an idea, feel free to pick it up here!

**Pull request closed without merging**
