### PR TITLE
fix(schema): pin jiti until babel bug is resolved

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

https://github.com/nuxt/nuxt/issues/25000
https://github.com/nuxt/nuxt.com/issues/1415

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This temporarily pins `jiti` to ensure we can generate comments from docs, until the upstream issue is resolved.

(Seems likely an issue in Babel itself, but we need to reproduce and file if possible.)

cc: @manniL, @pi0 

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
Have you tried https://github.com/nuxt/nuxt.com/issues/1415#issuecomment-1858520738 as fix in untyped?

**Comment by danielroe** [comment]
Oops, sorry for the review ping. No, I didn't try that.

**Comment by pi0** [comment]
It can be dangerous if we hide jiti v1 possible regressions for Nuxt to be caught in monorepo because of this.

**Comment by danielroe** [comment]
Indeed, that's true. We could also pin this only before releasing/building schema 😆

**Comment by pi0** [comment]
Checking issue now let's see if we can solve it easily otherwise sure pinning only for schema makes sense as hotfix 👍🏼

**Comment by pi0** [comment]
🐛 https://github.com/unjs/untyped/commit/7a941412c2ca6c78f1fc1bc6a7fb9f2701d4be2a

**Pull request closed without merging**
