### PR TITLE
feat(vue-app): remove __layout element

### PR DESCRIPTION
**Pull request by hgl**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Description

As discussed previously, `__layout` element isn't necessary. This PR removes it. Since it's a breaking change, PR is sent to Nuxt 3.

@Atinux 

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Review by clarkdo — COMMENTED** [review]
We can add a temporary option for disabling `__layout` and compatibility in 2.x, then remove both of them in 3.

**Comment by Atinux** [comment]
Sounds good @clarkdo

**Comment by manniL** [comment]
I see an opportunity here to somehow provide a workaround for #3877 by providing a named class/id instead of just `__layout`🤔

**Comment by Atinux** [comment]
Something like this @manniL ?

```js
const templateEl = h('div', {
  domProps: {
     class: 'layout-' + this.layoutName
  },
  key: this.layoutName
}, [ layoutEl ])
```

**Comment by manniL** [comment]
@Atinux Exactly ☺️ (now we just have to ensure that the layout name can be used as valid css class, e.g. by stripping spaces

**Review by pi0 — COMMENTED** [review]
I think makes sense merging this for v3 :)

**Comment by pi0** [comment]
Hi, @hgl thanks again for your contribution. As we are doing a full rewrite for vue-app, I'm going to close this PR but the unnecessary class will be removed.

**Comment by BobbyJonas** [comment]
It's been two years. and I've met the same problem.
How're things going now

**Comment by pi0** [comment]
Check out Nuxt 3. Layout is an opt-in component: 

- https://v3.nuxtjs.org/guide/directory-structure/layouts
- https://github.com/nuxt/framework/blob/main/packages/nuxt/src/app/components/layout.ts

**Pull request closed without merging**
