### PR TITLE
docs: add not about vue-tsc

### PR DESCRIPTION
**Pull request by cljamal**
Added a note about vue-tsc, since nuxt3 doesn't work with vue-tsc version 2, I lost a lot of time searching for a solution, I hope this little note helps others and saves a lot of time.

### CODE REVIEW

**Comment by danielroe** [comment]
I think there are a few bugs in the latest `vue-tsc` but it is working in this monorepo (we've updated and run tests with it).

Any issues should probably be raised in http://github.com/vuejs/language-tools - they may already have been resolved.

**Comment by cljamal** [comment]
@danielroe Hi!
It's not work in fresh install: https://stackblitz.com/edit/nuxt-starter-pgvktu?file=package.json

**Comment by mseeley** [comment]
Agreed, the works for me attitude is frustrating. It's definitively _not working_ for Nuxt users who refer to Nuxt's documentation.

At least update the docs that "Hey, everyone of you that enables `typeCheck: true` will run into this bug. We know, it sucks, but it's not us. Please see [this link]() for more information."

**Comment by danielroe** [comment]
We did add a note to the docs. See the PR linked at https://github.com/nuxt/nuxt/pull/26083

**Comment by mseeley** [comment]
Timing is impeccable. Thank you @danielroe. I just noticed the same and came back here to correct my comment. 🙇

**Pull request closed without merging**
