### PR TITLE
perf: use flatstr for SSR

### PR DESCRIPTION
**Pull request by galvez**
Seems we can take advantage of [flatstr](https://github.com/davidmarkclements/flatstr) for SSR?

### CODE REVIEW

**Comment by pi0** [comment]
I think before that we need benchmarks with different Node.js versions and platforms :)

```
// You may be tempted to copy and paste this, 
// but take a look at the commit history first,
// this is a moving target so relying on the module
// is the best way to make sure the optimization
// method is kept up to date and compatible with
// every Node version.
```

**Comment by pi0** [comment]
Besides the risks, in their docs it is mentioned: 

> The best place to use flatstr is just prior to passing it to an API that eventually runs non-v8 code (such as fs.WriteStream, or perhaps xhr or DOM apis in the browser).

We don't! We concatenate `HEAD` and `APP` before sending response :)

Also:

> calling flatstr too much can in fact negatively effect performance

Simply with more concurrency, we are calling it too much

**Comment by galvez** [comment]
> We don't!

We don't what? I think HTTP write streams are affected by this if fastify is to be believed :)

> We concatenate HEAD and APP before sending response :)

I think you're supposed to run it on a concatenated string.

Also, re: compatibility, it seems to work for our supported Node versions :)

**Comment by galvez** [comment]
> Simply with more concurrency, we are calling it too much

I'm interested in a benchmark, I'll try this out soon. Let's keep it in standby for now :)

**Comment by galvez** [comment]
@pi0 FWIW it seems `fastify` does use `flatstr` for concurrent requests :)

**Comment by pi0** [comment]
> We don't what? I think HTTP write streams are affected by this if fastify is to be believed :)

We don't directly send these strings to stream. We do a concat before that! This optimization can be done on the final string i think. 

> Also, re: compatibility, it seems to work for our supported Node versions.

Yes and No. Perf improvement is not guaranteed and also about next V8 versions which can be even backported.

> I'm interested in a benchmark, I'll try this out soon. Let's keep it in standby for now :)

Sure :) (however could be a simple issue/RFC or draft PR before asking review on something which is not tested)

> FWIW it seems fastify does use flatstr for concurrent requests.

Fastify is designed/optimized for API. Nuxt is working with SSR rendered content. Of course, both use Node.js.

**Comment by galvez** [comment]
> We don't directly send these strings to stream. We do a concat before that!

Gotcha, I moved it to `renderTemplate()` now and will benchmark :)

**Comment by galvez** [comment]
@pi0 My benchmark didn't show any significant different. Tried in multiple settings and two computers. Withdrawing this PR :)

**Pull request closed without merging**
