### PR TITLE
⚡️ Upgrade to Vue 2.3.x 

### LINKED ISSUE #632: ⚡️ Upgrade to Vue 2.3.x
Hello guys. I've opened this one trying to help making upgrade progress faster. Feel free closing if you are internally working on this. Following list is according to [2.3.0 release notes ](https://github.com/vuejs/vue/tree/v2.3.0) and [new dedicated Vue SSR guide](https://ssr.vuejs.org).

- [x] Allow [runInNewContext](https://ssr.vuejs.org/en/api.html#runinnewcontext) option. which can bring huge performance improvement in production.
- [x] `vue-ssr-webpack-plugin` is deprecated. ([webpack plugins](https://ssr.vuejs.org/en/api.html#webpack-plugins))
-  [x] [Generating clientManifest](https://ssr.vuejs.org/en/build-config.html#generating-clientmanifest)
- [x] ~~Vue 2.3.x broke middleware in dev #636~~ (seems working)
- [x] Duplicate assets in client manifest entry point
- [x] CI Fails with infinity wait with new vue-loader (12.x)
- [x] [server side directives](https://ssr.vuejs.org/en/api.html#directives)
- [x] New [CSS Management](https://ssr.vuejs.org/en/css.html)

### PR DESCRIPTION
**Pull request by pi0**
closes #632

### CODE REVIEW

**Comment by pi0** [comment]
When using `renderScripts()` according to [Manual Asset Injection](https://ssr.vuejs.org/en/build-config.html#manual-asset-injection) it has a strange problem which adds duplicate <script> tags: (tested with nuxt starter template) . (HTMLPlugin's `inject` option is also disabled) 

image

@alexchopin @Atinux Would you please check current implementation if i had missed anything?

**Comment by pi0** [comment]
Implementation is *almost* done :) I've tried to add comments for some special commits. 
@alexchopin @Atinux Can you please check if things are correct so i could work more if needed :)

**Comment by Atinux** [comment]
This is awesome @pi0 

I will take a deep look at it very soon.

**Comment by clarkdo** [comment]
look forward to amazing improvement

**Comment by Atinux** [comment]
Hi @pi0 

I have issue for including the CSS when used as global (try to run `bin/nuxt examples/global-css/`), it is not inlined, any idea?

**Comment by pi0** [comment]
Find out! Will open PR soon :)

**Comment by Atinux** [comment]
Awesome @pi0

**Pull request merged**
