### PR TITLE
babel: target current node in SSR builds

### PR DESCRIPTION
**Pull request by whtsky**

### CODE REVIEW

**Review by pi0 — CHANGES_REQUESTED** [review]
I think this might make some inconsistencies between different build environments. Node 8.x is already enough for needed things like async/await, arrow functions and const. Also sticking to LTS ensures there are no problems until next LTS :)

**Comment by whtsky** [comment]
IMO people usually use same node version in their build env and (production) runtime env, targeting node to current version will let user benefit from using latest, non-LTS node versions

**Comment by pi0** [comment]
@whtsky OK, but some important concerns:

- How can we **ensure** that people are using same node version for Dev, CI and production envs ?
- What benefits with using `current` instead of `8.0.0` will we actually have?

Another note, Nuxt dist itself is bundled against 8.0.0 using rollup as we require 8.0.0 as the minimum supported version in `package.json`. So this may make things more unpredictable.

Also presets is configurable using a function with `nuxt.config.js`:

```js
build: {
 babel: {
   presets({ isServer }) {
      // Return a customized preset
   }
 }
}
```

**Comment by whtsky** [comment]
* we can't. But node is not fully backward compatible, so running different versions for Dev, Ci & Prod would be an issue anyway. And I think it's really unlikely to have problems since babel should handle it perfectly.
* there's no actually benefits right now, but I think it's cool if there's a new Node version and I can use the new features natively w/o transpiles in my nuxt app by simply upgrading node version

**Comment by pi0** [comment]
> But node is not fully backward compatible

I think it's more likely to be LTS backward compatible rather than forward compatible :))

Anyway, i agree with you. Less transpilation and preferring native version is always so nice. Especially currently the browser version is not configurable enough at least in a gentle manner. What's your idea if you change this PR to make target configurable like this:

nuxt.config.js

```js
{
build: {
  target: {
    client: { ie: 9, uglify: true }, // Can be customized
    server: { node: '8.0.0' } // Can be customized
  }
 }
}
```

**Comment by whtsky** [comment]
looks great. It's late in China so I'll do it tomorrow :)

**Comment by pi0** [comment]
Cool. Thanks for your help :)

**Comment by simllll** [comment]
just use this in your nuxt.config.js and it should do what you like to have ;).

```
 babel: {
        presets: function(isServer) {
            return [
                [
                'vue-app', {
                    useBuiltIns: true,
                    targets: isServer ? { node: 'current' } : {ie: 9, uglify: true}
                }]
            ];
        }
    },
```

regards
Simon

**Pull request closed without merging**
