### PR TITLE
fix: fallback should always be a string

### PR DESCRIPTION
**Pull request by pimlie**
The SPA fallback option should always be a string, if in the user configuration it was specified as boolean true it should have been replaced by the default string value (currently 404.html) in lib/common/options.js

Added test on empty string fallback option

Added missing test for custom fallback option spa-fallback.html

### CODE REVIEW

**Review by galvez — APPROVED** [review]

**Review by clarkdo — APPROVED** [review]
LGTM

Actually `fallback` will never be `true` due to https://github.com/nuxt/nuxt.js/blob/dev/lib/common/options.js#L183-L185


Do you think will it be better give user a warn if fallback is empty string and also use `fallback !== ''`?

**Comment by pimlie** [comment]
@clarkdo Not sure if you are asking me or politely telling me. As I have no preference, please just tell me ;)

But let me take the opportunity to mention that by times I find it difficult to follow which code style guidelines Nuxt exactly uses (not talking about lint here of course). Because some code style guidelines would also require the return statement to be on a new line for better readability and also maybe require to always use block statements for conditionals. Eg like this:
```js
if (typeof fallback !== 'string' || fallback === '') {
  return
}
```
To be really nitpicking, why do we return preemptively without a log message? Although its a common technique to limit the number of indentations, I find such structures always confusing when I am reading new code. 
Also it was actually me who called that method `afterGenerate` as at that time I thought we needed a generic method to do 'clean-up'-things after generating, but to be honest I always disliked the method and its name. I already looked a couple of times in removing that method, but thats just not possible without restructuring the generator class quite a bit. Because also, why dont we check for any errors when rendering the spa route? Personally I dont see why we need a separate methods for generating routes and the spa fallback because that leads exactly to the issue we have now that there is no error handling in one of the cases.

Following up with the `hookWithTimes` method you proposed in my other pr, often that `afterGenerate` method would be split in a minimum of 3 methods, eg something like: `afterGenerate`, `hasSPAFallback` and `generateSPAFallback`:
```js
async afterGenerate() {
  if (this.hasSPAFallback()) {
    this.generateSPAFallback()
  }
}
```
Looking at the Nuxt codebase I just was not sure to which level we should split all the functionality, sometimes it seems a very pragmatic approach is taken (only implement what you need and only separate what is used more then once) and sometimes not (as in more by the theoretical book).

Anyway, not trying to be annoying but just something that was on my mind for some time. Sorry for that :)

**Comment by clarkdo** [comment]
My comment in review comment is just a question not asking you change it, sorry for my English.

Regarding to the codes separations, my personal opinion is that we separate methods when the single method can be reused and own single responsibility. The reason why I suggest having hookWithTimes is that a more meaningful named method may have better user experience, such like jest: toHavenBeenCalled and toHaveBeenCalledWithTimes, but this is just my personal opinion, it doesn’t represent Nuxt. Maybe I’m wrong(It’s often), but I believe we have same faith to make Nuxt better and I think we will make it through our discussion. 
At last, sorry for the comment format because I’m using phone.

**Comment by Atinux** [comment]
Good for me, thank you for improving Nuxt.js @pimlie 

You are a valuable contributor. It's a bit hard to keep the same code gudielines when we are a team that are all working remotely but we are improving it with times and are open to improve it too :)

**Comment by clarkdo** [comment]
And about the `hasSPAFallback` example, I also believe it's definitely unnecessary to separate the methods, because:

1. It has been simple and owned single responsibility enough
1. We don't have the requirements to reuse and extend/override them
1. They won't be exposed to users

The code style guidelines you talked about, I think it's very hard to form a unified coding style for uncommercial open source project like Nuxt. The community is a loosely orginisation, every contributor event core team member like @Atinux @pi0 has different background and experience in technical field and we all can only spend our spare time on it, so we must have diffenrent opinions and solutions on a same issue, but I think what we can do is trying to discuss and choose the proper one of all solutions for making project better and easier for users.

Actually I have to admit I'm not good enough in both technology and communication, sometimes I may make some picky comments, but please believe that I am not a impolite person at all, maybe it because my poor English makes you uncomfortable. I'm really realy very sorry for the impact brought to you.

**Comment by pimlie** [comment]
@clarkdo Absolutely no need to apologize, I actually really dont mind you telling me what I need to change. At least, not when it comes to Nuxt. Now if you would e.g. start telling me what I need to have for dinner I might have a problem with that unless you also plan to cook that dinner for me ;)
The reason I asked if you were 'telling me' was because that's just a common misconception between native English speakers who are more polite/formal and Dutch people like myself who are often not so formal. So no hard feelings, your English is good enough to make me think you are a native speaker!

Btw its not that I dont agree with what you are saying, its just that I find it sometimes difficult to understand with opensource projects (like Nuxt) which design patterns I should follow. Often I rely on looking at existing code, but as said with Nuxt that sometimes doesnt bring the enlightment I hoped for. And that's not a bad thing perse, there are many valid reasons why that came to be as Sebastien and you mention, which I all perfectly understand. But in the long run I think any opensource project should stay aware of this as if it gets too out of hand the code base could become too much spaghetti :spaghetti: 

With regards to `hasSPAFallback`, standard OOP would be to separate this anyway. We are not just programming for what we need now but also what someone else might need in the future. Separating the logic in separate methods to the extend in my pseudo example is much more flexible and makes it easier for other developers to implement their specific requirements.
E.g. I have seen quite a bit of feature requests to be closed because it should be implemented as a separate module. Following OOP and separating logic more than just to the extend what we (as in Nuxt Core developers) need makes it easier for other developers to implement their changes. We dont know what some developer in the future might need, so thats why OOP would normally separate those methods anyway as a precaution.

But maybe I am over thinking this, I dont know. 

And to clarify, nothing I say is meant as critique and I apologize in advance if it appears like that. Just trying to have an open discussion on some thoughts I was having.

**Pull request merged**
