### PR TITLE
fix(webpack): enable devtool for dev mode

### PR DESCRIPTION
**Pull request by clarkdo**
## Description

TODO:
- [ ] Test dev mode memory usage
- [ ] Update doc for default value

### CODE REVIEW

**Comment by pimlie** [comment]
What exactly is the default value currently? Would it be an idea to just set it to `cheap-module-eval-source-map` by default as for the server build?

I tried this locally but think the errors are still not as helpful as they can be

**Comment by clarkdo** [comment]
I think the default value of webpack may have more consideration and try to keep best practice in both readability and performance. And this config can be easily set via nuxt.config as well.

**Comment by clarkdo** [comment]
The default value is eval in dev mode which includes almost everything in source code

**Review by aldarund — DISMISSED** [review]

**Comment by pimlie** [comment]
Looking at https://webpack.js.org/configuration/devtool/, wouldnt it be best for DX to have at least the `original source` quality by default? `eval` has the quality `generated code` which is still not really helpful right?

As you said, if performance is an issue users can always set it back to `eval` themselves

**Review by pimlie — APPROVED** [review]
LGTM, thanks!

**Review by TheAlexLichter — APPROVED** [review]

**Review by aldarund — APPROVED** [review]

**Pull request merged**
