### PR TITLE
Fix file permission in `lib` and `test`

### PR DESCRIPTION
**Pull request by shirohana**
There's no reason to let them executable

_modified files:_

### CODE REVIEW

**Comment by shirohana** [comment]
Oh my god, how can I fail the tests by changing these file permission!?

**Comment by shirohana** [comment]
I've run tests several times locally, sometimes passed, sometimes stuck in different test...

Anyway, I have another pr which is no conflict with this pr, hope you like them ;)

**Comment by shirohana** [comment]
Rebase `nuxt.js:dev`

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Thank you @shirohana. Sorry if I've missed this PR for a while ❤️

**Pull request merged**
