### PR TITLE
fix(vite): use `h3` cors handler for vite routes only

### LINKED ISSUE #22512: Difference in CORS OPTIONS Response between Nuxt and Nitro Server Routes
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.8.0
- Nitro Version:    2.7.0
- Package Manager:  pnpm@7.29.3
- Builder:          vite
- User Config:      devtools

### Reproduction
https://github.com/samydoesit/repro-nuxt-cors-options

Run nuxt (`pnpm dev:nuxt`) or nitro (`pnpm dev:nitro`) and send a cors options request to the `http://localhost:3000/test` endpoint.

In the nuxt response, the `Access-Control-Allow-Credentials` header is missing, and the `Access-Control-Allow-Origin` header is incorrectly set to `*`, disregarding the actual origin.

The Nitro response behaves as expected, including the `Access-Control-Allow-Credentials` header and correctly setting the `Access-Control-Allow-Origin` header to the actual origin.

It looks like in nuxt context the event handler is not called for the cors options request.

httppie request:
```bash
http --follow --all OPTIONS :3000/test \
Origin:'protocol://test'
```

curl request:
```bash
curl -I -X OPTIONS http://localhost:3000/test
```
### Wrong Nuxt Response
```bash
HTTP/1.1 204 No Content
Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 0
Date: Wed, 25 Oct 2023 17:58:02 GMT
Keep-Alive: timeout=5
Vary: Access-Control-Request-Headers
```
### Correct Nitro Response
```bash
HTTP/1.1 200 OK
access-control-allow-credentials: true
access-control-allow-origin: protocol://test
connection: close
content-length: 4
content-type: text/html
date: Wed, 25 Oct 2023 17:59:01 GMT
vary: origin

TEST
```

### Describe the bug

I'm facing an issue when testing CORS preflight (OPTIONS) requests in a local development environment using Nuxt and Nitro. When sending a CORS OPTIONS request to the http://localhost:3000/test endpoint, the responses differ between the two.

It seems that within the Nuxt context, the event handler isn't being triggered for CORS OPTIONS requests.

### Event Handler 
https://github.com/unjs/nitro/issues/1095#issuecomment-1487953233
```typescript
export default defineEventHandler((event) => {
  setResponseHeader(event, 'x-custom', '123');
  setResponseHeader(event, 'access-control-allow-credentials', 'true');
  setResponseHeader(event, 'access-control-allow-origin', 'protocol://test');

  return {
    body: 'OK',
  }
})

```

### Logs

_No response_

### LINKED ISSUE #23962: Vite dev middleware overrides cors headers
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  pnpm@8.5.1
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/samydoesit/repro-nuxt-cors-options by @samydoesit (https://github.com/unjs/nitro/issues/1095#issuecomment-1779823612)

it has to run locally, for more readable reproduction, you can also change `test-handler.ts` to this:

```ts
export default defineEventHandler((event) => {
  setResponseHeader(event, 'x-custom', '123');
  setResponseHeader(event, 'access-control-allow-credentials', 'true');
  setResponseHeader(event, 'access-control-allow-origin', 'protocol://test');
  return '...';
});
```

`http OPTIONS :3000/test Origin:'protocol://test'` responds when using nuxt in development mode:

```
HTTP/1.1 204 No Content
access-control-allow-methods: GET,HEAD,PUT,PATCH,POST,DELETE
access-control-allow-origin: *
connection: close
content-length: 0
date: Thu, 26 Oct 2023 16:37:23 GMT
vary: Access-Control-Request-Headers
```

When running nuxt (nitro server alone) in production:

```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 3
Date: Thu, 26 Oct 2023 16:38:21 GMT
Keep-Alive: timeout=5
access-control-allow-credentials: true
access-control-allow-origin: protocol://test
content-type: text/html
x-custom: 123
```

### Describe the bug

It seems the vite dev server overrides those headers (thanks for the investigation from @danschalow in https://github.com/unjs/nitro/issues/1095#issuecomment-1781075661)

----

As a workaround, one might use `nuxt.config` to customize `vite.server.cors`:

```ts
export default defineNuxtConfig({
  vite: {
    server: {
      cors: {
        origin: true,
        methods: ['GET', 'HEAD', 'PUT', 'PATCH', 'POST', 'DELETE'],
        preflightContinue: true,
        optionsSuccessStatus: 204,
      },
    }
  }
})
```

Response:

```
HTTP/1.1 200 OK
access-control-allow-credentials: true
access-control-allow-methods: GET,HEAD,PUT,PATCH,POST,DELETE
access-control-allow-origin: protocol://test
connection: close
content-length: 3
content-type: text/html
date: Thu, 26 Oct 2023 16:40:54 GMT
vary: Origin, Access-Control-Request-Headers
x-custom: 123
```

### Additional context

Using `routeRules` `cors` allows overriding `access-control-allow-origin` but not the rest as it early handles headers:

```ts
export default defineNuxtConfig({
  routeRules: {
    '/test': { cors: true }
  }
})
```

```
HTTP/1.1 204 No Content
access-control-allow-methods: GET,HEAD,PUT,PATCH,POST,DELETE
access-control-allow-origin: *
connection: close
content-length: 0
date: Thu, 26 Oct 2023 16:42:54 GMT
vary: Access-Control-Request-Headers
```

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/22512
resolves https://github.com/nuxt/nuxt/issues/23962

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This turns off vite's cors handler (https://github.com/expressjs/cors) by default, in preference to using `h3`'s handler _only_ for routes to be transformed by vite. This should enable us to avoid CORS headers on Nuxt/Nitro endpoints that aren't handled by vite.

If the user configures `vite.server.cors` then this is respected.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
This is good imo for the fix but also we could find a way to disable vite cors overrides entirely allow both consistent behavior when h3 util / route rule used (route rule is normalized to cors headers not using utility) and also user custom behavior

**Comment by danielroe** [comment]
I think that is what this fix does. It does disable vite cors header handler entirely. But maybe I'm misunderstanding you?

**Comment by pi0** [comment]
Indeed it does disable vite feature and directly adds `OPTIONS` handler via a nuxt default behavior. What i meant was to avoid this too, in next steps iterating with nitro.

**Review by pi0 — APPROVED** [review]

**Comment by danielroe** [comment]
Ah, I see. But Nuxt only does this for routes that are handled by vite, leaving normal nitro routes unhandled.

**Pull request merged**
