### PR TITLE
 fix: generate failure

### LINKED ISSUE #5006: Cannot find module 'pages/index.js?v=d187aabeaedb9b4063f6' from '/sandbox'
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://codesandbox.io/s/ov642w2v25?module=%2Fnuxt.config.js](https://codesandbox.io/s/ov642w2v25?module=%2Fnuxt.config.js)

### Steps to reproduce

Make `chunkName` as `'[name].js?v=[contenthash]'` in `nuxt.config.js`

### What is expected ?

There is no error

### What is actually happening?

Error page with NuxtServerError
Cannot find module 'pages/index.js?v=d187aabeaedb9b4063f6' from '/sandbox'

### Additional comments?

PR https://github.com/nuxt/nuxt.js/pull/4439 make code simplier:
it was before:
```
bundle.files[asset.name] = compilation.assets[asset.name].source()
```
and after:
```
bundle.files[asset.name] = asset.name
```
I'am not sure is this line works early, but now it don't. 
Created `.nuxt/dist/server/server.manifest.json` contains:
```
{
  "entry": "server.js",
  "files": {
    "pages/index.js?v=825661537585209d20c2": "pages/index.js?v=825661537585209d20c2",
    "server.js": "server.js"
  },
  "maps": {
    "server.js": "server.js.map"
  }
}
```
Obviously, there is no that file.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8640">#c8640</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by karakum**
Allow to use `[name].js?v=[contenthash]` in chunk names.

## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
In continuos of #3387 #4073
Resolves: #5006

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Review by pi0 — DISMISSED** [review]

**Comment by karakum** [comment]
@manniL Who or what we are waiting for?

**Comment by manniL** [comment]
@karakum The PR hasn't even been on for 24 hours. Please be a little patient so that other team members have a chance to review the code as well ☺️

**Comment by manniL** [comment]
@karakum However, a fixture to test the correct behavior (and to therefore avoid regressions) would be highly appreciated 🙌

**Comment by Atinux** [comment]
I was writing my comment to ask you to add a fixture and a unit test...
Well you just made it before I clicked "comment" 👏 

I'm good with the PR if the test are all green

**Comment by Atinux** [comment]
ESLint is broken: https://circleci.com/gh/nuxt/nuxt.js/29158?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Don't we have a precommit hook for it @manniL @pi0 ?

**Comment by manniL** [comment]
@Atinux Yup, that's a great idea!

**Comment by karakum** [comment]
@Atinux All check have passed! 😎

**Comment by clarkdo** [comment]
Could we move test to a existed fixture since a new fixture may increase more CI time consuming?

**Comment by karakum** [comment]
I think no.
Main settings
```
  build: {
    filenames: {
      app: '[name].js?v=[contenthash]',
      chunk: '[name].js?v=[contenthash]'
    }
  }
```
can't be turned on/off while unit-test, just in whole fixture. Am I wrong?

**Comment by manniL** [comment]
@karakum Many thanks for your contribution 🙏

**Comment by galvez** [comment]
I was bit by this one -- many thanks @karakum :)

**Pull request merged**
