### PR TITLE
feat(nuxt): add layer meta and env overrides to config types

### PR DESCRIPTION
**Pull request by danielroe**
### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds route metadata (via `$meta`) as well as per-environment overrides to Nuxt config typings, all implemented upstream in c12:

- https://github.com/unjs/c12/pull/64
- https://github.com/unjs/c12/pull/62

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]
💯

**Comment by tonioriol** [comment]
Hey, not sure if this is the correct place to ask, but I'm not sure how the per-env configs takes precedence over non env specific configs. Could you give me some hints on how does that actually woks, or at least where can I check the implementation of the config to see it? 

```
$production: {
    routeRules: {
      '/**': process.env.CTF_PREVIEW === 'true' ? { ssr: false } : { isr: 86400 },
    },
  },
  $development: {
    routeRules: {
      '/**': { ssr: true },
    },
  },
  routeRules: {
    '/api/**': { cache: false, swr: false },
  },
```

For example, in this case, I'm not sure if the non env routeRules will be overridden by the catch-all rules in each env.

**Comment by danielroe** [comment]
Yes, you can override the top level rule (`/**`) within a subpath (`/api/**`). Your example will end up merged into something like:

```js
export default defineNuxtConfig({
  routeRules: {
    '/**': { ssr: true },
    '/api/**': { cache: false, swr: false },
  },
})
```

In future, it's best to ask a question on Discord or GitHub Discussions rather than commenting on a released PR.

**Comment by tonioriol** [comment]
> Yes, you can override the top level rule (`/**`) within a subpath (`/api/**`). Your example will end up merged into something like:
> 
> ```js
> export default defineNuxtConfig({
>   routeRules: {
>     '/**': { ssr: true },
>     '/api/**': { cache: false, swr: false },
>   },
> })
> ```
> 
> In future, it's best to ask a question on Discord or GitHub Discussions rather than commenting on a released PR.

It's the only place on the internet I could find that remotely mentioned/documented. I'm actually looking for the implementation, to understand it better. But sorry about that, and thanks for answering.

**Pull request merged**
