### PR TITLE
fix(schema): ignore empty string in `app.{rootId|rootTag}`

### LINKED ISSUE #22525: `app.rootId` set to an empty string isn't ignored
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.20.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.6.12`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

```
export default defineNuxtConfig({
  app: {
    rootId: ''
  }
})
```

### Describe the bug

image

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by DamianGlowala**
### 🔗 Linked issue

Resolves https://github.com/nuxt/nuxt/issues/22525

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR ignores passing empty string for `app.rootId` and `app.rootTag`.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]

**Comment by Lehoczky** [comment]
Regarding the discussion in https://github.com/nuxt/nuxt/issues/22525: shall we update the code to validate using a regex, like one suggested in [this stackoverflow thread](https://stackoverflow.com/questions/17103622/how-do-i-check-if-a-string-would-make-a-valid-html-id-using-js)?

**Comment by danielroe** [comment]
I'd be happy with that. 👍

**Comment by DamianGlowala** [comment]
A separate PR to address the id validation is very much welcome! I wanted to keep these separate, as this PR also ignores an empty string for `app.rootTag`.

**Comment by danielroe** [comment]
I think simple validation could be good and maybe even normalisation (e.g. trimming whitespace?), but nothing too complex. Objective is to prevent obvious errors rather than provide a fully safe validation.

**Pull request merged**
