### PR TITLE
feat(builder): `followSymlinks` option to allow for symlinks

### PR DESCRIPTION
**Pull request by SnirShechter**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [X] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This PR adds a build.followSymlinks boolean(default: false), and passes it to the builder's glob function inside resolveFiles().

This allows for following symlinks inside layouts/middleware/pages/store, thus including them in the app.
## Checklist:

- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [X] I have added tests to cover my changes (if not applicable, please state why)
- [X] All new and existing tests are passing.

### CODE REVIEW

**Comment by pimlie** [comment]
@SnirShechter Thanks for this pr. Would it maybe be possible to combine the tests with an existing fixture? Adding it to `basic` or `with-config` should be fine.
The reason for this is that every new fixture adds about ~10seconds to the test time. So we try to only add new fixtures for incompatible configs.

Also note that it seems you are using a different emailaddress in your local git config then for github. If you want you can either add that other emailaddress to your github account (Settings -> Emails) or correct the emailaddress & do a force-push (old commits will still be accessible though).

**Comment by SnirShechter** [comment]
> @SnirShechter Thanks for this pr. Would it maybe be possible to combine the tests with an existing fixture? Adding it to `basic` or `with-config` should be fine.
> The reason for this is that every new fixture adds about ~10seconds to the test time. So we try to only add new fixtures for incompatible configs.
> 
> Also note that it seems you are using a different emailaddress in your local git config then for github. If you want you can either add that other emailaddress to your github account (Settings -> Emails) or correct the emailaddress & do a force-push (old commits will still be accessible though).

Hey, sorry for the really late reply. I'm on it.

**Review by pimlie — APPROVED** [review]
LGTM. The only thing I was thinking about is to maybe make it possible for a user to set any [glob](https://github.com/isaacs/node-glob#options) option, but I think we probably shouldnt do that as changing a setting like `absolute` or `realpath` could result in unexpected behaviour in nuxt.

**Comment by SnirShechter** [comment]
It is something worth thinking of, but basically followSymlinks is (through my point of view) much more than a simple glob setting, since it allows separation of pages in different folders. For me and my company, this means that we can integrate one project into another, when built right.

Thanks for the approval 👍

**Review by pi0 — APPROVED** [review]

**Pull request merged**
