### PR TITLE
feat: add subFolders option for generate

### PR DESCRIPTION
**Pull request by Gomah**
Hi there,

First of all, thank you for this awesome project & all the effort you are putting together to make Nuxt.js awesome!

I faced a little issue using `nuxt generate` as it creates a directory for every route & write an index.html inside it.

```bash
index.html
/about/index.html
/contact/index.html
```

However, most CDN (& or static hosting) do URL normalization to enforce consistent URL patterns (e.g Netlify).

Quoted from Netlify documentation:

```
When “Pretty URLs” is enabled under processing settings for your site, Netlify will enforce consistent URL patterns.

A link to /about.html will be rewritten to /about in your HTML files and Netlify will enforce a redirect from /about/ to /about

A link to /about/index.html will be rewritten to /about/ and Netlify will redirect from /about to /about/
```

With that said, the current generate does not suit the following scenario:

Let's say I have the following routes:

```
- /
- /about
- /contact
```

1. My webapp loads on `/` (e.g: https://example.com)
2. I navigate to a route using CSR (e.g https://example.com/about)
3. I refresh & been redirected to https://example.com/about/

Which means, if Google crawls `/about`, it will face a 301 redirection to `/about/` (using Netlify for example).

Adding the `subFolders` option to `generate` fixes this problem.

Any thoughts/restrictions?

Fixes
-----
- [x] #721

Todo
-----
- [x] Tests
- [x] Add documentation under [Configuration / Generate](https://nuxtjs.org/api/configuration-generate)

### CODE REVIEW

**Comment by Atinux** [comment]
Hi @Gomah 

I talked with the team and we agree with this suggestion, could you add tests for it so we can merge it afterwards?

**Comment by Gomah** [comment]
Hi @Atinux, cool!

Just wondering what's the best approach to test this, as `basic.generate.test.js` generates the files by default before running the tests suite.

Should I just add the tests after [closing the server](https://github.com/nuxt/nuxt.js/blob/dev/test/basic.generate.test.js#L130) or is there a different method?

Also, what's the best way to test it?

a) Generate & check if the routes rendered in `fixtures/basic/dist` are a folder or a file by checking the type with `fs`.

b) Generate & check if the routes rendered path based on the `subFolders` option.

c) A better option? 😄

**Comment by pimlie** [comment]
As you will need to generate the files twice, you either have to add another test or re-generate within the same basic test. The first speaks for it self, for the later you could take a look how I approached that here: https://github.com/pimlie/nuxt-generate-cluster/blob/next/test/single.regenerate.test.js

So after the normal tests are done I first remove the full `dist/users/` folder and check if they really have been removed (eg the routes should give a 404). After that I run the generate command again but this time I dont build Nuxt but only initiate. After that you could check either check the fs but inline with the current test implementation I would test if you can retrieve eg `/user/1.html` from the server.

For your test you would also need to change the nuxt config of course before generating the second time.

**Comment by Gomah** [comment]
Ok, just got time to look at it!

@pimlie, Yeah, I'm trying to re-generate within the same basic test specs with a different configuration ;)

However, adding `subFolders: false` throws an error while trying to render the component in `lib/app/components/nuxt-child.js`.

```sh
TypeError: Cannot read property 'components' of undefined
```

```sh
# nuxt-child.js
# parent.$route
{ name: null,
  meta: {},
  path: '/stateless.html',
  hash: '',
  query: {},
  params: {},
  fullPath: '/stateless.html',
  matched: [] }
```
The `routerViewKey` computed function in `/lib/app/components/nuxt.js` actually return an invalid route:

```sh
/routename.html
```

instead of 

```
/routename
```

I'll try to get some time to deeply look at it this week-end.

@Atinux, @pimlie, any ideas where I should look at?

**Comment by Atinux** [comment]
Hi @Gomah 

For `TypeError: Cannot read property 'components' of undefined`, I made a fix to nuxt.js core (https://github.com/nuxt/nuxt.js/commit/4b79c38f41786566f86b993ef2ae3f5151c6a9c0).

Actually I remember why it's not possible. Most CDN cannot serve `/routename` to `routename.html` but instead has to be `/routename` -> `/routename/index.html`.

Also, if you go to `/routename.html`, Vue does not know this route (since it has an extension in its name) and cannot load the app.

Actually, the right solution is to use canonical urls in your header: https://support.google.com/webmasters/answer/139066?hl=en

Example of your `nuxt.config.js`:
```js
module.exports = {
  head: function () {
    const path = this.$route.path.replace(/\/$/, '') // Remove trailing /
    return {
      link: [{ rel: 'canonical', href: `https://my-website.com${path}` }]
    }
  }
}
```

I also made a fix so you can use `head() {...}` in the next release.

I believe we could add it to the documentation.

**Comment by Gomah** [comment]
Thanks for the fix!

Are we still considering this option? Even if the canonical url is set, I believe it's still crucial as Google is crawling 301s for those routes.

I just got the test working actually, I added the `extensions` option to the serveStatic function to set an extension fallback so the local server mounted during the tests behave like Netlify servers (or any other server using html fallbacks).

I've added `test/basic.generate.nosubfolders.test.js`, let me know if there's a better way to structure this test.

**Comment by Atinux** [comment]
I believe this option can be used with Netlify or the `extensions` set for `serve-static`.

I can merge it, but could you make the changes for the documentation: https://github.com/nuxt/docs/blob/master/en/api/configuration-generate.md

**Comment by Atinux** [comment]
Awesome :raised_hands:

**Comment by pimlie** [comment]
I was looking at the tests but I dont think they are specific enough. E.g. there is currently no check if `subfolders: true` really generates `users/1/index.html` and `subfolders: false` generates `users/1.html` as serveStatic will always magically translate the `users/1` url to the correct one. Currently if someone changes the following line https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/generator.js#L185 to read `if (true) {` the nosubfolder tests will still pass because of this.

As I mentioned in my comment above, I think you should make sure that in `basic.generate.js` you test one of the users as `users/1/index.html` and in the nosubfolders test you test one of the users as `users/1.html`.

But due to the fact that serveStatic can be an issue in the test itself, I actually think it would be best to _also_ add a fs check. For the nosubfolders test it would look like this:
```js
import { existsSync } from 'fs'
...
test('/users/1.html', async t => {
  const html = await rp(url('/users/1.html'))
  t.true(html.includes('<h1>User: 1</h1>'))
  t.true(existsSync(resolve(__dirname, 'fixtures/basic/dist', 'users/1.html')))
  t.false(existsSync(resolve(__dirname, 'fixtures/basic/dist', 'users/1/index.html')))
})
```
You never cant have enough tests ;)

**Comment by Gomah** [comment]
@pimlie True, I was focused on rendering the component properly with serveStatic that I forgot my initials thoughts!

Just added your suggestion #2132 👍

**Comment by piyushchauhan2011** [comment]
Hi @Gomah , I tried the your subfolders branch but when we try to generate, the `mounted` method is not called in my case but is being called correctly in `rc11` version

**Comment by Gomah** [comment]
@piyushchauhan2011 Weird, all my mounted hooks are working using nuxt@dev.

Do you have an example?

**Comment by gonshi** [comment]
@piyushchauhan2011 @Gomah 

Same problem occurred for me, but I founded the two cases.

1. When I use static routing like below, actually the generated `hoge.html` doesn't call `mounted` method.

```
.
├── pages
│     ├── index.vue
│     └── hoge.vue
```

2. but when I use dynamic routing, the generated `hoge.html` also call `mounted` method correctly.

```
.
├── pages
│     └── _id.vue
```

```nuxt.config.js
  generate: {
    routes: [
      'hoge'
    ]
  }
```

**Comment by jscheller** [comment]
I'm on Nuxt 1.4, and experiencing the same issue as @gonshi with subFolders:false. App looks great in dev or when generated with subFolders:true.

Would be great to see this working as it'd resolve some SEO  and URL canonicalization issues for non-dynamic routes very nicely.

**Pull request merged**
