### PR TITLE
fix(nuxt): regenerate imports after template

### LINKED ISSUE #18897: Composable auto-imports break when modified, `useXXX` is not defined (`pnpm run dev`/`npm run dev`)
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `pnpm@7.17.1`
- Builder:          `vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Start the dev server with `pnpm dev` or `pnpm run dev`
2. Edit a composable return
3. Refresh your web page and an error 500 should appear saying your composable useXXX is not defined

pnpm: https://stackblitz.com/edit/github-ywg4lu?file=composables%2FuseFoo.ts
npm: https://stackblitz.com/edit/github-1hay52-amtd8x?file=composables%2FuseNetwork.js _(edit @lihbr)_

If you stop and restart the server with `pnpm dev` or `pnpm run dev` it work again until you edit your composable again.

### Describe the bug

Starting the dev server with `pnpm dev` or `pnpm run dev` break the auto-load or something related when a composable is modified.
Everything work as expected if I use `pnpm nuxi dev` _(edit @lihbr `npx nuxi dev` doesn't seem to fix it the same way)_

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by antfu**
### 🔗 Linked issue

fixes #18897

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by antfu** [comment]
It's just an assumption, @lihbr if you have time, it would be great if you can help verify whether it fixes.

**Comment by lihbr** [comment]
First time tomorrow!

**Comment by lihbr** [comment]
Yep, this is it!

Tried before/after on the playground, before the bug happens as described in the issue, now I cannot reproduce it, even after dozens of changes 🚀

**Review by danielroe — APPROVED** [review]

**Comment by antfu** [comment]
Thanks a lot @lihbr!

**Pull request merged**
