### PR TITLE
feat: move to webpack-hot-client

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
It's... a mixed story. webpack-hot-client uses WebSocket which drops support for IE 8/9, but for developers this should be pretty fine.

The corresponding config is renamed and needs new options.

The biggest issue is that webpack-hot-client does not support overlays. The maintainer is sticking with his (personal) opinion to not include that functionality: https://github.com/webpack-contrib/webpack-serve/issues/4

A basic alternative coded by the community is included as a separate commit, but it is not feature complete, such as the styling being different from the former one, and doesn't show if you refresh while having bundle error (only shows when doing HMR).

### CODE REVIEW

**Comment by galvez** [comment]
@ishitatsuyuki can you take a look at the lint error?

**Comment by abellion** [comment]
Not only that webpack-hot-client doesn't support old browser, but doing HMR through websocket is a real mess inside a Docker setup.

It also makes remote testing more complicated (via local tunneling with https://www.browserstack.com/ for example) since two ports need to be exposed.

Except the tiny performance improvements it would bring, moving to a websocket system adds more downside IMHO.

**Comment by ishitatsuyuki** [comment]
I'd like to note that it's possible to mount the WebSocket onto the same Express/connect instance; that would solve many problem but I haven't code it yet.

**Comment by galvez** [comment]
@ishitatsuyuki I have two objections:

1. I believe `webpack-hot-client` still hasn't been as battle tested as `webpack-hot-middleware`, judging by the number of projects making use of it, so there would be a risk of potential issues that would affect developer experience.

2. At the very least, the potential Docker issue mentioned by @abellion should be investigated and documentation/examples should also be provided to ensure there's minimal disruption to users.

I'd say we hold this for 2.x as I'm not sure there's enough time before 2.0 by now.

**Comment by galvez** [comment]
ping @clarkdo @pi0 :)

**Comment by Atinux** [comment]
We will look at it after 2.0 release

**Comment by ishitatsuyuki** [comment]
webpack-serve was abandoned. Closing.

**Pull request closed without merging**
