### PR TITLE
fix builder

### PR DESCRIPTION
**Pull request by wormen**

### CODE REVIEW

**Comment by Atinux** [comment]
What exactly do these changes and why?

**Comment by wormen** [comment]
@Atinux with some modules, the builder shall issue the type of error
```
Module not found: Error: Can't resolve 'dns' in 
```

```
Module not found: Error: Can't resolve 'net' in
```

and so on
this fix corrects this

**Comment by Atinux** [comment]
This is an intended behaviour since it should not try to require `fs` or any other module from node if he is on client-side. That's why we added `process.BROWSER_BUILD`.

Otherwise, it will be worse, because he won't have any error, but a completely wrong behaviour of his application.

**Comment by wormen** [comment]
@Atinux 
1) I needed a module that should work regardless of the medium in which it is running
2) jsonwebtoken not dependent on the use environment

**Comment by wormen** [comment]
3) actually, the modules that are turned off are not used

**Pull request closed without merging**
