### PR TITLE
Improved default key for page with children

### PR DESCRIPTION
**Pull request by silverbackdan**
I think this as a default key would be better if a page being loaded from the layout has children. Ideally I'd like to find the page's parent fullpath but I haven't found a good way to do that just yet. This would satisfy my needs on a basic website.

P.s. with these huge releases I know this is not top priority and isn't important enough to take attention away from all the great work going on!

### CODE REVIEW

**Comment by Atinux** [comment]
Hey @silverbackdan 

Could you make a reproduction about it with Glitch (by forking https://glitch.com/edit/#!/nuxt-hello-world).

I'm not sure this is the best way by splitting with `/`, we should instead check the matched components and remove the children path (something like this for example: https://github.com/nuxt/nuxt.js/blob/dev/lib/app/client.js#L255-L256)

**Comment by silverbackdan** [comment]
Hiya @Atinux Sure I'll be happy to make something up to show what I mean. I'll try and have the replication done later today. I think you're right that it won't be the best way to go the more I think about it. That's a really good example too, thanks. I'll see about replicating that behaviour.

**Comment by silverbackdan** [comment]
I've created a reproduction here:
https://glitch.com/edit/#!/nuxt-child-key
https://nuxt-child-key.glitch.me

Switching between 'definition 1' and 'definition 2' pages

And a quick demonstration for why one may want that structure.

**Comment by Atinux** [comment]
Hey @silverbackdan 

I believe this should be the right way: https://glitch.com/edit/#!/nuxt-pull-1209

Demo: https://nuxt-pull-1209.glitch.me/

**Comment by silverbackdan** [comment]
That's really good and would work for me. As this is from the 'nuxt' tag too there should never be more than 1 child (otherwise should be using nuxt-child) Updating the PR now.

**Comment by Atinux** [comment]
Awesome :)

**Pull request merged**
