### PR TITLE
refactor: use PascalCase for components name

### PR DESCRIPTION
**Pull request by clarkdo**

### CODE REVIEW

**Review by TheAlexLichter — DISMISSED** [review]

**Review by pi0 — APPROVED** [review]

**Comment by MacZel** [comment]
This change introduces an issue. For example, I'm getting an error with `<nuxt/>` being changed to `<Nuxt/>` in https://github.com/nuxt/nuxt.js/blob/dev/examples/typescript/layouts/default.vue 
If changed back to lowercase it runs smoothly.

Node:
```
ERROR  [Vue warn]: Invalid component name: "pages/index.vue". Component names can only contain alphanumeric characters and the hyphen, and must start with a letter.
```
Console:
```
[Vue warn]: Unknown custom element: <Nuxt> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Default> at layouts/default.vue
       <Root>
```

**Comment by clarkdo** [comment]
@MacZel I'll have a look, thanks for the information.

**Comment by clarkdo** [comment]
@MacZel I've made some changes, could you have a try on latest `dev` branch ?

**Comment by MacZel** [comment]
@clarkdo I will try laetr this day and let you know

**Comment by MacZel** [comment]
@clarkdo Ok, one last fix:
Please add vue-meta entry to dependencies:
`"vue-meta": "^1.5.6",`
Otherwise you get an error:
```
 ERROR  Failed to compile with 1 errors               friendly-errors 14:04:51

This dependency was not found:                        friendly-errors 14:04:51
                                                      friendly-errors 14:04:51
* vue-meta in ./.nuxt/index.js                        friendly-errors 14:04:51
                                                      friendly-errors 14:04:51
To install it, you can run: npm install --save vue-meta
```

**Comment by manniL** [comment]
@MacZel Vue meta is already a dependency of `nuxt` itself

**Comment by MacZel** [comment]
@manniL My bad. Reinstalled the package and now everything is ok.
@clarkdo everything is running ok now

**Comment by Jan10** [comment]
@clarkdo the with-amp example don't work with `<AmpImg>` 

https://github.com/nuxt/nuxt.js/blob/dev/examples/with-amp/pages/dog.vue
https://www.ampproject.org/docs/reference/components/amp-img

**Comment by clarkdo** [comment]
@Jan10 
Thanks for reminding, I'll change it back.

**Comment by dzcpy** [comment]
Actually, could you explain why use camel case instead of kebab case? What's the convension?

**Comment by clarkdo** [comment]
@dzcpy FYI https://vuejs.org/v2/style-guide/#Component-name-casing-in-templates-strongly-recommended

**Comment by dzcpy** [comment]
@clarkdo Thanks!

**Pull request merged**
