### PR TITLE
feat(schema): enable opt-in to Nuxt v4 features/flags with `future. compatibilityVersion`

### PR DESCRIPTION
**Pull request by danielroe**
### 📚 Description

This enables users (for testing purposes) to opt-in to the following coming changes:

- [x] https://github.com/nuxt/nuxt/issues/25332
- [x] https://github.com/nuxt/nuxt/issues/26443
- [x] https://github.com/nuxt/nuxt/issues/25338
- [x] https://github.com/nuxt/nuxt/issues/25339

... with potentially more to come in the next weeks.

#### Usage

```ts
export default defineNuxtConfig({
  future: {
    compatibilityVersion: 4,
  },
  // Setting the `compatibilityVersion` above flips all the options below to `false`
  // you can granularly re-enable them when testing. Please file issues if so, so that
  // we can address in Nuxt or in the ecosystem.
  // experimental: {
  //   compileTemplate: true,
  //   templateUtils: true,
  //   relativeWatchPaths: true,
  //   defaults: {
  //     useAsyncData: {
  //       deep: true
  //     }
  //   }
  // }
})
```

### CODE REVIEW

**Comment by manniL** [comment]
@danielroe could we have a more gradual approach so v4 could be set to `true` or to an object containing the different changes? That might be easier to upgrade + "future-safe" in case we introduce more changes in a patch/minor.

**Comment by danielroe** [comment]
Good idea. Note that we probably do need to have granular control over things that we plan to allow people to configure on v4+, e.g. directory structure. But others will fully go away.

I think I'll move this to `experimental` and make it more granular, for now. But this is likely to be very short lived as an option.

**Comment by manniL** [comment]
> Good idea. Note that we probably do need to have granular control over things that we plan to allow people to configure on v4+, e.g. directory structure. But others will fully go away.
>
> I think I'll move this to `experimental` and make it more granular, for now. But this is likely to be very short lived as an option.

While others might go away, it might help with migration to toggle changes "step by step". Grouping some smaller ones is also fine IMO but that could make migration easier. `experimental` seems like a great place 👍🏻

**Review by TheAlexLichter — APPROVED** [review]

**Comment by manniL** [comment]
Great solution to have both, a "progressive" flag enabling more future's by default and the detail-level in case something doesn't work or break 👏

**Pull request merged**
