### PR TITLE
feat(webpack): allow babel plugins to be defined by function

### PR DESCRIPTION
**Pull request by danielroe**
This PR allows `build.babel.plugins` to be a function that receives context and returns Babel plugins.

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
With the [new format for `babel-polyfills`](https://github.com/babel/babel-polyfills/blob/master/docs/migration.md) it may be important to pass targets to Babel plugins, which will likely vary by `isModern`.

So, in line with the current `presets` configuration, it would be appropriate for `plugins` to take a function.

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Review by clarkdo — COMMENTED** [review]
Change looks good, can you please add some unit tests ?

@pi0 This may also needs ts type definition change?

**Comment by danielroe** [comment]
@clarkdo I'm happy to put a PR into [`@nuxt/types`](https://github.com/nuxt/typescript) with the updated type.

**Comment by clarkdo** [comment]
I think @pi0 is migrating types to core repo now.

**Comment by pi0** [comment]
Types package is already moved here [src](https://github.com/nuxt/nuxt.js/tree/dev/packages/types). Would be nice also updating it :)

**Review by pi0 — APPROVED** [review]

**Pull request merged**
