### PR TITLE
perf(vite): tree-shake `typeof process`

### PR DESCRIPTION
**Pull request by undermoonn**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [x] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by danielroe** [comment]
If we add this we should probably also do the same for webpack builder.

https://github.com/nuxt/nuxt/blob/a5dad0d2e83323abc2bed7cfe3541f4dbd495335/packages/webpack/src/presets/base.ts#L234-L237

Not sure whether this would cause any unintended consequences in the ecosystem, or why we might not have done this before. (cc: @pi0)

**Comment by undermoonn** [comment]
In the vite dev server, all the defines will be injected into window. The `'typeof process'` will become the gobal variable which seems wired. It shoube the value `undefined`, not the string value `'undefined'`.

Maybe it's the reason nuxt team not have done this before :)

**Comment by pi0** [comment]
> Not sure whether this would cause any unintended consequences in the ecosystem, or why we might not have done this before. (cc: @pi0)

As far as i remember, @manniL was working on Nuxt 2 version. I think too it is safe to enable by default.

**Comment by manniL** [comment]
Yeah, I had a feeling when I looked into the PR 😂
Let's give it a try 👍🏻

**Comment by danielroe** [comment]
Since we last discussed, Vite has moved away from direct string replacements (which would mean we need to use rollup/plugin replace for this, with the disadvantages that it might be less performant and potentially replace content of strings rather than just code).

It might be worth investigating to see if we can use `define` to handle `process` tree-shaking. (But note that this is more complex as we (and others) use `process.env.SOME_VAR` - which we should likely migrate away from within Vue app code anyway...)

See also https://github.com/nuxt/nuxt/pull/24711.

**Pull request closed without merging**
