### PR TITLE
Webworker

### PR DESCRIPTION
**Pull request by dotnetCarpenter**
Polishing the web-worker example. 

* Writes out long running worker threads messages to HTML instead of `console.log`
* Proper terminates a worker when the _Free long running Worker_ buttons is clicked, since you **can not** _"free"_ a web worker.

You will probably want to squash my commits upon merge. This is not easily done from my end, since my commits are not consecutive in regard to the nuxt.js repo.

### CODE REVIEW

**Comment by Atinux** [comment]
Thanks @dotnetCarpenter

**Comment by husayt** [comment]
Thanks for demo.

It is mentioned there that hot module reloading is not supported in nuxt 1.4 and below. What about nuxt-edge? From what I see it is not supported there too

**Comment by husayt** [comment]
It's a good question. I think we should already start moving all examples to nuxt-edge. That will help to make sure that on release of nuxt 2 all the examples are working.

Maybe for next release it would make sense to create a separate branch for new release. But as it is now current src in dev branch is nuxt-edge and it would make sense if rest of examples would match it.

Probably this needs to be discussed with @Atinux @pi0 @clarkdo

**Comment by dotnetCarpenter** [comment]
@husayt I just tried your suggestion and while HMR kinda of works, it does har page refresh and I get the following error in Firefox: `The connection to http://localhost:3000/__webpack_hmr was interrupted while the page was loading.`

My `nuxt.config.js` looks like this:
```js
module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: 'web-worker',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Nuxt.js project' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  /*
  ** Customize the progress bar color
  */
  loading: { color: '#3B8070' },
  plugins: [
    { src: '~/plugins/inject-ww', ssr: false } // web workers are only available client-side, hence ssr: false
  ],
  /*
  ** Build configuration
  */
  build: {
    /*
    ** Run ESLint on save
    */
    extend (config, { isDev, isClient }) {
      if (isDev && isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }

      // @see https://github.com/nuxt/nuxt.js/pull/3480#issuecomment-404150387
      config.output.globalObject = "this"

      if (isClient) { // web workers are only available client-side
        config.module.rules.push({
          test: /\.worker\.js$/, // this will pick up all .js files that ends with ".worker.js"
          loader: 'worker-loader',
          exclude: /(node_modules)/
        })
      }
    }
  }
}
```

**Comment by dotnetCarpenter** [comment]
@husayt Ok, the page reload only happens when I edit the web-worker code which makes sense, since it's a nuxt.js plugin, which could be server-side and the server would have to run the code in order pick up changes.

I'll update this PR with a nuxt.js 2.0 ready example and you guys can choose to merge it if you and when you want.

**Comment by dotnetCarpenter** [comment]
@husayt https://github.com/nuxt/nuxt.js/pull/3531

**Comment by husayt** [comment]
Thanks @dotnetCarpenter . One question, I was wondering why did you place worker js files in assets folder?

**Comment by dotnetCarpenter** [comment]
@husayt because all files in the `assets` folder gets picked up by webpack and Babel transpiled. It also enables versioning. See https://nuxtjs.org/guide/assets for more info. If I put them in the `static` folder the files are just served via HTTP. Since they are not `.vue` files, I thought the `assets` folder made the most sense. I could be wrong, so if you have a better suggestion, I'm listening.

AFAIK the webpack config is also only applied to the `assets` folder.

```js
      if (isClient) { // web workers are only available client-side
        config.module.rules.push({
          test: /\.worker\.js$/, // this will pick up all .js files that ends with ".worker.js"
          loader: 'worker-loader',
          exclude: /(node_modules)/
        })
      }
```

**Pull request merged**
