### PR TITLE
feat(routing): Add routing to new tabs

### PR DESCRIPTION
**Pull request by GalacticHypernova**
### 🔗 Linked issue

None
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR makes it possible for navigateTo to navigate to a new window if needed, preventing the originating route from being overridden.
### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by GalacticHypernova** [comment]
Also decided to add JSDoc documentation to it because why not =)

**Comment by danielroe** [comment]
This is a nice implementation! Thank you.

Unfortunately we have another open PR for exactly the same feature: https://github.com/nuxt/nuxt/pull/21333.

**Comment by danielroe** [comment]
I am sorry! 😢

**Comment by GalacticHypernova** [comment]
It's fine, I should be the one to apologize, didn't look hard enough to find similar pulls. I'll just push the JSDoc update in a new pull, similar to the grammar overhaul.

**Pull request closed without merging**
