### PR TITLE
Remove inaccurate and misleading "memory usage" in dev CLI output

### PR DESCRIPTION
**Pull request by koresar**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

After introducing the new DX feature - the "building project" page - the memory usage is printed **before** the app start. Whereas previously the memory usage was printed **after** the app start.

image

On the picture above the 58MB is quite inaccurate. Actual memory usage is around 300-500MB.

**Suggestion - do not print memory usage at all.**

Hence the PR.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by koresar** [comment]
The build is [broken](https://circleci.com/gh/nuxt/nuxt.js/38428?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) because `npm install --package-lock-only && npm audit --audit-level=moderate` returns `exit 1` - one vulnerable package found.

I'm afraid fixing that myself. Sorry.

**Comment by pimlie** [comment]
Instead of removing the functionality we could also move it. Eg add a method `showMemoryUsage` which uses a normal consola.info log to print the memory stats, then that method could be run eg after the build has finished

**Comment by koresar** [comment]
I'm happy if this PR is closed.

**Comment by pimlie** [comment]
@koresar I was hoping that you would be willing to change this PR to accommodate my suggestion :smile:  

Should be a nice first contribution which will be usefull to all nuxt users (and that doesnt happen often for first time contributors!)

**Comment by koresar** [comment]
Sorry mate. I'd love to contribute. But that sounds complicated even though it is easy for pros like yourself.

Maybe to improve the situation we merge this PR and create a new "good first issue" for volunteers specifically to implement your suggestion?

**Comment by pimlie** [comment]
I was trying to change it just now but it appears you made your PR from the defunct next branch. I understand the confusion, but it should've been the dev branch. So will close this in favour of a new PR.

Thanks for your work tough!

**Pull request closed without merging**
