### PR TITLE
fix: warn for non serializable data instead of Error

### LINKED ISSUE #4026: error NuxtServerError: Cannot stringify a function
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

Use lazy translations

### What is expected ?

For it to render the page

### What is actually happening?

Error message

### Additional comments?

✖ error NuxtServerError: Cannot stringify a function
at walk (xxx/node_modules/devalue/dist/devalue.umd.js:16:19)
at xxx/node_modules/devalue/dist/devalue.umd.js:49:72
at Array.forEach ()
at walk (xxx/node_modules/devalue/dist/devalue.umd.js:49:40)
at xxx/node_modules/devalue/dist/devalue.umd.js:49:72
at Array.forEach ()
at walk (xxx/node_modules/devalue/dist/devalue.umd.js:49:40)
at xxx/node_modules/devalue/dist/devalue.umd.js:49:72
at Array.forEach ()
at walk (xxx/node_modules/devalue/dist/devalue.umd.js:49:40)
at devalue (xxx/node_modules/devalue/dist/devalue.umd.js:53:5)
at Renderer.renderRoute (xxx/node_modules/nuxt/dist/nuxt.js:2042:50)
at process._tickCallback (internal/process/next_tick.js:68:7)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7882">#c7882</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by aldarund**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Resolves #4026
Will warn and skip instead of error
https://github.com/nuxt-community/devalue/pull/1 related PR in fork

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Review by galvez — APPROVED** [review]

**Comment by galvez** [comment]
@aldarund need to fix the tests.

**Comment by manniL** [comment]
We should consider adding test sets for the states.

**Review by TheAlexLichter — APPROVED** [review]

**Comment by clarkdo** [comment]
The extract-css test has been changed, I think you can just revert it, then we can merge this pr 😎

**Review by clarkdo — APPROVED** [review]

**Comment by aldarund** [comment]
@clarkdo merged latest dev, should be fine now

**Comment by benfavre** [comment]
Thanks

**Comment by davision** [comment]
Same error as before, when using asyncData: 

```
✖ error TypeError: Cannot convert object to primitive value
  at VueComponent.head [as $metaInfo] (pages/news/_slug.js:97:44)
  at getComponentOption (/node_modules/vue-meta/lib/vue-meta.js:376:19)
  at /node_modules/vue-meta/lib/vue-meta.js:390:16
  at Array.forEach (<anonymous>)
  at getComponentOption (/node_modules/vue-meta/lib/vue-meta.js:389:25)
  at /node_modules/vue-meta/lib/vue-meta.js:390:16
  at Array.forEach (<anonymous>)
  at getComponentOption (/node_modules/vue-meta/lib/vue-meta.js:389:25)
  at /node_modules/vue-meta/lib/vue-meta.js:390:16
  at Array.forEach (<anonymous>)
  at getComponentOption (/node_modules/vue-meta/lib/vue-meta.js:389:25)
  at getMetaInfo (/node_modules/vue-meta/lib/vue-meta.js:468:16)
  at Vue.inject (/node_modules/vue-meta/lib/vue-meta.js:723:37)
  at Renderer.renderRoute (/node_modules/nuxt/dist/nuxt.js:2024:28)
  at <anonymous>
```

Am I missing something

**Comment by aldarund** [comment]
@davision from your changelog u are using original devalue lib. Are u on nuxt 2.2 ? Delete node modules and lock file and reinstall then.

**Comment by aldarund** [comment]
@sh reproduction repo would help

**Comment by davision** [comment]
I am on 2.2 yes, also deleted node_modules completely and reinstall. Will check again with new PR!

**Comment by manniL** [comment]
@davision Be aware that there was no release yet, so you have to test it "manually".

**Comment by sh** [comment]
@aldarund awesome, thanks :)

I've pulled your changes from https://github.com/nuxt-community/devalue/pull/3 and can confirm it's fixed for me!

**Comment by manniL** [comment]
@aldarund I think we should do a minor release 🤔

**Comment by aldarund** [comment]
@manniL ye, i planned to do it today :)

**Comment by aldarund** [comment]
@sh @davision @manniL i have published updated version of devalue , now on npm

**Comment by davision** [comment]
Which version is it? with 1.0.4 there is still the same error.

**Comment by manniL** [comment]
@davision There is no `1.0.4` of @nuxtjs/devalue. Only `1.0.1`. https://github.com/nuxt-community/devalue

**Comment by davision** [comment]
I've tried reinstalling everything once again, and finally, it works! Thanks.

**Pull request merged**
