### PR TITLE
fix(nuxt, vite): do not use cjs utils to resolve/alias vue

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

https://github.com/nuxt/nuxt/issues/14146

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Vite and Nitro correctly resolve vue dependencies, and it is far better to defer resolution to the bundlers than override it ourselves, particularly with support for non-hoist:

You can test with this plugin:

<details>
<summary>Details</summary>

```ts
const logger = {
  name: 'log',
  writeBundle (_options, bundle) {
    for (const file in bundle) {
      const chunk = bundle[file]
      if (chunk.type === 'asset') { continue }
      const resolvedVueFiles = chunk?.moduleIds.filter(i => i.includes('vue'))
      if (resolvedVueFiles?.length) {
        console.log(resolvedVueFiles)
      }
    }
  }
}

export default defineNuxtConfig({
  experimental: {
    // you can try with and without
    externalVue: false
  },
  nitro: {
    rollupConfig: {
      plugins: [logger]
    }
  },
  vite: {
    plugins: [logger]
  }
})
```

</details>

(In my testing, before this PR, with `externalVue: false` vue was actually being bundled twice in nitro bundle.)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]
LGTM if you have already tested it against latest nitro. 

We had to get rid of this workaround sooner or later.

Also linking to https://github.com/unjs/nitro/issues/1118 which might be needed to dedup external vue

**Comment by danielroe** [comment]
I've tested it in the framework repo here. Are there module resolution changes coming upstream from nitro?

**Comment by sei-jdshimkoski** [comment]
I think this might have broken this particular Nuxt Config setting (Nuxt 3.6.2 with Nitro 2.5.2):

```
vite: {
    build: {
      rollupOptions: {
        output: {
          manualChunks(_id) {
            return 'index'
          }
        },
      },
    },
  },
```

I now get a bunch of `<BLAH> cannot be included in manualChunks because it is resolved as an external module by the "external" option or plugins.`

**Comment by danielroe** [comment]
@sei-jdshimkoski Maybe you you could open an issue with reproduction? I don't have an issue with that code in a minimal sandbox.

**Comment by wtagain** [comment]
> I think this might have broken this particular Nuxt Config setting (Nuxt 3.6.2 with Nitro 2.5.2):
> 
> ```
> vite: {
>     build: {
>       rollupOptions: {
>         output: {
>           manualChunks(_id) {
>             return 'index'
>           }
>         },
>       },
>     },
>   },
> ```
> 
> I now get a bunch of `<BLAH> cannot be included in manualChunks because it is resolved as an external module by the "external" option or plugins.`

Same question. Did you fix it?

**Comment by sei-jdshimkoski** [comment]
Sorry, was out of town and away from my computer. I'll try to open an issue with reproduction today.

**Comment by sei-jdshimkoski** [comment]
Ticket is here: https://github.com/nuxt/nuxt/issues/22127

**Pull request merged**
