### PR TITLE
fix: Vue.component('RouterLink') is undefined in vue-router 3.0.0

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)

## Checklist:

- [x] All new and existing tests are passing.

### CODE REVIEW

**Comment by manniL** [comment]
But they are installed as `PascalCase` versions :thinking: 
(see https://github.com/vuejs/vue-router/blob/dev/src/install.js#L46-L47)

**Comment by clarkdo** [comment]
@manniL It's not in 3.0.0 https://github.com/vuejs/vue-router/blob/v3.0.0/src/install.js 😄

**Comment by manniL** [comment]
@clarkdo Omg :see_no_evil: 
Thanks, you are right :sweat_smile:

**Review by aldarund — APPROVED** [review]

**Comment by pi0** [comment]
If this problem is fixed with `3.0.2`, should we still add this patch?

**Pull request merged**
