### PR TITLE
feat(kit): get module options with `getNuxtModuleOptions`

### PR DESCRIPTION
**Pull request by harlan-zw**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

When integrating with other modules, it's common to use some of their configuration. Relying on just the module config key isn't safe, instead, we introduce a utility to extract the options in a safer way.

For example, within Nuxt Simple Sitemap:

```ts
if (hasModule('@nuxtjs/i18n')) {
  const i18nVersion = await getNuxtModuleVersion('@nuxtjs/i18n')
  if (!await hasNuxtModuleCompatibility('@nuxtjs/i18n', '>=8'))
    logger.warn(`You are using @nuxtjs/i18n v${i18nVersion}. For the the best compatibility, please upgrade to @nuxtjs/i18n v8.0.0 or higher.`)
  const nuxtI18nConfig = await getNuxtModuleOptions('@nuxtjs/i18n') as NuxtI18nOptions
  if (nuxtI18nConfig?.pages) {
    // do logic
  }
}
```

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by harlan-zw** [comment]
This PR should also look to investigate if it's feasible to use this function internally to resolve the options for a module, so that we know the logic is consistent. This would also let us implement a caching layer to reduce the time needed to setup modules.

**Comment by AndreyYolkin** [comment]
Nice! I'll track this PR to include it in new kit documentation after merge

**Comment by danielroe** [comment]
@harlan-zw Is this still something you are planning on working on?

**Comment by harlan-zw** [comment]
I don't have the capacity to see if we can use this function internally, so we can either close this, merge it as is, or someone else wants to take it on.

**Pull request closed without merging**
