### PR TITLE
Feature generate scraper

### PR DESCRIPTION
**Pull request by jroxendal**
This PR implements a scraper for the generate command. If `generate.scrape` is truthy in the config each generated route will have their `a[href]` tags scraped, and any found `href` will be scheduled for rendering. 

The purpose of this feature is to avoid having to re-implement the same filtering logic in your `config.generate.routes` as in your actual vue files.

### CODE REVIEW

**Comment by Atinux** [comment]
@pimlie Would like to have your thoughts on this too since you know well the issue with cluster

**Comment by pimlie** [comment]
This wont work probably well at the moment without changes in nuxt-generate-cluster as currently the workers will probably generate duplicate routes and/or the balancing of routes between workers could become disrupted. Also I wonder whether the feature itself is really useful for the use-case where you need nuxt-generate-cluster.

Maybe it would be an idea to first implement a generic solution for adding more routes after generation has started with _optional_ automatic de-duplication? (this is actually already on my required feature list for a generate daemon).
When we have that functionality then we could implement this feature as an optional `generate:routeCreated` hook in `bin/nuxt-generate`?

**Comment by jroxendal** [comment]
@pimlie about the overlap in use-cases: yes and no, I think. My PR provides a more hands-off, what-you-see-is-what-you-generate kind of approach. But it also helps you to keep from bloating the routes function in your config with logic already implemented in your pages. Even hard-core nuxt-generate-cluster users would like to see that, right? 

I could refractor this PR so that scraping happens inside the `'generate:page'` in the `nuxt-generate` script, if that help? The `initRoutes`function would have to move there too, though, in order to get precise de-dupeing. Would that get us any closer to a scraper for nuxt-cluster-generate? 

I still think something like this scraper should be included in Nuxt by default: basically every project uses dynamic routes (right?) and this PR lowers the barrier of entry to `generate` by quite a lot!

**Comment by pimlie** [comment]
I didnt mean to imply that I thought we shouldnt add this feature, sorry if that was the case. Actually I think it would be a nice feature to add for the same reasons you mention.

But this feature could introduce a great uncertainty which routes nuxt will try to generate. Maybe I am too much of a control freak, but I like to be in full control about which pages are generated. Eg lets say I have a large blog which allows my clients to embed links, then all the '3rd party' content they post will be scraped by this feature. With the current implementation in this pr, nuxt will generate an error when:
- they use a relative link which is not on the first level
- they embed a link specifying any other protocol then http(s), eg ftp, mailto
- they link to eg a pdf or zip download

It will probably be quite some work to scrape these cases and the other ones we didnt thought of yet correctly. I will leave it up you and others to decide whether that effort is worth it :)

Implementation wise, you could also use the `generate:extendRoutes` hook to keep a copy of the original routes array in `bin/nuxt-generate`? Then you would only need to add a hook at the end of `generateRoutes` so you can generate the scraped routes?

**Comment by jroxendal** [comment]
I'll concede the need for a user-supplied filter function, perhaps the scrape property in the config could take a config object like:

```
{ scrape: { enabled: true, exclude_patterns: ["^mailto:", ".*.pdf$"] } }
```
Not a problem to implement, of course, but I would rather do so when the maintainers agree to the approach of this PR. Also I could write some tests at such a time. Does @Atinux want this feature to be compatible with nuxt-generate-cluster as well? Seems that would be a lot more work.

**Comment by pimlie** [comment]
For this (or any other) feature to work for nuxt-generate-cluster we would only need to make sure that the logic about which method does what when is controlled from within the `generate` method (or above through hooks). We could eg also change the method definitions as follows:

```js
generateRoutes({ routes, errors = [], scrapedRoutes = []})
generateRoute({ route, payload = {}, errors = [], scrapedRoutes = [] })
```
where the scraping is done in `generateRoute`.

Then in the `generate` method you could do:
```js
let scrapedRoutes = []
let errors = []
while (routes.length) {
  await this.generateRoutes({ routes, errors, scrapedRoutes })
  if (scrapedRoutes.length) {
    // call a dedup method and add to local routes in nuxt or send
    // a message with the scrapedRoutes to the master in generate-cluster
    scrapedRoutes = []
  }
}
```

**Comment by galvez** [comment]
I like this, but I think the default implementation should use [`cheerio`](https://github.com/cheeriojs/cheerio/issues/700), which is much lighter and faster for this purpose. Even better would be to accept `scrape` optionally as a function, that could be tweaked in `nuxt.config.js` on a per-project basis. Are you still interested in pursing this, @jroxendal?

**Comment by jroxendal** [comment]
I haven’t been keeping track of the latest changes to Nuxt and I don’t have
time to get back into it right now, but I still think this functionality
makes a ton of sense!

mån 6 aug. 2018 kl. 18:25 skrev Jonas Galvez <notifications@github.com>:

**Comment by galvez** [comment]
@Atinux let's close this and add it to the scope of @nuxtjs/press in v3?

**Comment by pimlie** [comment]
Imho the only feature we would need to add to implement this functionality is that the routes list (which is currenty a parameter to the `generateRoutes` method) is converted to a dynamic list with an addRoute hook and optional deduplication. You can already hook into `generate:page` to process / scrape the generated html, so you only need to be able to add routes from there. 
Scrape functionality is then just one of many possible implementations based on these hooks, which would probably also be best put into a separate nuxt module anyway.

**Comment by Atinux** [comment]
@pimlie I agree, this could definitely be implemented as a module. If you want to make a PR to add this possibility of adding new routes from the hook, please go ahead :)

@galvez I am closing it. @nuxtjs/scrapper will be this feature I think and @nuxtjs/press will be able to use it directly :)

**Pull request closed without merging**
