### PR TITLE
refactor: eliminate the coupling between ready and nuxt constructor

### LINKED ISSUE #3034: Core nuxt class should not have side effects on creation
Right now, the `Nuxt` class has an async side effect in the constructor. This (with the combination of being cached) makes it very hard to extend. You should instead have to run the `await nuxt.ready()` function be called by the parent.

https://github.com/nuxt/nuxt.js/blob/1080dfdbd678e41dc1af8b45ea3edac55fad2f2d/lib/core/nuxt.js#L40

### Personal use case

I am currently moving an old express app to use nuxt with SSR :confetti_ball:, but I need to keep backwards compatibility, which includes falling back to a proxy when no route is matched. To do this, I'm creating a new `Nuxt` class, rebinding the connect app to the already existing express app, and then removing the last middleware (error handling / 404 page). 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2629">#c2629</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by clarkdo**
Resolve #3034 

This pr will have a breaking change in custom server starting, user need to call `ready` manually after `new Nuxt`, for example in express:

```js
nuxt = new Nuxt(config)
await nuxt.ready() //need to call ready here
const app = express()
app.use(nuxt.render)
server = app.listen(port)
```

Actually even though `ready` was called in `nuxt construtor` before this pr, we should also call it for ensuring its execution is before custom server listening.

### CODE REVIEW

**Review by atinux — APPROVED** [review]
Agree but we will need to update `create-nuxt-app` and docs as well before this merge

**Comment by Atinux** [comment]
What about giving an option to avoid breaking changes? Like `autoReady: false`?

**Comment by galvez** [comment]
@clarkdo Fixed conflicts here for you, buddy :)

**Comment by pi0** [comment]
I will take over it soon. Will reuse most of the changes here.

**Pull request closed without merging**
