### PR TITLE
feat(nuxt): autocomplete layouts in `setPageLayout`/`<NuxtLayout>`

### PR DESCRIPTION
**Pull request by DamianGlowala**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Similarily to the `definePageMeta`'s layout property, `setPageLayout` could hint available layouts to the user, rather than accepting an arbitrary string.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]

**Comment by DamianGlowala** [comment]
WDYT about providing autocompletion for the `<NuxtLayout />` component as well? 😉

**Comment by danielroe** [comment]
Oh, that would be great!

**Comment by DamianGlowala** [comment]
Tried adding autocomplete for the `<NuxtLayout />`. I'm not sure why importing `PageMeta` from `#app` doesn't work in this case. Also, I left `MaybeRef<false>` instead of `Ref<false>` (even though `PageMeta` already contains `false` in its type, to make it `PageMeta`-independent.

I have also renamed the file from `layout.ts` to `nuxt-layout.ts` for consistency (and relevant import path). Let me know if there's any reason to keep it as it was, I'll revert it back.

**Comment by danielroe** [comment]
This looks like it's working well to me:

CleanShot 2023-07-30 at 23 52 45@2x

For linting, note that it should be run after `pnpm build:stub` and not after building the project.

**Review by danielroe — APPROVED** [review]

**Pull request merged**
