### PR TITLE
lint: require await in async function

### PR DESCRIPTION
**Pull request by TheAlexLichter**
Another PR to push up our `eslint` game. If a function is declared as `async`, it **must** have an await inside.

### CODE REVIEW

**Review by clarkdo — APPROVED** [review]
LGTM

**Comment by galvez** [comment]
@clarkdo @manniL check the test failure and make sure this has nothing to do with `await` or `then` being used to call these `async` functions.

**Comment by clarkdo** [comment]
Please take a look at error

**Comment by manniL** [comment]
Weird :thinking: Haven't "fixed" anything as it worked fine locally

**Pull request merged**
