### PR TITLE
feat(config): add `ignoreOptions` for `node-ignore`

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [x] New feature (a non-breaking change which adds functionality)

## Description

Since node-ignore 4.x, it has support `options` as parameter of constructor, so this pr is adding the config from nuxt.config.js.

With this change, #6588 can be solved by: 
```js
// nuxt.config.js

export default {
  ignoreOptions: {
    ignorecase: false
  }
}
``` 

TODO:

- [ ] Test
- [ ] Doc

### CODE REVIEW

**Review by galvez — APPROVED** [review]

**Review by pi0 — APPROVED** [review]

**Comment by chriscalo** [comment]
Just tried this in the latest release 2.11.0 and it doesn't seem to be working.

`nuxt.config.js`:

``` js
export default {
  // .nuxtignore
  ignoreOptions: {
    ignorecase: false,
  },
};
```

`.nuxtignore`:

``` text
pages/**/[A-Z]*.vue
```

All `pages/**/*.vue` in my project seem to be ignored regardless of how they are named.

**Comment by clarkdo** [comment]
@chriscalo What is the version of ignore in you project? The options is supported from v4

**Comment by clarkdo** [comment]
And also can you try by exact path like pattern abc.vue doesn’t ignore ABC.vue.

**Comment by chriscalo** [comment]
@clarkdo, thanks for the reply.

I'll check on the version when I get back to a computer, I haven't installed ignore myself. It's a dependency of Nuxt, so shouldn't Nuxt control the version rather than me?

> And also can you try by exact path like pattern abc.vue doesn’t ignore ABC.vue.

Not sure what you mean by this. Can you say more? Where should I try exact paths?

**Comment by clarkdo** [comment]
Yes, it’s a dep from nuxt, but it may have conflict or hoisting if your other dep also has ignore package as a dep.
I mean use exact pattern in your ignore file like pages/abc.vue and verify it doesn’t ignore pages/ABC.vue in your repo.

**Comment by clarkdo** [comment]
I’m sorry that I’m in holiday. I’ll check this as soon as I’m back.

**Comment by chriscalo** [comment]
Here's what I found in my `yarn.lock` file:

``` text
ignore@^5.1.1, ignore@^5.1.4:
```

**Comment by chriscalo** [comment]
> I mean use exact pattern in your ignore file like pages/abc.vue and verify it doesn’t ignore pages/ABC.vue in your repo.

Thanks, will try that.

> I’m sorry that I’m in holiday. I’ll check this as soon as I’m back.

Enjoy! Please don't rush on my account. This refactoring can wait. Just wanted to point out that it didn't seem to be working. Happy to provide more debug info if that's useful.

**Comment by chriscalo** [comment]
I think I may have figured out the problem: my macOS HD is case insensitive, which I'm guessing means the `ignoreCase` won't work as expected. I may have to find some other way of solving my problem. Apologies for the runaround on this.

**Pull request merged**
