### PR TITLE
Isolate client and server artifacts

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Preliminary work for #2517.

### CODE REVIEW

**Review by clarkdo — COMMENTED** [review]
LGTM
How about to extract dist server and client into options.js?

**Comment by ishitatsuyuki** [comment]
I have considered making these directories configurable, however it adds considerable complexity and I'm not sure it has an use case.

**Comment by clarkdo** [comment]
I don’t think it’s worth making them configurable, what I mean is add variables in option, so that we only need to resolve one time.

**Review by TheAlexLichter — APPROVED** [review]

**Comment by ishitatsuyuki** [comment]
Regarding putting it to `options.js`: I don't think that's necessary because it's resolved only a few times (across components), and putting it into another file may make the code harder to navigate.

**Comment by ishitatsuyuki** [comment]
@pi0 @Atinux Review ping!

**Review by atinux — APPROVED** [review]

**Comment by pi0** [comment]
That's a Breaking change for CDN deployments but great improvement @ishitatsuyuki 👍

**Comment by galvez** [comment]
@pi0 can you elaborate on why it breaks CDN deployment? You mean when we set `build.publicPath`? BTW, nice to see you!

**Comment by clarkdo** [comment]
Correct, we need to update [document](
https://nuxtjs.org/api/configuration-build#publicpath), user should upload dist/client to cdn.

**Comment by galvez** [comment]
@clarkdo like this? https://github.com/nuxt/docs/pull/719

**Comment by clarkdo** [comment]
Ues and maybe also release notes @Atinux

**Pull request merged**
