### PR TITLE
fix(builder): call extendPlugins after normalizing them

### PR DESCRIPTION
**Pull request by atinux**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)

## Description

Extending plugins should happen after normalising them.

## Checklist:

- [x] All new and existing tests are passing.
- Pending doc PR: https://github.com/nuxt/docs/pull/1698

### CODE REVIEW

**Review by galvez — APPROVED** [review]
Good catch, thanks!

**Comment by pimlie** [comment]
Hmm, but now plugins added in extendPlugins are not normalized anymore? Can we really trust the user to do everything as they supposed to?

**Comment by Atinux** [comment]
Indeed this could be an issue as well @pimlie

**Comment by Atinux** [comment]
Closing since it will make the `extendPlugins` harder to use for end users.

**Comment by manniL** [comment]
We could consider structural changes for the next major instead? :relaxed:

**Pull request closed without merging**
