### PR TITLE
fix(vue-app): prevent mounting page twice on redirect

### LINKED ISSUE #4757: Page mounted twice on redirect in SPA
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://codesandbox.io/s/40y7x1l0p4](https://codesandbox.io/s/40y7x1l0p4)

### Steps to reproduce

Open reproduction link
Open console
Add /random_string to the codesandbox project url like this https://40y7x1l0p4.sse.codesandbox.io/randome_string

### What is expected ?

Inside the console the String test should only exist once.

### What is actually happening?

The string test will be shown twice.

### Additional comments?

Already opened a bug ticket but it was closed duo to no response from the nuxt team:
https://cmty.app/nuxt/nuxt.js/issues/c8038

[aldarund](https://github.com/nuxt/nuxt.js/issues/4197#issuecomment-438785950) mentioned that asyncadata/fetch will only be triggered once but mounted/created twice. So only the component itself is created twice. This also happens in production mode. 
[goodslav](https://github.com/nuxt/nuxt.js/issues/4197#issuecomment-440202970) mentioned that you can use a workaround to get rid of it 
```
setTimeout(() => redirect()) 
```
But it's still a bug that need to be recognized!

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8463">#c8463</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by noe132**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

In spa mode and if in middleware `ctx.redirect` was call in the client first mount, it will trigger `fixPrepatch` afterEach hook, and `setLayout` being called **after** the app was mounted, which will cause the application v-dom structure to be changed and needs rerender, so the page component will be destroyed and re-created, it looks like app was mounted twice.

And, if redirect was call multiple times, the route won't be correct redirected route, because first render call `next` callback won't follow vue-router resolve flow.

fix: https://github.com/nuxt/nuxt.js/issues/4757
fix: first load multiple redirect
test: add spa redirect tests

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]
Not locally tested but overall LGTM

**Review by galvez — APPROVED** [review]
LGTM

**Review by atinux — APPROVED** [review]

**Comment by Atinux** [comment]
Really nice PR, thank you very much @noe132 

Waiting for @manniL review :)

**Comment by manniL** [comment]
Has anybody tested it locally yet?

**Comment by pi0** [comment]
Merging to land and test on `nuxt-edge`

**Pull request merged**
