### PR TITLE
fix: dont expose $nuxt in production

### PR DESCRIPTION
**Pull request by pimlie**
Exposing $nuxt is a potential security issue as it provides api access to the whole website

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
See #3858 for discussion why exposing $nuxt in production should be avoided

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by aldarund** [comment]
What about when someone want to run e2e test on production build, so needs $nuxt ?

**Comment by pimlie** [comment]
Not sure if I understand you correctly, all the unit/e2e tests already run in production mode. See https://github.com/nuxt/nuxt.js/blob/dev/test/utils/index.js#L28

**Comment by aldarund** [comment]
@pimlie i mean if end user want to run e2e test on their own site and want $nuxt for it

**Comment by pimlie** [comment]
Then I guess they should use the same 'trick' as I added for the e2e tests by assinging `window.$nuxt` in a layout: https://github.com/nuxt/nuxt.js/blob/e2de318259953fa5c62dc664326d1f5b8732c391/test/fixtures/basic/layouts/default.vue

**Comment by aldarund** [comment]
Yes, but then this should be documented.  Or maybe it just should be an option in config that will be disabled by default and when enabled $nuxt will be exposed,but not sure if it worth it

**Comment by pimlie** [comment]
Ah ok sorry, now I understand. Maybe it would be an idea to do that by adding a `NODE_ENV=testing`? I think currently nuxt only differentiates between dev and production, Testing could then be the same as production but eg with $nuxt exposed?

**Comment by pimlie** [comment]
@aldarund Thanks for the pointers, this is indeed a better solution :+1:

**Comment by pi0** [comment]
I'm not against this enhancement but we have to consider:

- Vue dev tools depend on `window.$nuxt` to detect nuxt.js production websites. So we can expose a less exposed version of `window.$nuxt` in production instead of `window.nuxt`
- Some projects depend on `window.$nuxt` for example to manually update the progress bar. That's not a valid approach but we should mention it as a breaking change when merged and released.
- `window.$nuxt` sometimes makes production debugging easier.  So we may add an option inside nuxt.config to make it configurable (To any arbitrary one like `window.$nuxtSecureObj` or disable at all)
- As an attacker point of view, he/she can still access this reference using debugger tools.

My suggestion is to first complete works on #3522. (configurable global names)

**Pull request closed without merging**
