### PR TITLE
fix(babel): loose option for babel class-properties and private-methods

### LINKED ISSUE #9224: Babel "loose" option error spamming in console on fresh project
### Versions

- nuxt: v2.15.4 
- node: v14 

### Reproduction

Just make a new project on CodeSandbox and you'll see the error.

Here is one I just made: https://codesandbox.io/s/serene-thunder-yl6rq

### Steps to reproduce

1. Make a new Nuxt project.
2. Run it.
3. Look at the console.

### What is Expected?

No random warnings.

### What is actually happening?

The warning...

```
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
```

...is spammed over and over again.

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Fix https://github.com/nuxt/nuxt.js/issues/9224

@babel/plugin-proposal-class-properties can be removed now as [it has been included in @babel/preset-env](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties)

image

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by danielroe — DISMISSED** [review]

**Comment by pi0** [comment]
Trying this in `examples/helloworld`:

```vue
<script>
class TestClass {
  // Property initializer syntax
  instanceProperty = 'bork';
  boundFunction = () => {
    return this.instanceProperty
  };

  // Static class properties
  static staticProperty = 'babelIsCool';
  static staticFunction = function () {
    return TestClass.staticProperty
  };
}
console.log(new TestClass().foo)

export default {
  head: {
    title: 'Home page'
  }
}
</script>
```

Throws a build error (**only for server**):

```
ERROR in ..../index.vue?vue&type=script&lang=js& (.../babel-loader/lib??ref--2-0!...index?vue&type=script&lang=js&) 12:19
Module parse failed: Unexpected token (12:19)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| class TestClass {
|   // Property initializer syntax
>   instanceProperty = 'bork';
|   boundFunction = () => {
|     return this.instanceProperty;
 @ ./examples/hello-world/pages/index.vue?vue&type=script&lang=js& 1:0-181 1:197-200 1:202-380 1:202-380
```

**Comment by clarkdo** [comment]
What’s your node version?

**Comment by pi0** [comment]
@clarkdo v14.16.1 (issues is webpack4 parser). Having plugin with `loose` (`: false`) _seems_ not adding dependency to `nuxt build` (#6435)

**Comment by clarkdo** [comment]
I don't think it's a depepdency issue, I think it because your node verison supports class property, so babel won't transpile it, but webpack (old acorn) doesn't support it, I'll have a look

**Comment by clarkdo** [comment]
@pi0 Updated, can you please double check and give me a review ?

**Review by pi0 — APPROVED** [review]

**Comment by clarkdo** [comment]
Oops, pr title is not updated. I’ll try to amend it

**Comment by hardydex** [comment]
Take a look at the following article

https://www.linkedin.com/pulse/nuxtjs-warn-though-loose-option-set-false-your-babelpreset-env-/

**Pull request merged**
