### PR TITLE
Improved nuxt dev restart on config change

### PR DESCRIPTION
**Pull request by dmitriie-brd**

### CODE REVIEW

**Comment by pi0** [comment]
Hi and thanks for your contribution. Would you please explain more about this improvement? I mean if we don't debounce reloads doesn't cause multiply web pack builds when fast reloading nuxt.config.js file?

**Comment by 0pt1m1z3r** [comment]
Hi! Previous code with debounce stops repeated call only for 2.5 seconds. If the restart time is longer and you change files fast then the restart tasks will accumulate.
My code excludes accumulation. Debounce duration = restart duration.

**Comment by 0pt1m1z3r** [comment]
@pi0 Strange errors in AppVeyor. Not found modules. Do you know what it is?

**Comment by pi0** [comment]
Windows bug not related to this PR. Will fix it soon. Thanks :)

**Pull request merged**
