### PR TITLE
fix(nuxt): prioritise vue app context when available

### LINKED ISSUE #20741: Cross-site request pollution with useAsyncData
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.4.3`
- Nitro Version:    `2.4.0`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `extends`, `shopware`, `runtimeConfig`, `modules`, `i18n`, `css`, `vite`, `router`, `nuxtShopwareCaching`, `prismic`, `app`
- Runtime Modules:  `modules/domainRuntimeInfo`, `@nuxtjs/prismic@3.0.0-rc.5`, `@mothership-gmbh/nuxt-shopware-caching@2.0.0`, `nuxt-schema-org@2.1.3`
- Build Modules:    `-`

### Reproduction

I'm working on a minimal reproduction.

### Describe the bug

When I request my app nearly at the same time with more than one request, there seems to be some cross-request pollution. See the screenshot. 
Bildschirmfoto 2023-05-09 um 12 32 25

The markup rendered on the server side is actually correct for each request and logging on the server side also shows that the values are present and correct for each request.
But if I inspect `window.__NUXT__` on the client side, the second request has the data of the other request in there, too, while the first request has it set to null.

I simplified the API-request that is normally done inside this useAsyncData.
```
const route = useRoute()

const returnValue = await useAsyncData('cmsResponse' + route.path, async () => {
  return {
    routeName: 'frontend.detail.page',
    foreignKey: '9855e4444b20459bbf9b94cc4f1c0c4c',
  }
})
```

Does anyone have an idea, why the second request can have the data of the first one?

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/20741
related https://github.com/nuxt/nuxt/pull/19624#issuecomment-1465838519
proper fix will need to come https://github.com/vuejs/core/pull/7743

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Now that we have access to `hasInjectionContext` we can ensure we only check for current vue instance when we are within a component (or `getCurrentInstance` should fail).

TODO:
- [x] confirm that https://github.com/vuejs/core/issues/7733 doesn't cause request to be shared when using this strategy

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by danielroe** [comment]
The test failure we're experiencing is a validation of https://github.com/nuxt/nuxt/issues/15164, meaning that the Nuxt test fixture is a reproduction (cc: @pi0).

**Review by pi0 — APPROVED** [review]
LGTM 💯

**Comment by pi0** [comment]
> The test failure we're experiencing is a validation of https://github.com/nuxt/nuxt/issues/15164, meaning that the Nuxt test fixture is a reproduction (cc: @pi0).

I will test this afterwards if you can confirm only dev tests are failing.

**Comment by danielroe** [comment]
@pi0 - Yes, that's the error code: https://github.com/nuxt/nuxt/actions/runs/5002108510/jobs/8961711745.

**Comment by iijaachok** [comment]
Had to rewrite the implementation of a test because of SSR payload structure changes, however after running a few tests I couldn't reproduce the issue anymore even with higher volume of requests - about 100 requests/sec.

Thanks for your help! 👍

**Pull request merged**
