### PR TITLE
feat: add optional chaining and null coalescing operator proposals

### PR DESCRIPTION
**Pull request by TheAlexLichter**
## Types of changes
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Add the two new stage 3 proposals to Nuxt by default via Nuxt's babel preset.
* https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator
* https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining.html

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by manniL** [comment]
Open question: Should be set `loose` to true for both by default? :thinking:

See https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator#loose

**Comment by clarkdo** [comment]
I’m not sure if they should be introduced as we never introduce stage 3(candidate) proposals into core

**Comment by manniL** [comment]
@clarkdo 	we never did by now, right. But what reason would speak against it?

**Comment by clarkdo** [comment]
I think it’s the same reason as babel-preset-env doesn’t support any stage-x proposal since proposals can continue to change before landing in browsers.

**Comment by clarkdo** [comment]
And we should find a good balance between development experience  and performance (size and time),  so following standard may be appropriate.

**Comment by clarkdo** [comment]
A good point from Babel and TC39 https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets

**Comment by manniL** [comment]
The blog post from the Babel team was kinda enlightening :+1: 	

Maybe we should provide an easy way to add it then, e.g. through a nuxt module? :thinking: 	(So ppl who need it can do it easily and w/o actually copy and pasting definitions in all projects?)

**Comment by clarkdo** [comment]
Plugins can be easily added by build.babel,plugins

**Comment by manniL** [comment]
True, but you still have to add the dependencies (of "all the proposals" you wanna add). However, this seems like it's not a huge effort in the end :relaxed: 	

Closing here :+1:

**Comment by clarkdo** [comment]
Update: optional chaining and null coalescing have been in stage-4 and @babel/preset-env will include them in short future https://github.com/babel/babel/pull/10811

**Comment by mathieutu** [comment]
Hi @clarkdo.

I've a brand new nuxt app, with @babel/preset-env:7.9.6, and I've a syntax error when using a optional chainin: 
```
Syntax Error: Unexpected token (1:112)                                                                                                                                 friendly-errors 20:27:39

                                                                                                                                                                       friendly-errors 20:27:40
 @ ./components/form/SubmitButton.vue?vue&type=template&id=f475626c& 1:0-222 1:0-222
 @ ./components/form/SubmitButton.vue
 @ /Users/mathieutu/Projects/dsecurite/node_modules/babel-loader/lib??ref--2-0!/Users/mathieutu/Projects/dsecurite/node_modules/vue-loader/lib??vue-loader-options!./pages/login.vue?vue&type=script&lang=js&
 @ ./pages/login.vue?vue&type=script&lang=js&
```

**Comment by clarkdo** [comment]
@mathieutu Can you provide more details like a reproducible repo?

**Comment by mathieutu** [comment]
I'll do a reproducible repo. For now I've just quickly replaced it with the standard `foo && foo.bar`. Actually, I think the problem is only in template. I remember using optional and coallescing in computed.

**Comment by clarkdo** [comment]
Ah, do you mean in template tag?

**Comment by mathieutu** [comment]
Ok, so nevermind, and thanks for the quick answer!

**Pull request closed without merging**
