### PR TITLE
fix(nuxt): move to `@typescript-eslint/typescript-estree`

### PR DESCRIPTION
**Pull request by christian-schwan**
### 🔗 Linked issue

#21662

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [x] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This package was moved to @typescript-eslint/typescript-estree

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by danielroe** [comment]
We also need to update the implementation here:

https://github.com/nuxt/nuxt/blob/c66c82e6a035b14a1c65aec18a8a4019cec24480/packages/nuxt/src/core/plugins/plugin-metadata.ts#L4

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
Thank you - good spot!

**Comment by favna** [comment]
At time of writing this creates a problem when running `npx nuxi@latest init` because the default nuxi template lacks a dependency on `typescript` which is a transitive required dependency for `@typescript-eslint/typescript-estree`

```
# This file contains the result of Yarn building a package (nuxt-app@workspace:.)
# Script name: postinstall

Nuxi 3.6.0

 ERROR  Cannot find module 'typescript'
Require stack:
- /Users/favna/workspace/temp/nuxt-app/node_modules/@typescript-eslint/typescript-estree/dist/convert.js
- /Users/favna/workspace/temp/nuxt-app/node_modules/@typescript-eslint/typescript-estree/dist/ast-converter.js
- /Users/favna/workspace/temp/nuxt-app/node_modules/@typescript-eslint/typescript-estree/dist/parser.js
- /Users/favna/workspace/temp/nuxt-app/node_modules/@typescript-eslint/typescript-estree/dist/index.js

  Require stack:
  - node_modules/@typescript-eslint/typescript-estree/dist/convert.js
  - node_modules/@typescript-eslint/typescript-estree/dist/ast-converter.js
  - node_modules/@typescript-eslint/typescript-estree/dist/parser.js
  - node_modules/@typescript-eslint/typescript-estree/dist/index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
  at Module._load (node:internal/modules/cjs/loader:920:27)
  at Module.require (node:internal/modules/cjs/loader:1141:19)
  at require (node:internal/modules/cjs/helpers:110:18)
  at Object.<anonymous> (node_modules/@typescript-eslint/typescript-estree/dist/convert.js:29:25)
  at Module._compile (node:internal/modules/cjs/loader:1254:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
  at Module.load (node:internal/modules/cjs/loader:1117:32)
  at Module._load (node:internal/modules/cjs/loader:958:12)
  at Module.require (node:internal/modules/cjs/loader:1141:19)

```

**Comment by danielroe** [comment]
~> https://github.com/nuxt/nuxt/issues/21723

**Pull request merged**
