### PR TITLE
fix(builder): corretly detect mode of hashed plugins

### LINKED ISSUE #5694: Plugin Filename drives mode via addPlugin
### What problem does this feature solve?

With the latest version of nuxt, plugins go to the right build via their filename when they are referenced in nuxt.config.js
  
plugin.server.js > goes to server bundle
plugin.client.js > goes to client bundle
plugin.js > goes to both

This functionality doesn't seem to work when adding plugins via modules using .addPlugin

This forces people to do .addPlugin( src:'...', mode:'something') when I'd expect the 'default' mode to be based off the source filename

https://nuxtjs.org/api/internals-module-container#addplugin-template-

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9184">#c9184</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by pi0**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

`moduleContainer.addPlugin` generates a hash suffixed name if no explicit `fileName` is provided to prevent name collisions inside `.nuxt`. This PR ensures mode of file names like `mode-test.plugin.client.530b6c6a.js` is also correctly detected.

fixes #5694

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by clarkdo — COMMENTED** [review]
Any file’s name includes client or server will be considered as mode plugin, like foo.client.bar.hash.js, is this behavior appropriate?

How about limting 0-2 times on \.\w or explicitly setting mode in addPlugin before hash generation

**Comment by pi0** [comment]
@clarkdo As the pattern is like `.(client|server|all).` I think it is safe to just allow extending suffix. Resolving mode in `addPlugin` introduces duplicate code. Any concerns for not allowing more than 2 suffixes?

**Comment by clarkdo** [comment]
Maybe an inappropriate example, foo.client.server.js

**Comment by clarkdo** [comment]
In normal usage, it’s fine, so feel free to merge.

**Comment by pi0** [comment]
The interesting fact is that with current replace strategy both previous and current result in something wrong :D

image

**Pull request merged**
