### PR TITLE
feat(vue-app): add vetur helpers for components auto-complete on VS Code

### LINKED ISSUE #3174: Nuxt.js auto completion in Vetur
Hey @Atinux, the thing we talked at VueConf US:

https://github.com/octref/nuxt-helper-json

nuxt

I'm hoping you guys can maintain it. It's just two simple json files.
Whenever you change a public API for nuxt's included components, update this package and Vetur can pull the latest definitions to power the auto completion.

Cheers!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6823">#c6823</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by atinux**
Add helpers to support auto-complete on VS Code.

Fixes https://github.com/nuxt/nuxt.js/issues/3174

One thing left, @octref needs to confirm that it can work since `@nuxt/vue-app` is a dependency of `nuxt` and is not a direct dependency of a nuxt project.

### CODE REVIEW

**Review by pi0 — COMMENTED** [review]
Should we also include new NLink and NChild aliases?

**Comment by Atinux** [comment]
I already did @pi0 :)

**Comment by octref** [comment]
I'll add a manual check for `vue-app` dependency (it's not explicitly stated in pacakge.jsos's dependencies, and I want to avoid checking all `node_modules`).

Does that mean https://github.com/nuxt-community/nuxt-helper-json can be archived?

**Comment by pi0** [comment]
@octref I think we would need that repo for backward compatibility.

**Review by galvez — DISMISSED** [review]

**Comment by octref** [comment]
- You didn't include them in `files` in `package.json`. They won't be published.
- These JSON will be importable from `@vue-app/helpers/vetur/nuxt-tags.json`, correct?
- You don't need the `vetur` key in `package.json` anymore.

**Comment by octref** [comment]
One more question. What's the version below which `@nuxt/vue-app` won't be available, so I can fallback to https://github.com/nuxt-community/nuxt-helper-json?

**Comment by pi0** [comment]
@octref Thanks for your patient review. I've tried to apply the required changes.

The helpers should be importable from either:
- `@nuxt/vue-app-edge/vetur/nuxt-tags.json`
- `@nuxt/vue-app/vetur/nuxt-tags.json`

The new `vue-app` package with helpers included should be available from next minor release (`v2.4.0`)

**Comment by octref** [comment]
From what @Atinux told me, nuxt, nuxt-legacy, nuxt-edge all depends on `@nuxt/vue-app`, where nuxt wants to ship those JSONs. What is `@nuxt/vue-app-edge`?

My plan was to check for `node_modules/@nuxt/vue-app` for the two JSON when I see `nuxt`, `nuxt-legacy`, `nuxt-edge` on deps or dev deps.

**Comment by pi0** [comment]
@octref Every nuxt mono-repo package has a version with `-edge` in front of it for edge release channel. (They are internally wired-up together) :) I somehow feel it would be easier to keep using a standalone repository for vetur integration. /cc @Atinux

**Comment by octref** [comment]
The problem is versioning. Let's say you shipped `<nuxt-new-component>`. The only way to ensure users who can use it in runtime also gets the updated IntelliSense is to ship the definitions with the runtime library.

So if I'm reading correct, is the situation:

- One nuxt app will have either `@nuxt/vue-app` or `@nuext/vue-app-edge` in `node_modules`
- `nuxt` and `nuxt-legacy` depends on `@nuxt/vue-app`
- `nuxt-edge` depends on `@nuxt/vue-app-edge`

**Comment by pi0** [comment]
@octref Yes, you are right. checking either `@nuxt/vue-app` or `@nuxt/vue-app-edge` in `node_modules` should do the trick :)

**Comment by Atinux** [comment]
Thank you @octref for your help on this :)

I validate @pi0 last comment:
> checking either @nuxt/vue-app or @nuxt/vue-app-edge in node_modules should do the trick :)

For people living on the edge (lol) and having the last definitions, it's good if vetur can also look to `@nuxt/vue-app-edge` too.

Is it good for you @octref ?

**Comment by octref** [comment]
OK, I'll do it this way:

- If nuxt/nuxt-legacy/nuxt-edge < 2.4.0 found in `package.json`, I'll fall back to use https://github.com/nuxt-community/nuxt-helper-json
- If nuxt/nuxt-legacy/nuxt-edge > 2.4.0 found in `package.json`, I'll check `@nuxt/vue-app` or `@nuxt/vue-app-edge` for the definitions.

**Comment by Atinux** [comment]
Perfect @octref 

I am merging this PR then :)

**Pull request merged**
