### PR TITLE
[wip] Babel 7 support

### LINKED ISSUE #3430: Babel 7 Support
### What problem does this feature solve?

I'd like to use the following new features of Babel:
1)  useBuiltIns: 'usage' 
2) esmodules: true
3) The new babel config file

All this to provide optimal bundling for small JS size leading to faster loading.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7223">#c7223</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Contains one hack, and tests are passing. However, it's not clear if everything is working good.

Things to watch out:
- `@babel/polyfill` impact on browsers
- Is nuxt-legacy still working?
- Does uglify work with ES6?

Close #3430

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Help wanted: I'd appreciate someone testing what I have listed above.

**Comment by aldarund** [comment]
Test on windows failing because https://github.com/nuxt/nuxt.js/blob/dev/bin/nuxt-build#L4 doesnt resolve to https://github.com/nuxt/nuxt.js/blob/dev/lib/nuxt.js like before. I dont know at all how is require('..') supposed to be working ( is there a doc for such syntax?), but clearly it doesnt want to work same way on win with this pr..

**Review by clarkdo — COMMENTED** [review]
@ishitatsuyuki Thank you so much for the pull request, but I'll close this one due to #3667

**Comment by clarkdo** [comment]
@ishitatsuyuki Thank you so much for the pull request, but I'll close this one due to #3667

**Pull request closed without merging**
