### PR TITLE
fix(inject): Throw error only if value is undefined

### PR DESCRIPTION
**Pull request by paulgv**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This change prevents the `inject()` method from throwing an error if provided value is defined but evaluates to `false`. It can be useful to inject a boolean or other "falsy" value.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

I've been trying to add some tests for the `inject()` method but having trouble with my Nuxt setup at the moment.

### CODE REVIEW

**Comment by pi0** [comment]
@paulgv Can you please add a simple test to prevent regressions in the future?

**Review by pi0 — DISMISSED** [review]

**Comment by paulgv** [comment]
@pi0 Yes, I'll try to make a working test case tomorrow!

**Comment by paulgv** [comment]
@pi0 just added some tests, I hope I put them in the right place, let me know.

**Review by TheAlexLichter — APPROVED** [review]
LGTM!

**Review by galvez — APPROVED** [review]

**Review by pi0 — APPROVED** [review]
Great

**Pull request merged**
