### PR TITLE
fix(nuxi): hard-reload nuxt when `.env` changes

### LINKED ISSUE #15040: .env values not updating properly
### Environment

Nuxi 3.0.0-rc.11                                                                                                  17:25:14
RootDir: /home/projects/github-gdfemr                                                                             17:25:16
Nuxt project info:                                                                                                17:25:16

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-gdfemr?file=.env

### Describe the bug

When updating values in `.env`, Nuxt will restart automatically but the changes aren't applied.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves  #15040

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Currently `.env` variables are not reloaded when they change. This works around that and uses the existing hard-reload functionality to force a fresh cache.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Hebilicious** [comment]
Suggestion : 
Should this supports `.env.*` instead ? People using something like `nuxt dev --dotenv .env.local` would need this as well.

**Comment by danielroe** [comment]
Maybe we could respect whatever is passed to `--dotenv`

**Review by pi0 — APPROVED** [review]
Overall change looks good to me 👍🏼 Supporting custom `--dotenv` would be also nice :)

**Comment by jianxing-xu** [comment]
This problem still exists in version 3.15 @danielroe

**Comment by danielroe** [comment]
@jianxing-xu please open a new issue with a reproduction 🙏

**Comment by jianxing-xu** [comment]
> @jianxing-xu please open a new issue with a reproduction 🙏

https://github.com/nuxt/nuxt/issues/30444

**Pull request merged**
