### PR TITLE
feat(types): add `asyncData` return types to component instance type

### PR DESCRIPTION
**Pull request by carbotaniuman**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [X] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This resolves the closed issues #7884 and nuxt/typescript#48. using a variant of @odanado work [here](https://github.com/nuxt/typescript/issues/48#issuecomment-672967770). This allows TypeScript users to use the return value of asyncData directly in their `computed` and `methods` without having to duplicate things again in `data`.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.
I'm not sure where to add these kind of tests, or even if we have tests on the type definitions themselves.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
Looks good to me but I'd love @kevinmarrec's eyes on it too.

**Comment by kevinmarrec** [comment]
Thanks for the PR @carbotaniuman 

@danielroe I didn't find time yet to check everything cause it needs to perfectly know Vue types to see if there's any mistake.

Also, I thought `fetch` was used over `asyncData` since some versions now ? But it may differ depending on user needs.

Finally, before merge I'd like something that show/prove me everything still work on medium to big projects with these changes.

**Comment by Radiergummi** [comment]
> Also, I thought `fetch` was used over `asyncData` since some versions now ? But it may differ depending on user needs.

They do slightly different things - `asyncData` blocks rendering (there's a bit of irony in that) and allows redirecting before finishing the navigation, while fetch is invoked in a component context, so navigation is already complete.

**Comment by carbotaniuman** [comment]
Good point. This would probably be better when Nuxt 3 comes around.

**Comment by rchl** [comment]
Can you please check the follow up at #19526? This doesn't seem to cause errors (at least with Vue 2.7, haven't checked 2.6).

**Comment by rchl** [comment]
Also this change doesn't even work. At least with vue 2.7:

Screenshot 2023-03-09 at 08 48 44

**Pull request merged**
