### PR TITLE
refactor: update nuxt-start dependencies dynamically

### PR DESCRIPTION
**Pull request by clarkdo**

### CODE REVIEW

**Comment by pi0** [comment]
Shouldn't we gitignore `start/package.json` now? Also why we need to do this?

**Comment by clarkdo** [comment]
Because I think we offen forgot to synchronize new versions when upgrade denpendencies

**Comment by pi0** [comment]
But we always auto-update **versions** during nuxt-edge-start release. Don't we? Maintaining `scripts/data/dependencies/start.json` would be just as hard as the `start/package.json`. BTW it's OK with your changes :D

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
@clarkdo Maybe we can gitignore `start/package.json` against accidental changes (Only allowed to locally modifiable)

**Pull request merged**
