### PR TITLE
tests: increase timeout for appveyor

### PR DESCRIPTION
**Pull request by TheAlexLichter**

### CODE REVIEW

**Review by clarkdo — COMMENTED** [review]
We’d better to investigate the root cause why appveyor is slow 😸 
/cc @pi0

**Comment by clarkdo** [comment]
I think https://github.com/nuxt/nuxt.js/pull/3581 fixed appveyor issue, so I'll close this ticket, but let's keep mornitoring and thanks very much for your efforts @manniL .

**Comment by manniL** [comment]
You are welcome! Happy it works without tweaking the timeout :relaxed:

**Comment by clarkdo** [comment]
It seemed that still have some timeout cased occasionally, let's investigate the root cause.

**Comment by clarkdo** [comment]
@manniL Issue is temporarily fixed by #3581 and #3584

**Pull request closed without merging**
