### PR TITLE
fix: SyntaxError Unexpected token export in importing babel runtime helper

### LINKED ISSUE #5400: class property does not work in v2.5.1
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://not-needed.com](https://not-needed.com)

### Steps to reproduce

```bash
$ npx create-nuxt-app nuxt-app
$ cd nuxt-app
```

Modify  `/pages/index.vue`.

```vue
<template>
  <section class="container">
    {{ name }}
  </section>
</template>

<script>
class Sample {
  static NAME = 'Alice'
}

export default {
  data() {
    return {
      name: Sample.NAME
    }
  }
}
</script>
```

Start Nuxt.js app

```bash
$ npm run dev
```

### What is expected ?

Start the application and create the instance having data: `{name: 'Alice'}`.

### What is actually happening?

Throw an Error: SyntaxError Unexpected token export

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8946">#c8946</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by ymmooot**
## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

If `useESModules` option of `@babel/plugin-transform-runtime` is true, browser can not parse the `export`.

Resolves: https://github.com/nuxt/nuxt.js/issues/5400

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by clarkdo** [comment]
The useESModules should be true since webpack will process it as babel doc described https://babeljs.io/docs/en/babel-plugin-transform-runtime#useesmodules

I think your issue may be because some other reason, could you provide a repo in the issue?

**Comment by ymmooot** [comment]
@clarkdo 
Here is the repository reproducing the issue 🙏 
https://github.com/ymmooot/reproduce-5400

**Comment by kiaking** [comment]
@ymmooot @clarkdo As I mentioned at #5400, when setting mode to `spa` this will work. So I'm guessing this is not the client side error. It should be happening at node side.

**Comment by clarkdo** [comment]
LGTM, wait for CI passing

**Pull request merged**
