### PR TITLE
fix(nuxt, vite): ignore `nuxt_component` ssr style and `isVue`

### LINKED ISSUE #93: Broken with latest version of Nuxt
image

Reported by @Atinux ;

Can be worked around using `experimental.inlineSSRStyles: false` in the `nuxt.config` file while it gets fixed.

### PR DESCRIPTION
**Pull request by antfu**
### 🔗 Linked issue

fix https://github.com/Tahul/pinceau/issues/93

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
I think we might also want to add something like this:

```ts


  // wrapper import which is generated by importing from #components
  if (query.nuxt_component && opts.type && !opts.type.includes('script')) {
    return false
  }
```

here:

https://github.com/nuxt/nuxt/blob/c7be5b4ec6a3b129c68e892c9f3dad816446bb10/packages/nuxt/src/core/utils/plugins.ts#L17-L20

What do you think?

**Comment by danielroe** [comment]
I think we might also want to add something like this:

```ts


  // wrapper import which is generated by importing from #components
  if (query.nuxt_component && opts.type && !opts.type.includes('script')) {
    return false
  }
```

here:

https://github.com/nuxt/nuxt/blob/c7be5b4ec6a3b129c68e892c9f3dad816446bb10/packages/nuxt/src/core/utils/plugins.ts#L17-L20

What do you think?

**Review by danielroe — COMMENTED** [review]
I think we might also want to add something like this:

```ts


  // wrapper import which is generated by importing from #components
  if (query.nuxt_component && opts.type && !opts.type.includes('script')) {
    return false
  }
```

here:

https://github.com/nuxt/nuxt/blob/c7be5b4ec6a3b129c68e892c9f3dad816446bb10/packages/nuxt/src/core/utils/plugins.ts#L17-L20

What do you think?

**Comment by antfu** [comment]
Do you think we should rename `?macro` to `?nuxt_macro` (or `?nuxt_page_meta`) to make them next-specific?

**Comment by danielroe** [comment]
Yes, I would agree - `nuxt_page_meta` makes sense.

**Pull request merged**
