### PR TITLE
feat: add build:extendLayouts hook

### PR DESCRIPTION
**Pull request by einsqing**
`
    await this.nuxt.callHook(
      'build:extendLayouts',
      templateVars.layouts,
      r
    )
`
## Types of changes
What types of changes does your code introduce? Put an x in all the boxes that apply:

- [ ]   Bug fix (a non-breaking change which fixes an issue)
- [x]   New feature (a non-breaking change which adds functionality)
- [ ]   Breaking change (fix or feature that would cause existing functionality to change)

## Description

Added hook to expand layout

## Checklist:

- [ ]   My change requires a change to the documentation.
- [ ]   I have added tests to cover my changes (if not applicable, please state why)
- [ ]   I have updated the documentation accordingly. (PR: #)
- [x]   All new and existing tests are passing.

### CODE REVIEW

**Comment by manniL** [comment]
Hey @einsqing! Thanks for the PR.

Please respect our issue template and explain your code changes.
Hey @einsqing! Thanks for the PR.

Please respect our issue template and explain your code changes.

---

Provide a general summary of your changes in the title above

## Types of changes
What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)


## Description
Describe your changes in detail
Why is this change required? What problem does it solve?
If it resolves an open issue, please link to the issue here. For example "Resolves: #1337"


## Checklist:
Put an `x` in all the boxes that apply.
If your change requires a documentation PR, please link it appropriately
If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.




## Checklist:



- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

**Review by TheAlexLichter — CHANGES_REQUESTED** [review]
Please add more info

**Comment by einsqing** [comment]
Types of changes
What types of changes does your code introduce? Put an x in all the boxes that apply:

  Bug fix (a non-breaking change which fixes an issue)
  New feature (a non-breaking change which adds functionality)
  Breaking change (fix or feature that would cause existing functionality to change)
Description
Describe your changes in detail
Why is this change required? What problem does it solve?
If it resolves an open issue, please link to the issue here. For example "Resolves: #1337"

Checklist:
Put an x in all the boxes that apply.
If your change requires a documentation PR, please link it appropriately
If you're unsure about any of these, don't hesitate to ask. We're here to help!

  My change requires a change to the documentation.
  I have updated the documentation accordingly. (PR: #)
  I have added tests to cover my changes (if not applicable, please state why)
  All new and existing tests are passing.
Checklist:
  My change requires a change to the documentation.
  I have updated the documentation accordingly. (PR: #)
  I have added tests to cover my changes (if not applicable, please state why)
  All new and existing tests are passing.

**Comment by einsqing** [comment]
Types of changes
What types of changes does your code introduce? Put an x in all the boxes that apply:

- [ ]   Bug fix (a non-breaking change which fixes an issue)
- [x]   New feature (a non-breaking change which adds functionality)
- [ ]   Breaking change (fix or feature that would cause existing functionality to change)

Description
Added hook to expand layout

Checklist:
Put an x in all the boxes that apply.
If your change requires a documentation PR, please link it appropriately
If you're unsure about any of these, don't hesitate to ask. We're here to help!

- [ ]   My change requires a change to the documentation.
- [ ]   I have updated the documentation accordingly. (PR: #)
- [ ]   I have added tests to cover my changes (if not applicable, please state why)
- [x]   All new and existing tests are passing.

**Comment by manniL** [comment]
Great! Now add tests for the feature, please. More information in our [Contribution Guide](https://nuxtjs.org/guide/contribution-guide)

**Pull request closed without merging**
