### PR TITLE
v2.9.0

### PR DESCRIPTION
**Pull request by pi0**
## Beta Testing

If you are interested in early testing this release, you can temporarily switch to the `nuxt-edge` distribution. Please make this change in package.json:

```diff
{
  "dependencies": {
--    "nuxt": "^2.8.1",
++    "nuxt-edge": "^2.9.0-26104024.b22e0543`",
  }
}
```

### ⚠️ Important Notes

- 👉 Minimum required node version is `8.9.0`
- 👉 Typescript support is now externalized. Refer to [official docs](https://typescript.nuxtjs.org) and [migration guide](https://typescript.nuxtjs.org/migration.html).
- 👉 `vue-meta` upgraded to [2.0.0](https://github.com/nuxt/vue-meta/releases/tag/v2.0.0). Please refer to the changelog to review notable changes.
- 👉 `scrollBehavior`  option is deprecated in favor of  `app/router.scrollBehavior.js` (#6055)
- 👉 `devModules`  option is deprecated in favor of  `buildModules` (#6203)

### 🐛 Bug Fixes

- `general`
  - #6118 Fix `modulepreload` warnings
  - #6075 Throw error when building failed in quiet mode
  - #6070 Support babel corejs config for modern mode
  - #6021 Babel polyfill can not be disabled
- `renderer`
  - #6033 Correctly load `nomodule` scripts in safari 10
- `cli`
  - #6020 Prevent both `nuxt` & `nuxt-edge` being installed
- `vue-app`
  - #6012 Emit `triggerScroll` to support hash navigation
  - #5920 Fix font-size and make width bigger
  - #5891 Always finish `transition.leave` asynchronously
  - #5890 Fix position of the build indicator when page scrolled
- `vue-renderer`
  - #6223 Call `render:resourcesLoaded` hook before `createRenderer`
  - #5964 Clone SPA meta to prevent cache modification
- `webpack`
  - #5906 Extract css breaks hmr and source-maps

### 🚀 Features

- `cli`
  - #6206 Export options
- `server`
  - #6178 Allow passing `loadingTimeout` and other arguments to `renderAndGetWindow`
- `webpack`
  - #6120 Allow function entries for `build.transpile`
- `vue-app`
  - #6194 Add `$nuxt.refresh`
  - #6186 Use EventSource instead of WebSocket for build indicator
  - #6055 Support `app/router.scrollBehavior.js` and deprecate `scrollBehavior`
  - #5941 Add `<client-only`> alias for `<no-ssr>`
  - #5844 Allow customizing loading indicator
  - #6194 Add `$nuxt.refresh()` method or refresh the actual page `asyncData` and `fetch`
  - #6231 Export router options
  - #6222 Support functional `watchQuery`
- `vue-renderer`
  - #5975 Add csp option for csp v1 compatibility
  - #6134 Support prepend/append body tags during ssr for all allowed tag types
- `typescript`
  - #5858 Externalize typescript support

### 💅 Refactors

- `config`
  - #6203 Rename `devModules` to `buildModules`
- `babel-preset-app`
  - #6197 Remove `babel-plugin-dynamic-import-node`
- `webpack`
  - #6179 Simplify transpile normalization
- `general`
  -  Refactor to adhere to [@nuxt/eslint-config](https://github.com/nuxt/eslint-config) v1

### 🏡 Chore

- `general`
  - #6065 Fix typo
  - #5990 Inverse wording of error message
  - #5910 Update opencollective infos
  - #5869 Rename backers -> nuxters
- `babel-preset-app`
  - #5897 Fix typo in babel-preset readme

### ⚓ Dependency Upgrades

- file-loader@4
- url-loader@2
- cache-loader@4
- css-loader@3
- vue-meta@2
- fs-extra@8

### 💖 Thanks to

- 719media (@719media)
- Anthony Fu (@antfu)
- Farzad Soltani (@farzadso)
- François Hodierne (@znarf)
- Josh Deltener (@hecktarzuli)
- Rafał Chłodnicki (@rchl)
- Ricardo Gobbo de Souza (@ricardogobbosouza)
- Ustun Ozgur (@ustun)
- William Chong (@williamchong007)
- bluelovers (@bluelovers)
- orblazer (@orblazer)
- yutanoma (@yutanoma)
- Dzmitry Bachko (@dbachko)

### CODE REVIEW

**Comment by vanling** [comment]
@pi0 Not sure if this is the correct place to mention this. Updating existing nuxt-edge or creating a new _--edge_ project with _create-nuxt-app_ always returns `' FATAL  Both nuxt and nuxt-edge are installed! This is unsupported, please choose one and remove the other one from dependencies.'`

**Comment by pi0** [comment]
Typescript related PRs that should be moved to typescript repo:  #6078, #6006, #5895, #5841 (probably already addressed) /cc @kevinmarrec

**Comment by kevinmarrec** [comment]
@pi0 Indeed already addressed, I've been keeping the external repo in sync :D

**Comment by pi0** [comment]
notes updated

**Review by pimlie — APPROVED** [review]
LGTM, no issues here

**Review by kevinmarrec — APPROVED** [review]

**Review by TheAlexLichter — APPROVED** [review]

**Pull request merged**
