### PR TITLE
misc: add user-defined chokidar files to watch

### PR DESCRIPTION
**Pull request by SabatinoMasala**
This allows us to (optionally) add user-defined files to watch with chokidar in nuxt.config.js.

### CODE REVIEW

**Comment by Atinux** [comment]
This is great thank you. Could you add a test case for it please?

**Comment by SabatinoMasala** [comment]
Sure,

**Comment by SabatinoMasala** [comment]
Sure, a few questions:
- Is there already a nuxt.config.js test I'm overlooking?
- I'd add a test in [cli.test.js](https://github.com/nuxt/nuxt.js/blob/dev/test/unit/cli.test.js) testing the nuxt-dev binary, is there a reason these tests are [marked as skipped](https://github.com/nuxt/nuxt.js/blob/dev/test/unit/cli.test.js#L14) though?

**Comment by Atinux** [comment]
@clarkdo Do you know why cli.test.js tests are skipped?

**Comment by Atinux** [comment]
@SabatinoMasala the cli tests has been added, you can add your test in there :)

**Comment by galvez** [comment]
@Atinux @SabatinoMasala I branched out this PR and made some slight improvements here:

https://github.com/galvez/nuxt.js/commit/b58ca3b1986145abe99538f3886589d6f890200f

@SabatinoMasala I'm working on the CLI test now -- let me know if you're around and still want to finish this, otherwise I'll submit a new PR with the remaining chores branching from yours, ok?

Very interested in seeing this come through for 2.0.

**Comment by galvez** [comment]
Here's what the test ended up looking like:

```
  test('nuxt dev', async () => {
    let stdout = ''
    const env = process.env
    env.PORT = port = await getPort()

    const nuxtDev = spawn('node', [nuxtBin, 'dev', rootDir], { env })
    nuxtDev.stdout.on('data', data => { stdout += data })

    // Wait max 20s for the starting
    await waitUntil(() => stdout.includes(`${port}`), 20)

    // Change file specified in `watchers` (nuxt.config.js)
    const customFilePath = join(rootDir, 'custom.file')
    await writeFile(customFilePath, 'This file is used to test custom chokidar watchers.')

    // Wait until two compilations are seen
    // The first one and the one that followed the change to `custom.file`
    await waitUntil(() => {
      let compiles = 0
      let match = stdout.indexOf(/Compiled client/g)
      while (match !== -1) {
        compiles++
        match = stdout.indexOf(/Compiled client/g, match)
      }
      return compiles > 1
    })
    await killNuxt(nuxtDev)
  })
```

**Pull request closed without merging**
