### PR TITLE
feat: Progress indication when generating routes

### PR DESCRIPTION
**Pull request by simplenotezy**
Adds a progress indication to the console when generating routes (e.g. `(2/3) Generated /about-us`)

nuxt generate progress

## Types of changes
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
As described in this issue: https://github.com/nuxt/nuxt.js/issues/7038 it would be handy with a little progress indication when generating routes.

I generate around 3000 routes for an e-commerce site, and it takes anywhere between 600-3000 seconds (currently investigating why) and it would be quite helpful for my impatience to have some kind of idea where in the process we are.

This pull request will add a simple indication when generating routes, like so:

    (1/3) Generated /home
    (2/3) Generate /about-us
    (3/3) Generated /contact

I would have loved to implement it using https://github.com/nuxt/webpackbar, however, lack of knowledge of how to implement it made me refrain from doing it (the webpackbar could use a little improvement in the documentation ;))

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

Not sure how to run the testsuite yet. Doubt this change would have an effect.

### CODE REVIEW

**Comment by simplenotezy** [comment]
hey @lihbr - thanks for your feedback and great ideas. How could this be turned into a module?

**Comment by simplenotezy** [comment]
Also I think you already get this "spam" when deploying, just without the `(2/5)`-part

**Comment by lihbr** [comment]
Oof my bad indeed, don't know why I was convinced that Nuxt was not displaying generated routes 🤔 Really sorry to have you puzzled on that!

As for the module you could have come up with something like the following but it doesn't make sense anymore ^^'
```javascript
const consola = require("consola");

module.exports = function () {
  this.nuxt.hook("generate:extendRoutes", routes => {
    const routesTotal = routes.length;
    let currentRoute = 0;

    this.nuxt.hook("generate:routeCreated", ({ route, errors }) => {
      if (!errors.length) {
        consola.success(`(${++currentRoute}/${routesTotal}) Generated ${route}`);
      }
    });
  });
};
```

**Comment by pi0** [comment]
Hi! Maybe we can try something like [ora](https://github.com/sindresorhus/ora)? It might be good to also honor nuxt `quite` option to make CI/CD silent and also `std-env`'s minimal to fall back to plain logs as is now.

**Comment by pi0** [comment]
Hi! As this PR is stalled and there might be different opinions on how to display progress indicator, postponing this enhancement for Nuxt3 but for sure will be improved. Thanks for contrib @simplenotezy ❤️

**Pull request closed without merging**
