### PR TITLE
docs: mention `<DevOnly>` component in api section

### PR DESCRIPTION
**Pull request by trdln**
### 🔗 Linked issue

No issue, just a minor addition to the documentation.

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Added information about `<DevOnly>` component in **Api** section of docs. Information about component was only in **Guide** section.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]

**Review by danielroe — COMMENTED** [review]
Should we remove from https://nuxt.com/docs/guide/directory-structure/components#devonly-component and link to here instead?

**Comment by trdln** [comment]
Seems fine for me, at your discretion.

**Comment by danielroe** [comment]
Then yes, let's do it.

**Comment by trdln** [comment]
Should we remove `<ClientOnly>` and `<NuxtClientFallback>` components too?

**Comment by danielroe** [comment]
That would make sense to me. wdyt @Atinux?

**Comment by Atinux** [comment]
Good for me to move them to the API, I still believe that it is nice to have a small section in the components directory page to mention about those `DevOnly` and `ClientOnly` components and link to them on the API section

**Review by danielroe — APPROVED** [review]

**Pull request merged**
