### PR TITLE
added support for multi-threaded nuxt-generate

### PR DESCRIPTION
**Pull request by pimlie**
As discussed in #1090.

This PR adds support for multi-threaded nuxt-generate by use of the `cluster` package. Two variables have been added to the Nuxt options:
- `options.generate.workers`: the number of workers that should be used, default 1
- `options.generate.worker_concurrency`: the (maximum) number of routes that should be sent to a worker per iteration

I have also added the option `-j` (or `--workers`) to `nuxt-generate` so you can set the number of workers more easily (e.g. `npm run generate -- -j 3`).

The logic in `lib/builder/generator.js` has been split into separate methods so we can call each step separately. Due to this the call to `applyPluginsAsync('generated', this)` is now done _before_ printing the duration and error report. And as I really wanted to call the method that generates the routes `generateRoutes`, I renamed the variable with the same name to `staticRoutes`

### CODE REVIEW

**Comment by pimlie** [comment]
Any thoughts about this? If you don't like the changes to `nuxt-generate` it would be nice if at least the changes to `generator.js` with regards to logic separation could be accepted (in the next rc?). Without them it will be difficult to implement but especially maintain a multi threaded generator in a separate package.

Here an example output I ran with ~7.8k routes, limiting factor here was my api that was running at 100% cpu load:
```
  nuxt:generate-master Worker 8126 generated 1131 routes in 281127ms +1ms
  nuxt:generate-master Worker 8131 generated 1154 routes in 281778ms with 11 errors +0ms
  nuxt:generate-master Worker 8136 generated 1103 routes in 281043ms with 5 errors +0ms
  nuxt:generate-master Worker 8141 generated 1121 routes in 281233ms +0ms
  nuxt:generate-master Worker 8146 generated 1111 routes in 281204ms +0ms
  nuxt:generate-master Worker 8151 generated 1102 routes in 281565ms +0ms
  nuxt:generate-master Worker 8156 generated 1139 routes in 281097ms +0ms
  nuxt:generate HTML Files generated in 317534s +5m
```
and
```
/var/www/nuxt/dist# find . -type f -name *.html | wc -l
7861
```

**Comment by Atinux** [comment]
Hi @pimlie 

This is not an easy choice to make, we are still talking about it, as you can see, we did not close it since it was in the backlog of nuxt.js, we are just trying to find a way to keep it simple.

I have one question why the short option for workers is `-j` instead of `-w`?

Also, could you generate the same example but with the actual `nuxt generate` to see the performance difference?

**Comment by pimlie** [comment]
@Atinux thanks for giving an update

Maybe `-w` is better indeed, I used `-j` as I have some damn muscle memory from using `make -jX` for years when I needed to compile something with more then one job/worker ;)

Btw, I noticed some small bugs in this PR. Eg there is a `break` in generate.js which is a leftover from debugging and time is calculated in millieseconds but displayed as seconds. Pending your decision I can push a new commit to fix those.

As requested, running generate single threaded (`npm run generate -- -j 1`):
```
  nuxt:generate HTML Files generated in 1815s +6ms
  nuxt:generate Generate done +30m
```
and as the test dataset has changed a bit also the output again of running with 7 threads (`npm run generate -- -j 7`). I am using 6-core machines so you can see that they are really maxing out here.
```
  nuxt:generate-master Worker 4618 generated 1224 routes in 295673ms with 5 errors +0ms
  nuxt:generate-master Worker 4623 generated 1217 routes in 295675ms +0ms
  nuxt:generate-master Worker 4628 generated 1239 routes in 296032ms +0ms
  nuxt:generate-master Worker 4633 generated 1247 routes in 295503ms +0ms
  nuxt:generate-master Worker 4638 generated 1237 routes in 295565ms +0ms
  nuxt:generate-master Worker 4643 generated 1261 routes in 295653ms +0ms
  nuxt:generate-master Worker 4648 generated 1258 routes in 295620ms with 12 errors +0ms
  nuxt:generate HTML Files generated in 341353s +5m
```
both results in:
```
/var/www/nuxt/dist# find . -type f -name *.html | wc -l
8683
```

**Comment by roja** [comment]
Any news on accepting this? For those of us looking to use nuxt to generate large sites it makes a significant difference to our ability to adopt nuxt.

**Comment by pimlie** [comment]
@pi0 @Atinux Could you maybe give a time frame when you think you will be able to have a look at this (if at all)? Would be very much appreciated :bowing_man:

**Comment by Atinux** [comment]
Hey @pimlie 

Sorry for the delay, we've seen we @pi0 and `2.0` will focus on performance, so we will be working on this PR after `1.0` release.

**Comment by pimlie** [comment]
Thanks for the update.

As now I know it might still take a while, I have created a separate package with the changes from this PR: [nuxt-generate-cluster](https://github.com/pimlie/nuxt-generate-cluster). This way me and others can already easily use this.

**Comment by Atinux** [comment]
Actually this is even more Awecome @pimlie!

Would you agree to transfert it on [nuxt-community](https://github.com/orgs/nuxt-community)? I invited you to be part of the team :)

**Comment by Atinux** [comment]
Closing the PR since the module is more awesome

**Comment by pimlie** [comment]
@Atinux thank you for the invite :bowtie:

But eh, does that mean I can just push the repo to the nuxt-community or should you first create a repo? Not sure what is expected from me to do now and dont want to do something I shouldnt...

**Comment by Atinux** [comment]
You can transfer you repo to `nuxt-community` so it can be **official** and that's it :)

**Comment by pimlie** [comment]
@Atinux ah great, didnt knew you could transfer ownership that easily :) 
And sorry but I have another question, how should I go about with publishing the npm package? Should I do that still with my own npm user or is there also a nuxt-community user for that?

**Comment by Atinux** [comment]
I like `nuxt-generate-cluster` :)

But could you add @pi0 and me as collaborator on NPM please?

**Comment by pimlie** [comment]
Sure, no problem. You have been added. Let me know if you have any other suggestions/remarks/wishes :)

**Pull request closed without merging**
