### PR TITLE
lib/server.js constructor add server and isNotListen support

### PR DESCRIPTION
**Pull request by yuchonghua**
lib/server.js constructor add server and isNotListen support
lib server js constructor add server and isnotlist

### CODE REVIEW

**Comment by Atinux** [comment]
I am sorry I cannot implement this since it's related to ddv directly.

You should create your plugin for ddv to add this logic.

**Comment by yuchonghua** [comment]
@Atinux In fact, this is not directly related to the development of a server interface, I am not sure whether you read this code

**Comment by yuchonghua** [comment]
@Atinux 
lib server js constructor add server and isnotlist

**Comment by yuchonghua** [comment]
@Atinux Suddenly think you do not look at the code to make this evaluation

**Comment by Atinux** [comment]
@yuchonghua I looked at the code and I confirm that it is not pertinent to merge it for nuxt.js

You can create a project call `ddv-nuxt` where you create your own server with node.js and add the isNotListen login inside.

See https://github.com/nuxt/express

**Pull request closed without merging**
