### PR TITLE
Deep fill env

### PR DESCRIPTION
**Pull request by dmitriie-brd**
nuxt.config.js
```js
env: {
  foo: {
    bar: {
      baz: "hi"
    }
  }
}
```

### Before:
```js
// process.env.foo.bar.baz
{ bar: { baz: "hi" } }.bar.baz
```

### After:
```js
// process.env.foo.bar.baz
"hi"
```

### CODE REVIEW

**Comment by Atinux** [comment]
Hi @0pt1m1z3r 

Thanks for the PR, I believe we can improve this, first of, `fillEnv` could be inside `webpack/utils.js` since it's used in two files.

Also, what about arrays?

**Comment by 0pt1m1z3r** [comment]
Ok. I will move it to utils.
Arrays keys now need to write like `.1.`. I will fix it to `[1]`. And for
string keys that can not be write with dots.

21 нояб. 2017 г. 4:41 ПП пользователь "Sébastien Chopin" <
notifications@github.com> написал:

Hi @0pt1m1z3r <https://github.com/0pt1m1z3r>

Thanks for the PR, I believe we can improve this, first of, fillEnv could
be inside webpack/utils.js since it's used in two files.

Also, what about arrays?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/nuxt/nuxt.js/pull/2171#issuecomment-346029591>, or mute
the thread

**Comment by 0pt1m1z3r** [comment]
@Atinux 
```js
env: {
    items: [
      { id: 1, name: 'Kobe' },
      { id: 2, name: 'Michael' }
    ],
    foo: {
      bar: {
        baz: 'hello',
        'wi-fi': true
      },
      'a"-"b': {
        'b\'c': {}
      }
    }
  }
```

```js
    console.log(process.env.items[0].id)
    // 1
    console.log(process.env.items[0].name)
    // "Kobe"
    console.log(process.env.items[0])
    // {"id":1,"name":"Kobe"}
    console.log(process.env.items[1].id)
    // 2
    console.log(process.env.items[1].name)
    // "Michael"
    console.log(process.env.items[1])
    // {"id":2,"name":"Michael"}
    console.log(process.env.items)
    // [{"id":1,"name":"Kobe"},{"id":2,"name":"Michael"}]
    console.log(process.env.foo.bar.baz)
    // "hello"
    console.log(process.env.foo.bar['wi-fi'])
    // true
    console.log(process.env.foo.bar)
    // {"baz":"hello","wi-fi":true}
    console.log(process.env.foo['a"-"b']['b\'c'])
    // {}
    console.log(process.env.foo['a"-"b'])
    // {"b\'c":{}}
    console.log(process.env.foo)
    // {"bar":{"baz":"hello","wi-fi":true},"a\\"-\\"b":{"b\'c":{}}}
```

**Comment by 0pt1m1z3r** [comment]
@Atinux ping

**Comment by mathieutu** [comment]
Hi, I've an issue with the env variables, and I'm currently making a PR which will be in conflict with this one. 

The issue is: 
```js
env: {
  FOO: 'bar'
}

console.log(process.env['FOO']);` //bar
`const key = 'FOO'; console.log(process.env[key]);` // undefined
``` 

I know how to fix it, but it involves to totally change the way the object which is putted in `definePlugin` is constructed.
 
@Atinux how do you want to process? Have you planed to merge this one? Can I integrate this PR in mine? 

Merci pour la réponse 😉 !

**Comment by Atinux** [comment]
Hi @mathieutu 

Actually, it's Webpack which replaces the values of `process.env.X` but I'm happy to see if there is a solution to use variables like you do.

I plan to merge this PR into 2.0 since it's a breaking change. It would be awesome if you could work on a branch from this PR directly :)

**Comment by mathieutu** [comment]
Ok, I'll do that so.
I've just tried to do it in a module, it works perfectly with the "old" way to handle env variables.

@Atinux Do you know when you will release the 2.0? Maybe should I make a PR before to fix the 1.* version?

**Comment by Atinux** [comment]
Sure you can already send a fix for the 1.x version :)

The version 2 will come in a month I believe

**Comment by mathieutu** [comment]
Hi!
Actually we don't need this PR anymore. 😅 
https://github.com/nuxt/nuxt.js/pull/2171 handle this behavior directly without any trick.
@0pt1m1z3r I let you test your needs on my branch an let us know if it's ok for you?

**Comment by 0pt1m1z3r** [comment]
@Atinux you can notify me when you want to merge this PR, and I will bring it to the actual code

**Comment by mathieutu** [comment]
Forgot to mention here that I finally merged this one with https://github.com/nuxt/nuxt.js/pull/2974, so no need to pull it. (Or it should be overwritten by the over.)
 🙂

**Pull request closed without merging**
