### PR TITLE
Fix Error Cannot stringify arbitrary non-POJOs

### PR DESCRIPTION
**Pull request by Mosharush**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

This error will show after using devalue instead of serialize.
When nuxt cached the component data will show the errors.

### CODE REVIEW

**Comment by Webstorm-IL** [comment]
If somebody wants to fix on him project add middleware on axios response for fix the object:
https://gist.github.com/Webstorm-IL/0d7bddedbb3212cd830e125b161add0c

**Comment by galvez** [comment]
@aldarund can you take a look?

**Comment by aldarund** [comment]
@Webstorm-IL what do u mean by cached component data? Do u have a reproduction? Codesandbox or github repo with step to reproduce

**Comment by galvez** [comment]
@Webstorm-IL thanks for your PR. We've discussed the issue and found this might silently introduce failures -- so we're closing it. We're addressing this problem differently.

**Pull request closed without merging**
