### PR TITLE
chore(deps): upgrade webpack loaders and require at least Node.js 10.13.0 (LTS)

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

As webpack loaders and 5 requires at least Node.js 10.13.0 (LTS), this pr is making same changes for Nuxt.

**Note:** This pr is a breaking change, so we may consider to merge it after webpack 5 migration.
 
## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by pi0** [comment]
So let's merge it with WP5 branch?

**Comment by clarkdo** [comment]
@pi0 I open this separate pr for reminding myself this breaking change for now 😃

**Comment by Atinux** [comment]
Should we create a `feat-webpack5` branch then?

**Comment by clarkdo** [comment]
@Atinux I'll move this to https://github.com/nuxt/nuxt.js/pull/4616

**Pull request closed without merging**
