### PR TITLE
feat(nuxt): allow configuring spa loading indicator

### LINKED ISSUE #14796: SPA loading placeholder
When SSR is false, while the initial page is being loaded, there is a white page (and if any error happens on the initial render it remains white). 

In Nuxt 2, we have [loadingIndicator](https://nuxtjs.org/docs/configuration-glossary/configuration-loading-indicator/) option with a preset of ready-to-use templates.

In Nuxt 3, it is possible to use a nitro plugin to replace the blank page.

In the meantime, we can use a Nitro plugin to have same effect:

https://stackblitz.com/edit/github-jvjkpp?file=nuxt.config.ts,server%2Fplugins%2Fplaceholder.ts

```ts
// server/plugins/placeholder.ts

export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('render:response', (res) => {
    res.body = res.body.replace(
      '<div id="__nuxt"></div>',
      `<div id="__nuxt">Loading....</div>`
    );
  });
});
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/14796

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This allows users to configure their SPA loading HTML, by creating a custom `app/spa-loading-template.html`. By default it also injects an animated Nuxt logo for the loading state, which can be disabled by setting `spaLoadingTemplate: false` in your nuxt config.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by atinux — APPROVED** [review]
💯

**Comment by danielroe** [comment]
Any thoughts on this @pi0? Would very much value your insight, but I'm hoping to merge this today in time for the release.

**Comment by MuhammadM1998** [comment]
Sorry if this a dumb question but why not using `.vue` extension as with error page for example?

**Comment by Barbapapazes** [comment]
> @danielroe Sorry if this a dumb question but why not using `.vue` extension as with error page for example?

Because Vue is not loaded at this time. Indeed, the loading page is shown while the app is loading. Using a  `vue` file could suggest to dev that they could use any JavaScript but it's not possible.

**Review by pi0 — APPROVED** [review]
Looks perfect 👌🏼 

I was going to suggest moving the template to assets that is done (https://github.com/nuxt/nuxt/pull/21640/commits/d3a8a4bef92450c80c3bcc77809319233c2abedc) and rest can be followed up from there. 

The Only thing we probably have to communicate in the release notes is that we are adding Nuxt branding to the production SPA loading indicator (Nuxt 2 didn't have a nuxt branded default loading screen as well as Nuxt 3 which was blank by default before). Some might find it undesired and surprising by to see a version bump in production....

**Comment by pi0** [comment]
>  Sorry if this a dumb question but why not using .vue extension as with error page for example?

As @Barbapapazes pointed out, Vue/Nuxt App is not initialized yet. However you can use [`petite-vue`](https://github.com/vuejs/petite-vue) to implement a custom Vue-powered loading indicator.

**Comment by pi0** [comment]
@danielroe Shall we improve docs too or with a full example for customization?

**Comment by amoralesdesign** [comment]
Hi, I'm trying to get Nuxt to grab the spa-loading-template.html that I have created inside myproject/app/spa-loading-template.html, but it doesn't work, is there something I'm doing wrong?

I have also tried setting spaLoadingTemplate: false, but it doesn't work.

loadingnuxt

**Comment by amoralesdesign** [comment]
> It should be within your srcDir. And if you update to 3.6.1 then you setting it to false should work.

I moved it to srcDir and it doesn't work either:
srcdir

**Comment by danielroe** [comment]
I mean, it should be `~/app/spa-loading-template.html`, where `~` means your `srcDir`.

**Comment by amoralesdesign** [comment]
I have moved the html with that path you told me and it doesn't work either:
newsrcdir

**Comment by danielroe** [comment]
Seems to be working fine for me: https://stackblitz.com/edit/github-y3znai?file=nuxt.config.ts,src/server/plugins/test.ts,src/app/spa-loading-template.html.

If not, please open a new issue with a reproduction and I'd be happy to help.

**Comment by EvgenijHenning** [comment]
> I have moved the html with that path you told me and it doesn't work either: newsrcdir

Actually, im playing with this feature and got it to work. 

As @danielroe mentioned the `~/app/spa-loading-template.html` ist the correct folder (not src as subdir). After putting it in the app folder I **had to restart nuxt/nitro**. Give it a try.

**Comment by jd1378** [comment]
@danielroe there's a moment of nothingness, more than a moment if network is slow, before the main content is loaded and after the template is unloaded, which is undesirable

can't we keep the template in body while we load the app, then unload the spa template when the page is finished rendering ? (it would be also nice if we could add an exit transition to it, like fading out, instant of just suddenly disappearing)

**Comment by LarisaShirokikh** [comment]
Снимок экрана 2023-12-15 в 15 21 13
The default Nuxt screensaver still works before my boot image
what am I doing wrong?

Снимок экрана 2023-12-15 в 15 24 35
Снимок экрана 2023-12-15 в 15 24 51

**Comment by MrPinacolada** [comment]
Hello there. But if I want to use vue component instead of html file or include some imports to run json animation, how should I do that? 
image

**Comment by Barbapapazes** [comment]
> Hello there. But if I want to use vue component instead of html file or include some imports to run json animation, how should I do that? 
> image
> 

You can't use a vue component instead of an html file.

**Comment by MrPinacolada** [comment]
> > Hello there. But if I want to use vue component instead of html file or include some imports to run json animation, how should I do that?
> > image
> 
> You can't use a vue component instead of an html file.

I understand that. But how can I put some animation player inside this html file? If I do this just by inserting some raw html context, it doesn't work( 
image

**Comment by danielroe** [comment]
It needs to be an html snippet that can be injected in the div that holds your Vue app, not the entire document.

**Pull request merged**
