### PR TITLE
Solves twitter problem

### PR DESCRIPTION
**Pull request by DominikAngerer**
Got your back @Atinux: https://mobile.twitter.com/Atinux/status/1133719426367410177

### CODE REVIEW

**Comment by Atinux** [comment]
🤣

**Review by clarkdo — COMMENTED** [review]
First step to be most ambitious framework in frontend.

**Comment by pi0** [comment]
jQuery is missing 🙈

**Comment by DominikAngerer** [comment]
Not sure if I should create another PR - this one got closed so fast... Tried my best :'D

**Pull request closed without merging**
