### PR TITLE
Only index route as a folder

### PR DESCRIPTION
**Pull request by blocka**
Just like the other pages can be a folder + index.vue file, I need the index page also to work the same way.
This PR makes index/index.vue the equivalent of index.vue.

### CODE REVIEW

**Comment by clarkdo** [comment]
Thank you for the contribution.

And if you want to define `pages/index/index.vue`, I suggest create both `pages/index.vue` and `pages/index/index.vue`, so you can get a workable nested index.

@pi0 @Atinux How do you think about this pr ?

**Comment by Atinux** [comment]
I'm not sure to understand what it does and solves exactly.

`pages/index/index.vue` is mostly used to be a child of `pages/index.vue` and I don't recommend this and instead to use a layout for this. Could you give me an example where the current implementation might have a problem in its behaviour?

**Comment by blocka** [comment]
Generally speaking, when I have break up a component into subcomponents, I turn the [component].vue file into a folder, and have [component]/index.vue + any child components.

So if I had a structure like this:

````
pages
    index.vue
    profile.vue
```
And I realized I wanted to extract one part out of profile.vue and make a subcomponent (that is _only_ used in the profile page), I would do

```
pages
    index.vue
    profile
       index.vue
       subcomponent.vue
```

As you can see, I can't do that with the index page.

This PR allows me to do:

```
pages
    index
       index.vue
       subcomponent.vue
```

**Comment by mojereliev** [comment]
This should solve this problem:
https://github.com/nuxt/nuxt.js/issues/2776

**Comment by mojereliev** [comment]
I tried it
```
.map(async ({ route, payload }) => {
    if (route !== '') {
        await waitFor(n++ * this.options.generate.interval)
        await this.generateRoute({ route, payload, errors })
    }
})
```
in https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/generator.js#L110
It works.

**Comment by Atinux** [comment]
@mojereliev @blocka Thanks for your explanations, one question tough, why not using a layout for this? Layouts are clode-splitted automatically, is it more for folders structure?

**Comment by qm3ster** [comment]
All along, you could turn
`pages/foo/bar.vue`
into
`pages/foo/bar/index.vue`

This PR adds in that it can now also be turned into
`pages/foo/bar/index/index/index/index/index/index.vue`?
or only
`pages/foo/bar/index/index.vue`?

And the purpose is ignoring all files and directories in 
`pages/foo/bar/index/` except `index.vue`, so that you can leave random files related to this page there?


Can we achieve the same benefits with the proposed general file and directory ignore syntax?
Eg:
```
pages/foo/bar/index.vue
pages/foo/bar/.subcomponents/yaboi.vue
pages/foo/bar/.subcomponents/yaboiiii.vue
pages/foo/bar/.barStool.vue
```

:pizza:

**Comment by blocka** [comment]
This is not about layouts. It's about allowing me to split up my index page into multiple components. Currently, if I do that the subcomponents have to live away from the actual component. What I want is that the index page can be a folder too, and the subcomponents in that folder. It's about code organization, mostly.

**Comment by qm3ster** [comment]
@blocka, would the example in my comment satisfy your needs?

**Comment by blocka** [comment]
@qm3ster are you saying that nuxt will support allow me to do something like
```
pages/index.vue
pages/.components/subcomponent.vue
```

If so that...kind of...satisfies my needs. I _could_ live with it. But if I was using vue-router alone, I wouldn't do that. I would point my '/' route to folder with an index.vue file.

**Comment by qm3ster** [comment]
Yup, including root.

**Comment by blocka** [comment]
Is there a particular objection to my approach?

**Comment by qm3ster** [comment]
It introduces a new specific syntax, while the ignored files/dirs is universal to the pages/middleware/store modules filesystem APIs.

**Comment by blocka** [comment]
I'm not sure what you mean by additional syntax. Every other page can be a
folder right now (eg., about/index.vue) will create a /about route. To me
this is just inconsistent.

**Comment by qm3ster** [comment]
It adds weird meaning to directories called `index`.
Currently, only **files** called `index` have special meaning, which comes directly from web tradition of `/foo/index.html`===`/foo/` (and sometimes `/foo`)
```
pages
    index
       index.vue
       subcomponent.vue
```
To me, the above should produce `index/(index.html)` and `index/subcomponent.html`
You are suggesting that it should now only produce `/(index.html)`

With the general purpose syntax, you could do

```
pages
    index.vue
    .subcomponent.vue
```
to produce `/(index.html)`, and 


```
pages
    index
       index.vue
       .subcomponent.vue
```
to produce `/index/(index.html)`

Do you disagree?

**Comment by blocka** [comment]
Is this feature in nuxt now? I don't see anything in the change log, and I didn't see any PRs to that effect? (or maybe it's been here all along and I just missed it in the docs?)

**Comment by galvez** [comment]
@Atinux I think we can close this by now?

**Pull request closed without merging**
