### PR TITLE
feat: client mode modern and support dev/generate

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This bug is reported by @aldarund 

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by aldarund** [comment]
@clarkdo Dont really help. There no such error with this PR. But it also dont build at all.
```
$ nuxt
[13:27:30] [INFO] Building project
[13:27:31] [WARN] addVendor has been deprecated due to webpack4 optimization
  nuxt:pwa Adding icons +0ms
  nuxt:pwa Adding manifest +1s
  nuxt:pwa Adding meta +0ms
  nuxt:pwa No host specified, skipping og:image +1ms
[13:27:33] [SUCCESS] Builder initialized
[13:27:33] [SUCCESS] Nuxt files generated
[13:27:34] [INFO] Compiling client
(node:25936) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[13:28:21] [SUCCESS] Compiled client in 46s
```
After that last message i waited 15 minutes and its stuck.

**Comment by aldarund** [comment]
```
 [JavaScript]:
   ticks  total  nonlib   name
   3311    2.2%   11.4%  Builtin: LoadIC
   3165    2.1%   10.9%  LazyCompile: *resolve path.js:138:28
   2898    1.9%   10.0%  LazyCompile: *normalize path.js:284:32
   1081    0.7%    3.7%  Builtin: StringAdd_CheckNone_NotTenured
   1016    0.7%    3.5%  Builtin: StringSubstring
    730    0.5%    2.5%  LazyCompile: *relative path.js:496:30
```
so it seems that it doing some really file traversing or going over same over and over again

**Comment by clarkdo** [comment]
@aldarund I’ll take a look, thank you so much for the information

**Comment by clarkdo** [comment]
@aldarund Could you pls check if this pr fix your issue ?

**Review by pi0 — APPROVED** [review]

**Comment by aldarund** [comment]
@clarkdo will do shortly, missed your message

**Pull request merged**
