### PR TITLE
feat: support core-js 3

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Migrate corejs in babel to V3

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by clarkdo** [comment]
The increased bundle size need to be investigated

**Comment by clarkdo** [comment]
image
image

**Review by TheAlexLichter — APPROVED** [review]

**Comment by manniL** [comment]
2 kB gzipped shouldn't stop us from upgrading to core-js 3 IMO.

**Comment by pi0** [comment]
Agree with @manniL. The size increase is reasonable. BTW Thanks @clarkdo for analyzing bundle too. Was going to do that :))

**Review by pi0 — APPROVED** [review]
Perfect

**Pull request merged**
