### PR TITLE
perf(nuxt): prefer iterating rather than `Object.fromEntries`

### PR DESCRIPTION
**Pull request by GalacticHypernova**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Many parts of nuxt require some sort of object manipulation, and therefore use Object.fromEntries and some more filter methods. This, especially in larger inputs, can really slow it down. This PR solves these issues by eliminating unnecessary iterations.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by GalacticHypernova** [comment]
@danielroe Should I group all of these updates into this one PR? (Marking this a draft so that in case you say yes I would be able to add them all here).

**Comment by GalacticHypernova** [comment]
Sorry this took so long, personal life has been very demanding! 
I would like to hear your opinion on whether this PR should be an all-around "perf PR" and kept around to group all improvements (kind of like a monorepo but in PR form) or separate them by topics (like this one currently is for Object.fromEntries)

**Comment by GalacticHypernova** [comment]
Thanks for the refactor! 
I had planned to do it but got a bit caught up with something, sorry about that 😅 
Although I do wonder why with reduce 2 checks were failing...

**Comment by GalacticHypernova** [comment]
May I ask why the revert? I get that smaller arrays would provide less of a performance improvement, but it's an improvement nonetheless. And I'm not even sure, could the bundles be considered small? Is it not user-input dependant?

**Review by danielroe — APPROVED** [review]

**Comment by GalacticHypernova** [comment]
Well, in that case I suppose it's reasonable. Thanks for the feedback!

**Pull request merged**
