### PR TITLE
chore(contribution-guide): remove duplicate guide and refer to docs

### PR DESCRIPTION
**Pull request by TheAlexLichter**

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

**Comment by sibbngheid** [comment]
Also both of them not up to date.

https://github.com/nuxt/nuxt.js/blame/dev/CONTRIBUTING.md#L40
I think we need `yarn build` here.

https://github.com/nuxt/nuxt.js/blame/dev/CONTRIBUTING.md#L82-L83
Also check this too.

**Comment by manniL** [comment]
@sibbngheid You are right. Feel free to send a PR (to the docs one)! :relaxed:

**Comment by pi0** [comment]
@sibbngheid We don't need `yarn build` step anymore :)

**Comment by pi0** [comment]
@sibbngheid @manniL Please accept my apologies. Actually, we still need `yarn build` before running tests until `esm` supports Jest and we can get rid of babel transformer. But for easier testing nuxt with `yarn nuxt examples/hello-wrold` a single call of `yarn` or `./scripts/dev` command is needed so `dists` will go back to the dev mode. Probably this PR was not the best place to mention this tips.

**Comment by sibbngheid** [comment]
@pi0 Feel free to send a PR (to the docs one)! 😂

**Pull request merged**
