### PR TITLE
chore(deps): upgrade to nitro 2.8

### PR DESCRIPTION
**Pull request by pi0**
### 🔗 Linked issue

https://github.com/unjs/nitro/issues/1928

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

(this is a prerelease draft for verifying the ecosystem) 

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
only the ui repo seems failing with the prerender error which i guess is unrelated 

image

/cc @benjamincanac @Atinux

**Comment by Atinux** [comment]
Weird since the page exists: https://ui.nuxt.com/getting-started/examples

How can we try locally? Using nitro-edge resolution?

**Comment by pi0** [comment]
Yep you can try by adding resolutions (also for nuxt and h3 would be best)

**Comment by benjamincanac** [comment]
@pi0 It is probably related to something inside: https://github.com/nuxt/ui/blob/dev/docs/modules/content-examples-code.ts

Is there any breaking change in nitro?

**Comment by danielroe** [comment]
The UI module is already failing on `main` - I've pinged @benjamincanac about this as I think it's not related to any change in Nuxt.

**Comment by benjamincanac** [comment]
@danielroe How do you explain that the `@nuxt/ui` CI and Vercel build works then? What's the difference?

**Comment by danielroe** [comment]
To replicate an ecosystem CI failure, you can clone `nuxt/ecosystem-ci` and run `pnpm i && pnpm test ui`.

In general, it might be a nitro issue as we do use `nitropack-nightly` when running CI. But in this case it's replicable with nitro 2.7.2 as well. (Just checked.)

So I would check whether the issue is the branch name or commit history (as it's running in a slightly different context), if you can't reproduce locally with pinned nightly versions of nuxt.

**Comment by benjamincanac** [comment]
Just set the resolutions locally but I can't check as `MDC` and `MDCRenderer` components are not found: `Failed to resolve component: MDC`. How can the `@nuxt/content` CI passes?

```
"resolutions": {
    "nuxt": "npm:nuxt-nightly",
    "nitropack": "npm:nitropack-nightly"
  }
```

**Comment by pi0** [comment]
@benjamincanac have you made sure to set **both** nuxt and nitro resolutions?

**Comment by benjamincanac** [comment]
@pi0 I've set the resolutions of my previous comment, am I missing something?

**Comment by benjamincanac** [comment]
@danielroe Have you been able to run the `pnpm test ui` locally? Where should I put the `.env` with the `NUXT_UI_PRO_LICENSE`, it gets erased in `workspace/ui/ui`.

**Comment by productdevbook** [comment]
pr title "refactor: upgrade to nitro 3.8 " -> "refactor: upgrade to nitro 2.8"

**Review by danielroe — APPROVED** [review]

**Pull request merged**
