### PR TITLE
feat(babel-preset-app): change default core-js to v3

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

As `core-js@2` has been deprecated officially, we can change default version to v3 now.

https://www.npmjs.com/package/core-js/v/2.6.10

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by manniL** [comment]
This will be a breaking change, right?

**Comment by clarkdo** [comment]
@manniL I think it's not a breaking change since user won't change anything for it.

**Comment by clarkdo** [comment]
@manniL Oh, one potential breaking change could be: User installed `core-js@2` manually but doesn't configured `corejs: 2`.

@nuxt/core-team What you think if we put notification in release note and doc, then release it as a feature in next minor release ?

**Comment by galvez** [comment]
> @nuxt/core-team What you think if we put notification in release note and doc, then release it as a feature in next minor release ?

Sounds good to me. Must be done carefully or we'll have a slew of bug reports due to a bad `package-lock.json`.

**Comment by manniL** [comment]
We should definitely give it a try but we have to assess the changes properly to avoid another bunch of core-js issues. IRC some projects, e.g. vue-cli, bumped the core-js version up to 3 in a major release.

**Comment by pi0** [comment]
Indeed we need to be careful about bumping to 3. Le'ts hold this on until next team meeting.

**Comment by clarkdo** [comment]
@pi0 @manniL I've added a core-js version checking, so I think it should be OK to migrate to v3 in next minor release as core-js@2 has been deprecated officially.

**Comment by garrensweet** [comment]
bump

**Comment by clarkdo** [comment]
> @pi0 @manniL I've added a core-js version checking, so I think it should be OK to migrate to v3 in next minor release as core-js@2 has been deprecated officially.

@pi0 Can you please have a look at latest change ?

**Comment by clarkdo** [comment]
cc @pi0

**Review by pi0 — APPROVED** [review]

**Pull request merged**
