### PR TITLE
feat(nuxt,schema): support v4 folder structure

### LINKED ISSUE #26444: Improved Directory Structure
### Discussed in https://github.com/nuxt/nuxt/discussions/20251

<div type='discussions-op-text'>

<sup>Originally posted by **Atinux** April 13, 2023</sup>
Nuxt 3 is now a fullstack framework thanks to [Nitro](https://nitro.unjs.io) with the ability to have [auto-imported modules](https://nuxt.com/docs/guide/directory-structure/modules) and [layers](https://nuxt.com/docs/getting-started/layers), I believe it's time to rethink the directory structure to give more separation for the "app" level.

This is the proposal I am thinking of:

```bash
.output/
.nuxt/
app/
  assets/
  components/
  composables/
  layouts/
  middleware/
  pages/
  plugins/
  utils/
  main.vue
  router.options.ts
content/
layers/
modules/
node_modules/
public/
server/
  api/
  middleware/
  plugins/
  routes/
  utils/
nuxt.config.ts
```

Do you see any downside of this approach?

The minimal starter would then be:

```bash
app/
  main.vue
public/
  favicon.ico
nuxt.config.ts
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/26444

### 📚 Description

This implements the new folder structure, if `future.compatibilityVersion` is set to `4` (which will be enabled by default when Nuxt v4 is released) - see https://github.com/nuxt/nuxt/pull/26925.

The main points (all only relevant when v4 compatibility is enabled):

* the new Nuxt default `srcDir` is `app/` by default, and most things are resolved from there.
* `serverDir` now defaults to ` <rootDir>/server` rather than `<srcDir>/server`
* `modules` and `public` are resolved relative to `<rootDir>` by default. If you want to revert this, set `dir.modules` to `'src/modules'` and `dir.public` to `'src/public'`.
* a new `dir.app` is added, which is the directory we look for `router.options.ts` and `spa-loading-template.html` - this defaults to `<srcDir>/` (under v4) and `<srcDir>/app` in v3 mode
* I have not changed `app.vue` to `main.vue` (as in the RFC) to avoid additional breaking changes
* in v4 mode, if there is no `app/` directory, we default to previous behaviour (and restart if the `app/` directory is added)

🚨 **Implementation details might change before the release of v4.** 🚨

<details>

<summary>The v4 folder structure.</summary>

```
.output/
.nuxt/
app/
  assets/
  components/
  composables/
  layouts/
  middleware/
  pages/
  plugins/
  utils/
  app.vue
  router.options.ts
modules/
node_modules/
public/
server/
  api/
  middleware/
  plugins/
  routes/
  utils/
nuxt.config.ts
```

</details>

### CODE REVIEW

**Comment by Celibioux** [comment]
What about the .config/ folder please ?

**Comment by danielroe** [comment]
@Celibioux That is already supported.

**Comment by Celibioux** [comment]
@danielroe thank you for your answer ! I was asking about the conf folder because i've noticed that is Not mentioned in the V4 folder structure ☺️

**Comment by JCtapuk** [comment]
> ### 🔗 Linked issue
> resolves #26444
> 
> ### 📚 Description
> This implements the new folder structure, if `future.compatibilityVersion` is set to `4` (which will be enabled by default when Nuxt v4 is released) - see #26925.
> 
> The main points (all only relevant when v4 compatibility is enabled):
> 
> * the new Nuxt default `srcDir` is `app/` by default, and most things are resolved from there.
> * `serverDir` now defaults to ` <rootDir>/server` rather than `<srcDir>/server`
> * `modules` and `public` are resolved relative to `<rootDir>` by default. If you want to revert this, set `dir.modules` to `'src/modules'` and `dir.public` to `'src/public'`.
> * a new `dir.app` is added, which is the directory we look for `router.options.ts` and `spa-loading-template.html` - this defaults to `<srcDir>/` (under v4) and `<srcDir>/app` in v3 mode
> * I have not changed `app.vue` to `main.vue` (as in the RFC) to avoid additional breaking changes
> * in v4 mode, if there is no `app/` directory, we default to previous behaviour (and restart if the `app/` directory is added)
> 
> The v4 folder structure.
> ```
> .output/
> .nuxt/
> app/
>   assets/
>   components/
>   composables/
>   layouts/
>   middleware/
>   pages/
>   plugins/
>   utils/
>   app.vue
>   router.options.ts
> modules/
> node_modules/
> public/
> server/
>   api/
>   middleware/
>   plugins/
>   routes/
>   utils/
> nuxt.config.ts
> ```

Since it duplicates the name app, it’s not nice, I suggest changing it to render since it renders the server and the client

**Comment by angelhdzmultimedia** [comment]
> > ### 🔗 Linked issue
> > resolves #26444
> > ### 📚 Description
> > This implements the new folder structure, if `future.compatibilityVersion` is set to `4` (which will be enabled by default when Nuxt v4 is released) - see #26925.
> > The main points (all only relevant when v4 compatibility is enabled):
> > 
> > * the new Nuxt default `srcDir` is `app/` by default, and most things are resolved from there.
> > * `serverDir` now defaults to ` <rootDir>/server` rather than `<srcDir>/server`
> > * `modules` and `public` are resolved relative to `<rootDir>` by default. If you want to revert this, set `dir.modules` to `'src/modules'` and `dir.public` to `'src/public'`.
> > * a new `dir.app` is added, which is the directory we look for `router.options.ts` and `spa-loading-template.html` - this defaults to `<srcDir>/` (under v4) and `<srcDir>/app` in v3 mode
> > * I have not changed `app.vue` to `main.vue` (as in the RFC) to avoid additional breaking changes
> > * in v4 mode, if there is no `app/` directory, we default to previous behaviour (and restart if the `app/` directory is added)
> > 
> > The v4 folder structure.
> > ```
> > .output/
> > .nuxt/
> > app/
> >   assets/
> >   components/
> >   composables/
> >   layouts/
> >   middleware/
> >   pages/
> >   plugins/
> >   utils/
> >   app.vue
> >   router.options.ts
> > modules/
> > node_modules/
> > public/
> > server/
> >   api/
> >   middleware/
> >   plugins/
> >   routes/
> >   utils/
> > nuxt.config.ts
> > ```
> 
> /app/app.vue -> /app/render.vue Since it duplicates the name app, it’s not nice, I suggest changing it to render since it renders the server and the client

app.vue is a Vue Component, not a render function, so it doesn't make sense renaming it to render.vue.
Even when using TSX or setupSFC (VueMacros), the file is/contains a component and then you have a function to render the template.

Now, your concern about duplication is correct, but that's a standard pattern in DDD, for example Angular and NestJS:

NestJS:
```
src/
  domains/
    user/
  features/
    auth/
      auth.controller.ts
      auth.service.ts
      auth.module.ts
   app/
     app.module.ts
     app.controller.ts
     app.service.ts
   main.ts
```

Angular:
```
src/
  domains/
    user/
  features/
    auth/
      auth.component.ts
      auth.service.ts
      auth.component.html
   app/
     app.component.ts
     app.component.html
     app.service.ts
   main.ts
```

When you open a file in VSCode, it shows only the name, not the base dir, so let's say I have `src/features/auth/module.ts` and open it, it will show `module.ts`. what module!? 🤔🔎

**Comment by angelhdzmultimedia** [comment]
> ### 🔗 Linked issue
> 
> resolves #26444
> ### 📚 Description
> 
> This implements the new folder structure, if `future.compatibilityVersion` is set to `4` (which will be enabled by default when Nuxt v4 is released) - see #26925.
> 
> The main points (all only relevant when v4 compatibility is enabled):
> 
>     * the new Nuxt default `srcDir` is `app/` by default, and most things are resolved from there.
> 
>     * `serverDir` now defaults to ` <rootDir>/server` rather than `<srcDir>/server`
> 
>     * `modules` and `public` are resolved relative to `<rootDir>` by default. If you want to revert this, set `dir.modules` to `'src/modules'` and `dir.public` to `'src/public'`.
> 
>     * a new `dir.app` is added, which is the directory we look for `router.options.ts` and `spa-loading-template.html` - this defaults to `<srcDir>/` (under v4) and `<srcDir>/app` in v3 mode
> 
>     * I have not changed `app.vue` to `main.vue` (as in the RFC) to avoid additional breaking changes
> 
>     * in v4 mode, if there is no `app/` directory, we default to previous behaviour (and restart if the `app/` directory is added)
> 
> 
> The v4 folder structure.

Congrats on the new structure! It's amazing! 🔥😁💚👋🤩
I know Nuxt team don't want us to be hyped for Nuxt 4... but I am. 😎
"That's my secret Cap, I'm always hyped for Nuxt!"

**Comment by Celibioux** [comment]
> > ### 🔗 Linked issue
> > resolves #26444
> > ### 📚 Description
> > This implements the new folder structure, if `future.compatibilityVersion` is set to `4` (which will be enabled by default when Nuxt v4 is released) - see #26925.
> > The main points (all only relevant when v4 compatibility is enabled):
> > 
> > * the new Nuxt default `srcDir` is `app/` by default, and most things are resolved from there.
> > * `serverDir` now defaults to ` <rootDir>/server` rather than `<srcDir>/server`
> > * `modules` and `public` are resolved relative to `<rootDir>` by default. If you want to revert this, set `dir.modules` to `'src/modules'` and `dir.public` to `'src/public'`.
> > * a new `dir.app` is added, which is the directory we look for `router.options.ts` and `spa-loading-template.html` - this defaults to `<srcDir>/` (under v4) and `<srcDir>/app` in v3 mode
> > * I have not changed `app.vue` to `main.vue` (as in the RFC) to avoid additional breaking changes
> > * in v4 mode, if there is no `app/` directory, we default to previous behaviour (and restart if the `app/` directory is added)
> > 
> > The v4 folder structure.
> > ```
> > .output/
> > .nuxt/
> > app/
> >   assets/
> >   components/
> >   composables/
> >   layouts/
> >   middleware/
> >   pages/
> >   plugins/
> >   utils/
> >   app.vue
> >   router.options.ts
> > modules/
> > node_modules/
> > public/
> > server/
> >   api/
> >   middleware/
> >   plugins/
> >   routes/
> >   utils/
> > nuxt.config.ts
> > ```
> 
> /app/app.vue -> /app/render.vue Since it duplicates the name app, it’s not nice, I suggest changing it to render since it renders the server and the client

App/main.vue would be good as in the RFC and what Daniel said ^^

**Comment by danielroe** [comment]
We'll go ahead and merge for testing. 🚨 Implementation details might change before the release of v4. 🚨

**Comment by bernhardberger** [comment]
Imho the auto-fallback should be removed and causes more confusion than it's worth..

Users can opt out of it anyways by just changing the config? At least that would be verbose and nobody would have to guess if it's actually using the new structure or falling back..

**Comment by danielroe** [comment]
@bernhardberger is there something not working, or inexplicable behaviour? if so, would you open a new issue with a reproduction?

**Comment by bernhardberger** [comment]
> @bernhardberger is there something not working, or inexplicable behaviour? if so, would you open a new issue with a reproduction?

Thing is: I have no clue if it's working.

See all my confusion, questions and answers by different guys pointing to contradicting YT "tutorials": https://github.com/nuxt/nuxt/discussions/20251#discussioncomment-10262761

I like the change, but it's (really) hard to gauge what goes where under which circumstances and what the implications of each are.

It's especially confusing what happens with modules, layers (why are layers not affected from the new structure?) as well as to what happens with other unmentioned directories in `rootDir`.

**Comment by JanHuyBE** [comment]
Where are the <stores>, <types> and <i18n> folders supposed to fit in the Nuxt4 directory structure? 
I suppose adjacent to <app>, <server> and <layers> so that the data can be used in other <layers>.

**Comment by JanHuyBE** [comment]
Where are the /stores/ (types/, and /i18n/ folders supposed to fit in the Nuxt4 directory structure?
I suppose adjacent to /app/ and /server/  and /layers/ so that the data can be used in other /layers/.

**Comment by beatlz-too** [comment]
With these changes, `~` is now pointing to `/app`. This means we don't have a direct way of having absolute paths in the `/server` folder out of the box. 

What's the recommended approach to have this? Since it's very comfortable to have them in project : )

**Comment by danielroe** [comment]
you shouldn't import from the server within your app/ folder

**Comment by beatlz-too** [comment]
Sorry, that's not what I meant, what I mean is if I'm working in a file with path `/server/services/myService.ts` and I want to import from `/server/utils/isEven.ts`, I can't do `import isEven from "~/server/utils/isEven`, because ~ and @ are now pointing to `/app`, 
which is frontend context.

And thanks for the super quick response!

EDIT:
After checking the tsconfig.server.json file, I saw that @ was pointing to root folder. I don't know why it wasn't working, but I deleted the /.nuxt folder, and after I rebuilt it was there. Thanks for the reply @danielroe 

image

image

**Comment by danielroe** [comment]
it should be ~~ and @@

**Comment by beatlz-too** [comment]
both @ and @@ seem to be pointing to root in tsconfig.server.json file

image

**Comment by OrbisK** [comment]
@beatlz-too 

what is your nuxt version?

image

**Comment by beatlz-too** [comment]
I'm at 4.0, fresh project I made just to test this

edit: I made a new fresh project and it's now showing the folder structure you're talking about 🤷 

image

image

image

image

@OrbisK

**Pull request merged**
