### PR TITLE
docs: update `.env` section

### LINKED ISSUE #22331: Cannot access environment variables in `useRuntimeConfig` using `source .env && node server.mjs`
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.1.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.6.6`
- Builder:          `vite`
- User Config:      `devtools`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Clone https://github.com/xuzuodong/nuxt-source-test 
2. run `pnpm i`
3. run `pnpm dev`, open `localhost:3000`, and then console will print runtime config object, including environment variable `testEnv`, which is accessible:
```js
{
  app: { baseURL: '/', buildAssetsDir: '/_nuxt/', cdnURL: '' },
  nitro: { envPrefix: 'NUXT_', routeRules: { '/__nuxt_error': [Object] } },
  public: {},
  testEnv: '12345678asdf'
}
```
4. quit the dev process and run `pnpm build`, then `pnpm start`
5. open `localhost:3000`, and then console will print runtime config, and value of environment variable `testEnv` is missing:
```js
{
  app: { baseURL: '/', buildAssetsDir: '/_nuxt/', cdnURL: '' },
  nitro: {
    envPrefix: 'NUXT_',
    routeRules: { '/__nuxt_error': [Object], '/_nuxt/**': [Object] }
  },
  public: {},
  testEnv: ''
}
```

### Describe the bug

According to [the doc](https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables), runtime config values are automatically replaced by matching environment variables at runtime. This works in development mode, but different behavior happens when I build and run the output with `.env` file sourced. 

According to [the env doc](https://nuxt.com/docs/guide/directory-structure/env), after server is built, environment variables should be set before server running, one recommended way is to source env file using `source .env && node .output/server/index.mjs`. 

However, such script cannot successfully inject environment variables declared in `.env`. 

Is there something I missed?

### Additional context

A temporary workaround I'm using now is manually assign environment variables to runtimeConfig in `nuxt.config.ts`: 

```
  runtimeConfig: {
    testEnv: process.env.NUXT_TEST_ENV
  }
```

### Logs

_No response_

### PR DESCRIPTION
**Pull request by xuzuodong**
### 🔗 Linked issue

resolves #22331

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Also improved readability a little bit.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]
Thanks! LGTM. Two things could be improved:

- Title: Maybe something like Production Preview?
- Dotenv: We need to specify this dependency needs to be installed as well

**Comment by danielroe** [comment]
This is great - thank you! ❤️ 

I wouldn't recommend using `node -r dotenv/config` for production as it requires dependencies to be installed in the package directory. But `.output/` is intended to be the only build output required. (And if you have dependencies installed you might as well run `nuxi preview`.)

**Comment by xuzuodong** [comment]
I think `nuxi preview` should be the recommended way, now is it better?

**Review by danielroe — APPROVED** [review]
Perfect 👌 

Thank you.

**Pull request merged**
