### PR TITLE
fix(vue-app): always import error layout, either internal or custom

### LINKED ISSUE #8066: NuxtJs: ReferenceError: NuxtError is not defined
I am learning nuxt and my fresh project is generated with the `2.14.5` nuxt version. I wanted to test how nuxt-link works so I intentionally put a nuxt-link to a route that doesn't work hoping to get redirected to the default 404 page. I put this line the `pages/index.vue` file:

`<nuxt-link to='/asksdkjd'>ssss</nuxt-link>`

And it displays in chrome like [this:](https://i.stack.imgur.com/U5aPI.png)

After I click the link I get these error in console:

`ReferenceError: NuxtError is not defined
at Vue.errorChanged (App.js?efe7:173)
at Watcher.run (vue.runtime.esm.js?2b0e:4568)
at flushSchedulerQueue (vue.runtime.esm.js?2b0e:4310)
at Array.eval (vue.runtime.esm.js?2b0e:1980)
at flushCallbacks (vue.runtime.esm.js?2b0e:1906)

vue.runtime.esm.js?2b0e:619 [Vue warn]: You may have an infinite update loop in watcher with expression "nuxt.err"
(found in <Root>)`

Here's the [error screenshot](https://i.stack.imgur.com/dNjp9.png) This error shows when I am redirected to the link because you can see the invalid link in the url bar. It doesn't render the default 404 page. But When I hit refresh, I can then see the 404 page( [screenshot](https://i.stack.imgur.com/B2p4K.png) ).

Here's my `nuxt.config.js` file which was generated when I installed this fresh project.(I ommited the comments.)

<pre>
export default {
  mode: 'universal',
  target: 'static',
  head: {
    title: process.env.npm_package_name || '',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: process.env.npm_package_description || '' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  css: [
  ],
  plugins: [
  ],
  components: true,
  buildModules: [
  ],
  modules: [
  ],
  build: {
  }
}
</pre>

I have been googling for this error for quite a while but couldn't find anything. I also tried in firefox but the same issue is happening. Hope you guys can help. Thanks in advance.

### PR DESCRIPTION
**Pull request by danielroe**
closes #8066

## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

The client template needs access to NuxtError and we can follow the pattern of App.js - thanks https://github.com/nuxt/nuxt.js/issues/8066#issuecomment-691556167 for a helpful diagnosis of the issue.

For reference:
* https://github.com/nuxt/nuxt.js/pull/6479 (original source of NuxtError import)
* https://github.com/nuxt/nuxt.js/pull/8016 (PR introducing regression that this fixes)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Review by msonowal — APPROVED** [review]

**Review by msonowal — APPROVED** [review]

**Review by clarkdo — APPROVED** [review]

**Review by pi0 — APPROVED** [review]
Thanks!

**Comment by aeadedoyin** [comment]
Hi @pi0  When will this be released? Asper 2.14.6

**Comment by Kolobok12309** [comment]
@danielroe, Thanks for fix this bug, my fail

**Comment by danielroe** [comment]
@Kolobok12309 Not at all! It was a good PR and we just didn't spot the issue...

**Pull request merged**
