### PR TITLE
fix(nuxt): await async payload revivers

### PR DESCRIPTION
**Pull request by cernymatej**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR resolves an issue where the payload reviver was not awaited if it was an asynchronous function. This could be useful for creating more versatile payload revivers (utilizing dynamic imports), for example. However, prior to this change, the revived value on the client would be a promise instead of its resolved value.

It would probably also be a good idea to add tests for this issue. However, I noticed that `definePayloadReducer` and `definePayloadReviver` are listed in `skippedComposables` in the tests. Is there a reason why they are not tested?

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]

**Comment by manniL** [comment]
@CernyMatej There are tests in place though, see https://github.com/nuxt/nuxt/blob/629461b7f768c17fa2b5815723a9d17e305b0b99/test/fixtures/basic/plugins/custom-type-registration.ts#L3-L4 and https://github.com/nuxt/nuxt/blob/629461b7f768c17fa2b5815723a9d17e305b0b99/test/fixtures/basic/plugins/custom-type-assertion.client.ts#L1-L2

**Review by TheAlexLichter — APPROVED** [review]

**Comment by CernyMatej** [comment]
@manniL thanks for pointing that out! Didn't notice them. However, those are only fixtures. Where are they used in tests? I'd be happy to write a test case for it if you could tell me where to put it.

**Comment by manniL** [comment]
@CernyMatej That's it! the first link shows where it is set up and the 2nd link shows where it is checked in the fixture, throwing an error and failing tests when the reviving would fail ☺️
Maybe it'd be already enough to make that case async though 🤔

**Comment by CernyMatej** [comment]
I noticed that I had made changes to the `devalue` source code to support asynchronous revivers before making the changes in Nuxt and forgot about them. 🤦‍♂️ 

At the moment, `parse()` from `devalue` isn't asynchronous and [doesn't actually await](https://github.com/Rich-Harris/devalue/blob/50af63e2b2c648f6e6ea29904a14faac25a581fc/src/parse.js#L60) the reviver which causes the revived value to stay as a fulfilled promise. I'm wondering what would be the best solution for this... 🤔

Changing `parse()` to be asynchronous would be a breaking change, wouldn't it? I'm thinking maybe include the parsing code in Nuxt and change it to be asynchronous - so that other users of devalue are not affected by this change?

**Comment by manniL** [comment]
@CernyMatej I think it would unless introducing a parseAsync function 😋

**Pull request merged**
