### PR TITLE
chore(release): v2.4.4

### PR DESCRIPTION
**Pull request by pi0**
[v2.4.4](https://github.com/nuxt/nuxt.js/compare/v2.4.3...v2.4.4) (2019-02-25)

### Bug Fixes and Improvements

* **builder:** bundle resources other than js(x)/json in node_modules ([#4913](https://github.com/nuxt/nuxt.js/issues/4913)) ([71a70fe](https://github.com/nuxt/nuxt.js/commit/71a70fe))
* **cli:** dont force exit when it was explicitly disabled ([#4973](https://github.com/nuxt/nuxt.js/issues/4973)) ([4b82aa9](https://github.com/nuxt/nuxt.js/commit/4b82aa9))
* **cli:** show warning on forced exit ([#4958](https://github.com/nuxt/nuxt.js/issues/4958)) ([3d2deac](https://github.com/nuxt/nuxt.js/commit/3d2deac))
* **dependencies:** update serve-placeholder and esm ([#4970](https://github.com/nuxt/nuxt.js/issues/4970)) ([111455f](https://github.com/nuxt/nuxt.js/commit/111455f))
* **vue-renderer:** preload modern resource in spa modern mode ([#5043](https://github.com/nuxt/nuxt.js/issues/5043)) ([3516580](https://github.com/nuxt/nuxt.js/commit/3516580))
* **vue-app:** fix `asyncData` memory leak on client-side ([#4966](https://github.com/nuxt/nuxt.js/issues/4966)) ([4086800](https://github.com/nuxt/nuxt.js/commit/4086800))
* **vue-app:** fix `getNuxtChildComponents` method ([#4969](https://github.com/nuxt/nuxt.js/issues/4969)) ([dbf7099](https://github.com/nuxt/nuxt.js/commit/dbf7099))

### CODE REVIEW

**Comment by manniL** [comment]
Tests are broken (a space too much for the asserts) see

**Comment by pi0** [comment]
Dependencies status:

```tsv
Package                                 Current      Wanted       Latest       Workspace              Package Type    URL                                                                                       
@babel/core                             7.2.2        7.3.4        7.3.4        nuxt.js                devDependencies https://babeljs.io/                                                                       
@babel/core                             7.2.2        7.3.4        7.3.4        @nuxt/babel-preset-app dependencies    https://babeljs.io/                                                                       
@babel/core                             7.2.2        7.3.4        7.3.4        @nuxt/webpack          dependencies    https://babeljs.io/                                                                       
@babel/core                             7.2.2        7.3.4        7.3.4        nuxt-legacy            dependencies    https://babeljs.io/                                                                       
@babel/plugin-proposal-class-properties 7.3.0        7.3.4        7.3.4        @nuxt/babel-preset-app dependencies    https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-class-properties
@babel/plugin-transform-runtime         7.2.0        7.3.4        7.3.4        @nuxt/babel-preset-app dependencies    https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-runtime        
@babel/preset-env                       7.3.1        7.3.4        7.3.4        nuxt.js                devDependencies https://babeljs.io/                                                                       
@babel/preset-env                       7.3.1        7.3.4        7.3.4        @nuxt/babel-preset-app dependencies    https://babeljs.io/                                                                       
@babel/preset-env                       7.3.1        7.3.4        7.3.4        nuxt-legacy            dependencies    https://babeljs.io/                                                                       
@babel/runtime                          7.3.1        7.3.4        7.3.4        @nuxt/babel-preset-app dependencies    https://github.com/babel/babel/tree/master/packages/babel-runtime                         
@types/node                             10.12.18     10.12.27     11.9.5       @nuxt/typescript       dependencies    https://github.com/DefinitelyTyped/DefinitelyTyped.git                                    
babel-jest                              23.6.0       23.6.0       24.1.0       nuxt.js                devDependencies https://github.com/facebook/jest#readme                                                   
boxen                                   2.1.0        2.1.0        3.0.0        @nuxt/cli              dependencies    https://github.com/sindresorhus/boxen#readme                                              
caniuse-lite                            1.0.30000932 1.0.30000939 1.0.30000939 @nuxt/webpack          dependencies    https://github.com/ben-eb/caniuse-lite#readme                                             
chokidar                                2.0.4        2.1.2        2.1.2        @nuxt/builder          dependencies    https://github.com/paulmillr/chokidar                                                     
codecov                                 3.1.0        3.2.0        3.2.0        nuxt.js                devDependencies https://github.com/codecov/codecov-node                                                   
consola                                 2.3.2        2.5.6        2.5.6        nuxt.js                devDependencies https://github.com/nuxt/consola#readme                                                    
consola                                 2.3.2        2.5.6        2.5.6        @nuxt/builder          dependencies    https://github.com/nuxt/consola#readme                                                    
consola                                 2.3.2        2.5.6        2.5.6        @nuxt/cli              dependencies    https://github.com/nuxt/consola#readme                                                    
consola                                 2.3.2        2.5.6        2.5.6        @nuxt/config           dependencies    https://github.com/nuxt/consola#readme                                                    
consola                                 2.3.2        2.5.6        2.5.6        @nuxt/core             dependencies    https://github.com/nuxt/consola#readme                                                    
consola                                 2.3.2        2.5.6        2.5.6        @nuxt/generator        dependencies    https://github.com/nuxt/consola#readme                                                    
consola                                 2.3.2        2.5.6        2.5.6        @nuxt/server           dependencies    https://github.com/nuxt/consola#readme                                                    
consola                                 2.3.2        2.5.6        2.5.6        @nuxt/typescript       dependencies    https://github.com/nuxt/consola#readme                                                    
consola                                 2.3.2        2.5.6        2.5.6        @nuxt/utils            dependencies    https://github.com/nuxt/consola#readme                                                    
consola                                 2.3.2        2.5.6        2.5.6        @nuxt/vue-renderer     dependencies    https://github.com/nuxt/consola#readme                                                    
consola                                 2.3.2        2.5.6        2.5.6        @nuxt/webpack          dependencies    https://github.com/nuxt/consola#readme                                                    
cssnano                                 4.1.8        4.1.10       4.1.10       @nuxt/webpack          dependencies    https://github.com/cssnano/cssnano                                                        
eslint                                  5.12.1       5.14.1       5.14.1       nuxt.js                devDependencies https://eslint.org                                                                        
eslint-plugin-import                    2.15.0       2.16.0       2.16.0       nuxt.js                devDependencies https://github.com/benmosher/eslint-plugin-import                                         
eslint-plugin-jest                      22.1.3       22.3.0       22.3.0       nuxt.js                devDependencies https://github.com/jest-community/eslint-plugin-jest#readme                               
eslint-plugin-vue                       5.1.0        5.2.2        5.2.2        nuxt.js                devDependencies https://eslint.vuejs.org                                                                  
esm                                     3.2.3        3.2.6        3.2.6        nuxt.js                devDependencies https://github.com/standard-things/esm#readme                                             
esm                                     3.2.3        3.2.6        3.2.6        @nuxt/cli              dependencies    https://github.com/standard-things/esm#readme                                             
esm                                     3.2.3        3.2.6        3.2.6        @nuxt/core             dependencies    https://github.com/standard-things/esm#readme                                             
jest                                    23.6.0       23.6.0       24.1.0       nuxt.js                devDependencies https://jestjs.io/                                                                        
jest-junit                              6.1.0        6.3.0        6.3.0        nuxt.js                devDependencies https://github.com/jest-community/jest-junit#readme                                       
lerna                                   3.10.8       3.10.8       3.13.0       nuxt.js                devDependencies https://lernajs.io/                                                                       
on-headers                              1.0.1        1.0.2        1.0.2        @nuxt/server           dependencies    https://github.com/jshttp/on-headers#readme                                               
puppeteer                               1.11.0       1.12.2       1.12.2       nuxt.js                devDependencies https://github.com/GoogleChrome/puppeteer#readme                                          
request-promise-native                  1.0.5        1.0.7        1.0.7        nuxt.js                devDependencies https://github.com/request/request-promise-native#readme                                  
rollup                                  1.1.2        1.2.3        1.2.3        nuxt.js                devDependencies https://github.com/rollup/rollup                                                          
rollup-plugin-commonjs                  9.2.0        9.2.1        9.2.1        nuxt.js                devDependencies https://github.com/rollup/rollup-plugin-commonjs                                          
rollup-plugin-node-resolve              4.0.0        4.0.1        4.0.1        nuxt.js                devDependencies https://github.com/rollup/rollup-plugin-node-resolve#readme                               
sort-package-json                       1.18.0       1.19.0       1.19.0       nuxt.js                devDependencies https://github.com/keithamus/sort-package-json#readme                                     
terser-webpack-plugin                   1.2.2        1.2.3        1.2.3        @nuxt/webpack          dependencies    https://github.com/webpack-contrib/terser-webpack-plugin                                  
thread-loader                           1.2.0        1.2.0        2.1.2        @nuxt/webpack          dependencies    https://github.com/webpack-contrib/thread-loader                                          
ts-jest                                 23.10.5      23.10.5      24.0.0       nuxt.js                devDependencies https://kulshekhar.github.io/ts-jest                                                      
tslint                                  5.12.1       5.13.0       5.13.0       nuxt.js                devDependencies https://palantir.github.io/tslint                                                         
tslint                                  5.12.1       5.13.0       5.13.0       @nuxt/typescript       dependencies    https://palantir.github.io/tslint                                                         
typescript                              3.2.4        3.3.3333     3.3.3333     nuxt.js                devDependencies https://www.typescriptlang.org/                                                           
typescript                              3.2.4        3.3.3333     3.3.3333     @nuxt/typescript       dependencies    https://www.typescriptlang.org/                                                           
vue                                     2.5.22       2.6.7        2.6.7        @nuxt/vue-app          dependencies    https://github.com/vuejs/vue#readme                                                       
vue                                     2.5.22       2.6.7        2.6.7        @nuxt/vue-renderer     dependencies    https://github.com/vuejs/vue#readme                                                       
vue                                     2.5.22       2.6.7        2.6.7        nuxt-start             dependencies    https://github.com/vuejs/vue#readme                                                       
vue-jest                                3.0.2        3.0.3        3.0.3        nuxt.js                devDependencies https://github.com/eddyerburgh/vue-jest#readme                                            
vue-loader                              15.6.2       15.6.4       15.6.4       @nuxt/webpack          dependencies    https://github.com/vuejs/vue-loader                                                       
vue-server-renderer                     2.5.22       2.6.7        2.6.7        @nuxt/vue-renderer     dependencies    https://github.com/vuejs/vue/tree/dev/packages/vue-server-renderer#readme                 
vue-template-compiler                   2.5.22       2.6.7        2.6.7        @nuxt/vue-app          dependencies    https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler#readme               
webpack                                 4.29.2       4.29.5       4.29.5       @nuxt/webpack          dependencies    https://github.com/webpack/webpack                                                        
webpack-bundle-analyzer                 3.0.3        3.0.4        3.0.4        @nuxt/webpack          dependencies    https://github.com/webpack-contrib/webpack-bundle-analyzer                                
webpack-dev-middleware                  3.5.1        3.6.0        3.6.0        @nuxt/webpack          dependencies    https://github.com/webpack/webpack-dev-middleware                                         
```

**Review by galvez — APPROVED** [review]

**Comment by galvez** [comment]
I've been using edge for some time now with no issues. Other than test error LGTM!

**Comment by pi0** [comment]
@galvez this is 2.x

**Review by aldarund — APPROVED** [review]

**Comment by pi0** [comment]
Autdit fail is safe (dependency of jest)

https://nodesecurity.io/advisories/786

E2E is failing because of a CI problem. Would try to backport that stuff to this patch

**Comment by manniL** [comment]
Please include:

* https://github.com/nuxt/nuxt.js/pull/5080
* https://github.com/nuxt/nuxt.js/pull/5104
* https://github.com/nuxt/nuxt.js/pull/5086

**Comment by kevinmarrec** [comment]
@pi0 PRs to be merged & included (IMO) :
https://github.com/nuxt/nuxt.js/pull/5086/files
https://github.com/nuxt/nuxt.js/pull/5104

**Pull request closed without merging**
