### PR TITLE
Support for .coffee files for store, middlewares and pretty much anywhere

### PR DESCRIPTION
**Pull request by alexananiev**
Currently, Nuxt recognizes only .js and .ts files so there is no way to use .coffee files for a store for example. Now you can use .coffee files for store and middlewares. Also, you can import/require coffee files without specifying the extension, same as for .js and .ts.

### CODE REVIEW

**Comment by pi0** [comment]
Hi, @alexananiev and thanks for your help. Would you please also include a basic example of `with-coffie` in examples dir?

**Comment by alexananiev** [comment]
Sure @pi0! Just added an example.

**Comment by qm3ster** [comment]
@pi0, **both** AppVeyor builds and the node v8 Travis build are wrongly marked as passed, they all failed the `spa › / (custom layout)` test.

In other news, this is the same test that fails on head of dev branch, so this doesn't break anything.

However, may I suggest making this a nuxt module instead?
A new api should be exposed, patterned after this commit, and used to excise both this and TypeScript support into modules.
This reduces nuxt dependencies, and separates concerns.

Similarly, css preprocessors should not be in core.

Finally, there are currently [mentions of `.ts` and `.jsx` inside the rollup config](https://github.com/nuxt/nuxt.js/blob/d5691f75e7e9d86c709f18bd8e131ca5598585b0/build/rollup.config.js#L68)  to build nuxt, although there aren't the necessary compilers, and nuxt source doesn't use any `.jsx` or `.ts` files.

I would like your feedback on the rationality of this, and whether there is any similar in progress work that would conflict with this, to see if I should start working on a PR.

Core modules should probably be in a monorepo, but in any case compatibility should be automatically tested whenever the module or core updates.

Lastly, I see this example doesn't have tests.
Wouldn't making every example a loose integration test be very useful for keeping the examples fresh?

**Comment by Atinux** [comment]
Thank you @alexananiev for your PR and @qm3ster for your review.

I agree with @qm3ster, we should keep Nuxt core to the minimal and use modules to add features.

We should expose a list of available file extensions that can be extended by module when Nuxt is looking for middleware/store/... files.

I keep this PR open until we develop a way of using custom files extension with nuxt modules.

**Comment by alexananiev** [comment]
I think it’s better to merge it now and iterate on this later because:
- The typescript support implemented in a similar way currently
- …and nuxt.js already understand .ts files, but not .coffee files
- The changes are minor, but without them, CoffeeScript users missing out on a lot of important features
- Extracting js and css preprocessors from the core is definitely the right way, but it might take some time, so it will delay CoffeeScript support.
- And why the delay if we can add coffee to the rest of preprocessors now and refactor them all together later?

Make sense? @Atinux @qm3ster

**Comment by qm3ster** [comment]
Yeah, I am definitely for merging this.
Sorry if I wasn't clear about that.
It's easy to pull this out after.

**Comment by Atinux** [comment]
[Handle files extensions via modules](https://trello.com/c/COrQa1Fh/9-handle-files-extensions-via-modules)

**Pull request merged**
