### PR TITLE
fix(nuxt): validate

### PR DESCRIPTION
**Pull request by noriyuki-shimizu**
### 🔗 Linked issue

https://github.com/nuxt/nuxt/issues/18567

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

In the vue file of pages, this change is made so that the validate of `definePageMeta` will function properly.

The current problems are considered to be the following three points.

* When the validate limit is violated, the transition from `NuxtLink` to the 404 screen is not possible.
* If the validate of `definePageMeta` is defined in the vue file of pages, the global middleware and the middleware of `definePageMeta` do not work.
* The existing `packages/nuxt/src/pages/runtime/validate.ts` process returned false if the validate limit was violated in the middleware, which caused the screen transition to fail.

This is a solution to the above problems.

https://github.com/nuxt/nuxt/issues/18567

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.
  - Currently, it was not working as described in the documentation, so this modification is to make it work as described in the documentation. Therefore, no checks have been made.

### CODE REVIEW

**Review by danielroe — CHANGES_REQUESTED** [review]
Thank you for spending time on this PR.

At the moment this will always show an error page if `validate` returns false. But if you have multiple pages matching a route, then this will wrongly show an error page even when there is a valid route:

```
pages/[product].vue // we have a validate function here to check
pages/[...slug].vue
```

In this case, if `[product].vue` returns false, we will never move on to `[...slug].vue`, which would be the correct behaviour.

I believe everything is working correctly at the moment, except for the issue of client-side navigation to an invalid route where no other routes match, as [my comment here](https://github.com/nuxt/nuxt/issues/18567#issuecomment-1415815122) states (note that we did ship a fix in 3.1.0 (https://github.com/nuxt/framework/pull/9180). (If not, it would be very helpful if you would comment in that issue with an example of what isn't working.)

Would you like to update this PR with a different method, for example by using a router lifecycle hook or maybe updating the plugin where we run middleware instead?

**Comment by noriyuki-shimizu** [comment]
Thanks for your comment!

I did not have a good grasp of what the issue was about.
Sorry about that.
I will organize the content and comment again on the following issue!

https://github.com/nuxt/nuxt/issues/18567

**Comment by danielroe** [comment]
@noriyuki-shimizu Fantastic! I have put together a possible solution at https://github.com/nuxt/nuxt/pull/18978 and would value your feedback. If you think it still needs more work, perhaps we could do a joint PR, or you could make a PR to my branch?

**Comment by noriyuki-shimizu** [comment]
@danielroe 
Thank you for responding!
I just checked the operation with the specified PR and this issue was cured!
Therefore, we have no additional requests, etc.
Thanks for the quick fix!

Having confirmed that this issue has been fixed, I am closing this PR!

**Pull request closed without merging**
