### PR TITLE
feat: set html attr `dir` to ltr by default

### PR DESCRIPTION
**Pull request by TheAlexLichter**
## Types of changes
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

Related: https://github.com/nuxt/nuxt.js/issues/4555

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by pi0 — CHANGES_REQUESTED** [review]
I really disagree with changing default browser behavior by implicitly adding top level dir prop. If it is a tooling problem with postcss/autoprefixer, we should document it.

Also this is a breaking change for RTL projects.

**Comment by manniL** [comment]
> I really disagree with changing default browser behavior by implicitly adding top level dir prop. If it is a tooling problem with postcss/autoprefixer, we should document it.

Agree to . Where should we document that? (As it's a very niche problem and probably should be in the postcss docs)

image

> Also this is a breaking change for RTL projects.

That might be true (if they did not set the `dir` attribute own their own), right.

**Comment by Atinux** [comment]
This is why I love having a core team from all part of the globe <3

I like the idea of helping the user setting the reading direction but I don't think the default should be set to `ltr`.

I think documentation is the key to it. And **if it's linked to multiple entries**, html attrs, postcss, why not giving an alias for it and updating the tools to respect it?

**Comment by manniL** [comment]
rel: https://github.com/nuxt/docs/issues/1108

**Pull request closed without merging**
