### PR TITLE
vue-18n integration

### PR DESCRIPTION
**Pull request by rpisarew**
A good support for i18n is essential.
[vue-i18n](https://github.com/kazupon/vue-i18n) in version 6.0.0 works well with ssr and I think it is mutch better than the example that you currently provide.

#107 #234 #236 #502 #525

### CODE REVIEW

**Comment by LowM4N** [comment]
Now you can pass the vue-i18n options through the nuxt.config.js, e.g:

```
// nuxt.config.js
module.exports = {
  ...
  i18n: {
    locale: 'de',
    fallbackLocale: 'en',
    messages: {
      de: {
        hello: 'Hallo'
      },
      en: {
        hello: 'Hello'
      }
    }
  },
  ...
}
```

**Comment by Atinux** [comment]
Hi @LowM4N 

This is great, but can you test if the [Custom Formatting](http://kazupon.github.io/vue-i18n/en/formatting.html) will works as well?

**Comment by LowM4N** [comment]
I tested now all the formatting options in vue-i18n, but the CustomFormatter dont work, because the JSON.stringify function ignore the formatter property reference.

```
// nuxt.config.js

// Custom Formatter implementaion
class CustomFormatter {
  constructor (options) {
    // ...
  }

  format (message, ...values) {
    // implement formatting logic here
    // ...

    // return the resolved message string
    return 'resolved message string'
  }
}

module.exports = {
  ...
  i18n: {
    locale: 'de',
    fallbackLocale: 'en',
    formatter: new CustomFormatter()
  },
  ...
}
```

This lines will generate...
```
// lib/app/index.js
...
Vue.use(I18N)
const i18n = new I18N(<%= JSON.stringify(i18n) %>)
...
```

This, and since JSON cant store references, I need to find a other solution for the configuration parameters.
```
...
Vue.use(I18N)
const i18n = new I18N({"locale":"de","fallbackLocale":"en","formatter":{}})
...
```

Maybe you have an idea?  If not, i will look how you does it with the scrollBehavior in the router. It's likekly the same case with the custom function parameter.

**Comment by LowM4N** [comment]
@Atinux Update, the custom formatter works well on all child components if you assign it in the component like that:

```
...
<template>
  <section class="container">
    <div>
      <logo/>
      <h1 class="title">
        NUXT
      </h1>
      <h2 class="subtitle">
        Universal Vue.js Application
        <div v-html="$t('hello', {name: 'Nuxt'})"></div>
      </h2>
      <div class="links">
        <a href="https://nuxtjs.org/" target="_blank" class="button--green">Documentation</a>
        <a href="https://github.com/nuxt/nuxt.js" target="_blank" class="button--grey">Github</a>
      </div>
    </div>
  </section>
</template>

<script>
import Logo from '~components/Logo.vue'

class CustomFormatter {
  format (message, ...args) {
    // implement formatting logic here
    // ...

    if (args.length > 0) {
      for (let arg in args[0]) {
        message = message.replace(`{${arg}}`, args[0][arg])
      }
    }

    return message.toUpperCase()
  }
}

export default {
  components: {
    Logo
  },
  i18n: {
    messages: {
      de: {
        hello: 'Hallo <strong>{name}!</strong>'
      },
      en: {
        hello: 'Hello <strong>{name}!</strong>'
      }
    },
    formatter: new CustomFormatter()
  }
}
</script>
...
```

the only last issue is, that i cant set the formatter to root vue instance.

I tried to separate the custom formatter to a plugin file, read it in to string and copy the code when the application was generated to index.js, but this feels realy hacky for me, with this solution you cant use external dependencies - all logic must be stay in this one file.

**Comment by Atinux** [comment]
@LowM4N I think I found an elegant solution to be generic as well, I will add an option `injectAs` in the https://nuxtjs.org/api/configuration-plugins keys.

So it will be something like this:
`nuxt.config.js`
```js
module.exports = {
  plugins: [
    { src: '~plugins/i18n.js', injectAs: 'i18n' }
  ]
}
```

`plugins/i18n.js`
```js
import Vue from 'vue'
import VueI18n from 'vue-i18n'

Vue.use(VueI18n)

const i18n = new I18N({
  // options
})

export default i18n
```

**Comment by LowM4N** [comment]
@Atinux Nice solution! Thank you.
I tested it, work well on my setup. I think you can close the pr.
But only one thing, you commited a unresolved merge conflict on your current master in the package.json .

**Comment by Atinux** [comment]
It's fixed, thank you @LowM4N for your idea, it helped me to imagine the injectAs feature :)

I will also try to make it inject in the context too so it will be accessible in the context as well.

**Comment by dohomi** [comment]
@Atinux is the `injectAs` feature maybe suitable for the `vue-apollo` issue as well? https://github.com/nuxt/nuxt.js/issues/504

**Comment by Atinux** [comment]
Yes @dohomi

**Pull request closed without merging**
