### PR TITLE
chore(pkg): build for es2019 target

### LINKED ISSUE #9321: [edge] Nullish operator available with node 14 only
I think issue is related with that change: 
https://github.com/nuxt/nuxt.js/commit/186df335d926b56f8eec5249d6330363622390b3#diff-cba57dce8689b0b15bac4cd779357605a9c6ce76da7d424eedf8c4eb385b75d8R92 

I think it should be transpilled, but is not, because I get an error:

```bash
/Users/merc/Projects/OpenSource/mymodule/node_modules/@nuxt/config-edge/dist/config.js:1119
  const dev = configOverrides.dev ?? options.dev ?? configContext.dev;
                                   ^

SyntaxError: Unexpected token '?'
```

Or should we use node 14 ? But I don't think so it is required at the moment. 

### Versions

- nuxt: edge 
- node: 12.20 

### Reproduction

just run nuxt-edge on node 12.20

### PR DESCRIPTION
**Pull request by pi0**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Use `esbuild` with `taget: es2019` (using `node*` transform to CJS which breaks rollup chunks!) to build dist files. Fixes #9321 Closes #9322

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by clarkdo — DISMISSED** [review]

**Comment by clarkdo** [comment]
Nice change

**Comment by clarkdo** [comment]
OOC, what will be broken when using node ?

**Comment by pi0** [comment]
@clarkdo cli dist (using dynamic imports) was getting broken

**Comment by clarkdo** [comment]
Is dynamic import not transpiled ?
I guess a version<12.20 will work ? But es2019 look better to me as well.

**Comment by pi0** [comment]
> Is dynamic import not transpiled ?

Actually it  transpiled to cjs by esbuild when using node while shouldn't (rollup is esm native and supports cjs with CommonJS plugin). Maybe we could use node if there was a node-es target...

**Comment by clarkdo** [comment]
Right, so node version >= 12.20 in target should work as it fully supports dynamic import.

**Comment by clarkdo** [comment]
OK, it seems not https://github.com/evanw/esbuild/issues/1084#issuecomment-810004991

**Pull request merged**
