### PR TITLE
feat(nuxt,schema): allow configuring vue `AppConfig`

### PR DESCRIPTION
**Pull request by DamianGlowala**
### 🔗 Linked issue

https://github.com/nuxt/nuxt/pull/28285#issuecomment-2333986417

### 📚 Description

This allows for configuring the Vue's [`app.config.idPrefix`](https://vuejs.org/api/application.html#app-config-idprefix) through `vue.idPrefix` in Nuxt config.

Thoughts on the name? Shall we consider `vue.useIdPrefix`?

### CODE REVIEW

**Review by huang-julien — COMMENTED** [review]
Isn't this something configurable with `app:created` hook ?

**Comment by DamianGlowala** [comment]
Good point, it is. The question is whether we should recommend creating a plugin like so:
```
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.hook('app:created', (app) => {
    app.config.idPrefix = 'foo'
  })
})
```
... or prefer to set it in the Nuxt config. (I don't have a strong opinion on this matter and happy to close the PR if using a hook is the preferred way.)

**Comment by huang-julien** [comment]
I'm in favor of letting users create a plugin. But our documentation may require a change if this wasn't clear enough that we can set runtime config of vue within a plugin :eyes:

**Comment by danielroe** [comment]
I can see a benefit to allowing users to define the _serialisable_ bits of the [vue app config](https://vuejs.org/api/application.html#app-config) in their nuxt.config file.

could we generalise this a bit, maybe with `vue.config`?

**Comment by DamianGlowala** [comment]
@danielroe updated 👌

**Review by danielroe — APPROVED** [review]

**Pull request merged**
