### PR TITLE
rewrote generate.js to async/await instead of coroutines

### PR DESCRIPTION
**Pull request by jroxendal**

### CODE REVIEW

**Comment by jroxendal** [comment]
Linting errors. Bummer. I'll have to look at it tomorrow!

**Comment by stephan281094** [comment]
Thanks for the PR! Just a heads up: this will change the minimal Node version required to run Nuxt to Node 7.6.0.

**Comment by pi0** [comment]
@stephab No as you see tests build matrix is also passing against 6.x too. Nuxt Bundle is being transpiled :)

**Comment by stephan281094** [comment]
@pi0 In that case: awesome!

**Comment by Atinux** [comment]
Thanks this is great 🙌

**Pull request merged**
