### PR TITLE
allow plugin in directory with index.js file

### LINKED ISSUE #3897: Plugins can't be found by an index reference
### Version

[2.0.0-25615151.226b90d](https://github.com/nuxt.js/releases/tag/2.0.0-25615151.226b90d)

### Reproduction link

[https://github.com/AndrewBogdanovTSS/nuxt-plugins-issue](https://github.com/AndrewBogdanovTSS/nuxt-plugins-issue)

### Steps to reproduce

Install latest Nuxt 2.0.0-25615151.226b90d
Create a plugin inside a folder with a default index.js name
Reference a plugin by it's folder in nuxt.config.js

### What is expected ?

Application is running

### What is actually happening?

× error Error: Plugin not found

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7751">#c7751</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by aldarund**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Resolves #3897

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Atinux** [comment]
Nice. Could you add a test case for it?

**Comment by aldarund** [comment]
@Atinux ye, i was thinking about adding them. But i didnt ended up with where it should be. E.g. create new test fixture or put it somewhere in existing ones ( if second - which one will be better ) ?

**Comment by manniL** [comment]
@aldarund You can put it either in `basic` or `with-config` ☺️

**Comment by aldarund** [comment]
added

**Pull request merged**
