### PR TITLE
fix: only encode non dynamic path params

### LINKED ISSUE #8420: Custom routes not working after upgrading to v2.14.8
### Versions
nuxt: v2.14.8
node: v12.18.3

**Routes:**
image

**Error:**
image

### PR DESCRIPTION
**Pull request by pi0**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Only encode non dynamic route paths. Resolves #8420 

Context: #8325 (with this PR, custom router is responsible to encode routes)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by clarkdo — APPROVED** [review]

**Review by atinux — APPROVED** [review]

**Comment by ydnar** [comment]
We just encountered a similar bug in our @domainr website frontend. We have tests that caught a URI-encoded param in a route. Previously, a `,` was decoded correctly. This is in the current latest version of Nuxt and vue-router.

**Comment by rchl** [comment]
What about routes like this one: https://github.com/vuejs/vue-router/blob/2c757a1cdc3aa8d55c3e3e22788a89f2351e58a0/examples/route-matching/app.js#L24
?

From a quick look at the code, it seems like it encodes all routes that are not non-dynamic but routes can be non-dynamic and contain regexp which will break when encoded.

**Comment by pi0** [comment]
@rchl Kindly please use a reproduction/issue. Last change only tries to encode auto scanned directories which do not support this convention.

**Comment by rchl** [comment]
Sounds good. Was just pointing out a potential issue without looking much at the code as I don't have time to dig into it now.

**Comment by ydnar** [comment]
> Released as hotfix [v2.14.9](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.9). @ydnar if still had issue, please open an issue :)

Still broken. I’ll file an issue!

**Pull request merged**
