### PR TITLE
Consistent parens in arrow functions

### PR DESCRIPTION
**Pull request by galvez**
I understand there may be a strong personal preference involved here, but with this PR I suggest we adopt the rule of [no paren-less arrow functions](https://eslint.org/docs/rules/arrow-parens). 

As I was studying Nuxt today, I found a few occurrences of inconsistency usage (places where there was a single param and parenthesis, and plenty of cases where there were none).

I hope I don't come off as nitpicky, just strongly believe adopting this rule makes things more readable and promotes more consistency.

I also made minor edits to a couple of places where the logic would extend too far into a single line, and I felt they could be broken down into multiple lines for the sake of readability.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Note: I'm not a Nuxt.js maintainer nor core member. I have a strong objection to that spam pinging.

Please remove it immediately from your PR description so that it will not cause endless commit mentions when merged.

**Comment by galvez** [comment]
@ishitatsuyuki Sorry about that. I had absolutely no idea there were people sensitive to this, or that was doing anything reprehensible at all. Once again, my apologies.

**Comment by manniL** [comment]
@galvez: In the end, this is a matter of opinion but I'd prefer no parens when they aren't needed (unary functions). However, a uniform style is definitely a goal that should be worked towards.

**Comment by galvez** [comment]
@manniL I used to prefer no parens when possible, but eventually realized the cognitive dissonance that causes. Take this example:

screen shot 2018-08-04 at 10 42 39

When quickly glancing at code, it's much easier to identify an arrow function if it consistently always has parenthesis than otherwise.

So that caused me to change my mind and understand why the ESLint setting exists. But yeah, this is really just a suggestion, with a bit of manual work done for the team, if they choose to adopt it.

**Comment by manniL** [comment]
@galvez There are definitely situations where you can recognize an arrow function faster with parens (directly on `(` instead of `argv =`). On the other hand, the difference isn't as substantial (in my eyes, as I likely read code very frequently and I'm using `no-parens`) and it makes small functions "larger".

Nevertheless, no matter if no-parens or forced-parens, a consistent style will help everyone :relaxed:

**Comment by qm3ster** [comment]
I think it's less readable.
```diff
- a.filter(x = >x.bool).map(x => x.prop)
+ a.filter((x) = >x.bool).map((x) => x.prop)
```
I believe `"as-needed"` is a lot more preferable.
Cases like 
```ts
export const func = arg => { /* code */ }
```
should fail not because they are without parenthesis, but because
```arg has an implicit `any` type```, prompting its change to
```ts
export const func = (arg: type) => { /* code */ }
```
Other cases when parentheses are inserted:
- async
- multiple arguments
- zero arguments `const defragment = () => {}`

Hence, no-parens only stays where it should, and where even git diff isn't an argument - truly anonymous functions being passed as an argument.

**Comment by galvez** [comment]
@qm3ster So yeah, this adds up to the idea that's it's truly up to the core maintainer's personal preference, but I do see more _value_ in consistency. We'll see :)

BTW: There's no problem with untyped function parameters in JavaScript. I just wanted say that out loud because there's a lot of TS mentality flowing into JS-land and I don't think that's such a good thing.

**Comment by Atinux** [comment]
Actually I like the comment of @qm3ster about some specific cases where it's more readable. Personally I always use parentheses for consistency but I am open to other people code of style.

Is there a way to force parentheses except in the cases where it's used as "callbacks"? 

Example:
```js
a.filter(x => x.bool).map(x => x.prop)
```

**Comment by galvez** [comment]
@Atinux as it turns out, there's an config prop **just for that**, `requireForBlockBody`.

I'll update the PR. This seems like a fair compromise.

**Comment by galvez** [comment]
I'll agree with @Atinux and @qm3ster that this looks pretty good now :)

**Comment by manniL** [comment]
Great consent :+1:

**Pull request merged**
