### PR TITLE
v2.10.2

### PR DESCRIPTION
**Pull request by pi0**
### 🐛 Bug Fixes

- `webpack`
  - #6495 Enable devtool for dev mode
  - #6566 Normalize devtool for terser compatibility
- `config`
  - #6583 Typo in `unsafeInlineCompatibility` name
- `vue-app`
  - #6590 Fix collapsed SSR log

### 📝 Examples

- `with-sockets`
  - #6586 Fix cannot read property 'app' of undefined on nuxt build

### 💖 Thanks to

- @PedroD
- Stephan Besser (@reskume)

### CODE REVIEW

**Review by galvez — APPROVED** [review]

**Comment by pi0** [comment]
@kevinmarrec seems random

**Comment by kevinmarrec** [comment]
:laughing:

**Review by kevinmarrec — APPROVED** [review]

**Review by atinux — APPROVED** [review]

**Review by TheAlexLichter — APPROVED** [review]

**Review by pimlie — COMMENTED** [review]
@clarkdo Although others and me already approved #6495 itself, the opening post in that PR still list a todo about checking memory usage in dev mode.

Before we release 6495, could you please confirm the status of that todo?

**Comment by clarkdo** [comment]
Will do it tonight

**Comment by clarkdo** [comment]
Verified with hot reloading, restarting and ssr benchmark.

**Pull request merged**
