### PR TITLE
feat: function watchQuery

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Another pr for function watchQuery, forgot dataRefresh part in last pr https://github.com/nuxt/nuxt.js/pull/6222.

@pi0 For getting this context, it brings in some overheads for getting all instances.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by Atinux** [comment]
Would be nice to add a test case for it :)

**Comment by clarkdo** [comment]
Test is added

**Comment by Atinux** [comment]
Lastly, a PR on https://github.com/nuxt/docs/blob/master/en/api/pages-watchquery.md to tell that the type can be a function that returns a Boolean and ready to merge :)

**Comment by clarkdo** [comment]
@Atinux Done

**Comment by pi0** [comment]
This had to be merged after 2.9.2 😂 Now I've to create a temp branch

**Comment by clarkdo** [comment]
Sorry, if it’s the only one, I can revert

**Pull request merged**
