### PR TITLE
feat: check expectated node version

### PR DESCRIPTION
**Pull request by NicoPennec**
To avoid any further issues on GitHub about node version 😇

### CODE REVIEW

**Comment by Atinux** [comment]
This is brillant 🙌

**Comment by Atinux** [comment]
I think it depends of which NPM version you are using

**Comment by NicoPennec** [comment]
npm doesn't check engines (before it did... https://docs.npmjs.com/files/package.json#enginestrict)

yarn check engines, but only on `npm build` on Nuxt core project, not on a project build that uses Nuxt as vendor.

https://github.com/yarnpkg/yarn/blob/879b4f3c893b5e5ec162a1d0a9234c3793e7ac01/src/package-compatibility.js#L59

**Comment by phlogisticfugu** [comment]
arrghhh, I was juust about to do some babel-magic to get nuxt to run on node6, in order to run it on AWS Lambda for https://github.com/phlogisticfugu/perfect-paca

and now I need to lock to nuxt 1.2 in order to avoid this...

is there any way for this to be a warning and not a fatal error?  or maybe do some feature detection instead of a strict semver check?

**Pull request merged**
