### PR TITLE
feat: configurable global name

### PR DESCRIPTION
**Pull request by JuliaNeumann**
First of, many thanks for Nuxt, it's a great project!!

This PR is related to / a partial solution for #1792, though the motivation is a bit different: The main goal is to be able to run multiple Nuxt apps on the same page (in a microservice / microfrontend setting), and this is a step towards it, as it makes it possible to set a custom string in the config which will be used instead of the default "nuxt" in the global variables & HTML wrappers.

I'd be happy to improve this based on any feedback you provide, also if you think a different approach should be taken here. But it would be awesome to see a feature like this included in Nuxt, as it would help both with the security concerns in the issue mentioned above and with the encapsulation needed for a microfrontend application.

### CODE REVIEW

**Review by clarkdo — COMMENTED** [review]
For me, I think it's a good idea, thank you for your contribution.

And maybe only make property names on `window` configurable is enough.

I'm not sure the benifits of using different nuxt apps in same page, maybe using different nuxt apps in a single project but different pages is more reasonable.

If you want to isolate different parts in a single page, you can use components and isolated stores to compose you whole page.

If any concerns, please feel free to comment.

**Review by clarkdo — COMMENTED** [review]
~~duplicate~~

**Comment by Atinux** [comment]
Hi @JuliaNeumann 

Thank you for this PR.

About 

> The main goal is to be able to run multiple Nuxt apps on the same page (in a microservice / microfrontend setting)

Could you explain a bit more your concept, I'm not sure to understand the use cases for this choice.

**Comment by JuliaNeumann** [comment]
Many thanks for your feedback, @clarkdo and @Atinux! I'll try to make our use case a little bit clearer: So the main goal is to replace a big application (which is implemented as a monolith at the moment) step-by-step with several self-contained systems (some of those will not correspond to a separate page) which will be implemented and maintained by different small teams. Also, some of these self-contained systems might be run in the context of other applications. So that's why our first idea was to have each as a Nuxt app which can run completely on its own. But we are aware of other options such as you proposed and are exploring those as well. 

So we just tried this approach of having two Nuxt apps on one page, and apart from the issue this PR should solve, it actually worked quite well. But if you think it's not a use case worth supporting, that's fine, as I said, we are also exploring other options and might well go with one of those in the end. 

Still, there remains the security concern mentioned in the issue above, which is also something we would like to address, so do you think this could be a possible approach?

**Review by pi0 — COMMENTED** [review]
I suggest wrapping window.* Into brackets. (window [globalName]) If globalName contains characters like dash (`-`) we get into trouble. Also we may make window (`globalObject`) configurable too with this enhancement. Which is useful for testing and complex senarios.

**Comment by galvez** [comment]
@pi0 duly noted!

**Comment by galvez** [comment]
@pi0 @JuliaNeumann I'm working on fixing the conflicts since 2.0.

I'll advise against `window[]` though because of the related variables, for instance:

    window._<%= globalName %>ReadyCbs = []

We should state in the documentation that `globalName` **must** be a valid JS identifier.

**Comment by galvez** [comment]
Opened new PR to track this work.

**Pull request closed without merging**
