### PR TITLE
feat(ts): add TSX support

### PR DESCRIPTION
**Pull request by kevinmarrec**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This PR provides better TS support, adding `.tsx` files support.
Vue SFC `.vue` with `lang='tsx'` should work too !

It uses a combination of 2 loaders :
- `ts-loader` to transpile Typescript
- `babel-loader` to handle JSX stuff

As for `.ts` files with `loaders.ts`, you can customize `ts-loader` options for `.tsx` files with `loaders.tsx`.

### Documentation

As for other PR's related to the TS support, there will be a PR regrouping the whole TS support documentation, and a section about TSX will figure in it.

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Review by pi0 — DISMISSED** [review]

**Comment by pi0** [comment]
@kevinmarrec Would you please locally resolve merge conflict?

**Comment by kevinmarrec** [comment]
@pi0 It should be alright now 🙂

**Review by pi0 — APPROVED** [review]

**Comment by chanlito** [comment]
@kevinmarrec are you working on documenting typescript feature as well?

**Comment by kevinmarrec** [comment]
@chanlito Sorry for late answer
Yes and I'll update the TypeScript example with the new setup :)

**Pull request merged**
