### PR TITLE
fix(types): prevent overwriting vue types in template

### PR DESCRIPTION
**Pull request by rchl**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/22801

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

See the issue.

It looks like this code was just plain wrong from the beginning (I've introduced it) and it worked for `<script>` tags but not for `<template>`.

I don't fully understand why the current code works for the script tag (it's tested by tests) but not for the template tag but I suppose it has to do with how Volar does things.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — DISMISSED** [review]

**Comment by rchl** [comment]
Just to add a bit more information here - the original code seemed to break this interface extend:

```ts
import 'vue';

declare module 'vue' {
    export interface GlobalComponents {
        MyComponent: typeof import('./components/my-component.vue').default;
        // ...
    }
}
```

which makes volar just see `GlobalComponents` as `any`.
Not sure why it doesn't reproduce in my simple project but I suppose it depends on what types are evaluated and in what order.

**Comment by danielroe** [comment]
Would be nice to add a `vue-tsc` typecheck to the 2.x branch to catch this.

**Comment by rchl** [comment]
Would you like that to be a part of this PR?

I'm a bit skeptical about that because Volar/vue-tsc is not shy of breaking things (on purpose or not) so it could contribute to instability of the CI.

**Comment by danielroe** [comment]
That would be great, if possible! I realise this is a straight bugfix but would be nice to catch any regression later.

I'm not worried about CI instability because that will reflect real user instability, and will give us warning so we can alert Johnson and hopefully resolve.

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
Beautiful. Thank you ❤️

**Pull request merged**
