### PR TITLE
feat(schema): add type hints for runtime config

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

https://github.com/nuxt/nuxt/pull/18594#discussion_r1090512835

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR adds type hints (within nuxt.config only, not within `useRuntimeConfig`) to advise on the way to override runtime config:

CleanShot 2023-01-31 at 22 58 22@2x

I would value some testing on this and improving the algorithm to make sure we are matching `scule`. (We might also move into `scule` itself if you like @pi0, and that way we could add more type tests there.)

BTW, I initially considered using https://github.com/sindresorhus/type-fest/blob/main/source/snake-case.d.ts but there were issues with it (e.g. `baseURL` and `PascalCase` both gave incorrect results) and I thought better to take a completely different approach.

▶️ [**TypeScript playground**](https://www.typescriptlang.org/play#code/C4TwDgpgBAogHsATgQwMbAKpkogwgCwFcA7AawB4AVKCBCYgEwGcomkBLYgcwD4oBeKNVrB6zKAAMAJAG9OAMwiIoAQQC+shUqgAhNRIBQUKAH5VNOoxZYcqZEwjkVPI8dO6Loq5Nk2ldh3I2RE5eDTliRWUAJQg2fVc3dx1PMRZpCKioXHDY+MMkpLMM9Vkc2XgkNExsJQISCjzgHgTCtwAuKGIIADclRI7VAc6AchHXTu6+xAMDUEgoAGUAG3ZUCAAZe2AqVO9g0L5BYUtxDK1lUsztPQLkvbPNSO1y6+UAEVa3M3eHljGBsYzCpAVBOiVwq8VmtNttyO8WndjKNxsiur1+nNwNA-IhFsRkKQILh7I4Tl5xAduAAaJbAZCiP5QEZsZCIYAjKAAH2ZywA9gB3JScnkjQi1RCcwQs+nskZHIRM87PS7hC66L7Apm4gKOZwDLUiNI+GQARm5UAATBaAMwWgAsFoArBaAGwWgDsFoAHBaAJwWgAMXyKJquuPxhOJpPIOlpI35QsliNBnUW9MZRu8CcFwotYolqLa9yzjxk0PWWzY5EqKHQuPqZFjPBaTyyTRDxbMFdh1dr1QbRCbOhbTIBxcKxQA+rJ1DOZBGCUSSYE48zWXKUxOkuD51ce1Wdv36xLGxQRy154uoyvHE14xuOVvt50UqXrBLdc3QW1p7PwrcP6FLu-6+BKkbLjGa45km8qdjudIMtA77rrKHJAUCYbhNekGrvGibCs+E6TBiMxtGmGbIac-yPiKvK5pKQHFGBtgxs42HgUu0Z4fRsFEcBkhXp+bGtgunE3lB+EMXBdydDqMaUC4swAPTKVAABifLKMgPR8uwDDIMQ6xQHy8hQAwfKEAARsAtLzNAVkQPgOnsJZyhMPglnLAwUAALYMqg+BQMA+DQEwXG3lAhDAOwqygFA8iIHyvnrqghDLBA4yqVA+DAMAYBMO0qlcOwIXWQAdKgyXKSQABWTDKUwaUZcpVn8lZyn+ZwjWIKgymcAwtDlcATAAMQbKagY2gAtBNgYegYIzqQA8stU46Co0SckwDLsEw8jsHEUA4dxjgjPIfJ8jobLyotK1rRtW2sLt+2HR+OAQad5BLZd13Jndq3rZt20vQdR0nbe32aVdwMuEtgOPUDABaIMxa94PibhZ3Q4910AF63SMKgAAoAJJTpQy0ANIwAAcpaNrI6je1g+9SifZDIzIGA7CUHyRLEAz+OEyT5OUzT9M2htKPPWjrPHZjX1czzfMCwzVnIATPBAA).

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by manniL** [comment]
Really nice DX 🔥

**Comment by pi0** [comment]
Since env handling logic is happening in Nitro, i think we could generate types also from nitro types. BTW really nice addition 🔥

**Comment by pi0** [comment]
For runtime consistency, we might also directly use scule (in build time) to generate precise types.

**Comment by Baroshem** [comment]
This is a really great feature! Cant wait to see it in the new version of nuxt module 🙂

**Comment by danielroe** [comment]
merging as a first step - moving to tsdoc is definitely better performance-wise but will need to be implemented in https://github.com/unjs/untyped.

**Pull request merged**
