### PR TITLE
fix(nuxt-ts): error catch in nuxt-ts binary

### LINKED ISSUE #4897: Even if `nuxt-ts build` fails, the status code will always be zero.
### Version

[nuxt-ts](https://github.com/nuxt.js/releases/tag/nuxt-ts)

### Reproduction link

[https://github.com/iwata/nuxt.js/tree/build-bug](https://github.com/iwata/nuxt.js/tree/build-bug)

### Steps to reproduce

```sh
$ git clone git@github.com:iwata/nuxt.js.git
$ cd ./nuxt.js
$ git checkout -t origin/build-bug
$ cd examples/typescript-tsx
$ yarn install
$ yarn build
$ echo $?
```

### What is expected ?

`echo $?` will show `1`.

### What is actually happening?

`echo $?` shows `0`.

### Additional comments?

If `nuxt build` fails in v2.4.0, it will be status code 1 as expected.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8570">#c8570</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by kevinmarrec**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Fixes #4897

### CODE REVIEW

**Review by atinux — APPROVED** [review]

**Comment by Atinux** [comment]
Failing tests apparently @kevinmarrec

**Comment by manniL** [comment]
@kevinmarrec extra space as it seems(`it `) 
image

**Comment by kevinmarrec** [comment]
@manniL I didn't change anything that may make tests fail , issue should be on `2.x` 🤷‍♀️

**Comment by manniL** [comment]
@kevinmarrec Yup. Related to https://github.com/nuxt/nuxt.js/commit/4b82aa9d84a79076cc76ed837e4ec1bbc7830582#diff-403be207e4fec169258c18d6af8cd953 🤷‍♂️

**Comment by clarkdo** [comment]
I manually fixed this in `dev` branch by https://github.com/nuxt/nuxt.js/commits/dev

You can do the same way.

**Comment by kevinmarrec** [comment]
Thanks @clarkdo , I cherry-picked you commit to fix the snapshot through this PR

**Comment by pi0** [comment]
Audit is regarding jest >  braces. Should be fixed after next minor release (dev ~> 2.x)

**Pull request merged**
