### PR TITLE
[v1] chore(vue-renderer): move title above meta

### PR DESCRIPTION
**Pull request by NightDiRaven**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Comment by manniL** [comment]
@NightDiRaven 	Please explain your proposed change properly :relaxed:

**Comment by NightDiRaven** [comment]
@manniL Its really only for some dumb CEO, they request proper order (i dunno why). In ver 2 of nuxt all in title -> meta order. But in 1.x its meta -> title
before
image 
after
image

**Comment by pi0** [comment]
Is this PR targeting nuxt 1.x? 🤔

**Comment by Atinux** [comment]
Shouldn't the title be after `<meta charset="utf-8">`?

**Comment by visualfanatic** [comment]
@Atinux exactly!
https://code.google.com/archive/p/doctype-mirror/wikis/MetaCharsetAttribute.wiki

> In order for all browsers to recognize a `<meta charset>` declaration, it must be
> 
> - Within the `<head>` element,
> - **Before any elements that contain text, such as the `<title>` element,** AND
> - Within the first 512 bytes of your document, including DOCTYPE and whitespace

**Comment by Atinux** [comment]
But actually we cannot filter the meta just for the charset, is it a real issue that title is after all the metas then?

**Comment by pimlie** [comment]
The official W3C HTML5 Recommendation doesn't seem to mention a need for ordering at all: https://www.w3.org/TR/html5/document-metadata.html#specifying-the-documents-character-encoding

As the document @visualfanatic links to seems to be from 2011 (the site was taken down in 2011) and first release of html5 was in 2014, I think its safe to ignore the ordering

**Comment by pi0** [comment]
@pimlie Yes. But I think even with the lack of spec reasoning about `encoding` ordering is valid. A text parser needs to know how many bytes is a character. Parsing first 512 bytes for encoding detection and then upgrading would be possible but not the opposite.

**Comment by pi0** [comment]
@NightDiRaven Thanks for this PR, but as v1 is in out of maintenance state, i would suggest to continue this topic in #5433.

**Pull request closed without merging**
