### PR TITLE
v2.16.0

### PR DESCRIPTION
**Pull request by pi0**
> $ You can try changes by using `nuxt-edge` package

### 🚀 Enhancements

  - **config:** Support `nuxtrc` in dist directory (#9280)
  - **generator:** Add `ignoreEnv` generate option during `ensureBuild` (#8955)
  - **server:** Allow disabling `serve-static` middleware (#9365)
  - **vue-app:** `context.beforeSerialize` method (#9332)
  - **vue-app:** Pass `store` to `createRouter` (#9629)
  - Default to `core-js` version to `3`` (#9987)
  - Updated dependencies (#10510)

### 🩹 Fixes

  - **vue-app:** Respect `scroll-margin-top` when navigating with hash (#9187)
  - **webpack:** Use `javascript/auto` for js rule (#9180)
  - **server:** Unregister error event listener (#9245)
  - **babel-preset-app:** Respect explicit options.targets for modern preset (#9337)
  - **vue-renderer:** Decode route path for `payload.js` (#9494)
  - **vue-app:** Redirect to external url replaces current history entry (#9500)
  - **utils:** `trailingSlash` causes error with dynamic nuxt-child routes (#9505)
  - **vue-app:** Re-register components construtor in HMR (#9539)
  - **vue-app:** Serialize route meta to allow functions (#9634)
  - **vue-app:** `null` check for `$root` access (#9150)
  - **vue-app:** Don't normalise route path if it's valid (#9460)
  - **generator:** Allow passing `builder` to `getGenerator` (#9574)
  - **generator:** Throw an error when Builder is missing (#9663)
  - **vue-app:** Use correct `$config` for finding basePath (#9706)
  - **vue-renderer:** Ensure custom build indicator preserves some whitespace (#9705)
  - **generator:** Decode path with `ufo` (#9739)
  - **cli:** Ensure nuxt instance is closed when skipping build (3e9d7e3e)
  - **vue-app**: Fix typo for `nuxt-child-key` in `web-types.json`` (#9792)
  - **vue-app:** Call ssrContext.unsetMutationObserver only if it exists (#10132)
  - **webpack:** Allow files with `.cjs` extension to be transpiled (#10340)
  - **vue-app:** Preview mode fetch (#10489)

### 🏡 Chore

  - **pkg:** Build for `ES2019` target (#9328)
  - **test:** Revert jest and babel-jest to 26 (#9377)
  - **utils:** Improve `stripWhitespace` utility (#9668)
  - **doc:** Fix link to contribution guide (#9815)
  - **test:** Fix external redirect link (#9816)
  - **readme:** Fix browserstack and saucelabs icons (#10068)

### 🌊 Types

  - Add `prefetchPayloads` to router options (#9715)
  - Add `asyncData` return types to component instance type (#9239)
  - Add nuxt.config alias type (#9424)
  - Add `onNuxtLoaded` and `onNuxtReady` types (#9510)
  - Add typing for `build.stats` options (#9555)
  - Return type of `$fetch` (#9854)
  - Add types for new `false` option for `render.static` (#9372)

### 💖 Thanks to

- Abdfn
- Aewshyae
- Ahmadou Waly NDIAYE
- Andrew Luca (@iamandrewluca)
- Carbotaniuman (@carbotaniuman)
- Daniil Okhlopkov
- David Ovčačík  (@dovca)
- Jacob
- Jon-ht
- K-utsumi
- Loick Le Digabel
- Matteo Rigon
- Matthieu Sieben (@matthieusieben)
- Mehmet
- Michał Kędrzyński
- Michiel Doesburg
- Mohammad Saleh Fadaei (@ms-fadaei)
- Mrazauskas (@mrazauskas)
- Ofer Shaal (@shaal)
- Payel Karmakar (@PayelKarmakar06)
- Rafał Chłodnicki
- Renovate[bot]
- @SlayerOfTheBad
- Thibault Vlacich
- William L'Archeveque (@wlarch)

### CODE REVIEW

**Comment by wlarch** [comment]
Any estimate release date for this version ?

**Comment by loick** [comment]
Any news about this release? 🙏

**Comment by daniluk4000** [comment]
Three months ago I have asked you to upgrade to TS 4.4. 

You did that, now, TS 4.5 released, and 2.16.0 still not released ;(

Please update to TS 4.5

**Comment by d3x7r0** [comment]
Hi there.

Sorry for pinging you guys but I was just wondering if there are expectations of when this version will get released? We found some annoying issues that can only be resolved by the two new features planned for the `vue-app` package in this release and it would help us tremendously to have them.

Is there any way we can help?

**Comment by DraftProducts** [comment]
Hi guys.
First, I wish you all a happy new year 🎉 

This PR is now pending for about 2 months, and we have no information about the future of this version 2.
Nuxt v3 is still not ready for production, and this version is becoming more and more obsolete due to the evolution of other tools like Vue, Typescript, Webpack, Stylelint...

If there is a way for us to help, I'm sure many would volunteer, even though it seems like only the administrative actions are missing.

**Comment by daniluk4000** [comment]
I've got some answer from Nuxt's Framework Lead pi0 (thanks him so much).

Looks like the package will be maintained as edge version for a while until it becomes stable and we'll have to wait for good reason.

изображение

**Comment by Gobler** [comment]
Is anything known about this version?
According to the roadmap it should be released already: https://v3.nuxtjs.org/community/roadmap/

**Comment by daniluk4000** [comment]
> You did that, now, TS 4.5 released, and 2.16.0 still not released ;(

This aged well

изображение

**Comment by DraftProducts** [comment]
> Is anything known about this version? According to the roadmap it should be released already: [v3.nuxtjs.org/community/roadmap](https://v3.nuxtjs.org/community/roadmap/)

The date has change multiple times, it planned for march last time I saw it 🤷‍♂️ 
It seems that having a stable version of Nuxt has not been a priority since November.

**Comment by pi0** [comment]
Hi dear @dargmuesli. I've just messaged you on discord sorry for the delay! Also, we do plan to release 2.16 in the upcoming weeks aligning with a first beta version of nuxt bridge with @danielroe to advise using 2.16 in production! Stay tuned!

**Comment by ms-fadaei** [comment]
@pi0 
Hi Pooya.
The Nuxt 2.16 will use the Vue 2.7 or not? Is there a plan to use The Vue 2.7 in the upcoming Nuxt 2 versions?

**Comment by MartinX3** [comment]
@lesion you shouldn't use node 12.
It's end of life since april 2022.
https://nodejs.org/de/about/releases/

**Review by dargmuesli — APPROVED** [review]
v2.16-edge works for me and fixes numerous issues with the current stable :)

**Comment by Gobler** [comment]
So little is missing... does anything know when to expect the release?

**Comment by noook** [comment]
Quick question: is this gonna be released one day or not ?

**Comment by MartinX3** [comment]
@noook just use nuxt-bridge
Since 2.16 is somehow a backport release of nuxt 3 it should be ready after nuxt 3 and nuxt-bridge are ready

**Comment by daniluk4000** [comment]
I wonder if we'll see "December 2022" here :(

изображение

**Comment by MartinX3** [comment]
The latest release still points to rc14 but at least the roadmap now tells us `autumn` for the 2.16 release.
https://nuxt.com/docs/community/roadmap#current-releases

So until the 2022-12-22

**Comment by YutaMoriJP** [comment]
@pi0 Hi, any estimates on the release date for this?

**Comment by MartinX3** [comment]
Subscribe this PR for updates:
https://github.com/nuxt/bridge/pull/648

**Comment by YutaMoriJP** [comment]
> Subscribe this PR for updates: [nuxt/bridge#648](https://github.com/nuxt/bridge/pull/648)

Isn't that a PR for nuxt-bridge?

**Comment by MartinX3** [comment]
> > Subscribe this PR for updates: [nuxt/bridge#648](https://github.com/nuxt/bridge/pull/648)
> 
> Isn't that a PR for nuxt-bridge? 

And 2.16 is a backport of 3.

**Comment by daniluk4000** [comment]
This was a historic MR

**Comment by danielroe** [comment]
Remade -> https://github.com/nuxt/nuxt.js/pull/10907

For more info on the repository changes happening at the moment, see https://nuxt.com/vision-2023 and https://github.com/nuxt/framework/issues/10147.

**Pull request closed without merging**
