### PR TITLE
fix(vue-app): use mixin to provide `this.$nuxt` #8068

### LINKED ISSUE #7696: Nuxt server $nuxt.context changed by latter request
### How do I discover this problem?

In production env, I use $nuxt.context.route info to determine which header to show ( use v-if ) in defaultLayout(which is shared between all routes), because we believe $nuxt.context should be the same in one request, but turn out not the same.
In large concurrent request , Accidentally A page will display B page header, which should only be displayed in B page, so I print out the $nuxt.context.route.name , but unfortunately printed B when refresh A page, then we printed out some $nuxt.context info which is also related to B page when refresh A page

So I did a simple demo below to reproduce the problem, hope this unknown but important issue be addressed quickly

### Versions

- nuxt: 2.10.2
- node: v8.11.2

### Steps to reproduce

1. create a nuxt project
2. add 2 simple vue files to mimic 2 routes: 

./pages/index.vue
./pages/B.vue

3. change ./layouts/default.vue to below content

```js
<template>
  <div>
    <p>{{ $route.name }}</p>

    <p>{{ $nuxt.context.route.name }}</p>

    <Nuxt />
  </div>
</template>
<script>
export default {
  created() {
    setTimeout(() => {
      console.log('--------', this.$route.name, this.$nuxt.context.route.name)
    }, 1000)
  },
}
</script>
```
4. visit http://localhost:3000/ then quickly visit http://localhost:3000/b

### What is Expected?

on both client and server side
1 second later, print out  
```bash
-------- index index
-------- B B
```

### What is actually happening?

1 second later
client side print out the same as expected

```bash
-------- index index
-------- B B
```

But server side terminal print out 
```bash
-------- index B
-------- B B
```
### Conclusion
It's obvious that first visited page index this.$nuxt.context is alter by second request (which visited page B)

Anybody know why? Is it a bug or a usage problem?

### PR DESCRIPTION
**Pull request by clarkdo**
## Description

closes #7696

Continue work on #8068 (author @danielroe)

### TODO:

- [ ] Use `defineProperty` with a getter
- [ ] Test

### CODE REVIEW

**Comment by galvez** [comment]
Wondering if passing `nuxt` as instance option + prototype getter would work...

```js
if (!Vue.prototype.$nuxt) {
  Object.defineProperty(Vue.prototype, '$nuxt', {
    get () {
      return this.$root.$options.nuxt
    }
  })
}
```

**Comment by clarkdo** [comment]
Yes, we talked here https://github.com/nuxt/nuxt.js/pull/8068#issuecomment-701339239
Haven’t got a chance to update and add test.

**Comment by danielroe** [comment]
closes #7696

**Comment by pi0** [comment]
closing in favor of #8170

**Pull request closed without merging**
