### PR TITLE
Node modules css test

### PR DESCRIPTION
**Pull request by galvez**
This PR introduces a test failure that can only be fixed when [this is too](https://github.com/vuejs/vue-style-loader/pull/30) or we find a workaround in Nuxt itself.

### CODE REVIEW

**Comment by galvez** [comment]
To debug locally:

```
bin/nuxt dev test/fixtures/basic/
```

screen shot 2018-08-18 at 16 48 17

**Review by clarkdo — CHANGES_REQUESTED** [review]
Didn't commit node_modules/test-module
And another point is that I suggest adding this test into existed one, because always introduce a new building for simple scenario is kind of expensive.

**Comment by galvez** [comment]
screen shot 2018-08-19 at 20 55 44

@Atinux @clarkdo Just to be clear guys, this test is failing because of the vue-style-loader related bug. What it demonstrates is that you cannot have a node_modules CSS import inside a Vue template running in Nuxt:

```
import 'module/modules-internal-path/file.css'
```

Now, let me know if we're not going to dedicate efforts into fixing this and I'll open a PR to make a note about this limitation in the documentation. I'm probably removing the import from my use-case app and adding that CSS manually to my build.

**Comment by galvez** [comment]
This is _unfortunately_ a regression for Nuxt because the same statement works in 1.4.2 :(

**Comment by galvez** [comment]
For reference, discusson on the vue-style-loader's PR: https://github.com/vuejs/vue-style-loader/pull/30

**Comment by Atinux** [comment]
Well I found where it comes from, and it's not from Nuxt.js or Vue Server Renderer but the library itself that is not constructed correctly.

It works perfectly when doing:
1. `vue build --target lib --name test-module index.vue` inside the `node_modules/test-module/` directory (think of `npm install -g @vue/cli @vue/cli-service-global`)
2. Updating `node_modules/test-module/index.vue` to:
```vue
<script>
import './test-style.css'

export default {}
</script>
```
3. Updating `plugins/testModule.js` to:
```js
import '../node_modules/test-module/'
import '../node_modules/test-module/dist/test-module.css'
```

Also, since the library is only a CSS file at the end, `import '../node_modules/test-module/'` is useless :)

It is crucial that CSS is exported for a library, otherwise, Webpack will add `document.createElement....` to add dynamically the CSS, and it is not recommended at all.

**Comment by galvez** [comment]
Cool, I'm adding docs to prevent people from doing this mistake :)

**Pull request closed without merging**
