### PR TITLE
v2.6.3

### PR DESCRIPTION
**Pull request by pi0**
## Fixes

- **cli**: Watch and reload `nuxt.config` (#5574)
- **utils**: serialize inline functions (#5051) (#5580)
- **vue-app**: Fix context `req` and `res` types (#5560)
- **webpack**: Fix production font preloading (#5436)
- Don't customize esm options (91c3642e64166a939683b856e5b34ef42d12bb0e)

## Dependency Upgrades

- Update `webpackbar` to [^3.2.0](https://github.com/nuxt/webpackbar/blob/master/CHANGELOG.md#320-2019-04-18)
- Update `vue-router` to [^3.0.6](https://github.com/vuejs/vue-router/blob/dev/CHANGELOG.md#306-2019-04-17)
- Update `@nuxt/loading-screen` to [`^0.5.0`](https://github.com/nuxt/loading-screen/blob/master/CHANGELOG.md#050-2019-04-24)

### CODE REVIEW

**Comment by pi0** [comment]
@clarkdo can we include https://github.com/nuxt/nuxt.js/commit/aea9db6f56ed369f16d5688cfb0502e95743a115 too?

**Comment by clarkdo** [comment]
> @clarkdo can we include [aea9db6](https://github.com/nuxt/nuxt.js/commit/aea9db6f56ed369f16d5688cfb0502e95743a115) and [30c2b95](https://github.com/nuxt/nuxt.js/commit/30c2b9542e90f44fd0f3b83e3e6d5297cf3db624)?

Yes

**Review by galvez — APPROVED** [review]
LGTM

**Comment by pi0** [comment]
Added #5580

**Review by pimlie — DISMISSED** [review]
I receive an `Expected "0" to be defined` error on navigation within the app. Its thrown from this line: https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/utils.js#L474

**Comment by clarkdo** [comment]
@pimlie What's the version of vue-router are you using ?

**Comment by pimlie** [comment]
@clarkdo `3.0.6`, see https://github.com/pimlie/nuxt-issues/tree/bug-router0 for a repro (@pi0 confirmed it as well in the mean time)

**Review by atinux — APPROVED** [review]

**Review by kevinmarrec — APPROVED** [review]

**Review by TheAlexLichter — APPROVED** [review]

**Pull request merged**
