### PR TITLE
build: hide yarn.lock file for better diff

### PR DESCRIPTION
**Pull request by jbpionnier**
https://medium.com/@clarkbw/managing-generated-files-in-github-1f1989c09dfd

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by pi0 — CHANGES_REQUESTED** [review]
I'm against hiding diffs. PRs may accidentally/intentionally change this lock file to use wrong/valnurable CDN for some packages and we can't detect it on right time. Also by observing lots of changes we will be notified something is wrong.

**Comment by galvez** [comment]
Agree with @pi0 here.

**Review by TheAlexLichter — CHANGES_REQUESTED** [review]
@jbpionnier Nice approach but I share the opinion of @pi0.

**Comment by pi0** [comment]
It seems that renovate problem with yarn integrity is finally resolved too. @jbpionnier I'm so sorry for closing this PR. And appreciate your help. Keep up doing it ❤️

**Pull request closed without merging**
