### PR TITLE
add: print warning when using build.extractCSS.allChunks

### LINKED ISSUE #4094: Show a warning if extractCSS.allChunks is set
### What problem does this feature solve?

Since v2.0.0, `extractCSS` isn't responsible for extracting CSS in **one file**. This was possible before by using `extractCSS: { allChunks: true }`. Now, it has to be done through webpacks `splitChunk` settings.

To make users aware of that we should give them a proper warning if it is still set.

Documenting how to leverage single file css extraction again would be nice too: https://github.com/nuxt/docs/issues/856

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7956">#c7956</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by tohutohu**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Resolve: #4094 

I have a question.
When build.extractCSS.allChunks is set, what should be the default value?

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by manniL** [comment]
I wouldn't alter the value of `extractCSS` in this case as it could possibly contain other settings for `mini-css-extract-plugin`. Even if not, it'll evaluate to `true` and the CSS will be extracted as expected.

**Comment by manniL** [comment]
Thanks! Almost good to go from my perspective.

Could you adjust the "new property" (which is `build.optimization.splitChunks`)? :relaxed:

**Comment by tohutohu** [comment]
@manniL 
Thanks.
I changed it just as you pointed out.

**Comment by manniL** [comment]
Thank you! ☺️

**Review by TheAlexLichter — APPROVED** [review]

**Review by clarkdo — APPROVED** [review]

**Review by galvez — APPROVED** [review]

**Comment by galvez** [comment]
@clarkdo @pi0 let's get this in?

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Thanks, @tohutohu.

**Pull request merged**
