### PR TITLE
v2.7.0

### PR DESCRIPTION
**Pull request by pi0**
## Beta Testing

If you are interested in early testing this release, you can temporarily switch to the `nuxt-edge` distribution. Please make this change in package.json:

```diff
{
  "dependencies": {
--    "nuxt": "^2.6.3",
++    "nuxt-edge": "^2.7.0-25959901.0099e9d5`",
  }
}
```

### SSR logs in your browser 🖥️

We all know the `console.log` debugging method, but when working with universal applications, you have to remember that sometimes, your logs are in your terminal and not in your browser console.

This can be really annoying when developing a Nuxt.js application, starting with this version and running `nuxt dev`, the **ssr logs are now reported to your browser console**:

nuxt-logs-ssr

### Detecting `store/` creation 👀

Nuxt.js now detects when you created a `store/` directory and will reload himself auto-magically so you don't have to restart it anymore.

nuxt-store-watch

PS: We also improved the `serverMiddleware` watch to restart Nuxt.js and clean their cache

## Fixes ✔️

- **builder**: corretly detect mode of hashed plugins (#5695)
- **builder**: call `watch:restart` after `watch:fileChanged` hook (#5620)
- **utils**: node v8 not support dotAll in regex (#5608)
- **vue-app**: properly catch component loading error (#5687) (#5688) (#5690)
- **vue-app**: consider `watchQuery` option in `routerViewKey` (#5516)
- **vue-renderer**: await on `spa:templateParams` hook (#5619)
- **webpack**: set log level to warn for `HardSourcePlugin` (#5653)
- **vue-app**: properly catch loading error in component prefetching (#5688) (#5690)
- **vue-app**: avoid using aliases in templates (#5656)
- **builder**: watch store dir and `serverMiddleware` paths (#5681)

## Features 🚀

- **vue-app**: rename `transition` to `pageTransition` and deprecate it (#5558)
- **vue-renderer/vue-app**: report SSR console logs to the browser with consola (#5673)
- **webpack**: suppress not found typescript warnings (#5635)
- **webpack**: extendable `babel.presets` and babel `envName` (#5637)
- configurable aliases (#5655)

## Refactors 🧹

- **server**: exclude dist files request from browser detection (#5571)
- **vue-renderer**: remove chalk in renderer (#5609)
- **vue-renderer**: split renderer into ssr, spa and modern (#5559)
- move modern detection from server to utils (#5584)

## Examples 📚

- **auth-routes:** fix typo (#5651)
- **babel-preset-app:** add `core-js@3` example in the readme (#5633)
- **docker**: fix Dockerfile casing (#5705)

## Typescript 👷

Only for typescript users, Nuxt.js v2.7 [**dropped support for node < 8.6 relate to `ts-loader v6`**](https://github.com/TypeStrong/ts-loader/releases/tag/v6.0.0)

- add babel config types (#5666)
- upgrade ts-loader to v6 (#5691)
- fix `context.app` type (#5701)
- fix `extendRoutes` method type (#5700)
- prevent `ts-node` to register twice (#5699)

## Thanks to 🙏

- Christian Lehr (@clehr)
- Hyunje Jun (@utatti)
- Rafał Chłodnicki (@rchl)
- Yama-Tomo (@Yama-Tomo)
- René Stalder (@renestalder)
- Kohei Ota (@inductor)

### CODE REVIEW

**Comment by kevinmarrec** [comment]
Tested **nuxt-edge@2.7.0-25958473.545afa8d** + **@nuxt/typescript-edge@2.7.0-25958473.545afa8d** against 2 small TS projects, no error or issues detected. Will approve PR when the 3 little pending TypeScript PR's will be merged.

**Review by atinux — APPROVED** [review]

**Comment by dan-gamble** [comment]
> SSR logs in your browser

This is awesome!

Do you think there's any benefit to prefix this with something like `Server: $message`? Might slightly help with debugging if the server slide log just so happens to be different to the client side log.

**Comment by pi0** [comment]
@dan-gamble Indeed it is prefixed with `[NUXT:SSR]`

**Review by kevinmarrec — APPROVED** [review]
Tested one more time a project against **2.7.0-25960330.0099e9d5**, LGTM.

**Comment by Atinux** [comment]
Docs PR: https://github.com/nuxt/docs/pull/1370

**Comment by justindasilva** [comment]
Looks great!

What is the chance of having this feature in an upcoming version: https://cmty.app/nuxt/nuxt.js/issues/c8213

Although useful for my specific case, there are many examples of where such a feature can be quite useful in a Nuxt App.

**Pull request merged**
