### PR TITLE
fix(nuxt): restore static page generation

### LINKED ISSUE #27828: Static routes are no longer rendered in v3.11.0
### Environment

- Operating System: Darwin
- Node Version:     v18.19.0
- Nuxt Version:     3.11.0
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      ssr
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

I can reproduce on a fresh install using SSR from v3.11.0. 

## Reproduce on v3.12.2

```
npx nuxi@latest init reproduce-prerender-routes-error --gitInit=false --packageManager=npm
cd reproduce-prerender-routes-error

mkdir pages
echo "<template>Testing</template>" > pages/testing.vue
echo "export default defineNuxtConfig({
  ssr: false
})" > nuxt.config.ts

npm install
npm run generate
cat .output/public/testing/index.html
```

> cat .output/public/testing/index.html: No such file or directory

## Downgrade to v3.10.3 to resolve

```
npm install nuxt@3.10.3 --save-exact
npm run generate
cat .output/public/testing/index.html
```

> ...(html)...

## Upgrade to next version, v.3.11.0 to reproduce

```
npm install nuxt@3.11.0 --save-exact
npm run generate
cat .output/public/testing/index.html
```
> cat .output/public/testing/index.html: No such file or directory

### Describe the bug

I expect static route generation to create a file for every route. 

I observe that only default routes are being created.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by jdbdnz**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/27828

### 📚 Description

Restores the code to generate static pages which was removed in https://github.com/nuxt/nuxt/pull/26694

My understanding is that PR is concerned with enhancing SSR route prerendering, and it was an error to remove the code for static prerendering of pages.


### Quality Assurance 

I have confirmed using the Playground that it resolves the issue by adding a `pages/testing.vue`, setting `ssr=false`, and running the generate command. 

With this change:
```
pnpm generate
...

ℹ Prerendering 4 initial routes with crawler                                                                                                                                                                                                                                                         nitro 5:59:52 PM
  ├─ /testing (36ms)                                                                                                                                                                                                                                                                                  nitro 5:59:52 PM
  ├─ /index.html (4ms)                                                                                                                                                                                                                                                                                nitro 5:59:52 PM
  ├─ /404.html (5ms)                                                                                                                                                                                                                                                                                  nitro 5:59:52 PM
  ├─ /200.html (6ms)                                                                                                                                                                                                                                                                                  nitro 5:59:52 PM
ℹ Prerendered 4 routes in 0.732 seconds                                                                                                                                                                                                                                                              nitro 5:59:52 PM
```

Without this change:

```
pnpm generate
...
ℹ Initializing prerenderer                                                                                                                                                                                                                                                                           nitro 6:00:47 PM
ℹ Prerendering 3 initial routes with crawler                                                                                                                                                                                                                                                         nitro 6:00:48 PM
  ├─ /index.html (4ms)                                                                                                                                                                                                                                                                                nitro 6:00:48 PM
  ├─ /404.html (5ms)                                                                                                                                                                                                                                                                                  nitro 6:00:48 PM
  ├─ /200.html (32ms)                                                                                                                                                                                                                                                                                 nitro 6:00:48 PM
ℹ Prerendered 3 routes in 0.964 seconds   
```


<!----------------------------------------------------------------------
Before creating the pull request, please make sure you do the following:

- Check that there isn't already a PR that solves the problem the same way. If you find a duplicate, please help us reviewing it.
- Read the contribution docs at https://nuxt.com/docs/community/contribution
- Ensure that PR title follows conventional commits (https://www.conventionalcommits.org)
- Update the corresponding documentation if needed.
- Include relevant tests that fail without this PR but pass with it.

Thank you for contributing to Nuxt!
----------------------------------------------------------------------->

### CODE REVIEW

**Comment by danielroe** [comment]
We are waiting for the next Nitro release to run it fully at runtime (when generating `200.html`).

Let's track in https://github.com/nuxt/nuxt/issues/27694#issuecomment-2187964635. For now you can work around by adding one of your routes to `nitro.prerender.routes` and using this workaround to remove the index route from being generated: https://github.com/nuxt/nuxt/issues/27694#issuecomment-2187482399.

**Comment by jdbdnz** [comment]
Thanks for your hard work and attention @danielroe 

> We are waiting for the next Nitro release to run it fully at runtime (when generating `200.html`).

Can you provide any further details? Do you expect a Nitro release to fix this, are will it introduce a new API you want to wait for before fixing this issue?

> Let's track in [#27694 (comment)](https://github.com/nuxt/nuxt/issues/27694#issuecomment-2187964635). For now you can work around by adding one of your routes to `nitro.prerender.routes` and using this workaround to remove the index route from being generated: [#27694 (comment)](https://github.com/nuxt/nuxt/issues/27694#issuecomment-2187482399).

I see the issues as unrelated (reasoning here https://github.com/nuxt/nuxt/issues/27828). I did attempt your workaround but observed no effect. This matches my expectations since I see no code which processes pages during static generation (why I reintroduced it in this PR).

**Comment by danielroe** [comment]
The next Nitro patch release will include this fix (https://github.com/unjs/nitro/pull/2517) which will enable us to inject with `prerenderRoutes` all of the _actual_ routes used by vue router, so we can get very accurate prerendering.

I expect that release to be very shortly, and I will then implement the logic in Nuxt...

**Comment by jdbdnz** [comment]
> The next Nitro patch release will include this fix ([unjs/nitro#2517](https://github.com/unjs/nitro/pull/2517)) which will enable us to inject with `prerenderRoutes` all of the _actual_ routes used by vue router, so we can get very accurate prerendering.
> 
> I expect that release to be very shortly, and I will then implement the logic in Nuxt...

Oh, ok great. I'm fine to close this PR and wait for a fix using the new feature. 

Can we please reopen https://github.com/nuxt/nuxt/issues/27828 though?

**Pull request closed without merging**
