### PR TITLE
Add components nuxtServerInit hooks on components matched by the route

### PR DESCRIPTION
**Pull request by Pavel-Mishalov**
This hook will be executed when the server is loading the application
and will not be executed when routing in the browser.

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This hook is required to perform actions in the component when the application is first loaded and does not require a call when routing on the client side

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by manniL** [comment]
Hey @Pavel-Mishalov 👋 

Thanks for the PR. I'd probably wait for https://github.com/vuejs/vue/pull/9017 to get merged into Vue so we have that functionality out of the box. 

For now I'd go with:

1. `nuxtServerInit` in the store
2. `asyncData` + `process.server` for page components

**Comment by Pavel-Mishalov** [comment]
Thank @manniL for considering my proposal, I didn’t immediately check option 2 for the idea it should work out accordingly

**Comment by galvez** [comment]
@Atinux @pi0 also agree with @manniL here. Should we close?

@Pavel-Mishalov the problem is that we're likely introducing similar enhancements based on the upcoming `ssrPrefetch` option, so introducing an isolated, stored-specific API for this right now might create a conflict in the near future.

**Comment by pi0** [comment]
@manniL @galvez Thanks for your insights.

@Pavel-Mishalov You contribution is more than appreciated by us. To prevent doing the same thing in a different way I suggest waiting for Vue.js ssrPrefetch.

**Pull request closed without merging**
