### PR TITLE
feat(store): allow a function named 'initialState' to define the state

### LINKED ISSUE #3995: Use initialState instead of state when exporting in modules mode
### What problem does this feature solve?

The issue I've encountered is this:

```js
export const state = () => ({
  someState: 'foo',
});

export const actions = {
  ACTION({ dispatch, commit }) {
    
    // I forgot to destructure state in the function arguments
    // so now I'm accessing the state function by accident

    if (state.something) {
      // .. never true
    }
  }
};
```

### What does the proposed changes look like?

Allow state to be exported as `initialState`:

```js
export const initialState = () => ({
  someState: 'foo',
});

export const actions = {
  ACTION({ dispatch, commit }) {
    
    // Error can now be picked up by ESLint or will 
    // throw an error with state being undefined
  }
};
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7851">#c7851</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by felubra**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
When using the Vuex store in the modules mode, the changes in this PR will allow the state to be defined by a function named 'initialState' instead of 'state' - this resolves #3995.
The existing functionality stays unaltered: Nuxt will first search for a function named 'state', then, if not found, search for the new 'initialState'.

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Comment by galvez** [comment]
@felubra I'm not sure I get this. What's the advantage over `state` and/or `createStore`?

**Comment by aldarund** [comment]
What about case when there both state and initialState will be in code. It wouldnt be obvious which one is used. I think its will be fine to throw error in this case

**Comment by aldarund** [comment]
@galvez read the linked issue https://github.com/nuxt/nuxt.js/issues/3995

**Comment by manniL** [comment]
Good point @aldarund!

**Comment by galvez** [comment]
@manniL @felubra @aldarund I see this as a matter of documentation. Introducing a new non-standard Vuex feature just to catch a programming mistake seems overkill to me.

Please comment @clarkdo @pi0 @Atinux :)

**Comment by felubra** [comment]
Awaiting for you guys ✌

**Comment by galvez** [comment]
@felubra we discussed this in the core team channel and we agreed to open a nuxt/docs PR instead with a hint on how to avoid this error. Actually feel free to do so on our behalf and I'll get it approved right away. Adding this to our docs TODO for now. Thank you!

**Pull request closed without merging**
