### PR TITLE
Add Nuxt + Apollo example

### PR DESCRIPTION
**Pull request by stursby**
- Simple master/detail demo
- Uses the [apollo-client](https://github.com/apollographql/apollo-client) GraphQL client
- Uses [Graphcool](https://www.graph.cool/) as the backend

### CODE REVIEW

**Comment by stursby** [comment]
Yo @Atinux, wondering if you could shed some light on these two failing tests:
- [/404 should display an error too Test finished without running any assertions](https://travis-ci.org/nuxt/nuxt.js/jobs/221067548#L1658) (tried fixing this with #1e56eae by adding a `/layouts/error.vue` but no luck.
- [setAnsiColors](https://travis-ci.org/nuxt/nuxt.js/jobs/221067548#L1668)

**Comment by dohomi** [comment]
@stursby thanks for this example. Two questions though
* why are you not using `vue-apollo` (supposed to be first class citizen for apollo with vue?)
* how to react on interaction on the client side to refetch the query with params

**Comment by stursby** [comment]
@dohomi Well, I was mainly just trying to get a demo working with `apollo-client`, and hadn't even looked into `vue-apollo`, but it looks like `vue-apollo` builds on top of `apollo-client`. And I'm not sure if I fully understand your second question... what do you mean by "how to react..."?

**Comment by dohomi** [comment]
Let's say you have a search text field and want to update the query based on that searchterm variable on the client side. How would you update the query based on the search term variable?

**Comment by stursby** [comment]
@dohomi My demo wasn't intending to have search, and I have not tried to do search yet within GraphQL, so unfortunately I don't have an answer. I'm using [graph.cool(https://www.graph.cool/) as a backend though, and they do offer an [integration with Algolia](https://www.graph.cool/docs/tutorials/algolia-auto-syncing-for-graphql-backends-aroozee9zu/) that would give you robust searching capabilities.

**Comment by dohomi** [comment]
@stursby I do have the same setup. Though I think its a valid use case that users would like to modify the variables on client side, thats why I was asking. For a simple example your use case is good, but as soon the user would like to interact with the received data, I currently don't see how to solve it.

**Comment by Atinux** [comment]
I believe the examples should not be too complicated but you have a point @dohomi 

I will also make an example with vue-apollo soon when Nuxt.js will be compatible (I'm working on it).

@stursby thank you for this example, for the tests, don't worry I am working on them.

Anyway, thank you for contributing to nuxt.js 😄

**Comment by dohomi** [comment]
@Atinux great stuff! From my current experience working with NUXT and vue-apollo for 1 month now:
- client-server hydration breaks quite often
- network-only is the only working fetchPolicy at the moment

It will be great if both packages working hand in hand!

**Comment by Atinux** [comment]
cc @akryum

**Comment by Akryum** [comment]
> client-server hydration breaks quite often
This maybe due to the fact that the apollo cache state is not injected to the client (unless you already did this).

**Comment by dohomi** [comment]
@Akryum thats true.. currently I don't see a way how to do so in `NUXT`. The middleware does not seem to provide a place to set the initial state

**Pull request merged**
