### PR TITLE
docs: include example for server utilities

### PR DESCRIPTION
**Pull request by MSchutt**
### 🔗 Linked issue

https://github.com/nuxt/nuxt/issues/21315

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

I have a use case where I need to encapsulate all responses from each endpoint within an object. This can be achieved by utilizing a server utility. However, it appears that the documentation currently lacks proper explanation of this feature, and it would be beneficial to include a concise example for clarification. (Credits to [@maou-shonen](https://github.com/maou-shonen) for bringing this possibility to my attention, as discussed in this GitHub issue: https://github.com/unjs/h3/issues/397)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — COMMENTED** [review]
I think this is a useful thing to do in your case. Having said that, this is a very specific kind of utility that is probably not relevant for most people - and also potentially quite complex. For example, what does `doSome` look like? How does it handle errors? or null responses?

What do you think about providing a simpler example, such as this kind of thing:

```ts
import { H3Event } from 'h3'

export function getUserSession(event: H3Event) {
  const config = useRuntimeConfig()
  return useSession(event, { password: config.sessionPassword })
}

export function setUserSession(event: H3Event, data: any) {
  const config = useRuntimeConfig()
  return updateSession(event, { password: config.sessionPassword }, data)
}
```

**Comment by MSchutt** [comment]
I would like to draw attention to a valuable and practical aspect: the ability to access the result both before and after the route handler by utilizing server utilities. This feature is commonly found in middleware frameworks like Express or Fastify, but it has not been explicitly documented in Nuxt yet. However, I completely understand and get any concerns you may have. What do you think about this code snippet that gracefully handles errors, encapsulating both the result and the error within objects. I would appreciate your thoughts on it, but maybe even such a use-case might be too specific as server utils are quite powerful. 
Thank you!

```ts [server/utils/handler.ts]
import type { H3Event } from 'h3'
export const defineMyHandler = (handler: (event: H3Event) => any) => {
  const _handler = async (event: H3Event) => {
    try {
      // do something before the route handler
      const response = await handler(event)
      // do something after the route handler
      return { response }
    } catch (err) {
      // Error handling
      return { err }
    }
  }
  return defineEventHandler(_handler)
}
```

**Comment by pi0** [comment]
For having init/once logic for an event handler defenition, we can use `lazyEventHandler` wrapper. It supports both async init and types without need to manually import:


```ts
export default lazyEventHandler(() => {
  // Initial preparation logic
  // Can be async too
  return defineEventHandler((event) => {

  })
})
```

**Comment by danielroe** [comment]
How about this?

```ts
import type { EventHandler } from 'h3'

export const defineWrappedResponseHandler = (handler: EventHandler) =>
  defineEventHandler(async (event) => {
    try {
      // do something before the route handler
      const response = await handler(event)
      // do something after the route handler
      return { response }
    } catch (err) {
      // Error handling
      return { err }
    }
  })
```

**Review by pi0 — APPROVED** [review]
👍🏼 

Worth to note that event handlers with object syntax are coming soon to h3 (with `pre`, `post`, `error` hooks). Once ready we shall update the docs to advice using object composable API over custom wrapper

**Comment by OrlS15** [comment]
> How about this?
> 
> ```ts
> import type { EventHandler } from 'h3'
> 
> export const defineWrappedResponseHandler = (handler: EventHandler) =>
>   defineEventHandler(async (event) => {
>     try {
>       // do something before the route handler
>       const response = await handler(event)
>       // do something after the route handler
>       return { response }
>     } catch (err) {
>       // Error handling
>       return { err }
>     }
>   })
> ```

This isn't typed properly.
Fetching an endpoint with $fetch or useFetch returns wrong type
```ts
let a = $fetch("/api/wrappedEndpoint")
//  let a: Simplify<SerializeObject<{
//     response: any;
//     err?: undefined;
//} > | SerializeObject<{
//     err: unknown;
//     response?: undefined;
// }>>
```
So the editor doesn't give you suggestions when you write a.something

Maybe something like this fixes it?
```ts
export function defineWrappedResponseHandler<T>(handler: EventHandler<T>) : EventHandler<T>
```

**Comment by sutoh** [comment]
I had the same problem, but I found a solution with the following code. I hope this helpful.

```typescript
import { type EventHandler, type H3Event, H3Error } from 'h3'
import { Prisma } from '@prisma/client'

export interface IErrorResponse {
  statusCode: number
  statusMessage?: string
  cause?: any
}

const errorResponse = (
  event: H3Event,
  response: IErrorResponse
): IErrorResponse => {
  event.node.res.statusCode = response.statusCode
  event.node.res.statusMessage = response.statusMessage as string
  return {
    statusCode: response.statusCode,
    statusMessage: response.statusMessage,
    cause: response.cause ? response.cause : null,
  }
}

export const defineWrappedResponseHandler = <T>(
  handler: EventHandler<T>
): EventHandler<T> =>
  defineEventHandler(async (event) => {
    try {
      // do something before the route handler
      const response = await handler(event)
      // do something after the route handler
      return response
    } catch (err) {
      console.error(err)

      // Error handling
      // catch the createError()
      if (err instanceof H3Error) {
        throw errorResponse(event, {
          statusCode: err.statusCode,
          statusMessage: err.statusMessage,
          cause: err.message,
        })
      }

      // Handling Prisma errors
      if (err instanceof Prisma.PrismaClientKnownRequestError) {
        throw errorResponse(event, {
          statusCode: 400,
          statusMessage: 'Bad Request',
          cause: 'Database access error',
        })
      }
      if (err instanceof Prisma.PrismaClientValidationError) {
        throw errorResponse(event, {
          statusCode: 400,
          statusMessage: 'Bad Request',
          cause: 'Database validation error',
        })
      }

      // Handling other errors
      throw errorResponse(event, {
        statusCode: 500,
        statusMessage: 'Internal Server Error',
        cause: 'Unknown error. Please check the server log.',
      })
    }
  })

```

**Pull request merged**
