### PR TITLE
docs: prefer `~` to `@` alias in examples

### PR DESCRIPTION
**Pull request by heyongqi02bot**
### 🔗 Linked issue

The example path on the official website is incorrect, and global style variables cannot be introduced correctly
image

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)

### 📚 Description

Changing @ to~is necessary to correctly implement the introduction.
image

### CODE REVIEW

**Review by atinux — APPROVED** [review]

**Comment by manniL** [comment]
I wonder why as `@` and `~` are both valid aliases by default 🤔

**Review by TheAlexLichter — CHANGES_REQUESTED** [review]
https://stackblitz.com/edit/nuxt-pull-24574?file=app.vue,nuxt.config.ts,assets%2F_var.scss

This works fine for me as documented

**Comment by xxhls** [comment]
It's strange, the bug on my project has also disappeared. Maybe it is better to be correspond with the official document.
image

**Comment by danielroe** [comment]
I personally prefer `~` and it is in general what we document (these are some of the few instances in the docs where we use it), so I think we could merge this anyway, alongside changing:

https://github.com/nuxt/nuxt/blob/a5dad0d2e83323abc2bed7cfe3541f4dbd495335/packages/schema/src/config/app.ts#L277-L280

and

https://github.com/nuxt/nuxt/blob/8af10e459fceec2f2b93cd6223692d1d861bdb2d/docs/1.getting-started/4.styling.md#L212-L238

**Comment by manniL** [comment]
@danielroe Good point with regards to consistency 👍

**Review by danielroe — APPROVED** [review]

**Comment by pi0** [comment]
Adding from history, I also agree about `~` preference over `@` it is much safer in edge-cases where `@` has special meaning in toolings, previously with webpack CSS loader we had some _unresolvable_ issues. I think main reason we first introduced `@` also was ecosystem consistency with vue-CLI also the fact that europian (maybe more?) keyboards have not nice accessibility for typing `~` character as they have for `@`

**Pull request merged**
