### PR TITLE
fix(config): typo in `unsafeInlineCompatibility` name

### PR DESCRIPTION
**Pull request by PedroD**
Replacing all occurrences of `unsafeInlineCompatiblity` to `unsafeInlineCompatibility` (notice the missing "i" in "Compatibility".

## Types of changes
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
**Edit:** Removed the [x] from "Breaking change", as it is now a non-breaking typo fix.

## Description
Just fixing a minor typo that can create confusion when typing this property (correctly) from memory. This can lead to wasted time in debugging a wrong property name.

Replacing all occurrences of `unsafeInlineCompatiblity` to `unsafeInlineCompatibility`.

**Note:** This can cause all apps using the old property name to stop working!

## Checklist:
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly. (PR: https://github.com/nuxt/docs/pull/1650)
- [X] I have added tests to cover my changes (if not applicable, please state why)
- [X] All new and existing tests are passing.

### CODE REVIEW

**Review by clarkdo — COMMENTED** [review]
This is a breaking change for users who are using `unsafeInlineCompatiblity`, we can change it in major release or normalize `unsafeInlineCompatiblity` to `unsafeInlineCompatiblity` with a warning message

**Comment by manniL** [comment]
@PedroD Example how you could do that: https://github.com/nuxt/nuxt.js/pull/4674/files

**Comment by PedroD** [comment]
Ok, allow me some time, I'll try to implement this.

**Comment by PedroD** [comment]
Please take a look if the changes I made are ok.

So Nuxt should allow the usage of both old and new property names. When the developer uses the old name, an alert message appears.

I created tests to make sure both names are supported, thus making this PR non-breaking.

**Review by clarkdo — APPROVED** [review]
LGTM，could you open a pr for changing doc as well? Thanks🙏

**Comment by PedroD** [comment]
@clarkdo I think the doc was already updated accordingly, please take a look here: https://github.com/nuxt/docs/pull/1650

**Comment by clarkdo** [comment]
Great， thanks

**Comment by PedroD** [comment]
Hmmm, there seems to be a linter error on file `examples/with-sockets/io/index.js`

image

This file comes from the merge result (wasn't modified on this PR). Is it an error caused by a previous unrelated commit?

**Comment by PedroD** [comment]
I found that the problematic file comes from this PR (https://github.com/nuxt/nuxt.js/pull/6586).

The linter also failed in there: https://circleci.com/gh/nuxt/nuxt.js/56629?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I can try and fix the issue still on the scope of this PR (if I still have permissions after the merge attempt), or this should be done in the original PR? Or in a new PR at all?

**Comment by clarkdo** [comment]
Fixed

**Pull request merged**
