### PR TITLE
docs: Added additional instructions for server types

### PR DESCRIPTION
**Pull request by victorgarciaesgi**
### 📚 Description

I managed to keep `nuxi typecheck` working by adding this lines to my  root`tsconfig.json`.

### CODE REVIEW

**Review by danielroe — COMMENTED** [review]
If this is a better solution we should update the generated tsconfig instead. (It's already something I'm considering.)

**Comment by victorgarciaesgi** [comment]
Oh yeah I see, that's maybe better than to do it manuelly yeah! Otherwise on server plugin I get typecheck error with vue-tsc

**Comment by danielroe** [comment]
When you do this, does api inference work - e.g. `$fetch('/api/route')` returns correctly value?

**Comment by danielroe** [comment]
> When you do this, does api inference work - e.g. `$fetch('/api/route')` returns correctly value?

checking, this breaks API type inference, so I wouldn't want to recommend it.

But improving the type support for server vs app is an important priority for me now that we have a directory structure in nuxt v4 that is more conducive to it...

**Pull request closed without merging**
