### PR TITLE
feat(router): custom route name splitter

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [X] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

By default Nuxt.js creates the names of the routes with the splitter `-`.
With this PR you can customize.

```js
export default {
  router: {
    routeNameSplitter: '/'
  }
}
```

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [X] I have added tests to cover my changes (if not applicable, please state why)
- [X] All new and existing tests are passing.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

**Review by atinux — APPROVED** [review]

**Comment by Atinux** [comment]
Dammit, it makes me want to add `/` by default now ahah

Great PR @ricardogobbosouza :)

**Comment by ricardogobbosouza** [comment]
Hi @Atinux 
I also think it would be better by default `/`, but many things can break.
Thanks

**Comment by Atinux** [comment]
It will be for Nuxt 3 the default option then :)

**Comment by manniL** [comment]
@ricardogobbosouza can you add docs?

**Comment by ricardogobbosouza** [comment]
@manniL I do not know if it is documented correctly ..

https://github.com/nuxt/docs/pull/1054

**Pull request merged**
