### PR TITLE
fix(vue-app, webpack): remove consola from client

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Fix https://github.com/nuxt/nuxt.js/pull/6298#issuecomment-537563409

~~- Use `consola BrowserReporter` directly which have smaller size and better compatibility~~
~~- Remove unnecessary consoal webpack `alias` config~~
- Remove consola from client side

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by pi0** [comment]
Reporters are not designed to be directly used. Normalization and other logicis happen in core.

**Comment by clarkdo** [comment]
Does client side need normalization since logObj was put from server.

If this way isn’t appropriate, I think we may consider removing consola from client side

**Comment by clarkdo** [comment]
If consola has to be used in client side, we need adding it into babel-loader in dev mode client build, I feel it brings more inconsistencies between dev and prod than it should be

**Comment by pi0** [comment]
I think so :) We don't really need it and brings not much DX

**Comment by clarkdo** [comment]
Great, I’ll change this pr accordingly

**Review by pi0 — APPROVED** [review]

**Pull request merged**
