### PR TITLE
perf(nuxt): render css/inline css higher than resource hints

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

https://github.com/nuxt/nuxt/issues/21784#issuecomment-1607199537

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

As suggested by @prashantpalikhe, this reorders the head tags to prioritise styles over resource hints. I think there's likely some future space for optimisation here, both in unhead and (possibly) in nuxt/bundle-renderer, such as 'splitting up' head metadata to prioritise 'important' meta at top, and defer less important meta after resource hints. (cc: @harlan-zw) Would value thoughts.

Co-authored-by: Prashant Palikhe <prashpal09@gmail.com>

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by c-schwan** [comment]
hi @danielroe 

why not just reorder to prioritise inline styles over resource hints?

https://github.com/nuxt/nuxt/blob/f4be14a38ac530dfd0958567e5baf3b0fdae7830/packages/nuxt/src/core/runtime/nitro/renderer.ts#L320-L322

to 

```
inlinedStyles,
ssrContext.styles,
_rendered.renderStyles()
```

**Comment by danielroe** [comment]
@c-schwan Could you explain more about what you mean?

**Comment by c-schwan** [comment]
> @c-schwan Could you explain more about what you mean?
e.g. Tailwindcss should be added before scoped or style rendered styles

**Comment by danielroe** [comment]
Is that not what this PR does? Are you suggesting a change to this PR?

**Comment by c-schwan** [comment]
> Is that not what this PR does? Are you suggesting a change to this PR?

oh sorry i did look at the changed files. can you merge this pr to master, or is there any timeline for it?

**Comment by danielroe** [comment]
@c-schwan You can now try this out by installing `nuxt@npm:nuxt3@pr-21793`

**Comment by c-schwan** [comment]
> @c-schwan You can now try this out by installing `nuxt@npm:nuxt3@pr-21793`

Thx and happy holidays

**Comment by c-schwan** [comment]
> @c-schwan You can now try this out by installing `nuxt@npm:nuxt3@pr-21793`

hey @danielroe, i just tried out the pr or the latest nuxt edge release but on production build and start i got those error:

```
Error: Cannot find module '/.output/server/node_modules/parse5/dist/cjs/index.js'
...
  at  Object.<anonymous> (.output/server/node_modules/jsdom/lib/jsdom/browser/parser/html.js:3:16
```

is there an issue with nitro?

**Comment by danielroe** [comment]
@harlan-zw do you think we still need something like this now that https://github.com/nuxt/nuxt/pull/22179 is merged?

**Comment by harlan-zw** [comment]
> @harlan-zw do you think we still need something like this now that #22179 is merged?

Afaik the PR being merged won't change the order of the CSS / resource hints, since they are registered in the same order as before.

Unhead won't rearrange any tags except those that need to be in a specific spot to avoid things breaking. 

I think the best fix, for now, is just to move the styles (currently ` // 4. Styles` to before the `// 2. Resource Hints`).

We can't really start applying default sort positions until the rest are set:

**Comment by danielroe** [comment]
Okay, I think the next step is to remove the duplicate link preload that is now _after_ the actual link to the same css file. This can't be necessary or helpful.

**Comment by danielroe** [comment]
~> https://github.com/nuxt-contrib/vue-bundle-renderer/pull/51

**Review by harlan-zw — APPROVED** [review]

**Pull request merged**
