### PR TITLE
fix(builder): call `watch:restart` after `watch:fileChanged` hook

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

@pi0 Should this be deprecacted ? I don't see any doc is refering it.

If there is anyone using it, this may be a slightly breaking change since there is no `builder` as param anymore.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by pi0 — DISMISSED** [review]

**Comment by pi0** [comment]
@clarkdo Yes. Although almost all hooks should be deprecated in flavor on new namespaces with nuxt 3. This may just be annoying for some module users that are using this hook. Not something emergency.

Still if you feel is good to deprecate sooner feel free to merge. But i vote for deprecating all once with a single PR in flavor of better namespaces.

**Comment by clarkdo** [comment]
@pi0 Yes, a separated pr make sense.

**Comment by clarkdo** [comment]
@pi0 I reverted the deprecation change and make hooks run in-order

**Comment by manniL** [comment]
@clarkdo I tried to fix the PR titled ☺️

**Comment by pi0** [comment]
If we allow async watch handlers, promise rejection should be somehow handled. Probably via a console.fatal or error.

**Comment by clarkdo** [comment]
The handler is async now since callHook returns promise, the changing in this pr is just keeping order of the execution.

About the `rejection`, will `restart` hook process it now ?

**Comment by pi0** [comment]
@clarkdo Both previously and now errors was unhandled. It was an enhancenment idea to catch and pipe errors to core/nuxt

**Comment by clarkdo** [comment]
> @clarkdo Both previously and now errors was unhandled. It was an enhancenment idea to catch and pipe errors to core/nuxt

Cool, let me add it

**Comment by pi0** [comment]
@clark right. I didn't remembered that.

**Review by pi0 — APPROVED** [review]

**Pull request merged**
