### PR TITLE
fix(vue-app): Page mount twice

### LINKED ISSUE #10873: Page mounted twice
### Versions

- nuxt: 2.15.8
- node: v14.19.0

### Reproduction

https://codesandbox.io/p/github/Kolobok12309/nuxt-page-layout-mount-twice/draft/stoic-beaver - playground
https://github.com/Kolobok12309/nuxt-page-layout-mount-twice - repo

### Steps to reproduce

1. Config nuxt
```js
// nuxt.config.js
export default {
  features: {
    transitions: false,
  },

  build: {
    splitChunks: {
      layouts: true,
    },
  },
}
```

2. Create 2 layouts and 2 pages
3. Add `console.log('mounted', this.$nuxt.layoutName)` to `mounted` hook of each page
4. Go from one page to another

### What is Expected?

```
// from page-1 to page-2
mounted layout-2
// page-2 to page-1
mounted layout-1
```

### What is actually happening?

```
// from page-1 to page-2
mounted layout-1
mounted layout-2
// page-2 to page-1
mounted layout-2
mounted layout-1
```

### Additional info

If i set `features.transitions: true`, all to be fine, but we can't use it(some problems with meta)

### PR DESCRIPTION
**Pull request by Kolobok12309**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Resolves: #10873 

Split `setLayoutForNextPage` function for two, first `async getLayoutForNextPage` for `beforeResolve` hook(extract layoutName and load layout), and second sync `setLayoutForNextPage` for set page

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by danielroe** [comment]
We're approaching end-of-life for Nuxt v2.

Is this PR still relevant for you?

**Comment by Kolobok12309** [comment]
> We're approaching end-of-life for Nuxt v2.
> 
> Is this PR still relevant for you?

Yea, but we fork repo and already use fork

**Comment by Kolobok12309** [comment]
Nuxt has same error but with error layout, i push our fix in about 7-8 hours

**Comment by Kolobok12309** [comment]
PR with error layout fix
https://github.com/Kolobok12309/nuxt.js/pull/1

**Comment by danielroe** [comment]
Do you want to merge it first, or submit it as a secondary PR?

**Comment by Kolobok12309** [comment]
> Do you want to merge it first, or submit it as a secondary PR?

Better as second and you recheck, it worked for us and tests passed, but...

**Comment by Kolobok12309** [comment]
Create separated pr https://github.com/nuxt/nuxt/pull/27484 for error page

**Review by danielroe — APPROVED** [review]

**Pull request merged**
