### PR TITLE
fix(kit): remove `baseUrl` and use relative paths in tsconfig

### LINKED ISSUE #21827: IDE types are broken after upgrade to 3.6.0 when using Docker (and WSL Webstorm)
### Environment

- Operating System: Linux
- Node Version:     v18.16.1
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.1
- Package Manager:  yarn@3.6.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/daniluk4000/nuxt-3.4.2-docker-error

1. Run `docker-compose up`
2. Open app.vue with IDE and look at the imports
3. Run `sudo yarn dev` (as Docker probably broke file system perms if you are not Mac user)
4. Look at the fixed imports (using VS Code or non-WSL Webstorm)

### Describe the bug

Before Nuxt 3.5.3 update tsconfig paths were generated relatively to current directory

image

But after Nuxt 3.6.0 update it now has absolute paths

image

And breaks IDE as Docker has different folder names inside of it:

image

### Additional context

This also breaks Webstorm when using with WSL, it can't resolve imports as well even without using docker for me.

It would be so good, if this was made for some reason, to optionally opt-out and use relative paths.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/21827

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This finishes work in https://github.com/nuxt/nuxt/pull/21081 and https://github.com/nuxt/nuxt/pull/21632 to remove `baseUrl` and normalise all absolute paths in `include`/`exclude`/`paths` to relative urls.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by daniluk4000** [comment]
Nice!

**Comment by danielroe** [comment]
(Failures are not related to this PR.)

**Comment by danielroe** [comment]
ok, now Elk failure is normal and unrelated to this PR 😆

**Review by pi0 — APPROVED** [review]

**Review by antfu — APPROVED** [review]

**Pull request merged**
