### PR TITLE
loading: add throttle option to skip progress for fast loads

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
## Types of changes

New feature (non-breaking change which adds functionality)

## Description

Loading bars are kind of annoying when they flash without the need. Sites like Medium just don't show it when things load fast.

## Checklist:

- My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
@ishitatsuyuki Seems this has broken E2E tests. Would you please check it up? 

https://circleci.com/gh/nuxt/nuxt.js/756

**Comment by ishitatsuyuki** [comment]
Yes, I'm working on it.

**Comment by ishitatsuyuki** [comment]
Ready.

**Review by galvez — APPROVED** [review]
LGTM

**Comment by pi0** [comment]
@ishitatsuyuki Can't we have tests for it?

**Comment by ishitatsuyuki** [comment]
@pi0 It sounds kinda hard to me. Do you have any idea how should I test it?

**Comment by galvez** [comment]
@pi0 regular loading tests don't seem to break, so that's something.

**Comment by pimlie** [comment]
I would propose to use a render function for `nuxt-loading.vue` like this:
```js
    let el = h(false)
    if (this.show) {
      el = h('div', {
        staticClass: 'nuxt-progress',
        style: {
          'width': this.percent+'%',
          'height': this.height,
          'background-color': this.canSuccess? this.color : this.failedColor,
          'opacity': this.show ? 1 : 0
        }
      })
    }
    return el
...
  methods: {
    start () {
      this.show = true
      
      this.$nextTick(() => {
        this.canSuccess = true
...
```

I think it is in general a better solution to remove the loading div from the DOM unless navigation occurs.

The side effect of this is that for this issue you should be able to listen for DOM insertion using [this trick](https://davidwalsh.name/detect-node-insertion).

```js
// snippet for use in e2e/basic.browser.test.js
...
    page = await browser.page(url('/'))
    await page.exposeFunction('insertNodeTriggered', evt => {
      nodeInserted = true
    })
    await page.evaluate(() => {
      document.addEventListener('animationstart', evt => {
        if (evt.animationName === 'nodeInserted') {
          window.insertNodeTriggered(evt)
        }
      }, false)
    })
```

Disclaimer: I only tested if the separated code snippets worked. So I _guess_ it should work in total as well ;)

**Comment by ishitatsuyuki** [comment]
I don't think you should write E2E tests that tightly relies on the internals. The loading bar is just a decoration, we should test it conservatively.

**Comment by pimlie** [comment]
I am not sure I fully understand what you mean with 'tightly relies on the internals'?

**Review by atinux — APPROVED** [review]
Approved, but E2E tests should be refactored to not depend on loading bar.

**Comment by zerosym** [comment]
@Atinux @pi0 @ishitatsuyuki 

Am I missing something or is this new "option" not really an option?  A 200ms throttle delay is hard coded into the loading component.

This change was merged into 2.0 release without an update to the documentation either, which is a bit frustrating, since it is a noticeable visual change and you have to dig through the issues currently to figure out what happened to the bar.

I appreciate the addition and think it will work out well in the end, but it was unexpected.  In my humble opinion the default should've been to leave the throttle at 0 to maintain previous behavior, with an update to docs explaining how people can opt in.

**Comment by ishitatsuyuki** [comment]
@zerosym It's intended to be configurable from the same "loading" configuration option. If it doesn't work, please tell me.

I'm sorry for the documentation delay and I will find some time to file a PR soon.

**Comment by zerosym** [comment]
@ishitatsuyuki The value is hard coded as 200 here, rather than `<%= loading.throttle %>`

https://github.com/nuxt/nuxt.js/blob/7a68e1dde17e0ed7eb7598d9c63ca1ac2383b76e/lib/app/components/nuxt-loading.vue#L15-L26

**Comment by pimlie** [comment]
@zerosym I noticed that as well and have already added that in #3891 as part of more nuxt-loading changes/refactoring.

**Pull request merged**
