### PR TITLE
refactor: resolve styleResources when not null

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by manniL** [comment]
Not sure if I get this PR right :thinking: 

The warning will be emitted and `styleResources` will be handled anyway (to avoid a breaking change).
Your PR changes that behavior (if `styleResources` are empty) :thinking:

**Review by TheAlexLichter — CHANGES_REQUESTED** [review]
See comment

**Comment by clarkdo** [comment]
If styleResources is undefined or empty，the loop is unnecessary since it just runs an empty look, I think this way is easier to understand and reduce the empty loop

**Comment by clarkdo** [comment]
Got you

**Comment by manniL** [comment]
That should, in theory, never happen. `styleResources` is `{}` by default. The user must have set it to `undefined` or `null` to reproduce this error.

**Review by TheAlexLichter — CHANGES_REQUESTED** [review]
You might want to move the actual loop in the `if` statement and add the or in line 79 instead https://github.com/nuxt/nuxt.js/blob/f60cb39c968ed622fdcaa64fb602fe24df479ad2/packages/webpack/src/builder.js#L79.

**Comment by clarkdo** [comment]
Make sense, close it then

**Pull request closed without merging**
