### PR TITLE
2.15.0

### PR DESCRIPTION
**Pull request by pi0**
### 💡 Highlights

⚠️This release introduces minor breaking changes. Update with caution ⚠️

- Minimum supported Node.js version is 12.0.0 (See https://github.com/nuxt/nuxt.js/issues/8327 for why)
- Using [jiti](https://github.com/nuxt-contrib/jiti) as new require engine with typescript support
- [Plug and play](https://yarnpkg.com/features/pnp) works out of the box
- Allow opting-in to use `postcss@8` (See https://github.com/nuxt/nuxt.js/issues/8546)
- Several encoding issues resolved by consistently using [ufo](https://github.com/nuxt-contrib/ufo)
- [Components ](https://github.com/nuxt/components) updated to v2  (please read [migration guide](https://github.com/nuxt/components#migration-guide))

### 🐛 Bug Fixes

- `general`
  - #8794 Ignore trailing slash in static payloads manifest
  - #8738 Encoding issues with payload paths
  - #8423 `trailingSlash` and child routes not working
- `config`
  - #8778 Prevent invalid css filenames in webpack output
- `utils`
  - #8780 `serializeFunction` fails with certain functions
- `vue-app`
  - #8759 Enable dynamic `publicPath` on server-side
  - #8701 Static payload fetching bugfixes
  - #8612 Check for `Page.options` before looking within
  - #8611 Don't remove `req`, `res` and `query` from context unless in full static mode
  - #8608 Ensure `link.__prefetch` exists before calling it
  - #8596 Add missing `id` attribute to `noopApp`
  - #8557 Scroll-to-top on route changes only
  - #8523 Set `push` on router instance rather than prototype
  - #8486 Do not preserve state when registering client-side dynamic module
  - #8802 Add leading slash for payload hydration
- `server, vue-app`
  - #8748 Address encoding issues with query params
- `dev`
  - #8697 Clearnup vue installed plugins from server in dev mode
  - #8556 Resolve module required by create-require in jiti
- `cli`
  - #8683 Disable parallel build behaviour when generating
- `webpack`
  - #8555 Can't resolve absolute url in css
- `server`
  - #8593 Fix HMR issue with serverMiddleware when `router.base` is set
- `babel`
  - #8545 Enable polyfilling of proposal core-js features
- `vue-app, vue-renderer, utils`
  - #8489 Respect `trailingSlash` setting for payloads
- `generator`
  - #8474 Ensure static manifest dir exists
  - #8803 Normalize trailing slashes before `extendRoutes`

### 🚀 Features

- `cli`
  - #8792 Warn if incompatible node and package versions detected
- `postcss`
  - #8546 Support postcss v8 with explict postcss installation
- `config, vue-app, vue-renderer`
  - #8520 Support dynamic `base` and `publicPath`
- `general`
  - #8389 Support plug-and-play, typescript runtime and native modules
  - #8346 Update all dependencies that require node 10.x
- `vue-app`
  - #8466 Support custom `fetchKey` for full static generation
- `vue-renderer`
  - #8347 Allow adding async attribute to `<script>` tags

### 💅 Refactors

- `utils, vue-app`
  - #8765 Use `ufo` to parse queries and join urls
- `vue-app`
  - #8621 Simplify scrollToTop checking
- `general`
  - Consistent behavior for resolveModule

### 🏡 Chore

- `general`
  - #8440 Fix router base handling with dev-middleware (closes )
  - #8408 Pin css-loader to 4.x
  - #8808 Simplify contributors
- `cli`
  - #8674 Fix typo
- `types`
  - #8630 Lint types
- `builder`
  - Remove validateTemplate check (ed6e8cd307ea21d9f314a88b6d7603b8e40769ea)
- `readme`
  - #8436 Fix invalid links

### 🇹 Types

- #8784 Add missing ssr option to config types
- #8767 `vue.config` types should be optional
- #8530 Add missing `redirect` overload to `Context` interface
- #8638 Add `enablePreview` to context
- #8648 Add missing `loadingScreen` type definition

### 💖 Thanks to

- Alexander Lichter (@manniL)
- Ahad Birang (@farnabaz)
- Beorn Facchini (@beornf)
- Flo Edelmann (@FloEdelmann)
- @gekkedev
- @GeopJr
- @LKHO
- Maarten Van Hoof (@vanhoofmaarten)
- Paulo Amosse Cuambe (@paulocuambe)
- Rafał Chłodnicki (@rchl)
- And all nuxters helping everyday with valuable feedbacks

### CODE REVIEW

**Review by kadirselcuk — APPROVED** [review]

**Comment by frankievx** [comment]
I would be thrilled to see this merged! I'm very interested in using Tailwind 2 with my current Nuxt project.

**Comment by pi0** [comment]
@frankievx You can already beta test final release with `nuxt-edge` package :) We are still checking to ensure there are minimum possible regressions with this release.

**Comment by manniL** [comment]
> 
> 
> I would be thrilled to see this merged! I'm very interested in using Tailwind 2 with my current Nuxt project.

Be aware that you *can* use TW2 already with `nuxt`. More info: https://tailwindcss.nuxtjs.org/setup#tailwind-2

**Review by kadirselcuk — APPROVED** [review]

**Review by kadirselcuk — APPROVED** [review]

**Comment by debs-obrien** [comment]
seem to be having a few issues with loading screen not showing when using this version. One nuxtjs.org it doesn't show the loading screen at all and on debbie.codes I get a minified version of loading screen with just the words loading and not the client and server bundle info. All projects using v2.14 show the loading screen as normal. Can someone else please check on this, thanks. cc @pi0 
Screenshot 2021-01-25 at 12 06 06

**Comment by pi0** [comment]
@debs-obrien Is there an open PR/branch to try? (also would appreciate if can create an issue to track not this PR)

**Comment by debs-obrien** [comment]
Hey sure can open an issue. The nuxt site is live using this version so no open pr as already merged but noticed this today

**Review by clarkdo — APPROVED** [review]

**Review by SNiTEBoBy — APPROVED** [review]

**Review by danielroe — APPROVED** [review]

**Review by SNiTEBoBy — APPROVED** [review]
#8591 
Reviews and change

**Comment by Timkor** [comment]
ETA ??

**Review by kadirselcuk — APPROVED** [review]

**Review by w3bdesign — APPROVED** [review]

**Comment by AlejandroRodarte** [comment]
Thank you so much for the update! One quick question though. Upgrading to this new version broke mi server middleware API. It informs me that I need to install `express` to make it work. Does this mean that ` from now on will not come bundled with `express`?

**Comment by AlejandroRodarte** [comment]
Thank you for the support! One quick question though. I updated my applications from `2.14.12` to `2.15` and my server middlewares suddenly stopped working since the `express` module was not found. Does this means that, from now on, `nuxt` will not come bundled with `express` anymore? Thanks again for your hard work!

**Comment by manniL** [comment]
> 
> 
> Thank you for the support! One quick question though. I updated my applications from `2.14.12` to `2.15` and my server middlewares suddenly stopped working since the `express` module was not found. Does this means that, from now on, `nuxt` will not come bundled with `express` anymore? Thanks again for your hard work!

Nuxt never came with express out of the box. It uses `connect` under the hood (and still does).

**Comment by AlejandroRodarte** [comment]
> > Thank you for the support! One quick question though. I updated my applications from `2.14.12` to `2.15` and my server middlewares suddenly stopped working since the `express` module was not found. Does this means that, from now on, `nuxt` will not come bundled with `express` anymore? Thanks again for your hard work!
> 
> Nuxt never came with express out of the box. It uses `connect` under the hood (and still does).
> If you use express, you should add it to your dependencies :)

I see! I added it now to my dependencies and everything is working as usual. Just found it weird that updating `nuxt` to this version affected my `express` imports. Thank you!

**Pull request merged**
