### PR TITLE
fix(vue-renderer): call `render:resourcesLoaded` hook before `createRenderer`

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Resloves #5960, move hook before renderers creation, provide possibility to change resources at runtime.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]
waiting for CI... thanks :)

**Comment by pi0** [comment]
I was also thinking to make it possible dynamically changing `publicPath` without the hooks hack.

**Comment by clarkdo** [comment]
Function publicPath？

**Comment by pi0** [comment]
@clarkdo no. simply updating the value from loaded config. which can be set differently at production. currently it is loaded from dist manifest.

**Comment by clarkdo** [comment]
Also need a manual updating step at runtime?

**Comment by pi0** [comment]
by nuxt :) WIll create a PR after this :)

**Comment by timmw** [comment]
> I was also thinking to make it possible dynamically changing `publicPath` without the hooks hack.

@pi0 could you ping me when you make this PR. Thanks!

**Comment by gapipro** [comment]
Is changing `publicPath` working only in SSR mode al also somehow in SPA? We are trying to get it to work, but there isn't any effect after this change.

**Comment by clarkdo** [comment]
For spa, since browser has not interaction after first page request, so even you change the publicPath, the client side can't know the changes before a page reload. Could try refreshing the page ? If it still doesn't work, could you provide a repo ?

**Comment by gapipro** [comment]
Well ideally it would be that `publicPath` that is updated in one of the hooks gets injected into final `runtime` bundle. Thats one way.

The other solution would be that Nuxt gets support for `__webpack_public_path__`

**Pull request merged**
