### PR TITLE
docs: add additional example for setting `baseURL` and `cdnURL`

### PR DESCRIPTION
**Pull request by itchina110**
Correct the Example of baseURL and cdnURL

### CODE REVIEW

**Comment by manniL** [comment]
Using environment variables to set these values should work and is correct I think 🤔

**Comment by danielroe** [comment]
The example should be correct. If it is not working for you, would you mind opening an issue with a reproduction? 🙏

**Comment by itchina110** [comment]
As a beginner with Nuxt, I find the documentation at ["Nuxt Configuration"](https://nuxt.com/docs/api/nuxt-config) suggesting configuration in the `nuxt.config.ts` file. However, the examples for `baseURL` and `cdnURL` in the documentation are clearly not suitable for `nuxt.config.ts`. This can be very confusing for beginners. I believe the official documentation should be improved to consider various scenarios and provide clear descriptions.

**Comment by danielroe** [comment]
Understood! I've updated the PR so it adds an extra example rather than removing the one about overriding at runtime.

**Pull request merged**
