### PR TITLE
fix for #1234, order less greedy routes first

### PR DESCRIPTION
**Pull request by pimlie**
As it is possible to use dynamic route matching with nuxt, you can get into problems when you have multiple routes that match the same url. See #1234 for an example case.

The [vue-router documentation](https://router.vuejs.org/en/essentials/dynamic-matching.html) states that:
> Sometimes the same URL may be matched by multiple routes. In such a case the matching priority is determined by the order of route definition: the earlier a route is defined, the higher priority it gets

This commit changes the route sorting behaviour by making sure that less greedy routes are listed _before_ more greedy routes. In this context a less greedy route is defined as having more segments in its path (e.g. `/a/b/c` is less greedy then `/a`)

### CODE REVIEW

**Comment by pimlie** [comment]
CI fails because the order of the routes in `.nuxt/router.js` has changed. If you give this commit your approval I will update the test to reflect the new route orders before merging

**Comment by alexchopin** [comment]
Hi @pimlie, I see what you mean, however, this PR resolve only your use case. (e.g: `/` route will be sorted after `* ` unfortunately)
I'll take a look on it 👍

**Comment by pimlie** [comment]
@alexchopin In my rc3 project the `/` route is still set as the first entry:

```
            {
                        path: "/", 
                        component: _7dcc7ef7,
                        name: "index"
                },
                {
                        path: "/*/p",
                        component: _1f3bd925,
                        name: "all-p",
                        children: [
                                {
                                        path: "*", 
                                        component: _3ffae7f5,
                                        name: "all-p-all"
                                }
                        ]
                },
                {       
                        path: "/disclaimer",
                        component: _50775646,
                        name: "disclaimer"
                },
                {       
                        path: "/blog",
                        component: _c7e6c1e6,
                        children: [
                                {
                                        path: "",
                                        component: _2556e7d0,
                                        name: "blog"
                                },
                                {
                                        path: "*", 
                                        component: _689c5846,
                                        name: "blog-all"
                                }
                        ]
                },
                {       
                        path: "/*",
                        component: _15c1aa07,
                        name: "all"
                }
```

**Comment by alexchopin** [comment]
@pimlie What's happening if you are going to this URL `/blog/p/a`?

**Comment by pimlie** [comment]
Then it indeed goes to the product component and not the blog. 

I rewrote the commit to check for segment length within the for loop, now the following route list is generated:
```
    routes: [
                {
                        path: "/",
                        component: _7dcc7ef7,
                        name: "index"
                },
                {
                        path: "/missie",
                        component: _0ba97ec3,
                        name: "missie"
                },
                {
                        path: "/disclaimer",
                        component: _50775646,
                        name: "disclaimer"
                },
                {
                        path: "/blog",
                        component: _c7e6c1e6,
                        children: [
                                {
                                        path: "",
                                        component: _2556e7d0,
                                        name: "blog"
                                },
                                {
                                        path: "*",
                                        component: _689c5846,
                                        name: "blog-all"
                                }
                        ]
                },
                {
                        path: "/*/p",
                        component: _1f3bd925,
                        name: "all-p",
                        children: [
                                {
                                        path: "*",
                                        component: _3ffae7f5,
                                        name: "all-p-all"
                                }
                        ]
                },
                {
                        path: "/*",
                        component: _15c1aa07,
                        name: "all"
                }
    ],

```

Seems to work better indeed.

**Comment by pimlie** [comment]
@alexchopin Looking at the code a final time, what is exactly the meaning of the following code? 
```js
          if (i === _b.length - 1 && res === 0) {
            res = 1
          }
```

**Comment by Atinux** [comment]
Hi @pimlie 

It was a bit different to make it work, but your issue and PR helped us to update the code to make the fix, thank you!

See the updated tests and code to see the fix: https://github.com/nuxt/nuxt.js/commit/db47df07619e7c99d24518d43b024b6a01e9a169

It will be available soon in `rc5`

**Comment by pimlie** [comment]
@Atinux Thanks, as long as the issue is resolved I am happy :+1:

**Pull request closed without merging**
