### PR TITLE
feat(nuxt): add `appMiddleware` route rule

### LINKED ISSUE #21913: setting nuxt route middleware in `routeRules`
Nuxt currently supports defining global route middleware (with `.global.` suffix) and named route middleware that can be opted-into per-route using `definePageMeta`.

But in some cases there are more complex patterns, where users may want to set middleware for a _group_ of pages or apply a named middleware to the entire site. For example:

- https://github.com/nuxt/nuxt/issues/21454
- https://github.com/nuxt/nuxt/issues/19948

To resolve these issues, we can support a new route rule. Something like:

```ts
export default defineNuxtConfig({
  routeRules: {
    '/**': {
      routeMiddleware: 'auth',
      routeMiddleware: ['auth'],
      // both above are normalised to object syntax, which allows overriding
      // in another more specific route-rule
      routeMiddleware: {
        auth: true
      }
    },
  }
})
```

We're currently thinking about the best name for the rule. I think at the moment `routeMiddleware` makes most sense as we have `defineNuxtRouteMiddleware` but ideas welcome to make it clear that this is only relevant in the Vue part of your app (i.e. not applied to nitro routes).

**Note**: This rule will be possible once https://github.com/nuxt/nuxt/issues/21370 is implemented.

### LINKED ISSUE #26062: fetch manifest returns 404 in dev mode
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.14.1
- Builder:          -
- User Config:      pages, modules
- Runtime Modules:  ()
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-nwqxcj?file=pages%2Findex.vue,app.vue

### Describe the bug

in dev mode, fetching the manifest fails

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by HigherOrderLogic**
### 🔗 Linked issue

Resolves #21913.
closes https://github.com/nuxt/nuxt/pull/26063
fixes https://github.com/nuxt/nuxt/issues/26062

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR add the option to set middlewares in the `routeRules` option in `nuxt.config.ts`.

I'll add docs once the code is finalized.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by HigherOrderLogic** [comment]
I'm clueless about why the test's failing.

I'll look more into it.

**Comment by HigherOrderLogic** [comment]
@danielroe 

Can you help me figure out why the code hang at https://github.com/nuxt/nuxt/pull/25841/files#diff-1a6c0a2ba25b7a4a22ae30ee79885811bf4ae9f99685385027d98ad7584f117bR177? Thanks!

**Comment by danielroe** [comment]
The issue here was that the manifest is emitted in the public directory and isn't actually accessible on the server, just the client.

But in this case we need isomorphic behaviour. So I've updated our manifest utilities to allow that.

I've also made a few more changes in line with what I think you were going for (e.g. the normalised Record, etc.). Also threw in type safety...

**Comment by HigherOrderLogic** [comment]
> see if we can implement in the universal router as well

Since https://github.com/unjs/nitro/blob/7e13a51fe6cf005109fd5ab60015cb1b38380be9/src/prerender.ts#L92-L93 exists, I think it's possible.

**Comment by danielroe** [comment]
sorry for pushing directly!

this is looking good to me - what do you think? 🙏

**Comment by HigherOrderLogic** [comment]
For some reason, I cant get the middleware to run if I am using inline route rules.

<details open>
<summary>Error</summary>
<br>

(This doesnt look related to this PR however)

```bash
 FAIL  test/basic.test.ts [ test/basic.test.ts ]
RollupError: test/fixtures/basic/pages/route-rules/middleware-inline.vue (2:7): "default" is not exported by "test/fixtures/basic/pages/route-rules/middleware-inline.vue?vue&type=script&lang.ts", imported by "test/fixtures/basic/pages/route-rules/middleware-inline.vue".
file: nuxt/test/fixtures/basic/pages/route-rules/middleware-inline.vue:2:7
1: import { PageRouteSymbol as __nuxt_route_symbol } from '#app/components/injections';
2: import _sfc_main from "nuxt/test/fixtures/basic/pages/route-rules/middleware-inline.vue?vue&type=script&l...
          ^
3: export * from "nuxt/test/fixtures/basic/pages/route-rules/middleware-inline.vue?vue&type=script&lang.ts";
4: import { toDisplayString as _toDisplayString, createElementVNode as _createElementVNode, openBlock as _openBlock, cre...
1: import { PageRouteSymbol as __nuxt_route_symbol } from '#app/components/injections';
2: import _sfc_main from "nuxt/test/fixtures/basic/pages/route-rules/middleware-inline.vue?vue&type=script&l...
          ^
3: export * from "nuxt/test/fixtures/basic/pages/route-rules/middleware-inline.vue?vue&type=script&lang.ts";
4: import { toDisplayString as _toDisplayString, createElementVNode as _createElementVNode, openBlock as _openBlock, cre...
```

</details>

Aside from, I think all are good to go.

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
It’s not known 👌

**Comment by victorgarciaesgi** [comment]
Correction we're on `3.11.1`, we'll update to `3.11.2` and keep you updated!

**Pull request merged**
