### PR TITLE
refactor: styleLoader and postcss

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Related to #4313, let's discuss a proper solution @Atinux @pi0 @manniL .

Introduced `order` in `postcss` object config:

```js
postcss: {
  preset: {...},
  plugins: {...},
  order(names, presets) {
    return ...
  }
}
```

`order` supports:

1. Array: the ordered plugins names, `['postcss-import', 'postcss-preset-env', 'cssnano']`
1. String: name of one order preset, 'cssnanoLast' (put `cssnanao` in last), this is the `default` value.
1. Function: parameters are `names(all plugins names)` and `presets(all predefined order presets)`, `order: (names, presets) => presets.cssnanoLast(names)`

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

**Comment by manniL** [comment]
In terms of #4313, we could use a custom `order` function while providing preset (like `cssnanoLast`) 🤔

**Comment by clarkdo** [comment]
@manniL Yep, I'add one.

**Review by TheAlexLichter — APPROVED** [review]
Awesome refactor! 👍

**Review by atinux — APPROVED** [review]

**Review by galvez — APPROVED** [review]

**Comment by manniL** [comment]
@clarkdo Maybe we should push `postcss-preset-env` between the rest and cssnano because it contains autoprefixer :thinking: 

so: `[..., postcss-preset-env, cssnano]`


I know that's already a thing in userland but might be nice to have (if the order has influence on autoprefixing stuff)

**Comment by clarkdo** [comment]
Sorry，which part do you mean？

**Comment by manniL** [comment]
@clarkdo yes, exactly!

**Comment by clarkdo** [comment]
I think it should be forcely put at last only if it depends on all other plugins output， what do you think？

**Comment by manniL** [comment]
@clarkdo well, I think it does as it prefixes the "final" CSS output (with vendor prefixes, e.g. -webkit or -moz or -ms).

And `postcss-preset-env` includes Autoprefixer as stated in https://github.com/csstools/postcss-preset-env#autoprefixer

**Comment by clarkdo** [comment]
Yes, that’s why I removed the explicit autoprefixer in postcss config.
I’ll open a pr tmr, please remind me if I don’t 😅

**Comment by manniL** [comment]
Sure thing! :relaxed:

**Pull request merged**
