### PR TITLE
docs: <script setup> changed to <script setup lang="ts">

### PR DESCRIPTION
**Pull request by shahabbasian**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

due to the:
https://github.com/nuxt/nuxt/pull/22157

lang="ts" By default, it was placed in the content of the document

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by TheAlexLichter — CHANGES_REQUESTED** [review]
Thanks for the contribution! I'd only change it in case we use TS in there though so people could copy and paste it without using TS as well ☺️

**Comment by shahabbasian** [comment]
> Thanks for the contribution! I'd only change it in case we use TS in there though so people could copy and paste it without using TS as well ☺️

Please see the link below:
https://github.com/nuxt/nuxt/pull/22157

**Comment by danielroe** [comment]
Without `lang="ts"` a lot of the magic just won't work. I think it's safe to use even if people aren't writing actual TypeScript. What do you think @manniL?

**Comment by manniL** [comment]
Fair point. Let's stick with it then 👍

**Review by TheAlexLichter — APPROVED** [review]

**Pull request merged**
