### PR TITLE
fix(generator): encode routes and show error summary

### PR DESCRIPTION
**Pull request by pi0**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

- Ensure generated routes are encoded (fs output is decoded) possibly fixing https://github.com/nuxt/nuxt.js/pull/6159#issuecomment-635013365 (reported by @rajesh-h)
- Fix DX issue by displaying an inline summary for handled errors

Before:
image

After:
image

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by atinux — DISMISSED** [review]
Thank you, for so long I was missing the error message 😅

**Comment by rajesh-h** [comment]
Hi Team,

I was unable to try this branch. Am I doing something wrong in my package.json?

Previous line -` "nuxt-edge": "^2.13.0-26509786.618eb5fa",`
I changed it as below
`"nuxt": "nuxt/nuxtjs#fix/static-encode",`

I get below error
```Output:
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.```

**Comment by pi0** [comment]
@rajesh-h Linking monorepo packages should be one by one and needs a build step. I would suggest waiting to merge and test with `nuxt-edge` :) Changes almost done trying to fix tests.

**Comment by rajesh-h** [comment]
> @rajesh-h Linking monorepo packages should be one by one and needs a build step. I would suggest waiting to merge and test with `nuxt-edge` :) Changes almost done trying to fix tests.

@pi0 Thank you very much for this info. I downloaded the latest nuxt-edge and I no more have that weird 404 for payload.js. Things look much better now thanks a lot.

I have observed another issue during generation, as I was not sure where I should be raising the issue I raised it under nuxt/content. https://github.com/nuxt/content/issues/141

**Pull request merged**
