### PR TITLE
docs: add hint for useAsyncData() in local environment

### PR DESCRIPTION
**Pull request by jannescb**
When working with APIs on `localhost` it seems that you have to use real IPs in order to work with `useAsyncData()` in `SSR` mode.
A small hint in the docs might help a lot as it's hard to find any information on this.

### CODE REVIEW

**Comment by oritwoen** [comment]
Thanks for updating the documentation @jannescb . However, for me, even using the IP does not help because it still treats it as part of the nuxt local instance and a internal loop is created.

I had to change /etc/hosts and create `IP -> domain` mask to test local CMS (Strapi or some own system).

It's very problematic. Not sure if it shouldn't be an issue @danielroe ?

**Comment by danielroe** [comment]
Yes, this sounds like a bug; this hint shouldn't be necessary. I would appreciate an issue/reproduction if you can. 🙏

**Comment by danielroe** [comment]
I'm closing this for now as I think this shouldn't be required, but please do create an issue with a reproduction if you can 🙏

Alternatively I think there are some factors developers on Windows might need to know and we could possibly hint about them. (cc: @pi0)

**Comment by oritwoen** [comment]
@danielroe Actually, I haven't noticed this problem lately.

I use Linux every day and the problem probably solved itself when I updated Nuxt or packages and the `/etc/hosts` file.

I can't say now what caused the problem (at least in my case), but I suspect it could be due to a wrong system configuration somewhere.

**Pull request closed without merging**
