### PR TITLE
fix(webpack): resolve consola to latest

### LINKED ISSUE #5721: process is not defined
### Version

[v2.7.0](https://github.com/nuxt.js/releases/tag/v2.7.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js/releases/tag/v2.7.0](https://github.com/nuxt/nuxt.js/releases/tag/v2.7.0)

### Steps to reproduce

- `npm up` to upgrade to nuxt 2.7.0
- have `"@nuxtjs/dotenv": "^1.3.0",` as dep in your project
- have `require('dotenv').config();` in your `nuxt.config.js` file

try to use `process.env` variables in your nuxt.config.js, and it'll throw a error

### What is expected ?

Ability to access .env variables inside the nuxt app

### What is actually happening?

Nuxt app breaks down squawking about the `process` error

### Additional comments?

Screenshot from @cannap on Discord
unknown

Screenshot from me:
Screenshot 2019-05-14 at 6 30 52 PM

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9208">#c9208</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by clarkdo**
Fix #5721 
Fix nuxt-community/auth-module#348

### CODE REVIEW

**Comment by clarkdo** [comment]
@pi0 Will consola change it in future ?

**Comment by pi0** [comment]
@clarkdo We keep this dist path consistent :)

**Review by pi0 — DISMISSED** [review]

**Comment by clarkdo** [comment]
@pi0 Changed. For `server`, if any code is using incompatible api between v1 and v2, it may still have error in SSR

**Comment by pi0** [comment]
@clarkdo for node, it won't and is guarded here: https://github.com/nuxt/consola/blob/master/src/node.js#L31

For browser, we should add this guard :)

**Comment by clarkdo** [comment]
But SSR will be run in different context

**Comment by pi0** [comment]
@clarkdo better idea :+1:

**Review by pi0 — APPROVED** [review]

**Pull request merged**
