### PR TITLE
Store directory structure changes (2)

### PR DESCRIPTION
**Pull request by galvez**
Picking up on [another abandoned PR](https://github.com/nuxt/nuxt.js/pull/2733/files)

### CODE REVIEW

**Comment by husayt** [comment]
I think it would be a nice addition for ver 2.0

thanks @galvez  and @airjp73

**Comment by pbastowski** [comment]
This sounds interesting. Is there an issue or any documentation at all that describes this change/improvement?

**Comment by manniL** [comment]
@pbastowski I guess @galvez will come up with a doc-PR soon :relaxed:

**Comment by pbastowski** [comment]
I just saw Nuxt 2 got released. So, is the documentation for the above changes already included in the online docs?

**Comment by manniL** [comment]
@pbastowski Should be included (see https://github.com/nuxt/docs/commit/2c1cdcf2d81261c8460255251ff1ab92f5098a45)

**Comment by pbastowski** [comment]
Thanks

**Pull request merged**
