### PR TITLE
Offline plugin integration

### PR DESCRIPTION
**Pull request by rohitcelestial**
I know NUXT aims to provide PWA out of the box, so just to start things in that direction, I have added integration for [offline-plugin](https://www.npmjs.com/package/offline-plugin).

image

Functionality will be configurable through nuxt config

**nuxt.config.js**
```
module.exports = {
  offline: true, // true or https://github.com/NekR/offline-plugin/blob/master/docs/options.md
  plugins: ['~plugins/init-offline.js']
}
```

Service Workers requires to be installed in root directory, so they will be available in static directory after thing config instead of _nuxt directory. Also, appcache will be available as well.

**init-offline.js**
Add service worker registration here or back  up
```
if (process.BROWSER_BUILD && process.env.NODE_ENV === 'production') {
  require('offline-plugin/runtime').install()
  // register service worker here
}

```

### CODE REVIEW

**Comment by sebastianmacias** [comment]
Thanks writing this integration. I look forward to testing it soon.

**Comment by Atinux** [comment]
Since a lot of changes has been made for the `0.10`, I will take a look at it after the release.

Thank you for your hard work @rohitpal99

**Comment by qm3ster** [comment]
I took a look at the CI and it seems it is just nyc@10.1.2>istanbul-lib-hook@1.0.0>append-transform@0.4.0 using new declaration syntax without --use_strict on old node versions.
For some reason the current master build which also requires append-transform@0.4.0 runs fine on those old node versions.
Can someone rerun the Travis?

**Comment by Atinux** [comment]
I merged it, will make few changes to make it easier to use it with Nuxt.js and make a new release soon 👍

**Pull request merged**
