### PR TITLE
add component options to context

### PR DESCRIPTION
**Pull request by cj**

### CODE REVIEW

**Comment by Atinux** [comment]
Hi @cj 

I'm not sure to see the interest here, but you can easily do it by adding a global middleware which add the route component directly inside the context :)

**Comment by cj** [comment]
@Atinux I found I needed to access the component options for a custom plugin so that I could programmatically fetch if needed.



I'm happy with adding a middleware to do that, would you be able to give me a quick example?  cheers!

**Comment by cj** [comment]
ah, I see you can access it via `route.matched[0].components.default`.  I guess I'll just do that for now then, I still think it would be nice to have access to the component directly in `context` :)

**Comment by Atinux** [comment]
I see, something that will have more sense will be to call asyncData & fetch with Component.options as context (like: `fetch.call(Component.options, context)`)

**Pull request closed without merging**
