### PR TITLE
feat(webpack): use `vue-meta` browser build for client bundle

### PR DESCRIPTION
**Pull request by pimlie**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Similar to consola, explicitly using the vue-meta browser dist for client builds saves ~1.5KB in bundle size

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by clarkdo — APPROVED** [review]

**Comment by husayt** [comment]
@pi0, After this change I am getting error:

> This vue app/component has no vue-meta configuration

**Comment by pimlie** [comment]
@husayt Thanks for the report, could you please share your config / reproduction?

That message should only be printed when initialization of vue-meta failed but a refresh of the meta-info is still called: https://github.com/nuxt/vue-meta/blob/master/src/client/refresh.js#L24

**Comment by husayt** [comment]
I have rolled back on that project to before the change. Will try to reproduce on a fresh project and share. General config wise it's a generate only  SPA with modern mode set  to client.

**Comment by kevinmarrec** [comment]
@pimlie Reproduction :
```
git clone https://github.com/nuxt-community/vuetify-module
yarn
yarn dev
```

**Comment by frck006** [comment]
Since Nuxt 2.10.0, and @nuxtjs/vuetify@1.9.0, Vuetify doesn't work.

In Vuetify, file:/services/theme/index.ts, the method "initVueMeta()" uses "root.$meta()" which returns object with "options" to "undefined"
After, meta.getOptions().keyName throw an exception.

**Comment by pimlie** [comment]
@frck006 thanks but see the vuetify issue that was linked 2 hrs ago

**Comment by frck006** [comment]
Yes I see: https://github.com/vuetifyjs/vuetify/issues/9181
Thanks

**Pull request merged**
