### PR TITLE
fix: properly serialize undefined in vuex store

### LINKED ISSUE #3825: Computed value that depends on a state in Vuex store with initial value 'undefined' lose reactivity
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/bingtimren/nuxt-store-state-undefined-bug](https://github.com/bingtimren/nuxt-store-state-undefined-bug)

### Steps to reproduce

`npm run dev`

Goto http://localhost:3000, then

Open Vue tools, switch to Vuex tab, find Base State has states "counter" and "message1", but "message2" is missing.

Click "Increase", watch mutations. Although "message2" appears in state, the computed value "messages2" has no reactivity.

I first thought this might be a Vuex bug, but I tested the same and found Vuex works just fine. See https://jsfiddle.net/n9jmu5v7/22559/

### What is expected ?

In my store/index.js, I have 

```
export const state = () => ({
  counter: 0,
  message1: "",
  message2: undefined
})
```

In my page, I have computed values that maps to the states:

```  
computed: {
    ...mapState({
      counter:'counter',
      message1:'message1',
      message2:'message2'
    }),
  },
```

Both computed values "message1" and "message2" should be reactive. 

### What is actually happening?

"message2" lost reactivity because the initial value is "undefined"

This problem relates to Nuxt. Vuex works just fine. See https://jsfiddle.net/n9jmu5v7/22559/

### Additional comments?

It seems the cause of the problem is that in the Base State (the initial Vuex store state), "message2" is missing because its initial value is undefined. Due to this reason, the computed value "message2" does not link its dependency to this state and lost reactivity.

Also this is not a Vuex problem as shown in the above mentioned fiddle.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7661">#c7661</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by aldarund**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Resolves #3825
serialize-javascript dont serialize undefined values.
https://github.com/yahoo/serialize-javascript/issues/35
This PR use https://github.com/Rich-Harris/devalue for json serialization instead. JSON.stringify not used to avoid XSS

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by manniL** [comment]
Thanks for you effort @aldarund ☺️ 

If `devalue` provides more value *(no pun intended)* and is a drop-in replacement for `serialize-javascript` I'd advocate to fully replace `serialize-javascript` with it.

* No inconsistencies
* Better support of common structures
  * Map
  * Set
  * undefined
  * cyclical references,
  * repeated references

**Comment by manniL** [comment]
We should also keep in mind that `devalue` **does not** support function serialization and has no plan to add this.

**Comment by aldarund** [comment]
@manniL i did replaced serialize-javascripteverywhere where it was used for json. As i see in other places it is used for javascript serialization ( at least calls to serialize-javascript dont have isJson argument) so it probably cant be replaced entirely

**Comment by Atinux** [comment]
Could you fix conflicts @aldarund ?

**Comment by aldarund** [comment]
conflicts fixed

**Review by TheAlexLichter — APPROVED** [review]

**Review by galvez — APPROVED** [review]

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Waiting to CI passing :)

**Comment by appinteractive** [comment]
Hey the new option kills all methods (like formatters for tables) when serializing. That’s intended right?

**Comment by aldarund** [comment]
@appinteractive not quite follow. What u do mean by methods? Functions? If functions they were killed before as well
See here 
https://runkit.com/5baa3cac92a46f00121e2985/5babafa1191da800121dc83f

**Comment by benfavre** [comment]
Getting isues with this now.

✖ error NuxtServerError: Cannot stringify a function
  at walk (xxx/node_modules/devalue/dist/devalue.umd.js:16:19)
  at xxx/node_modules/devalue/dist/devalue.umd.js:49:72
  at Array.forEach (<anonymous>)
  at walk (xxx/node_modules/devalue/dist/devalue.umd.js:49:40)
  at xxx/node_modules/devalue/dist/devalue.umd.js:49:72
  at Array.forEach (<anonymous>)
  at walk (xxx/node_modules/devalue/dist/devalue.umd.js:49:40)
  at xxx/node_modules/devalue/dist/devalue.umd.js:49:72
  at Array.forEach (<anonymous>)
  at walk (xxx/node_modules/devalue/dist/devalue.umd.js:49:40)
  at devalue (xxx/node_modules/devalue/dist/devalue.umd.js:53:5)
  at Renderer.renderRoute (xxx/node_modules/nuxt/dist/nuxt.js:2042:50)
  at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by manniL** [comment]
@benfavre can you provide us your state? Likely there is a function inside

**Comment by benfavre** [comment]
image

**Comment by benfavre** [comment]
i18n issues again ...👎

**Comment by manniL** [comment]
@benfavre Could you open up an issue [here](https://cmty.app/nuxt/issues/new?repo=nuxt-i18n) ?

**Comment by manniL** [comment]
@benfavre According to [the source code](https://github.com/nuxt-community/nuxt-i18n/blob/64794d6fa923fc52ccb83a1148f1087e00071665/src/helpers/utils.js#L131) messages should never be a function, only an object 🤔

**Comment by benfavre** [comment]
This is because I use the Lazy option.
https://nuxt-community.github.io/nuxt-i18n/lazy-load-translations.html

**Comment by manniL** [comment]
@benfavre But even with `lazy` it should `await` the promise properly ([source](https://github.com/nuxt-community/nuxt-i18n/blob/master/src/plugins/main.js#L81))

**Comment by benfavre** [comment]
apparently not, nothing special in my lang files

image

image

image

**Comment by manniL** [comment]
Weird. Could you open up a new issue with reproduction as request ([here](https://github.com/nuxt/nuxt.js/pull/3913#issuecomment-425890522))? Let's continue the discussion there.

**Comment by benfavre** [comment]
https://cmty.app needs forces a repro link ... randomly pasted jsfiddle (probably going to get many of theses)

**Comment by vhf** [comment]
I think this should have been a breaking change, I rolled back to `nuxt<2.1.0` because my project throws `Cannot stringify arbitrary non-POJOs` from `devalue` now. ;)

Repro is basically this: https://github.com/Rich-Harris/devalue/blob/d73708c51f70bf9b962103976b44e782b1e3a068/test/test.ts#L89-L93 , putting `foo` in nuxt's vuex store.

(Just a heads up, I'm not complaining, thanks for the awesome work!)

**Comment by manniL** [comment]
@vhf We are working on replacing the error with "just" a warning to revert the breaking change.

**Pull request merged**
