### PR TITLE
refactor(core): use hable

### PR DESCRIPTION
**Pull request by pi0**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

[jsless/hable](https://github.com/jsless/hable) is an extraction of our internal hooks implementation with the same tests and features. Pros of externalizing:
- Easier maintenance
- Using a consistent solution across different areas (I'm making a PR for using hooks in cli for example)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by pimlie** [comment]
Hable & Hookable dont have a fully similar interface and implementation

**Comment by pi0** [comment]
@pimlie hmm I'm not sure. Can you please elaborate more about differences and potentially missing requirements?

PS: Failing test is because hable uses its own consola instance. I'll work on an option to provide custom logger.

**Review by atinux — DISMISSED** [review]
YES!

**Review by clarkdo — DISMISSED** [review]
LGTM

**Review by pimlie — DISMISSED** [review]
Hookable:
+ flatHooks as instance method (probable safe to remove though, but who knows)
+ filter(Boolean) in addHooks

Hable:
+ deprecateHook

When moving to Hable, Nuxt should use the `deprecateHook` method instead of setting the prop directly.

Hable will add _falsy_ hooks in addHooks / flatHooks util. Actually it will also add all other non-function hooks, but thats also the case with Hookable.

**Comment by pi0** [comment]
> flatHooks as an instance method (probable safe to remove though, but who knows)

This is an internal utility. So I think it is safe to not include instance.

> deprecateHook

Yeah. That's an addition of hable that we can leverage :) I'll refactor to use it.

> filter(Boolean) in addHooks

Main [hook](https://github.com/jsless/hable/blob/v2.1.0/lib/hookable.js#L14) function which is called by addHooks already prevents adding falsy hooks.

**Review by pimlie — APPROVED** [review]

**Pull request merged**
