### PR TITLE
fix(nuxt): use static nitro build if possible

### LINKED ISSUE #638: images return 404 when using `nuxt generate` + vercel preset
Using nuxt-img with local images and they dont seem to work when the pages are prerendered. They throw a 404 error.
Screenshot2022-10-29 at 21 23 51@2x

The images are displayed locally in dev environment. 
image

Reproduction - https://github.com/fayazara/nuxt-image-issue-reproduction

Deployed on Vercel - https://nuxt-image-issue-reproduction.vercel.app/
Deployed on Netlify - https://wondrous-medovik-574c06.netlify.app/

A remote image URL work btw. Happens only with local static images. 

Build command was set to `yarn generate`

### LINKED ISSUE #757: `nuxt generate` Does Not Generate Transformed Images When Deployed On Vercel
I am hosting my Nuxt project on Vercel, and using `nuxt generate` to create a static build. This works as expected on my machine, but on the Vercel deployment, no images are generated. The original files are available under their respective URL, but any transformed versions, which should be generated by the image module and available under a URL like `/_vercel/image?url=/images/example.jpg&w=1280&q=100` simply do not exist.

I searched online for this problem, but the only thing I found was [this issue](https://github.com/nuxt/image/issues/215) from 2021, which describes - as far as I can tell - the same problem, but with Nuxt 2 and Nuxt Image < 1.0, which does not help me very much.

I have a completely empty image configuration and no route specific rendering rules. Using `nuxt build` works perfectly fine, and - as I said - `nuxt generate` does work on my machine. It just does not work when deployed on Vercel.

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/image/issues/757
resolves https://github.com/nuxt/image/issues/638

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This will enable automatically using new nitro static presets with platform support.

**Waiting for:**
- [x] https://github.com/unjs/nitro/pull/1324
- [x] new nitro release

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]
LGTM 💯  (i think we can merge this and try integration with nitro/nuxt edge)

**Comment by danielroe** [comment]
You can go ahead and install `nuxt@npm:nuxt3@pr-21655` to try on edge - testing on Vercel, it resolved linked issues 🥳

**Pull request merged**
