### PR TITLE
feat(nuxt): add `pages:routerOptions` hook

### LINKED ISSUE #24141: hook to allow module authors to add additional `router.options` files
`pages:routerOptions`? (suggested by @pi0)

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/24141

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds a new hook: `pages:routerOptions`. It allows modifying the detected `app/router.options.ts` files from layers, as well as adding new router options (for example, from a module).

If `optional: true` is set, then this will not force pages integration. (Which is ideal for a custom scroll behaviour, for example.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by atinux — APPROVED** [review]

**Comment by danielroe** [comment]
I think we probably do need to keep calling this within the template (or update it manually when watched paths are detected) or we won't have updates when user adds/removes an `app/router.options.ts`.

**Comment by Atinux** [comment]
Makes sense, reverted :)

**Pull request merged**
