### PR TITLE
feat(builder): backport --no-generate option for spa build to 1.x versions

### PR DESCRIPTION
**Pull request by maxma241**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] mini change for Nuxt command with v1.x

## Description

add new option `nuxt build --no-generate` for SPA mode
I saw v2.x has this option for SPA mode without generate `./dist/**` files.
my projects use `v1.4.2`, and customize an express server with TypeScript.
If I upgrade to `v2.x`, I need to refactor too many files.
(I use SPA mode, and do not need .html files. want to build faster)
So, I refer `nuxt-build` of v2.x to make this change.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]
LGTM

**Comment by pi0** [comment]
@pimlie Would you please check the last failing test? It complains about this test:

```
basic.dev › /stateless

/usr/src/app/test/basic.dev.test.js:51
```

It seems spies are not working for this specific test

**Comment by pimlie** [comment]
That was caused by this fix: https://github.com/vuejs/vue/issues/7565

If you add a `await Utils.waitFor(5)` just after `renderAndGetWindow` it should work again.

**Comment by pi0** [comment]
Now is available in [v1.4.4](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.4).

**Pull request merged**
