### PR TITLE
fix(nuxt): correctly move v-if from slot to wrapper component

### LINKED ISSUE #26361: Setting `selectiveClient: 'deep'` breaks components with conditional slots
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.0
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      experimental
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-romtaf

### Describe the bug

Setting `componentIslands.selectiveClient` to `deep` currently breaks things like conditionally rendered slots because the transform isn't handling directives properly. It's transforming `v-if="foo"` to ``:props="[{ v-if: `foo` }]"``

### Additional context

Also, if I refactor to template + v-if + slot (https://stackblitz.com/edit/github-romtaf-cwixc1), I'm getting warnings like ` WARN  [Vue warn]: Extraneous non-props attributes (data-v-875a1e80) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.` However, there is no warning if I don't enable that option.

### Logs

```
[vite-node] [plugin:vite:vue] [SyntaxError] ./components/Foo.vue:6:0

<script setup lang="ts">
import { vforToArray as __vforToArray } from '#app/components/utils'
import NuxtTeleportIslandComponent from '#app/components/nuxt-teleport-island-component'
import NuxtTeleportSsrSlot from '#app/components/nuxt-teleport-island-slot'
const foo = true;
</script>

<template>
  <NuxtTeleportSsrSlot name="default" :props="[{ v-if: `foo` }]"><slot v-if="foo" /></NuxtTeleportSsrSlot>
</template>
```

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue

fix #26361 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Hi :wave: this fix a bug where v-if are not correctly moved from the slot to the wrapper component

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by brc-dd** [comment]
There might be cases like v-else-if or v-show too. Is there some generic way to solve this instead of having to list out each directive manually? 👀 

Also, I believe `getPropsToString` in islandsTransform doesn't handle props with hyphen properly:

```
getPropsToString({'foo-bar': 'baz'}) // [{ foo-bar: `bar` }]"
```

which is invalid JS.

**Comment by huang-julien** [comment]
indeed thank you ! I'm currently working on changing the way slots and client works internally to make this work for non-SFC too.

For now I think we only need to extract a few directive, I believe we still want to leave directive on the component (other than v-if/else/elseif)

**Comment by brc-dd** [comment]
> Also, I believe getPropsToString in islandsTransform.ts doesn't handle props with hyphen properly:

This is still not fixed. Or is it guaranteed that the passed bindings won't contain any name having any character other than :a-zA-Z 👀  If not then something like this at line 162 of `packages/nuxt/src/components/islandsTransform.ts` might be better:

```ts
  const content = Object.entries(bindings).filter(b => b[0] && b[0] !== '_bind').map(([name, value]) => isBinding(name) ? `[\`${name.slice(1)}\`]: ${value}` : `[\`${name}\`]: \`${value}\``).join(',')
```

**Comment by huang-julien** [comment]
oops sorry, i completly forgot about that ! thanks !

**Review by danielroe — APPROVED** [review]

**Pull request merged**
