### PR TITLE
feat(nuxt): warn when accessing private runtimeConfig on client

### PR DESCRIPTION
**Pull request by nopeless**
### 🔗 Linked issue

None

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

I wasted a bit too much time having trouble why server hydration and client view was different until I realized that I was accessing `useRuntimeConfig().<some prop>` in client as well. This would prevent future issues like that

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — COMMENTED** [review]
I think this is a great idea! Thank you ❤️ 

However, I think as written it will warn when these keys are accessed on server side as well given that we are manipulating the config within the SSR renderer.

Maybe just warn on client side? (We could add the guard within the `import.meta.client` block within `app/nuxt`.)

**Comment by nopeless** [comment]
> I think this is a great idea! Thank you ❤️ 
> 
> However, I think as written it will warn when these keys are accessed on server side as well given that we are manipulating the config within the SSR renderer.
> 
> Maybe just warn on client side? (We could add the guard within the `import.meta.client` block within `app/nuxt`.)

SSR context is untouched. In fact, it exposes even more properties, specifically .nitro (which in my opinion makes more sense, let me know if this behaviour is not what you want)

only SPA context is altered

**Comment by nopeless** [comment]
bump

**Comment by danielroe** [comment]
(This PR is waiting for a minor release - probably Nuxt v3.12.)

**Review by danielroe — APPROVED** [review]

**Pull request merged**
