### PR TITLE
fix(types): import `Location` from `vue-router`

### PR DESCRIPTION
**Pull request by h-kishi**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Fixed `vue-router`'s `Location` type was not imported and global `Location` type was used for `redirect` argument type.

https://github.com/nuxt/nuxt/blob/2.x/packages/types/app/index.d.ts#L60-L61

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
Thanks!

**Comment by tjhiggins** [comment]
Having an issue now with the redirect type not supporting another route:
image

**Comment by danielroe** [comment]
It should already be published.

**Comment by tjhiggins** [comment]
> It should already be published.

My bad. For whatever reason it didn't show up when I ran `npm outdated`, but I see on npm page. Thanks.

**Comment by blimmer** [comment]
I was also confused about the type packages not being published - it looks like they're not being marked as `latest` anymore, so tools like `npm outdated`, `npm-check-updates`, `yarn upgrade-interactive`, etc. don't show an upgrade past 2.16.0 as available.

Screenshot 2023-03-13 at 18 09 12

Since v3 doesn't require the types package, could we keep publishing types for 2.x as `latest`?

**Comment by danielroe** [comment]
Indeed. That's already been fixed in the release script and the next version will be tagged as latest.

**Pull request merged**
