### PR TITLE
fix(cli): initialize server for build when there pages should be gene…

### LINKED ISSUE #6519: nuxt build fails with spa mode
### Version

[v2.10.0](https://github.com/nuxt.js/releases/tag/v2.10.0)

### Reproduction link

[https://github.com/vinayakkulkarni/nuxt-2.10-bug](https://github.com/vinayakkulkarni/nuxt-2.10-bug)

### Steps to reproduce

npm install
npm run build

### What is expected ?

Nuxt to build all routes and files post build success. 

### What is actually happening?

```
ℹ Generating pages                                                                                                                                                                                  18:52:53

 ERROR   /                                                                                                                                                                                          18:52:53

TypeError: Cannot read property 'renderRoute' of undefined
    at Generator.generateRoute (/Users/vinayak/Development/Personal/nuxt/nuxt-2.10-bug/node_modules/@nuxt/generator/dist/generator.js:222:42)
    at /Users/vinayak/Development/Personal/nuxt/nuxt-2.10-bug/node_modules/@nuxt/generator/dist/generator.js:120:24
    at async Promise.all (index 0)
    at async Generator.generateRoutes (/Users/vinayak/Development/Personal/nuxt/nuxt-2.10-bug/node_modules/@nuxt/generator/dist/generator.js:115:7)
    at async Generator.generate (/Users/vinayak/Development/Personal/nuxt/nuxt-2.10-bug/node_modules/@nuxt/generator/dist/generator.js:48:20)
    at async Object.run (/Users/vinayak/Development/Personal/nuxt/nuxt-2.10-bug/node_modules/@nuxt/cli/dist/cli-build.js:101:5)
    at async NuxtCommand.run (/Users/vinayak/Development/Personal/nuxt/nuxt-2.10-bug/node_modules/@nuxt/cli/dist/cli-command.js:2575:7)


 FATAL  Cannot read property 'renderRoute' of undefined                                                                                                                                             18:52:53

  at Generator.afterGenerate (node_modules/@nuxt/generator/dist/generator.js:168:43)
  at async Generator.generate (node_modules/@nuxt/generator/dist/generator.js:50:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:101:5)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-command.js:2575:7)


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │   ✖ Nuxt Fatal Error                                           │
   │                                                                │
   │   TypeError: Cannot read property 'renderRoute' of undefined   │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuxt-2.10-bug@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuxt-2.10-bug@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vinayak/.npm/_logs/2019-10-06T13_22_53_417Z-debug.log
```

### Additional comments?

Related issues: #6500, #6513 & #6514

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9867">#c9867</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by aldarund**
…rated

fixes #6519

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
In spa mode we need to generate page, so hence need server to be initialized

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x ] All new and existing tests are passing.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

**Comment by clarkdo** [comment]
Initialise server in build will affect some functionalities which depend on runtime.

For example, `modern` will be detected at runtime and changed to `false`, so the modern build won't be triggered if you build more than once, and this issue was raised by @aldarund before.

**Comment by clarkdo** [comment]
Initialise server in build will affect some functionalities which depend on runtime.

For example, `modern` will be detected at runtime and changed to `false`, so the modern build won't be triggered if you build more than once, and this issue was raised by @aldarund before.

Currently only enable it for generate should be safe, but maybe we can improve it in next minor release, like initialising server lazily just before rendering, the the building phase won't be affected.

**Comment by pi0** [comment]
Thanks @clarkdo for clarifications. Can we probably keep an open issue for improvements?

**Comment by clarkdo** [comment]
https://github.com/nuxt/nuxt.js/issues/6531

**Pull request merged**
