### PR TITLE
feat: support root components outside layout

### LINKED ISSUE #7753: Components into root element
Initially, i just needed simple toast, i'm thinking how it would be working in another layouts. The first thing came up with the idea to use `Vuex` and place component(list with toasts) in all layout. The idea in itself is not very good, it was also aggravated by the fact that when changing the `layout`, a rerender takes place. After this i check `vue-toasted` source, [link](https://github.com/ankurk91/vue-toast-notification/blob/master/src/js/api.js#L16) nice idea, i try use it, but some components in my toast use `vuex` and i can`t remove it

After this attempts i found #2603 issue, this my problem yeah... without solution

Please add some api for use global(between layouts and outside router-view) components it be usefull for modals, toasts etc

image

P.S. Why `nuxt.config.js` `build.template` not mentioned anywhere?) Found it late, but it's too complicated for me)

### PR DESCRIPTION
**Pull request by Kolobok12309**
Now it's impossible to add component which not rerender when change layout

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
With this prop in config we can add components under root nuxt instance like this
image

Resolves: #7753, #2603
`nuxt.config.js`
### Array variant
```js
  ...
  rootComponents: [
    '@/components/global.vue',
  ],
  ...
```
### Object variant
```js
  ...
  rootComponents: {
    global: '@/components/global.vue',
  },
  ...
```

And use it in components
```js
{
  methods: {
    method() {
      const { global } = this.$nuxt.$rootComponents;
      if (global) {
        global.someMethod();
      }
    }
  }
}
```

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly. (PR: nuxt/docs#2118)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

Add fixture, update config snapshot and fix 2 tests in `cli`

### CODE REVIEW

**Comment by pi0** [comment]
Hi @Kolobok12309 thanks for PR ❤️ Actually with nuxt3 it is possible to define top-level components via `app.vue`. Since nuxt2 is feature freeze, closing but can see benefit of avoiding re-render by layout changes. If it is making critical issues, we can think of a workaround for #7753

**Comment by Kolobok12309** [comment]
Hi @pi0, ok, when released nuxt3 with vue3 try feature.
Is not critical moment, so we can wait nuxt3.
Mb someone else will ask for this feature :D

**Comment by 9-lives** [comment]
i just mount manually that component in middleware once.

**Comment by lopugit** [comment]
Wait, are you telling me that nuxt re-renders all layout components on route change? Isn't that the whole point of layouts, that they don't re-render, only the route specific data in <nuxt> should re-render?

damn 😮

**Pull request closed without merging**
