### PR TITLE
fix: context.route issue in plugins

### PR DESCRIPTION
**Pull request by mshahbazi**
`context.route` always points to the `/`, when `splitChunks.pages == false` in `nuxt.config.js`
it seems sort of an edge case. BTW, the issue is resolved with this change

### CODE REVIEW

**Review by clarkdo — COMMENTED** [review]
Remove function ``() => ${route._name}.default || ${route._name}`` will break route components lazy loading, can you describe more details about your issue ?

**Comment by mshahbazi** [comment]
@clarkdo, I have a plugin in which I need to get the current `context.route.path`. The plugin works perfectly with a  fresh `nuxt.config.js`. 
The problem raises when I set the `splitChunks.pages` to `false` in the `nuxt.config.js`. In this case, the `context` does not provide the right route. It actually returns `/`, no matter what the current page is. Digging into the code led me to the `vue-app` template file. Removed the line, resolved the issue.

**Comment by clarkdo** [comment]
Cool, thanks for the explanation, so your issue is related to `splitChunks.pages: false`, then we should keep left part of conditional operator and add `route._name` as value of `splitChunks.pages: false` condition.

BTW, could you please add proper tests for this case ?

**Comment by mshahbazi** [comment]
@clarkdo, you are right.
Let me add some thoughts:
The left part is already `route._name` and the right part causes the wrong `context.route` issue. My best guess was: at the time of loading the plugin, the async route component has not been loaded yet. To deal with this, I could think of two options:

1. Use an `await` mechanism to make sure that the component is loaded before the plugin. There are negative points in this: (1) requires deep code review; (2) I doubt if there is any point in async loading while all the route components are supposed to be loaded before the plugin.
2. Omit the condition. This disables async component loading.

To save time, I went for the second option and used chunk grouping to make sure that the components are optimally loaded. This resolved my issue, though the first option seems more sustainable.

**Comment by clarkdo** [comment]
Thanks.

I didn't notice that `interopDefault` has been wrapped with the component in `import()`.

**Review by clarkdo — APPROVED** [review]

**Comment by mshahbazi** [comment]
@clarkdo thank you so much

**Pull request merged**
