### PR TITLE
test: use `got` instead of `request`

### PR DESCRIPTION
**Pull request by clarkdo**
As you may already notice, the tests are failing randomly recently.
From node 13.2, the condition becomes even worse, CI is 100% failing now.
Through my investigation, it's related to `request` lib, it seemed that there is reference leak and race condition, so this pr is gonna replace it with `got`

### CODE REVIEW

**Comment by clarkdo** [comment]
Looks like issue still persists, let's continue to observe and investigate.

**Comment by clarkdo** [comment]
I disabled `csp` test in `dev` for now, let's track in this pr.

**Comment by clarkdo** [comment]
Update: Test is failed event in v2.8.0 and only happened in Node.js 13.2.0

**Comment by clarkdo** [comment]
Update: Looks like it's related to vue renderer `runInNewContext: false` in prod mode

**Comment by galvez** [comment]
@clarkdo In any case, switching to `got` is a Good Thing, I think. Been using it at work.

**Pull request merged**
