### PR TITLE
chore: tailwind purgecss example

### PR DESCRIPTION
**Pull request by stursby**
New example piggybacking on the existing Tailwind CSS demo, however, this one leverages Purgecss to drastically reduce the CSS size.

### CODE REVIEW

**Comment by galvez** [comment]
@stursby can you do `npm run lint` and fix the errors?

**Comment by stursby** [comment]
@galvez Yep! Done.

**Comment by manniL** [comment]
LGTM! (though it might be great to have an example with [`nuxt-purgecss`](https://github.com/Developmint/nuxt-purgecss) as well :thinking: )

**Review by TheAlexLichter — APPROVED** [review]

**Comment by stursby** [comment]
@manniL I didn't know `nuxt-purgecss` existed! 😜I should have know... well, I could refactor unless we want to keep this "manual" setup?

**Comment by stursby** [comment]
@manniL By "package-version only" do you mean redo with the nuxt purgecss module?

**Comment by Atinux** [comment]
I love the PR, thank you @stursby

**Pull request merged**
