### PR TITLE
feat(ts): nuxt configuration typedefs

### PR DESCRIPTION
**Pull request by kevinmarrec**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Add TypeScript type definitions for the Nuxt Configuration file.
It also has the objective to be compatible for either `nuxt.config.ts` only config or `config` future configuration folder specification.

### I. nuxt.config.ts
```ts
import NuxtConfiguration from '@nuxt/config'

const config: NuxtConfiguration = {
  build: {
    cache: true
  }
}

export config
```
### II. config/build.ts (using namespace)
```ts
import { NuxtConfiguration } from '@nuxt/config'

const build: NuxtConfiguration.Build = {
  cache: true
}

export build
```

### III. config/build.ts (not using namespace - flat type name)
```ts
import { Build } from '@nuxt/config'

const build: Build = {
  cache: true
}

export build
```

## Status / TODO
- [x] Main interface
- [x] NuxtConfiguration**Build** (`build` property)
- [x] uxtConfiguration**Env** (`env` property)N
- [x] NuxtConfiguration**Fetch** (`fetch` property https://github.com/nuxt/nuxt.js/pull/5028)
- [x] NuxtConfiguration**Generate** (`generate` property)
- [x] NuxtConfiguration**Globals** (`globals` property)
- [x] NuxtConfiguration**Head** (`head` property)
- [x] NuxtConfiguration**Hooks** (`hooks` property)
- [x] NuxtConfiguration**Loading** (`loading` property)
- [x] NuxtConfiguration**LoadingIndicator** (`loadingIndicator` property)
- [x] NuxtConfiguration**Module** (for `modules` property)
- [x] NuxtConfiguration**Plugin** (for `plugins` property)
- [x] NuxtConfiguration**Render** (`render` property)
- [x] NuxtConfiguration**Router** (`router` property)
- [x] NuxtConfiguration**ServerMiddleware** (for `serverMiddleware` property)
- [x] NuxtConfiguration**Server** (`server` property)
- [x] NuxtConfiguration**VueConfiguration** (`vue.config` property)
- [x] NuxtConfiguration**Watchers** (`watchers` property)_
- [x] Namespaced types export
- [x] Flat (without NuxtConfiguration prefix) types export

## Notes

Some definitions won't totally be defined for first types release (they are defined as `any` type for now).
They will be improved and better defined overtime, with the help of the Nuxt community.
`TBD (To Be Defined)` comments are present in the typedefs to easy know what's not totally defined yet.

This PR also update `@nuxt/vue-app/types` to follow a default codestyle for type definitions : no semi-colons, single quotes.

### CODE REVIEW

**Comment by chanlito** [comment]
The `NuxtConfiguration` prefix seems too long 😬for my taste.

**Comment by kevinmarrec** [comment]
@chanlito Yeah, I'll need to see what can be done, I just didn't want to have conflicts with things like `Plugin`, `Module`, etc ...

Cause for example, a real Nuxt Module is a `function`, meanwhile the `modules` section of the configuration is either a "Nuxt Module" or array of `string`, etc ...

There is also an issue where a `Layout` interface is already defined in `@nuxt/vue-app` types, and is needed in `@nuxt/config` types as well. So we'll need to either have a `common` types folder somewhere or have all types in a single `@nuxt/types` package.

**Comment by kevinmarrec** [comment]
@chanlito 
```
import { NuxtConfigurationBuild } from `@nuxt/config` // Current
import { ConfigurationBuild } from `@nuxt/config` // Better ?
import { Build } from `@nuxt/config` // Best ?
```

**Comment by kevinmarrec** [comment]
OR declare `NuxtConfiguration` as a namespace and
```ts
// config/build.ts
import NuxtConfiguration from '@nuxt/config'

const build: NuxtConfiguration.Build = {
  ...
}

export default build
```

**Comment by chanlito** [comment]
I really like the last one `import { Build } from '@nuxt/config'` but why from `@nuxt/config`?

It'd be nice to do something like `import { Build, Context, Builder, Config, Nuxt } from 'nuxt'` but I think this will have existing name conflict.

**Comment by kevinmarrec** [comment]
@chanlito Well the thing is that in your last example, there are things that are classes, and other things that are types/interfaces, so it can bring lot of confusion.

**Comment by chanlito** [comment]
Well I can't say for other people, but this is what I usually see in typescript libs.

**Comment by kevinmarrec** [comment]
@chanlito `@nuxt/config` is not a scoped module but a Nuxt core package https://github.com/nuxt/nuxt.js/tree/dev/packages/config , so IMO it's logic to have types imported from the core package related to the configuration 😃

**Comment by chanlito** [comment]
Ah I see, that mono repo thing. 

But still this looks best
```js
import { Build } from '@nuxt/config'
```

**Comment by kevinmarrec** [comment]
@chanlito Yep

Sure, I will make it used this way ;)

**Review by atinux — DISMISSED** [review]
Awesome work @kevinmarrec 👏 
Could you open a PR on nuxt/docs to add these example in a TypeScript section?

**Comment by kevinmarrec** [comment]
@Atinux I'm working on a dedicated Vuepress setup for TS docs which includes a section about this feature.

If we don't keep my Idea to have dedicated doc, it should be juste about copy-pasting things in main docs :)

**Review by pi0 — APPROVED** [review]

**Pull request merged**
