### PR TITLE
feat(utils): export sort routes

### PR DESCRIPTION
**Pull request by pimlie**
(Helps to) resolve:
- #6275
- https://github.com/nuxt-community/nuxt-i18n/issues/152

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Well, not really a feature but also not a bug fix. 

If a user calls `extendRoutes` and adds new routes, he/she is also responsible for maintaining proper order of the routes. This is quite a cumbersome task, by exposing the sortRoutes method a user can import it, add route to his/her liking and then easily sort them properly again.

(This is useful until vue-router fully supports auto path ranking)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by manniL** [comment]
Would it make sense to provide it as an argument for `extendRoutes`?

**Review by TheAlexLichter — APPROVED** [review]

**Review by galvez — APPROVED** [review]

**Comment by Atinux** [comment]
Nice PR @pimlie 

Would it be even better if we call `sortRoutes` just after `extendRoutes` so they won't have to deal with sorting and just push the new route to the array?

**Comment by pimlie** [comment]
It would be better probably, but are we 100% sure that `sortRoutes` doesnt contain any bugs at all and will sort all possible routes always perfectly? Unfortunately I think it doesnt, its too much meant to work with nuxt-routes which are often a bit simpler then the full range or possible routes with vue-router (eg regular expressions). Thats probably also why a lot of people will use extendRoutes anyway.

As vue-router seems to be already adding functionality for this, I think its best if we just provide a temporary fix until auto path ranking is merged in vue-router.

**Comment by Atinux** [comment]
Did not think of this, you are right @pimlie 

Ready to merge 👍

**Review by kevinmarrec — APPROVED** [review]

**Comment by bravokiloecho** [comment]
Is there any documentation of how to use this anywhere?

**Pull request merged**
