### PR TITLE
feat: stateful component injection via plugins

### PR DESCRIPTION
**Pull request by galvez**
This PR introduces a backwards-compatible extension to plugins in the form of a `componentInject()` helper, preceded by `inject()` in the plugin function signature. The difference between `inject()` and `componentInject()` is that `componentInject()` may only take a function as value (a _setter_), which in turn receives a reference to the *_current_* component.

```js
export default function(ctx, inject, componentInject) {
  componentInject('api', (component) => {
    return new Proxy({}, {
      get(_, apiMethod) {
        return async (...args) {
          // Look ma, altering current component state only!
          component.loading = true
          const result = await component.$axios.post(`/call/${apiMethod}`, { args })
          component.loading = false
          return result
        }
      }
    })
  })
}
```

TODO:

- [ ] Update tests
- [ ] Update docs

Calling for early feedback on the idea before I devote work on tests/docs.

### CODE REVIEW

**Comment by nagipogu** [comment]
import { Injectable } from '@angular/core';
import { ConfigService } from './config.service';
import { Observable } from 'rxjs/Rx';
import { DataService } from './data.service';
import { CacheService } from './cache.service';

@Injectable({
  providedIn: 'root'
})
export class GetListService {

  constructor(private configService: ConfigService,
    public dataService: DataService,
    public cacheService: CacheService,) { }

    getOccupationList(obj) {
      return this.dataService.postData(this.configService.OCCUPATION_LIST, obj)
        .flatMap(rData => {
          console.log('--Occupation List----------->')
          console.log(rData)
          if (this.cacheService.CashedOccupationList) {
            this.cacheService.CashedOccupationList = _.concat(this.cacheService.CashedOccupationList, rData.Occupationlist)
          } else {
            this.cacheService.CashedOccupationList = rData.Occupationlist;
          }
          return Observable.of(rData)
        });
    } 
}

**Comment by nagipogu** [comment]
this is code i have been trying
 this.cacheService.CashedOccupationList = _.concat(this.cacheService.CashedOccupationList, rData.Occupationlist)

here i am getting error.

**Comment by nagipogu** [comment]
error is

ERROR in src/app/services/get-list.service.ts(22,54): error TS2304: Cannot find name '_'.                   src/app/services/get-list.service.ts(36,51): error TS2304: Cannot find name '_'.                            src/app/services/get-list.service.ts(50,48): error TS2304: Cannot find name '_'.                            src/app/services/get-list.service.ts(64,55): error TS2304: Cannot find name '_'.
--

**Comment by galvez** [comment]
@nagipogu Please open an issue or try our [Discord channels][https://discord.nuxtjs.org/], commenting on a PR is not the appropriate way to seek help. I've deleted your comments here.

**Comment by manniL** [comment]
@galvez Could you elaborate some use cases (besides changing a component's loading state)? ☺️

**Comment by galvez** [comment]
@Atinux @manniL The use-case is the same as mixins, but lighter. Say you want to make sure a method is available for every component but Vue.mixin would be too costly: `componentInject()` to the rescue. It will only do anything if you try and use it (since it uses `defineProperty`).

**Comment by galvez** [comment]
After discussing this with @Atinux I've decided to offer it as an external utility.

**Comment by galvez** [comment]
@Atinux @pi0 @manniL just found another use for this:

https://twitter.com/anothergalvez/status/1110622070881353729

Do you think there's a more elegant way to achieve the same without `componentInject()`?

**Comment by pi0** [comment]
@galvez Sweet use case! But really can't be a component mixin? A nuxt module/plugin can be then able to register that mixin.

**Comment by galvez** [comment]
@pi0 wouldn't this perform better than Vue.mixin()? I mean, wouldn't `Vue.mixin()` cause every Vue instance to have an individual copy of the method? With `componentInject()`, we ensure it's only defined once?

**Comment by pi0** [comment]
I think it's already handled by Vue itself for global mixins. The _copy_ is happening for function reference not entirely copying.

**Comment by galvez** [comment]
Right, still one could argue _safely_ injecting into `Vue.prototype` performs better than duplicating function references around? (I'm really curious about this) :)

**Pull request closed without merging**
