### PR TITLE
feat(schema): add snow effect on loading screen in winter

### PR DESCRIPTION
**Pull request by lihbr**
https://github.com/user-attachments/assets/cac06ab3-2490-470f-9b2a-13f3ddbc5318

### 📚 Description

This PR adds a seasonal (temporary) snow effect on Nuxt 3 loading screen. It's just an idea I wanted to play with after a discussion during our last meeting. If we don't like it, we can trash it, or see how to make it better ☺️

I tried to keep the code as minimal as possible. It also respects the user's preferences regarding animations.

For credits, the snow effect is inspired by [Boris Šehovac previous WebGL work on Codepen](https://codepen.io/bsehovac/pen/GPwXxq), but written using the Canvas's 2d context for conciseness here.

### CODE REVIEW

**Comment by lihbr** [comment]
Glad you like it ☺️

I believe it's enough on the loading template, and that having it everywhere would be a bit overkill, at least for now while we experiment with seasonal effects.

If it's something the community likes, maybe we could later on just load instead a hosted script from nuxt.com, this way we can change it/remove it without prompting a package release. This would also allow us to change it more often and let the community contribute to it, a bit like with [Google's doodles](https://doodles.google)

**Comment by danielroe** [comment]
For some reason I'm getting this:

CleanShot 2024-12-03 at 10 07 32@2x

Can investigate more.

**Comment by lihbr** [comment]
I'll investigate and make it Nov - December - January only if that works :)

**Comment by lihbr** [comment]
Just curious what do you run to get the above result? Looks like Tailwind as a whole struggle to load as even the Nuxt logo is not centered 🤔

**Comment by danielroe** [comment]
I ran:

```
pnpm i
pnpm dev:prepare

pnpm nuxi dev test/fixtures/basic
```

and then opened localhost:3000 in the browser.

**Comment by lihbr** [comment]
OK thank you so much! This should be good ☺️

💅 Style fixes
📆 Winter-bound

**Review by danielroe — APPROVED** [review]

**Comment by typed-sigterm** [comment]
The first time I felt that not having DST was not a good thing🤔Maybe we can add a button to toggle it manually?
??

**Comment by lihbr** [comment]
Thanks for your feedback @typed-sigterm, you have a toggle animation button at the top right of the loading screen :)

**Comment by M-GRV** [comment]
> Thanks for your feedback @typed-sigterm, you have a toggle animation button at the top right of the loading screen :)

congrats on the merge! I love this!

**Comment by seanchatmangpt** [comment]
How can I disable this? It is making me motion sick. You might want to consider accessibility or a clear way to disable in the future.

**Comment by atomflunder** [comment]
@seanchatmangpt Theres a button on the top right of the loading screen to toggle the effect.  
You only see it when you hover over it.

**Comment by memochou1993** [comment]
Some countries, like Taiwan, don’t use daylight saving time (DST), so the timezone offset stays the same year-round.

😞 

image

**Comment by danielroe** [comment]
Improvements are welcome 🙏

**Comment by hendriksenremco** [comment]
Is there a way to disable this effect?

**Comment by danielroe** [comment]
Yes, as Lucie commented above, there's a link in the top right of the loading screen.

https://volta.net/nuxt/nuxt/pull/29871#comment-4872944

**Comment by danielroe** [comment]
Agreed. As I commented above - improvements are welcome!

**Comment by hendriksenremco** [comment]
> (also, no need to delete your comment!)

Yes, sorry about that. My actions were faster then my mind.

**Comment by typed-sigterm** [comment]
@danielroe I made [this](https://github.com/typed-sigterm/which-hemisphere), perhaps it can help.

**Comment by finnbuster** [comment]
Hello, just reporting from Australia where we don't get snow in winter ;)

**Comment by danielroe** [comment]
@finnbuster it _tries_ to detect hemisphere. is that not working?

**Comment by finnbuster** [comment]
@danielroe it's definitely getting the hemisphere right and is displaying snow in our winter as defined in the code but the thing is that it doesn't snow in most of the souther hemisphere :) https://earthobservatory.nasa.gov/global-maps/MOD10C1_M_SNOW#:~:text=Snow%20and%20ice%20cover%20most,snow%20cover%20almost%20year%20round.

**Comment by danielroe** [comment]
😱

**Pull request merged**
